entityType: ""
providerType: "Databricks"
fields:
- name: "INSTRUMENT CODE"
  dataType:
    type: "String"
- name: "ISIN"
  dataType:
    type: "String"
- name: "CUSIP"
  dataType:
    type: "String"
- name: "PRODUCT TYPE"
  dataType:
    type: "String"
