---
version: 2
models:
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_142"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_21"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_226"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_38"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_4"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_52"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_65"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_77"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__AlteryxSelect_96"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Filter_206"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Filter_93"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_198_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_199_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_200_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_208_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_213_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_218_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_229_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_50_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Formula_82_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Join_94_left"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Summarize_124"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Summarize_16"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Summarize_231"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Union_103"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_testnew__Union_197"
  tags:
  - "prophecy_temp"
