---
version: 2
models:
- name: "Alpha_workflow_update1__AlteryxSelect_336"
  tags:
  - "prophecy_temp"
- name: "Alpha_workflow_update1__AlteryxSelect_515"
  tags:
  - "prophecy_temp"
- name: "Alpha_workflow_update1__Filter_345_reject"
  tags:
  - "prophecy_temp"
