---
version: 2
models:
- name: "pbasic__CountRecords_0"
  tags:
  - "prophecy_temp"
- name: "pbasic__DataCleansing_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__DataEncoderDecoder_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__DataMasking_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__DynamicSelect_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__FindDuplicates_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__FuzzyMatch_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__GenerateRows_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__MultiColumnEdit_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__MultiColumnRename_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__Regex_1"
  tags:
  - "prophecy_temp"
- name: "pbasic__Sample_1"
  tags:
  - "prophecy_temp"
