---
version: 2
models:
- name: "Will_it_Snow_Today__AlteryxSelect_15"
  tags:
  - "prophecy_temp"
- name: "Will_it_Snow_Today__Filter_23"
  tags:
  - "prophecy_temp"
- name: "Will_it_Snow_Today__Filter_23_reject"
  tags:
  - "prophecy_temp"
- name: "Will_it_Snow_Today__PortfolioComposerText_29"
  tags:
  - "prophecy_temp"
