---
version: 2
models:
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__AlteryxSelect_50"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Filter_2"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Filter_258"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Formula_93_1"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Join_112_inner"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Join_3_inner"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Join_57_inner"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_100"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_104"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_11"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_110"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_13"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_15"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_223"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_259"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_263"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_5"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_7"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_85"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_9"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Sort_99"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Summarize_16"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Summarize_17"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Summarize_315"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Summarize_36"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Summarize_52"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Summarize_54"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Summarize_61"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__Unique_34"
  tags:
  - "prophecy_temp"
- name: "Backtest_Analysis_v2_Call_Model_Priority_3__numberofcallsto_231"
  tags:
  - "prophecy_temp"
