---
version: 2
sources:
- name: "transpiled_sources"
  database: "sony"
  schema: "orch_test"
  config:
    enabled: true
  tables:
  - name: "BarrierBendingM_73_ref"
    identifier: "{{ var('BarrierBendingM_73') }}"
    config:
      tags:
      - "pipeline:Barrier_Bend_Monitoring_1_"
    columns:
    - name: "Smart Bending"
      dataType:
        type: "String"
    - name: "Inmt Id"
      dataType:
        type: "String"
    - name: "$FV Bent"
      dataType:
        type: "Double"
    - name: " %FV Impact  Smart Bending"
      dataType:
        type: "Decimal"
    - name: "Smart Bending (Y/N)"
      dataType:
        type: "String"
    - name: "Position"
      dataType:
        type: "Double"
    - name: " FV Impact  Smart Bending"
      dataType:
        type: "Decimal"
    - name: "Legal/Risky"
      dataType:
        type: "Decimal"
    - name: "$FV Legal"
      dataType:
        type: "Double"
    - name: "Exit?"
      dataType:
        type: "Boolean"
    - name: "Count of Inm>(2% & $100k)"
      dataType:
        type: "String"
    - name: "Smart Bend TH Breach"
      dataType:
        type: "String"
    - name: "$FV Bent(Rainbow)"
      dataType:
        type: "Double"
    - name: "$FV Unbent"
      dataType:
        type: "Double"
  - name: "BarrierBendingM_74_ref"
    identifier: "{{ var('BarrierBendingM_74') }}"
    config:
      tags:
      - "pipeline:Barrier_Bend_Monitoring_1_"
    columns:
    - name: "Imnt Id"
      dataType:
        type: "String"
    - name: "Asset Pyramid Name"
      dataType:
        type: "String"
    - name: "MaxBends"
      dataType:
        type: "String"
    - name: "Desk"
      dataType:
        type: "String"
    - name: "Relative Risk Levels"
      dataType:
        type: "String"
    - name: "Sum_USDLegalRisky"
      dataType:
        type: "Double"
    - name: "Bends"
      dataType:
        type: "String"
    - name: "Smart Bending Breach"
      dataType:
        type: "String"
    - name: "Asset Spot"
      dataType:
        type: "String"
    - name: "barType"
      dataType:
        type: "String"
    - name: "Option Class"
      dataType:
        type: "String"
    - name: "Legal Barrier Next"
      dataType:
        type: "Double"
    - name: "Barrier at max disc vs Current Spot"
      dataType:
        type: "Decimal"
    - name: "Next Barrier vs Current Spot"
      dataType:
        type: "Decimal"
    - name: "VCG Accepted"
      dataType:
        type: "String"
    - name: "hasStaticCheckMaxBreach"
      dataType:
        type: "String"
    - name: "Comment"
      dataType:
        type: "String"
    - name: "Relative Legal Levels"
      dataType:
        type: "String"
    - name: "Legal Barrier At Max Disc"
      dataType:
        type: "String"
  - name: "BarrierBendingM_102_ref"
    identifier: "{{ var('BarrierBendingM_102') }}"
    config:
      tags:
      - "pipeline:Barrier_Bend_Monitoring_1_"
    columns:
    - name: "Imnt Id"
      dataType:
        type: "String"
    - name: "Smart Bending"
      dataType:
        type: "String"
    - name: "Smart Bending Breach"
      dataType:
        type: "String"
    - name: "Smart Bending Instrument"
      dataType:
        type: "String"
    - name: "Abs"
      dataType:
        type: "Decimal"
    - name: "Legal/Risky"
      dataType:
        type: "String"
    - name: "Accepted Breach?"
      dataType:
        type: "String"
    - name: "Final- Breach or Pending QR or <TH"
      dataType:
        type: "String"
    - name: "Inmt ID Accepted"
      dataType:
        type: "String"
    - name: "Final Breach"
      dataType:
        type: "String"
    - name: "Check?"
      dataType:
        type: "String"
  - name: "BarrierBendingM_5_ref"
    identifier: "{{ var('BarrierBendingM_5') }}"
    config:
      tags:
      - "pipeline:Barrier_Bend_Monitoring_1_"
    columns:
    - name: "F16"
      dataType:
        type: "Double"
    - name: "Bar Type"
      dataType:
        type: "String"
    - name: "F12"
      dataType:
        type: "Double"
    - name: "Desk"
      dataType:
        type: "String"
    - name: "Inmt ID"
      dataType:
        type: "Double"
    - name: "F10"
      dataType:
        type: "String"
    - name: "F13"
      dataType:
        type: "Double"
    - name: "Option Class"
      dataType:
        type: "String"
    - name: "F19"
      dataType:
        type: "Double"
    - name: "Barrier at max disc vs Current Spot"
      dataType:
        type: "Double"
    - name: "F11"
      dataType:
        type: "Double"
    - name: "F15"
      dataType:
        type: "Double"
    - name: "Next Barrier vs Current Spot"
      dataType:
        type: "Double"
    - name: "Review Date"
      dataType:
        type: "Date"
    - name: "F18"
      dataType:
        type: "Double"
    - name: "VCG Accepted"
      dataType:
        type: "String"
    - name: "F17"
      dataType:
        type: "Double"
    - name: "Comment"
      dataType:
        type: "String"
    - name: "F14"
      dataType:
        type: "Double"
  - name: "BarReport_APAC__1_ref"
    identifier: "{{ var('BarReport_APAC__1') }}"
    config:
      tags:
      - "pipeline:Barrier_Bend_Monitoring_1_"
    columns:
    - name: "Imnt Id"
      dataType:
        type: "String"
    - name: "LegalBarrierNextSuppressFlag"
      dataType:
        type: "String"
    - name: "Position Ccy V/S Dollar FX Rate"
      dataType:
        type: "String"
    - name: "Asset Pyramid Name"
      dataType:
        type: "String"
    - name: "isContinuous"
      dataType:
        type: "String"
    - name: "Category Used"
      dataType:
        type: "String"
    - name: "MinBends"
      dataType:
        type: "String"
    - name: "barrierName"
      dataType:
        type: "String"
    - name: "Smoothing Values"
      dataType:
        type: "String"
    - name: "hasSmoothing"
      dataType:
        type: "String"
    - name: "Interp"
      dataType:
        type: "String"
    - name: "hasStaticCheckMinBreach"
      dataType:
        type: "String"
    - name: "MaxBends"
      dataType:
        type: "String"
    - name: "USD Position"
      dataType:
        type: "String"
    - name: "ForwardNext"
      dataType:
        type: "String"
    - name: "Asset Type"
      dataType:
        type: "String"
    - name: "LegalBarrierForwardRatioNext"
      dataType:
        type: "String"
    - name: "USD Risk Discontinuity Max"
      dataType:
        type: "String"
    - name: "WOF"
      dataType:
        type: "String"
    - name: "Desk"
      dataType:
        type: "String"
    - name: "BendingLegalBarrierRatioNext"
      dataType:
        type: "String"
    - name: "Smoothing Dates"
      dataType:
        type: "String"
    - name: "Relative Risk Levels"
      dataType:
        type: "String"
    - name: "USDRiskyDelta"
      dataType:
        type: "String"
    - name: "COT Id"
      dataType:
        type: "String"
    - name: "Bends"
      dataType:
        type: "String"
    - name: "Country"
      dataType:
        type: "String"
    - name: "Risky Barrier Next"
      dataType:
        type: "String"
    - name: "description"
      dataType:
        type: "String"
    - name: "Field_1"
      dataType:
        type: "String"
    - name: "NEXT_KO_PV"
      dataType:
        type: "String"
    - name: "Position"
      dataType:
        type: "String"
    - name: "variableType"
      dataType:
        type: "String"
    - name: "Risky Barrier At Max Disc"
      dataType:
        type: "String"
    - name: "Asset Reference Level"
      dataType:
        type: "String"
    - name: "Tier Used"
      dataType:
        type: "String"
    - name: "MultiAssetMonitoringType"
      dataType:
        type: "String"
    - name: "Asset Spot"
      dataType:
        type: "String"
    - name: "Discontinuity Dates"
      dataType:
        type: "String"
    - name: "EXPECTED_MATURITY"
      dataType:
        type: "String"
    - name: "barType"
      dataType:
        type: "String"
    - name: "USDLegalFV"
      dataType:
        type: "String"
    - name: "Barrier Date At Max Disc"
      dataType:
        type: "String"
    - name: "Portfolio"
      dataType:
        type: "String"
    - name: "USDLegalRisky"
      dataType:
        type: "String"
    - name: "Option Class"
      dataType:
        type: "String"
    - name: "Liquidity"
      dataType:
        type: "String"
    - name: "Legal Barrier Next"
      dataType:
        type: "String"
    - name: "assetName"
      dataType:
        type: "String"
    - name: "USDLegalDelta"
      dataType:
        type: "String"
    - name: "isUp"
      dataType:
        type: "String"
    - name: "USD Clean Legal Discontinuity Max"
      dataType:
        type: "String"
    - name: "Next Barrier Date"
      dataType:
        type: "String"
    - name: "Clean Dollar Discontinuities"
      dataType:
        type: "String"
    - name: "Ccy of Position"
      dataType:
        type: "String"
    - name: "NEXT_KO_COUPONS"
      dataType:
        type: "String"
    - name: "Imnt Name"
      dataType:
        type: "String"
    - name: "USD Clean Legal Discontinuity Next"
      dataType:
        type: "String"
    - name: "Dollar Discontinuities"
      dataType:
        type: "String"
    - name: "bendDirection"
      dataType:
        type: "String"
    - name: "Expiry"
      dataType:
        type: "String"
    - name: "USD Legal Discontinuity Max"
      dataType:
        type: "String"
    - name: "USD Risk Discontinuity Next"
      dataType:
        type: "String"
    - name: "Asset Ccy"
      dataType:
        type: "String"
    - name: "LegalBarrierForwardDiffNext"
      dataType:
        type: "String"
    - name: "hasStaticCheckMaxBreach"
      dataType:
        type: "String"
    - name: "Bending At Next Date"
      dataType:
        type: "String"
    - name: "RiskyBarForwardDiffNext"
      dataType:
        type: "String"
    - name: "Bending At Max Disc"
      dataType:
        type: "String"
    - name: "RiskyFilteredAssets"
      dataType:
        type: "String"
    - name: "BarrierBreachMessages"
      dataType:
        type: "String"
    - name: "Relative Legal Levels"
      dataType:
        type: "String"
    - name: "LegalBarrierAtMaxDiscontinuitySuppressFlag"
      dataType:
        type: "String"
    - name: "NEXT_KO_DISCONTINUITY"
      dataType:
        type: "String"
    - name: "NEXT_KO_PROBABILITY_RND"
      dataType:
        type: "String"
    - name: "USD Legal Discontinuity Next"
      dataType:
        type: "String"
    - name: "USDRiskyFV"
      dataType:
        type: "String"
    - name: "BendingForwardRatioNext"
      dataType:
        type: "String"
    - name: "Legal Barrier At Max Disc"
      dataType:
        type: "String"
