---
version: 2
sources:
- name: "transpiled_sources"
  database: "{{ var('db_name') }}"
  schema: "{{ var('schema_name') }}"
  config:
    enabled: true
  tables:
  - name: "ItemNumberUploa_75_ref"
    identifier: "{{ var('ItemNumberUploa_75') }}"
    config:
      tags:
      - "pipeline:4PL_Inventory_Report_Extended"
    columns:
    - name: "ItemNumber"
      dataType:
        type: "Float"
  - name: "Source_File__ex_1_ref"
    identifier: "{{ var('Source_File__ex_1') }}"
    config:
      tags:
      - "pipeline:4PL_Inventory_Report_Extended"
    columns:
    - name: "LocationCode"
      dataType:
        type: "String"
    - name: "AvailableQuantity"
      dataType:
        type: "Numeric"
    - name: "ItemProductGroupCode"
      dataType:
        type: "String"
    - name: "ItemNumber"
      dataType:
        type: "String"
    - name: "InventoryDate"
      dataType:
        type: "Date"
    - name: "ItemPrimaryVendorID"
      dataType:
        type: "String"
    - name: "ItemDescription"
      dataType:
        type: "String"
  - name: "MajorCodes_w_Bu_126_ref"
    identifier: "{{ var('MajorCodes_w_Bu_126') }}"
    config:
      tags:
      - "pipeline:4PL_Inventory_Report_Extended"
    columns:
    - name: "LocationCode"
      dataType:
        type: "String"
    - name: "ItemProductGroupCode"
      dataType:
        type: "String"
    - name: "ItemNumber"
      dataType:
        type: "String"
    - name: "InventoryDate"
      dataType:
        type: "Date"
    - name: "ItemDescription"
      dataType:
        type: "String"
    - name: "File Name"
      dataType:
        type: "String"
    - name: "Sum_AvailableQuantity"
      dataType:
        type: "Numeric"
