---
version: 2
models:
- name: "AOC24__Filter_16"
  tags:
  - "prophecy_temp"
- name: "AOC24__Filter_16_reject"
  tags:
  - "prophecy_temp"
- name: "AOC24__Filter_17"
  tags:
  - "prophecy_temp"
- name: "AOC24__TextInput_1_cast"
  tags:
  - "prophecy_temp"
