{{
  config({    
    "materialized": "table",
    "alias": "SM_CREDIT_CARD_PLAN_CAL_MTH_HIS",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH SQ_CREDIT_PLAN AS (

  SELECT 
    /*+ parallel(AMA) parallel(PLB) parallel(PLI) use_hash(AMA PLB PLI)*/
    SUBSTR('$$MP_BUSDATE', 1, 6) PERIODID,
    AMA.ACC_NUM,
    PLI.APR_1,
    PLB.CURRENT_BALANCE,
    PLB.PLAN_NUMBER,
    PLB.PLAN_TYPE
  
  FROM ALL_MONTHLY_ACCOUNTS AS AMA, CREDIT_PLAN_BALANCE AS PLB, CREDIT_PLAN_INTEREST AS PLI
  
  WHERE AMA.ACCID = PLB.ACCID
        AND AMA.ACCID = PLI.ACCID
        AND PLB.PLAN_NUMBER = PLI.PLAN_NUMBER
        AND PLB.PLAN_DATE = PLI.PLAN_DATE
        AND AMA.SOURCE_SYSTEM_CODE = 'G'
        AND AMA.ACC_TYPE IN ('410', '420', '510', '520')
        AND AMA.CLIENTID IS NOT NULL
        AND TO_DATE('$$MP_BUSDATE', 'YYYYMMDD') BETWEEN PLB.EFROM AND NVL(PLB.ETO, TO_DATE('40001231', 'YYYYMMDD'))
        AND TO_DATE('$$MP_BUSDATE', 'YYYYMMDD') BETWEEN PLI.EFROM AND NVL(PLI.ETO, TO_DATE('40001231', 'YYYYMMDD'))

),

SQ_CREDIT_PLAN_EXPR_93 AS (

  SELECT 
    ACCOUNT_NUMBER AS CC_ACCOUNT_NUMBER,
    APR_1 AS CC_PLAN_APR,
    CURRENT_BALANCE AS CC_PLAN_CURRENT_BALANCE,
    PLAN_NUMBER AS CC_PLAN_NUMBER,
    PLAN_TYPE AS CC_PLAN_TYPE,
    PERIODID AS PERIODID
  
  FROM SQ_CREDIT_PLAN AS in0

)

SELECT *

FROM SQ_CREDIT_PLAN_EXPR_93
