{{
  config({    
    "materialized": "table",
    "alias": "SM_LOAN_CAL_MTH_END_HIST",
    "database": "tanmay",
    "schema": "default"
  })
}}

WITH EXP_CURRENT_DELINQUENCY AS (

  SELECT *
  
  FROM {{ ref('m_mmrt_loan_cal_hist_sum_load__EXP_CURRENT_DELINQUENCY')}}

),

EXP_CURRENT_DELINQUENCY_EXPR_8 AS (

  SELECT 
    ACC_NUM AS LN_ACCOUNT_NUMBER,
    PAST_DUE AS LN_PAST_DUE,
    BLOCK_CODE AS LN_BLOCK_CODE,
    CHARGE_OFF_AMOUNT AS LN_CHARGE_OFF_AMOUNT,
    CURR_BALANCE AS LN_CURRENT_BALANCE,
    CYCLE_DAY AS LN_CYCLE_DAY,
    GOOD_BAD_FLAG AS LN_GOOD_BAD_FLAG,
    PAYMENT_METHOD AS LN_PAYMENT_METHOD,
    SCORE AS LN_BEHAVIOUR_SCORE,
    CURRENT_DEINQUENCY AS LN_CURRENT_DELINQUENCY,
    UNEARNED_INTEREST AS LN_UNEARNED_INTEREST,
    REBATE_PROMOTION_INDICATOR AS LN_REBATE_PROMOTION_INDICATOR,
    PERIODID AS PERIODID,
    STATUS AS LN_ACCOUNT_STATUS,
    ARREARS_VALUE AS LN_ARREARS_VALUE,
    USER_CODE_1 AS LN_USER_CODE_1,
    USER_CODE_2 AS LN_USER_CODE_2
  
  FROM EXP_CURRENT_DELINQUENCY AS in0

)

SELECT *

FROM EXP_CURRENT_DELINQUENCY_EXPR_8
