---
version: 2
models:
- name: "m_mmrt_loan_cal_hist_sum_load__EXP_CURRENT_DELINQUENCY"
  tags:
  - "prophecy_temp"
- name: "m_mmrt_loan_cal_hist_sum_load__SM_ACCOUNT_GOOD_BAD"
  tags:
  - "prophecy_temp"
- name: "m_mmrt_loan_cal_hist_sum_load__SM_LOAN_CAL_MTH_END_HIST"
  tags:
  - "prophecy_temp"
