---
version: 2
models:
- name: "Log_Extraction__AlteryxSelect_22"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__AlteryxSelect_41"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__AppendFields_40"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__DetourEnd_26_14"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__Filter_16"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__Filter_5_14"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__Filter_5_14_reject"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__FolderBrowse_17_14"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__FolderBrowse_24"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__FolderBrowse_26"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__Formula_35_14_0"
  tags:
  - "prophecy_temp"
- name: "Log_Extraction__Union_12_14"
  tags:
  - "prophecy_temp"
