---
version: 2
models:
- name: "Record_ID_sample_all__TextInput_123_cast"
  tags:
  - "prophecy_temp"
- name: "Record_ID_sample_all__generate_incremental_id"
  tags:
  - "prophecy_temp"
- name: "Record_ID_sample_all__generate_record_id"
  tags:
  - "prophecy_temp"
- name: "Record_ID_sample_all__incremental_recordid_group_region"
  tags:
  - "prophecy_temp"
