---
version: 2
models:
- name: "m_rep_cards_orig_account_alias_update__EXP_ACCOUNT_ALIAS_VARS_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_alias_update__MAINTAINS"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_alias_update__NEW_ACCOUNT_ALIAS"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_alias_update__RTR_FORTRAV_ACCOUNT_ALIAS_EXPR_NEW_ACCOUNT_ALIAS"
  tags:
  - "prophecy_temp"
