---
version: 2
models:
- name: "Household_Clustering_1_Household_Creation_Priority_2__Cleanse_11"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Filter_13"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Filter_17"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Filter_27"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Filter_27_reject"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Join_14_left"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Summarize_12"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Summarize_19"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Summarize_20"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Summarize_21"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Summarize_22"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Summarize_24"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Summarize_25"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Summarize_26"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__Unique_4"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__address_for_geo_18"
  tags:
  - "prophecy_temp"
- name: "Household_Clustering_1_Household_Creation_Priority_2__recast_cache_cs_2"
  tags:
  - "prophecy_temp"
