---
version: 2
models:
- name: "wsfr__FlattenSchema_1"
  tags:
  - "prophecy_temp"
- name: "wsfr__RecordID_1"
  tags:
  - "prophecy_temp"
- name: "wsfr__Reformat_1"
  tags:
  - "prophecy_temp"
- name: "wsfr__SQLStatement_1"
  tags:
  - "prophecy_temp"
