---
version: 2
models:
- name: "Focus_Pages_MVP_Priority_2__AlteryxSelect_133"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Filter_114"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Filter_155"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Filter_157_to_Filter_97"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Filter_92"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Filter_93"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Formula_101_1"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Formula_102_1"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Formula_80_1"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Formula_90_0"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Join_107_inner"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Join_107_left"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Join_109_inner_formula_0"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Join_126_inner"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Join_135_inner_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Sort_150"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Sort_160"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Sort_39"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_111"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_113"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_141"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_142"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_143"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_144"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_145"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_146"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_151"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_152"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_153"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_154"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_156"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_46"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_82"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_94"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_95"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Summarize_96"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Union_103"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Unique_106"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Unique_110"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Unique_125"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__Unique_127"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__back_surgery_cs_219"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__cancer_pt_csv_198"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__diabetes_cache__30"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__diabetes_csv_47"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__diag_cd_desc_cs_211"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__high_risk_preg__237"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__hip_proc_csv_235"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__knee_replacemen_231"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__mother_birthing_199"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__msk_members_csv_72"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__neck_surgery_cs_227"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__oncology_cache__21"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__pregnancy_comp__236"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__pregnancy_compl_170"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__pregnancy_membe_162"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__rrclm_f_csv_207"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__shoulder_surger_223"
  tags:
  - "prophecy_temp"
- name: "Focus_Pages_MVP_Priority_2__vague_msk_csv_215"
  tags:
  - "prophecy_temp"
