---
version: 2
models:
- name: "subject_workflow__AlteryxSelect_20"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__AlteryxSelect_213"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__AlteryxSelect_25"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__AlteryxSelect_26"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__AlteryxSelect_429"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__DynamicRename_351"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__Filter_381"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__Filter_381_reject"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__Formula_208_0"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__Formula_433_to_Formula_380_0"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__JoinMultiple_15"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__Join_194_left"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__Join_210_inner"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__Join_288_left_UnionFullOuter"
  tags:
  - "prophecy_temp"
- name: "subject_workflow__Sort_348"
  tags:
  - "prophecy_temp"
