{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH JoinMultiple_15 AS (

  SELECT *
  
  FROM {{ ref('subject_workflow__JoinMultiple_15')}}

),

AlteryxSelect_292 AS (

  SELECT 
    STUDY_ID AS STUDY_ID,
    SUBJECT_ID AS SUBJECT_ID,
    SCREENING_DT AS SCREENING_DT,
    SCREEN_FAIL_DT AS SCREEN_FAIL_DT,
    RANDOMIZATION_DT AS RANDOMIZATION_DT,
    DISCONTINUED_DT AS DISCONTINUED_DT,
    SCREENING_VISIT_NAME AS SCREENING_VISIT_NAME,
    SCREEN_FAIL_VISIT_NAME AS SCREEN_FAIL_VISIT_NAME,
    RANDOMIZATION_VISIT_NAME AS RANDOMIZATION_VISIT_NAME,
    DISCONTINUED_VISIT_NAME AS DISCONTINUED_VISIT_NAME,
    SCREENING_SRC_SYS AS SCREENING_SRC_SYS,
    SCREEN_FAIL_SRC_SYS AS SCREEN_FAIL_SRC_SYS,
    RANDOMIZATION_SRC_SYS AS RANDOMIZATION_SRC_SYS,
    DISCONTINUED_SRC_SYS AS DISCONTINUED_SRC_SYS,
    SCREENING_TABLE_SRC AS SCREENING_TABLE_SRC,
    SCREEN_FAIL_TABLE_SRC AS SCREEN_FAIL_TABLE_SRC,
    RANDOMIZATION_TABLE_SRC AS RANDOMIZATION_TABLE_SRC,
    DISCONTINUED_TABLE_SRC AS DISCONTINUED_TABLE_SRC,
    PENULTIMATE_DT AS PENULTIMATE_DT,
    LAST_DATE_OF_PARTICIPATION_DT AS LAST_DATE_OF_PARTICIPATION_DT,
    COMPLETED_DT AS COMPLETED_DT,
    PENULTIMATE_VISIT_NAME AS PENULTIMATE_VISIT_NAME,
    LAST_DATE_OF_PARTICIPATION_VISIT_NAME AS LAST_DATE_OF_PARTICIPATION_VISIT_NAME,
    COMPLETED_VISIT_NAME AS COMPLETED_VISIT_NAME,
    PENULTIMATE_SRC_SYS AS PENULTIMATE_SRC_SYS,
    LAST_DATE_OF_PARTICIPATION_SRC_SYS AS LAST_DATE_OF_PARTICIPATION_SRC_SYS,
    COMPLETED_SRC_SYS AS COMPLETED_SRC_SYS,
    LAST_DATE_OF_PARTICIPATION_TABLE_SRC AS LAST_DATE_OF_PARTICIPATION_TABLE_SRC,
    PENULTIMATE_TABLE_SRC AS PENULTIMATE_TABLE_SRC,
    COMPLETED_TABLE_SRC AS COMPLETED_TABLE_SRC,
    * EXCLUDE ("STUDY_ID", 
    "SUBJECT_ID", 
    "SCREENING_DT", 
    "SCREEN_FAIL_DT", 
    "RANDOMIZATION_DT", 
    "DISCONTINUED_DT", 
    "SCREENING_VISIT_NAME", 
    "SCREEN_FAIL_VISIT_NAME", 
    "RANDOMIZATION_VISIT_NAME", 
    "DISCONTINUED_VISIT_NAME", 
    "SCREENING_SRC_SYS", 
    "SCREEN_FAIL_SRC_SYS", 
    "RANDOMIZATION_SRC_SYS", 
    "DISCONTINUED_SRC_SYS", 
    "SCREENING_TABLE_SRC", 
    "SCREEN_FAIL_TABLE_SRC", 
    "RANDOMIZATION_TABLE_SRC", 
    "DISCONTINUED_TABLE_SRC", 
    "PENULTIMATE_DT", 
    "LAST_DATE_OF_PARTICIPATION_DT", 
    "COMPLETED_DT", 
    "PENULTIMATE_VISIT_NAME", 
    "LAST_DATE_OF_PARTICIPATION_VISIT_NAME", 
    "COMPLETED_VISIT_NAME", 
    "PENULTIMATE_SRC_SYS", 
    "LAST_DATE_OF_PARTICIPATION_SRC_SYS", 
    "COMPLETED_SRC_SYS", 
    "LAST_DATE_OF_PARTICIPATION_TABLE_SRC", 
    "PENULTIMATE_TABLE_SRC", 
    "COMPLETED_TABLE_SRC")
  
  FROM JoinMultiple_15 AS in0

),

DynamicRename_351 AS (

  {{
    prophecy_basics.MultiColumnRename(
      ['AlteryxSelect_292'], 
      [
        'SCREEN_FAIL_VISIT_NAME', 
        'RANDOMIZATION_TABLE_SRC', 
        'LAST_DATE_OF_PARTICIPATION_DT', 
        'PENULTIMATE_VISIT_NAME', 
        'DISCONTINUED_SRC_SYS', 
        'RANDOMIZATION_DT', 
        'DISCONTINUED_DT', 
        'LAST_DATE_OF_PARTICIPATION_TABLE_SRC', 
        'LAST_DATE_OF_PARTICIPATION_SRC_SYS', 
        'LAST_DATE_OF_PARTICIPATION_VISIT_NAME', 
        'SCREEN_FAIL_TABLE_SRC', 
        'PENULTIMATE_DT', 
        'PENULTIMATE_SRC_SYS', 
        'SCREEN_FAIL_DT', 
        'PENULTIMATE_TABLE_SRC', 
        'DISCONTINUED_TABLE_SRC', 
        'RANDOMIZATION_VISIT_NAME', 
        'SCREENING_VISIT_NAME', 
        'COMPLETED_VISIT_NAME', 
        'RANDOMIZATION_SRC_SYS', 
        'SCREENING_TABLE_SRC', 
        'SCREENING_DT', 
        'DISCONTINUED_VISIT_NAME', 
        'COMPLETED_SRC_SYS', 
        'SCREENING_SRC_SYS', 
        'COMPLETED_TABLE_SRC', 
        'COMPLETED_DT', 
        'STUDY_SITE_NUMBER', 
        'SCREEN_FAIL_SRC_SYS'
      ], 
      'editPrefixSuffix', 
      [
        'DISCONTINUED_DT', 
        'DISCONTINUED_SRC_SYS', 
        'STUDY_ID', 
        'LAST_DATE_OF_PARTICIPATION_TABLE_SRC', 
        'LAST_DATE_OF_PARTICIPATION_VISIT_NAME', 
        'RANDOMIZATION_TABLE_SRC', 
        'RANDOMIZATION_VISIT_NAME', 
        'SCREENING_DT', 
        'COMPLETED_VISIT_NAME', 
        'LAST_DATE_OF_PARTICIPATION_SRC_SYS', 
        'COMPLETED_DT', 
        'SCREENING_TABLE_SRC', 
        'SCREENING_VISIT_NAME', 
        'LAST_DATE_OF_PARTICIPATION_DT', 
        'PENULTIMATE_VISIT_NAME', 
        'PENULTIMATE_DT', 
        'RANDOMIZATION_SRC_SYS', 
        'COMPLETED_TABLE_SRC', 
        'SCREEN_FAIL_TABLE_SRC', 
        'SUBJECT_ID', 
        'PENULTIMATE_TABLE_SRC', 
        'PENULTIMATE_SRC_SYS', 
        'SCREENING_SRC_SYS', 
        'RANDOMIZATION_DT', 
        'DISCONTINUED_VISIT_NAME', 
        'DISCONTINUED_TABLE_SRC', 
        'SCREEN_FAIL_DT', 
        'COMPLETED_SRC_SYS', 
        'STUDY_SITE_NUMBER', 
        'SCREEN_FAIL_VISIT_NAME', 
        'SCREEN_FAIL_SRC_SYS'
      ], 
      'Suffix', 
      '_der', 
      ""
    )
  }}

)

SELECT *

FROM DynamicRename_351
