{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH aka_GPDIP_EDLUD_437 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('subject_workflow', 'aka_GPDIP_EDLUD_437') }}

),

AlteryxSelect_438 AS (

  SELECT 
    SUBJ_REASON_FOR_WITHDRAWAL AS SUBJ_REASON_FOR_WITHDRAWAL,
    SUBJ_STATUS AS SUBJ_STATUS,
    SUBJ_WITHDRAWAL_TIMEFRAME AS SUBJ_WITHDRAWAL_TIMEFRAME,
    SUBJ_SCREEN_FAILURE_DT AS SUBJECT_SCREEN_FAILURE_DT,
    SUBJ_STR_STRATA_NUM AS SBJ_STR_STRATA_NUM,
    CAST(SUBJ_COH_COHORT_NUM AS DOUBLE) AS SBJ_COH_COHORT_NUM,
    SUBJ_STRATA_CODE_VALUE_DESC AS SBJ_STRATA_CODE_VALUE_DESC,
    SUBJ_COH_COHORT_DESC AS SBJ_COH_COHORT_DESC,
    LEGACY_SUBJ_STATUS AS LEGACY_SUBJ_STATUS,
    SUBJ_ETHNICITY AS SUBJ_ETHNICITY,
    SUBJ_GENDER AS SUBJ_GENDER,
    SUBJ_RACE AS SUBJ_RACE,
    SRC_SYS_NAME AS SRC_SYS_NAME,
    SRC_SYS_TYPE AS SRC_SYS_TYPE,
    SITE_ID AS SITE_ID,
    START_DT AS CREATION_TS,
    END_DT AS END_TS,
    DELETE_FLAG AS DELETE_FLAG,
    * EXCLUDE ("SUBJ_REASON_FOR_WITHDRAWAL", 
    "SUBJ_STATUS", 
    "SUBJ_WITHDRAWAL_TIMEFRAME", 
    "LEGACY_SUBJ_STATUS", 
    "SUBJ_ETHNICITY", 
    "SUBJ_GENDER", 
    "SUBJ_RACE", 
    "SRC_SYS_NAME", 
    "SRC_SYS_TYPE", 
    "SITE_ID", 
    "DELETE_FLAG", 
    "SUBJ_SCREEN_FAILURE_DT", 
    "SUBJ_STR_STRATA_NUM", 
    "SUBJ_COH_COHORT_NUM", 
    "SUBJ_STRATA_CODE_VALUE_DESC", 
    "SUBJ_COH_COHORT_DESC", 
    "START_DT", 
    "END_DT")
  
  FROM aka_GPDIP_EDLUD_437 AS in0

),

Formula_208_0 AS (

  SELECT 
    (
      CASE
        WHEN ((STUDY_ID = 'C4591001') AND (STUDY_SITE_NUMBER = '4444'))
          THEN '1231'
        ELSE STUDY_SITE_NUMBER
      END
    ) AS STUDY_SITE_NUMBER,
    * EXCLUDE ("STUDY_SITE_NUMBER")
  
  FROM AlteryxSelect_438 AS in0

)

SELECT *

FROM Formula_208_0
