{{
  config({    
    "materialized": "table",
    "alias": "UPD_CLIENT_PREFERENCE",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_CARDS_ORIG_CLIENT_PREFERENCE AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_client_preference_update__EXP_CARDS_ORIG_CLIENT_PREFERENCE')}}

),

RTR_CARDS_ORIG_CLIENT_PREFERENCE_out1 AS (

  SELECT * 
  
  FROM EXP_CARDS_ORIG_CLIENT_PREFERENCE AS in0
  
  WHERE (((CLID_CLIENT_PREFERENCE IS NOT NULL) AND (TOTAL_COMPARE > 0)) AND (ROW_NUMBER = 1))

),

RTR_CARDS_ORIG_CLIENT_PREFERENCE_EXPR_UPDATE_CLIENT_PREFERENCE AS (

  SELECT 
    CLID_CLIENT_ALIAS AS CLID_CLIENT_ALIAS3,
    CLID_CLIENT_PREFERENCE AS CLID_CLIENT_PREFERENCE3,
    MARKETING_OPT_IN_TEL AS MARKETING_OPT_IN_TEL3,
    MARKETING_OPT_IN_EMAIL AS MARKETING_OPT_IN_EMAIL3,
    MARKETING_OPT_IN_TEXT AS MARKETING_OPT_IN_TEXT3,
    MARKETING_OPT_IN_POST AS MARKETING_OPT_IN_POST3,
    MAIL_PREFERENCE AS MAIL_PREFERENCE3,
    MAIL_PREFERENCE_DATE AS MAIL_PREFERENCE_DATE3,
    PHONE_PREFERENCE AS PHONE_PREFERENCE3,
    PHONE_PREFERENCE_DATE AS PHONE_PREFERENCE_DATE3,
    EMAIL_PREFERENCE AS EMAIL_PREFERENCE3,
    EMAIL_PREFERENCE_DATE AS EMAIL_PREFERENCE_DATE3,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE3,
    business_date AS business_date3,
    ROW_NUMBER AS ROW_NUMBER3,
    TOTAL_COMPARE AS TOTAL_COMPARE3
  
  FROM RTR_CARDS_ORIG_CLIENT_PREFERENCE_out1 AS in0

),

UPD_CLIENT_PREFERENCE1_add_missing_column_0 AS (

  SELECT 
    CAST(NULL AS STRING) AS MPS_PREFERENCE,
    CAST(NULL AS TIMESTAMP) AS MPS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS TPS_PREFERENCE,
    CAST(NULL AS TIMESTAMP) AS TPS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS ICOS_PREFERENCE,
    CAST(NULL AS TIMESTAMP) AS ICOS_PREFERENCE_DATE,
    *
  
  FROM RTR_CARDS_ORIG_CLIENT_PREFERENCE_EXPR_UPDATE_CLIENT_PREFERENCE AS in0

),

UPD_CLIENT_PREFERENCE_EXP AS (

  SELECT 
    CLID_CLIENT_PREFERENCE3 AS CLID,
    SOURCE_SYSTEM_CODE3 AS SOURCE_SYSTEM_CODE,
    MARKETING_OPT_IN_POST3 AS MAIL_PREFERENCE,
    business_date3 AS MAIL_PREFERENCE_DATE,
    MARKETING_OPT_IN_TEL3 AS PHONE_PREFERENCE,
    business_date3 AS PHONE_PREFERENCE_DATE,
    MARKETING_OPT_IN_EMAIL3 AS EMAIL_PREFERENCE,
    business_date3 AS EMAIL_PREFERENCE_DATE,
    MARKETING_OPT_IN_TEXT3 AS SMS_PREFERENCE,
    business_date3 AS SMS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS MPS_PREFERENCE,
    CAST(NULL AS STRING) AS MPS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS TPS_PREFERENCE,
    CAST(NULL AS STRING) AS TPS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS ICOS_PREFERENCE,
    CAST(NULL AS STRING) AS ICOS_PREFERENCE_DATE
  
  FROM UPD_CLIENT_PREFERENCE1_add_missing_column_0 AS in0

)

SELECT *

FROM UPD_CLIENT_PREFERENCE_EXP
