pipelines:
  RM_SEM_V3:
    visualGroups:
      NEWMARKET:
        isCollapsed: false
        height: 540
        width: 1206
        nodes:
        - "Formula_385_0"
        - "Join_384_inner"
        - "Join_384_left"
        - "Join_387_right_UnionRightOuter"
        - "Summarize_386"
      OutputtoGoogleSheets:
        isCollapsed: true
        height: 72
        width: 434
        nodes:
        - "googlesheetsoutput_476"
      POTENTIALREVENUE:
        isCollapsed: false
        height: 675
        width: 1158
        nodes:
        - "Database__LOADI_394"
        - "Database__LOADI_395"
        - "Formula_392_0"
        - "Join_391_left_UnionFullOuter"
        - "Join_393_inner"
      TURNSEMOFFFOROD:
        isCollapsed: false
        height: 720
        width: 484
        nodes:
        - "AlteryxSelect_470"
        - "Formula_471_0"
      flows:
        isCollapsed: false
        height: 675
        nodes:
        - "AlteryxSelect_443"
        - "Filter_439"
        - "Filter_441"
        - "Formula_442_0"
        - "Join_438_inner"
        - "Join_444_inner"
        - "Join_445_inner"
        - "MultiRowFormula_440"
        - "MultiRowFormula_440_row_id_0"
        - "MultiRowFormula_440_row_id_drop_0"
        - "Summarize_436"
        width: 2766
        colorPreset: "gray-blue"
      localcopy:
        isCollapsed: false
        height: 630
        nodes:
        - "SEM_Support_Lis_475"
        width: 310
        colorPreset: "blue"
  perpetual_inventory_details:
    visualGroups:
      AccountingTransactionTypes:
        isCollapsed: false
        height: 2093.5
        width: 6425
        nodes:
        - "Transactions"
      ClosingBalance:
        isCollapsed: false
        height: 1061.3333740234375
        width: 2350
        nodes:
        - "AccountingTrans_98"
        - "AlteryxSelect_48"
        - "AlteryxSelect_50"
        - "AlteryxSelect_59"
        - "AppendFields_60"
        - "Directory_57"
        - "Directory_57_reformat"
        - "DynamicInput_49"
        - "Filter_61"
        - "Formula_53_0"
        - "Formula_58_0"
        - "Join_52_inner"
        - "Join_76_inner"
        - "OpeningBalance"
      DataSources:
        isCollapsed: false
        height: 2293.5
        width: 6760
        nodes:
        - "AccountingTransactionTypes"
        - "Summarize_108"
      Dates:
        isCollapsed: false
        height: 915
        width: 1000
        nodes:
        - "AlteryxSelect_107"
        - "AlteryxSelect_24"
        - "Facilities"
        - "Filter_23"
        - "Formula_27_0"
        - "Formula_29_0"
        - "SamtecFacilitie_106"
        - "TextInput_26"
        - "TextInput_26_cast"
      Facilities:
        isCollapsed: false
        height: 280
        width: 280
      OpeningBalance:
        isCollapsed: false
        height: 355.3333435058594
        width: 1200
        nodes:
        - "AlteryxSelect_39"
        - "AlteryxSelect_41"
        - "DynamicInput_40"
        - "Formula_44_0"
        - "Join_43_inner"
        - "Join_75_inner"
      PartNumber:
        isCollapsed: false
        height: 280
        width: 280
      Transactions:
        isCollapsed: false
        height: 1893.5
        width: 6290
        nodes:
        - "AlteryxSelect_62"
        - "AlteryxSelect_66"
        - "DynamicInput_63"
        - "Join_64_inner"
        - "Join_81_inner"
        - "Validation"
      UserInput:
        isCollapsed: false
        height: 2576.833251953125
        width: 8615
        nodes:
        - "AlteryxSelect_103"
        - "Cleanse_94"
        - "DataSources"
        - "Formula_92_0"
        - "Join_88_left_UnionFullOuter"
        - "Join_91_left_UnionFullOuter"
        - "Join_99_inner"
        - "MultiRowFormula_96"
        - "MultiRowFormula_96_window"
      Validation:
        isCollapsed: false
        height: 1693.5
        width: 5095
        nodes:
        - "AlteryxSelect_12"
        - "AlteryxSelect_37"
        - "AppendFields_16"
        - "ClosingBalance"
        - "Dates"
        - "Directory_11"
        - "Directory_11_reformat"
        - "Filter_15"
        - "Formula_13_0"
        - "PartNumber"
        - "Summarize_14"
        - "Test_18"
        - "TextInput_33"
        - "TextInput_33_cast"
