pipelines:
  LU_Document_Selection_Disabled:
    visualGroups:
      "1ReadProductionPfLEETSubCountryData":
        isCollapsed: false
        height: 720
        width: 778
        nodes:
        - "Cleanse_290"
        - "aka_GPDIP_EDLUD_289"
      "23ReplacementforInitialCOMPASSDeployment":
        isCollapsed: true
        height: 72
        width: 718
        nodes:
        - "Join_308_inner"
        - "aka_GPDIP_EDLUD_307"
      "2AssociateGDMSCORErepeatingattributes":
        isCollapsed: false
        height: 2550
        width: 2482
        nodes:
        - "23ReplacementforInitialCOMPASSDeployment"
        - "AlteryxSelect_327"
        - "Filter_303"
        - "Filter_303_reject"
        - "Join_306_inner"
        - "Join_310_inner"
        - "Summarize_305"
        - "aka_GPDIP_EDLUD_302"
      "3AssociateGDMSCOREsingleattributes":
        isCollapsed: false
        height: 1851
        width: 884
        nodes:
        - "Formula_300_0"
        - "Join_299_inner"
        - "aka_GPDIP_EDLUD_298"
      "43SupplementalStepspendingGDMSDevelopment":
        isCollapsed: false
        height: 945
        width: 748
        nodes:
        - "Join_320_inner"
        - "aka_GPDIP_EDLUD_319"
      "4AssociateGDMSPRESCRIBINGINFOrepeatingattributes":
        isCollapsed: false
        height: 2820
        width: 2546
        nodes:
        - "43SupplementalStepspendingGDMSDevelopment"
        - "AlteryxSelect_326"
        - "Filter_323"
        - "Filter_323_reject"
        - "Join_318_inner"
        - "Join_322_inner"
        - "Summarize_317"
        - "aka_GPDIP_EDLUD_324"
      "5AssociateGDMSPRESCRIBINGINFOsingleattributes":
        isCollapsed: false
        height: 1851
        width: 884
        nodes:
        - "Formula_314_0"
        - "Join_313_inner"
        - "aka_GPDIP_EDLUD_312"
      "6Unionandwritetodatabase":
        isCollapsed: false
        height: 798
        width: 1170
        nodes:
        - "AlteryxSelect_294"
        - "DBOutput"
        - "Union_292"
      DBOutput:
        isCollapsed: false
        height: 399
        width: 280
        nodes:
        - "aka_GPD_UDDL_Wr_295"
  LU_Product_Selection_Disabled:
    visualGroups:
      "1Preparesubcountrydata":
        isCollapsed: false
        height: 1446
        width: 1272
        nodes:
        - "Cleanse_121"
        - "Filter_118"
        - "Filter_118_reject"
        - "Filter_88"
        - "Filter_88_reject"
        - "Join_119_inner"
        - "aka_GPDIP_EDLUD_113"
      "214IsolateuniqueSubcountryIDs":
        isCollapsed: false
        height: 900
        width: 1386
        nodes:
        - "AlteryxSelect_24"
        - "Filter_38"
        - "Summarize_33"
        - "Unique_28"
      "215IsolateUniqueGenericNames":
        isCollapsed: false
        height: 855
        width: 1298
        nodes:
        - "AlteryxSelect_25"
        - "Filter_39"
        - "Summarize_42"
        - "Unique_29"
      "216IsolateUniqueCompoundNumbers":
        isCollapsed: false
        height: 900
        width: 1298
        nodes:
        - "AlteryxSelect_26"
        - "Filter_40"
        - "Summarize_43"
        - "Unique_30"
      "217IsolateUniqueTradenames":
        isCollapsed: false
        height: 855
        width: 1298
        nodes:
        - "AlteryxSelect_27"
        - "Filter_41"
        - "Summarize_44"
        - "Unique_31"
      "2PrepareproductmappingtoCOREsubcountries":
        isCollapsed: false
        height: 4137
        width: 4590
        nodes:
        - "214IsolateuniqueSubcountryIDs"
        - "215IsolateUniqueGenericNames"
        - "216IsolateUniqueCompoundNumbers"
        - "217IsolateUniqueTradenames"
        - "AlteryxSelect_18"
        - "AlteryxSelect_181"
        - "CrossTab_23"
        - "Filter_15"
        - "Filter_17"
        - "Filter_180"
        - "JoinMultiple_45"
        - "Join_10_inner"
        - "Join_12_inner"
        - "Join_6_inner"
        - "Join_6_left"
        - "Union_89"
        - "aka_GPDIP_EDLUD_11"
        - "aka_GPDIP_EDLUD_9"
      "314IsolateUniqueSubcountryIDs":
        isCollapsed: false
        height: 900
        width: 1386
        nodes:
        - "AlteryxSelect_146"
        - "Filter_150"
        - "Summarize_148"
        - "Unique_147"
      "315IsolateUniqueGenericNames":
        isCollapsed: false
        height: 855
        width: 1298
        nodes:
        - "AlteryxSelect_152"
        - "Filter_155"
        - "Summarize_156"
        - "Unique_153"
      "316IsolateUniqueCompoundNumbers":
        isCollapsed: false
        height: 900
        width: 1298
        nodes:
        - "AlteryxSelect_158"
        - "Filter_161"
        - "Summarize_162"
        - "Unique_159"
      "317IsolateUniqueTradenNames":
        isCollapsed: false
        height: 855
        width: 1298
        nodes:
        - "AlteryxSelect_164"
        - "Filter_167"
        - "Summarize_168"
        - "Unique_165"
      "3PrepareproductmappingtoMARKETsubcountries":
        isCollapsed: false
        height: 4356
        width: 5432
        nodes:
        - "314IsolateUniqueSubcountryIDs"
        - "315IsolateUniqueGenericNames"
        - "316IsolateUniqueCompoundNumbers"
        - "317IsolateUniqueTradenNames"
        - "AlteryxSelect_123"
        - "AlteryxSelect_143"
        - "CrossTab_144"
        - "Filter_124"
        - "Filter_130"
        - "Filter_142"
        - "JoinMultiple_145"
        - "Join_125_inner"
        - "Join_125_left"
        - "Join_128_inner"
        - "Join_129_inner"
        - "NonCurrentObjectIssueFix"
        - "Union_131"
        - "aka_GPDIP_EDLUD_132"
        - "aka_GPDIP_EDLUD_133"
      "4UnionCoreandPrescribingInfoDataandPrepareforDBWriteback":
        isCollapsed: false
        height: 1341
        width: 1432
        nodes:
        - "DBOutput"
        - "Formula_94_0"
        - "OptionalExcelOutput"
        - "Union_84"
      DBOutput:
        isCollapsed: false
        height: 399
        width: 280
        nodes:
        - "aka_GPD_UDDL_Wr_92"
      NonCurrentObjectIssueFix:
        isCollapsed: false
        height: 579
        width: 780
        nodes:
        - "Join_173_inner"
        - "Unique_172"
        - "Unique_174"
      OptionalExcelOutput:
        isCollapsed: false
        height: 399
        width: 422
        nodes:
        - "lu_product_sele_95"
  RM_SEM_V3:
    visualGroups:
      NEWMARKET:
        isCollapsed: false
        height: 540
        width: 1206
        nodes:
        - "Formula_385_0"
        - "Join_384_inner"
        - "Join_384_left"
        - "Join_387_right_UnionRightOuter"
        - "Summarize_386"
      OutputtoGoogleSheets:
        isCollapsed: true
        height: 72
        width: 434
        nodes:
        - "googlesheetsoutput_476"
      POTENTIALREVENUE:
        isCollapsed: false
        height: 675
        width: 1158
        nodes:
        - "Database__LOADI_394"
        - "Database__LOADI_395"
        - "Formula_392_0"
        - "Join_391_left_UnionFullOuter"
        - "Join_393_inner"
      TURNSEMOFFFOROD:
        isCollapsed: false
        height: 720
        width: 484
        nodes:
        - "AlteryxSelect_470"
        - "Formula_471_0"
      flows:
        isCollapsed: false
        height: 675
        nodes:
        - "AlteryxSelect_443"
        - "Filter_439"
        - "Filter_441"
        - "Formula_442_0"
        - "Join_438_inner"
        - "Join_444_inner"
        - "Join_445_inner"
        - "MultiRowFormula_440"
        - "MultiRowFormula_440_row_id_0"
        - "MultiRowFormula_440_row_id_drop_0"
        - "Summarize_436"
        width: 2766
        colorPreset: "gray-blue"
      localcopy:
        isCollapsed: false
        height: 630
        nodes:
        - "SEM_Support_Lis_475"
        width: 310
        colorPreset: "blue"
  intervention:
    visualGroups:
      STEP1:
        isCollapsed: false
        height: 4638.16650390625
        width: 8414.849609375
        nodes:
        - "AlteryxSelect_1000"
        - "AlteryxSelect_1002"
        - "AlteryxSelect_1022"
        - "AlteryxSelect_1635"
        - "AlteryxSelect_1639"
        - "AlteryxSelect_1646"
        - "AlteryxSelect_774"
        - "AlteryxSelect_781"
        - "AlteryxSelect_790"
        - "AlteryxSelect_791"
        - "AlteryxSelect_795"
        - "AlteryxSelect_804"
        - "AlteryxSelect_810"
        - "AlteryxSelect_828"
        - "AlteryxSelect_838"
        - "AlteryxSelect_852"
        - "AlteryxSelect_856"
        - "AlteryxSelect_860"
        - "AlteryxSelect_887"
        - "AlteryxSelect_890"
        - "AlteryxSelect_998"
        - "Cleanse_892"
        - "CrossTab_846"
        - "Filter_1019"
        - "Filter_1019_reject"
        - "Filter_1020"
        - "Filter_1020_reject"
        - "Filter_1638"
        - "Filter_1645"
        - "Filter_1649"
        - "Filter_1649_reject"
        - "Filter_1650"
        - "Filter_1650_reject"
        - "Filter_1652"
        - "Filter_1652_reject"
        - "Filter_1655"
        - "Filter_1655_reject"
        - "Filter_1656"
        - "Filter_1656_reject"
        - "Filter_1659"
        - "Filter_1659_reject"
        - "Filter_787"
        - "Filter_813"
        - "Filter_816"
        - "Filter_831"
        - "Filter_869"
        - "Filter_869_reject"
        - "Filter_870"
        - "Filter_870_reject"
        - "Filter_871"
        - "Filter_871_reject"
        - "Filter_872"
        - "Filter_872_reject"
        - "Filter_873"
        - "Filter_873_reject"
        - "Filter_874"
        - "Filter_874_reject"
        - "Filter_875"
        - "Filter_875_reject"
        - "Filter_876"
        - "Filter_876_reject"
        - "Filter_877"
        - "Filter_877_reject"
        - "Filter_878"
        - "Filter_878_reject"
        - "Filter_879"
        - "Filter_879_reject"
        - "Filter_880"
        - "Filter_880_reject"
        - "Filter_883"
        - "Filter_883_reject"
        - "Filter_884"
        - "Filter_884_reject"
        - "Formula_1006_0"
        - "Formula_1021_0"
        - "Formula_775_0"
        - "Formula_782_0"
        - "Formula_814_0"
        - "Formula_832_to_Formula_833_0"
        - "Formula_837_0"
        - "Formula_847_0"
        - "Formula_889_0"
        - "HRHCReportLive__1679"
        - "INTERVENTION_LI_765"
        - "Join_1010_left_UnionFullOuter"
        - "Join_776_left_UnionFullOuter"
        - "Join_783_left_UnionLeftOuter"
        - "Join_783_right"
        - "Join_792_left_UnionLeftOuter"
        - "Join_798_left_UnionLeftOuter"
        - "Join_800_left_UnionLeftOuter"
        - "Join_805_left_UnionLeftOuter"
        - "Join_815_inner"
        - "Join_815_left"
        - "Join_822_left_UnionLeftOuter"
        - "Join_834_left_UnionLeftOuter"
        - "Join_850_left_UnionLeftOuter"
        - "Join_864_inner"
        - "Join_864_left"
        - "Join_886_left_UnionLeftOuter"
        - "Join_997_inner"
        - "MultiFieldFormula_772"
        - "Productioned_xl_1669"
        - "ProviderDetailR_1661"
        - "ProviderDetailR_1677"
        - "Sample_796"
        - "Sample_807"
        - "Sample_808"
        - "Sample_812"
        - "Sample_830"
        - "Summarize_1640"
        - "Summarize_1642"
        - "Summarize_1643"
        - "Summarize_1647"
        - "Summarize_771"
        - "Summarize_777"
        - "Summarize_779"
        - "Summarize_785"
        - "Summarize_786"
        - "Summarize_801"
        - "Summarize_818"
        - "Summarize_819"
        - "Summarize_820"
        - "Summarize_824"
        - "Summarize_825"
        - "Summarize_826"
        - "Summarize_851"
        - "Union_1641"
        - "Union_1648"
        - "Union_784"
        - "Union_817"
        - "Union_866"
        - "Unique_1018"
        - "Unique_794"
        - "Unique_891"
        - "Unique_891_after"
        - "Unique_891_before"
  perpetual_inventory:
    visualGroups:
      AccountingPlannerCodes:
        isCollapsed: true
        height: 72
        width: 450
        nodes:
        - "AccountingTrans_70"
        - "AlteryxSelect_72"
      AccountingTransactionTypes:
        isCollapsed: true
        height: 72
        width: 492
        nodes:
        - "AccountingTrans_71"
      BuildReconciliation:
        isCollapsed: false
        height: 513
        width: 1286
        nodes:
        - "CombineBalancesTransactionsDimensions"
        - "CombineCostsCodes"
        - "Output"
        - "SummarizeTransactions"
      ClosingBalance:
        isCollapsed: true
        height: 72
        width: 430
        nodes:
        - "AlteryxSelect_34"
        - "DynamicInput_33"
        - "Formula_39_0"
        - "Join_36_inner"
      ClosingINV:
        isCollapsed: true
        height: 72
        width: 412
        nodes:
        - "AlteryxSelect_105"
        - "AlteryxSelect_97"
        - "Cleanse_104"
        - "DynamicInput_161"
      CombineBalancesTransactionsDimensions:
        isCollapsed: true
        height: 72
        width: 674
        nodes:
        - "AlteryxSelect_90"
        - "Cleanse_94"
        - "Formula_134_0"
        - "Formula_91_0"
        - "Formula_91_1"
        - "Join_122_left_UnionLeftOuter"
        - "Join_138_inner"
        - "Join_43_left_UnionFullOuter"
        - "Join_87_left_UnionFullOuter"
        - "Summarize_157"
        - "Summarize_158"
      CombineCostsCodes:
        isCollapsed: true
        height: 72
        width: 424
        nodes:
        - "AlteryxSelect_111"
        - "AlteryxSelect_112"
        - "AlteryxSelect_113"
        - "AlteryxSelect_118"
        - "Cleanse_123"
        - "Join_114_left_UnionFullOuter"
        - "Join_115_left_UnionFullOuter"
        - "Join_127_left_UnionLeftOuter"
        - "Join_129_left_UnionLeftOuter"
        - "Join_130_left_UnionLeftOuter"
      DataSources:
        isCollapsed: false
        height: 870
        width: 1060
        nodes:
        - "AccountingPlannerCodes"
        - "AccountingTransactionTypes"
        - "ClosingBalance"
        - "ClosingINV"
        - "OpeningBalance"
        - "OpeningINV"
        - "Part"
        - "PreviousQuarterClosingINV"
        - "Transactions"
      Dates:
        isCollapsed: true
        height: 72
        width: 428
        nodes:
        - "Formula_2_0"
        - "Formula_95_0"
        - "TextInput_1"
        - "TextInput_1_cast"
      Facilities:
        isCollapsed: true
        height: 72
        width: 400
        nodes:
        - "AlteryxSelect_173"
        - "AlteryxSelect_23"
        - "Filter_12"
        - "SamtecFacilitie_179"
      Filters:
        isCollapsed: false
        height: 366
        width: 528
        nodes:
        - "Dates"
        - "Facilities"
      OpeningBalance:
        isCollapsed: true
        height: 72
        width: 468
        nodes:
        - "AlteryxSelect_29"
        - "DynamicInput_28"
        - "Formula_38_0"
        - "Join_31_inner"
      OpeningINV:
        isCollapsed: true
        height: 72
        width: 424
        nodes:
        - "AlteryxSelect_101"
        - "AlteryxSelect_96"
        - "Cleanse_100"
        - "DynamicInput_159"
      Output:
        isCollapsed: true
        height: 72
        width: 242
        nodes:
        - "PerpetualInvent_144"
      Part:
        isCollapsed: true
        height: 72
        width: 256
        nodes:
        - "AlteryxSelect_182"
        - "AlteryxSelect_74"
        - "DSN_r2s_prod_ed_181"
      PreviousQuarterClosingINV:
        isCollapsed: true
        height: 72
        width: 604
        nodes:
        - "AlteryxSelect_109"
        - "AlteryxSelect_98"
        - "Cleanse_108"
        - "DynamicInput_164"
      SummarizeTransactions:
        isCollapsed: true
        height: 72
        width: 1186
        nodes:
        - "AccountingTrans_82"
        - "AlteryxSelect_85"
        - "AlteryxSelect_86"
        - "Cleanse_84"
        - "CrossTab_81_0"
        - "CrossTab_81_1"
        - "CrossTab_81_regularActions"
        - "CrossTab_81_rename"
        - "Join_80_inner"
        - "Union_83"
      Transactions:
        isCollapsed: true
        height: 72
        width: 960
        nodes:
        - "AlteryxSelect_59"
        - "AlteryxSelect_63"
        - "AlteryxSelect_67"
        - "AppendFields_61"
        - "Directory_57"
        - "Directory_57_reformat"
        - "DynamicInput_184"
        - "DynamicInput_64"
        - "Filter_183"
        - "Filter_183_reject"
        - "Filter_62"
        - "Formula_178_0"
        - "Formula_58_0"
        - "Join_65_inner"
        - "Union_185"
      UserInput:
        isCollapsed: false
        height: 510
        width: 800
        nodes:
        - "Validation"
      Validation:
        isCollapsed: true
        height: 72
        width: 674
        nodes:
        - "AlteryxSelect_48"
        - "AppendFields_52"
        - "Directory_46"
        - "Directory_46_reformat"
        - "Filter_51"
        - "Formula_49_0"
        - "Summarize_50"
        - "Test_54"
  perpetual_inventory_details:
    visualGroups:
      AccountingTransactionTypes:
        isCollapsed: false
        height: 2093.5
        width: 6425
        nodes:
        - "Transactions"
      ClosingBalance:
        isCollapsed: false
        height: 1061.3333740234375
        width: 2350
        nodes:
        - "AccountingTrans_98"
        - "AlteryxSelect_48"
        - "AlteryxSelect_50"
        - "AlteryxSelect_59"
        - "AppendFields_60"
        - "Directory_57"
        - "Directory_57_reformat"
        - "DynamicInput_49"
        - "Filter_61"
        - "Formula_53_0"
        - "Formula_58_0"
        - "Join_52_inner"
        - "Join_76_inner"
        - "OpeningBalance"
      DataSources:
        isCollapsed: false
        height: 2293.5
        width: 6760
        nodes:
        - "AccountingTransactionTypes"
        - "Summarize_108"
      Dates:
        isCollapsed: false
        height: 915
        width: 1000
        nodes:
        - "AlteryxSelect_107"
        - "AlteryxSelect_24"
        - "Facilities"
        - "Filter_23"
        - "Formula_27_0"
        - "Formula_29_0"
        - "SamtecFacilitie_106"
        - "TextInput_26"
        - "TextInput_26_cast"
      Facilities:
        isCollapsed: false
        height: 280
        width: 280
      OpeningBalance:
        isCollapsed: false
        height: 355.3333435058594
        width: 1200
        nodes:
        - "AlteryxSelect_39"
        - "AlteryxSelect_41"
        - "DynamicInput_40"
        - "Formula_44_0"
        - "Join_43_inner"
        - "Join_75_inner"
      PartNumber:
        isCollapsed: false
        height: 280
        width: 280
      Transactions:
        isCollapsed: false
        height: 1893.5
        width: 6290
        nodes:
        - "AlteryxSelect_62"
        - "AlteryxSelect_66"
        - "DynamicInput_63"
        - "Join_64_inner"
        - "Join_81_inner"
        - "Validation"
      UserInput:
        isCollapsed: false
        height: 2576.833251953125
        width: 8615
        nodes:
        - "AlteryxSelect_103"
        - "Cleanse_94"
        - "DataSources"
        - "Formula_92_0"
        - "Join_88_left_UnionFullOuter"
        - "Join_91_left_UnionFullOuter"
        - "Join_99_inner"
        - "MultiRowFormula_96"
        - "MultiRowFormula_96_window"
      Validation:
        isCollapsed: false
        height: 1693.5
        width: 5095
        nodes:
        - "AlteryxSelect_12"
        - "AlteryxSelect_37"
        - "AppendFields_16"
        - "ClosingBalance"
        - "Dates"
        - "Directory_11"
        - "Directory_11_reformat"
        - "Filter_15"
        - "Formula_13_0"
        - "PartNumber"
        - "Summarize_14"
        - "Test_18"
        - "TextInput_33"
        - "TextInput_33_cast"
