pipelines:
  POC_FLUFFY_TT:
    visualGroups:
      AllpossibleCNX:
        isCollapsed: false
        height: 1383
        width: 3098
        nodes:
        - "AlteryxSelect_40"
        - "AlteryxSelect_41"
        - "AlteryxSelect_42"
        - "AlteryxSelect_43"
        - "Filter_23"
        - "Filter_24"
        - "Filter_25"
        - "Filter_28"
        - "Formula_18_0"
        - "Formula_20_0"
        - "Formula_21_0"
        - "Formula_26_0"
        - "Join_14_inner"
        - "Join_19_inner"
        - "Join_22_inner"
        - "Join_27_inner"
        - "Union_32"
      Usagebasedonroute:
        isCollapsed: false
        height: 795
        width: 2550
        nodes:
        - "AlteryxSelect_176"
        - "Filter_58"
        - "Join_59_left_UnionLeftOuter"
        - "Join_61_left_UnionLeftOuter"
        - "Join_63_left_UnionLeftOuter"
        - "Join_65_left_UnionLeftOuter"
        - "Join_67_left_UnionLeftOuter"
        - "POC_TT_Paths_Pa_175"
  RM_SEM_V3:
    visualGroups:
      NEWMARKET:
        isCollapsed: false
        height: 540
        width: 1206
        nodes:
        - "Formula_385_0"
        - "Join_384_inner"
        - "Join_384_left"
        - "Join_387_right_UnionRightOuter"
        - "Summarize_386"
      OutputtoGoogleSheets:
        isCollapsed: true
        height: 72
        width: 434
        nodes:
        - "googlesheetsoutput_476"
      POTENTIALREVENUE:
        isCollapsed: false
        height: 675
        width: 1158
        nodes:
        - "Database__LOADI_394"
        - "Database__LOADI_395"
        - "Formula_392_0"
        - "Join_391_left_UnionFullOuter"
        - "Join_393_inner"
      TURNSEMOFFFOROD:
        isCollapsed: false
        height: 720
        width: 484
        nodes:
        - "AlteryxSelect_470"
        - "Formula_471_0"
      flows:
        isCollapsed: false
        height: 675
        width: 2766
        nodes:
        - "AlteryxSelect_443"
        - "Filter_439"
        - "Filter_441"
        - "Formula_442_0"
        - "Join_438_inner"
        - "Join_444_inner"
        - "Join_445_inner"
        - "MultiRowFormula_440"
        - "MultiRowFormula_440_row_id_0"
        - "MultiRowFormula_440_row_id_drop_0"
        - "Summarize_436"
      localcopy:
        isCollapsed: false
        height: 630
        width: 310
        nodes:
        - "SEM_Support_Lis_475"
  perpetual_inventory_details:
    visualGroups:
      AccountingTransactionTypes:
        isCollapsed: true
        height: 72
        width: 492
        nodes:
        - "AccountingTrans_98"
      ClosingBalance:
        isCollapsed: true
        height: 72
        width: 526
        nodes:
        - "AlteryxSelect_48"
        - "AlteryxSelect_50"
        - "DynamicInput_49"
        - "Formula_53_0"
        - "Join_52_inner"
        - "Join_76_inner"
      DataSources:
        isCollapsed: false
        height: 510
        width: 868
        nodes:
        - "AccountingTransactionTypes"
        - "ClosingBalance"
        - "OpeningBalance"
        - "Transactions"
      Dates:
        isCollapsed: true
        height: 72
        width: 452
        nodes:
        - "Formula_27_0"
        - "Formula_29_0"
        - "TextInput_26"
        - "TextInput_26_cast"
      Facilities:
        isCollapsed: true
        height: 72
        width: 400
        nodes:
        - "AlteryxSelect_107"
        - "AlteryxSelect_24"
        - "Filter_23"
        - "SamtecFacilitie_106"
      Filters:
        isCollapsed: false
        height: 366
        width: 552
        nodes:
        - "Dates"
        - "Facilities"
      OpeningBalance:
        isCollapsed: true
        height: 72
        width: 540
        nodes:
        - "AlteryxSelect_39"
        - "AlteryxSelect_41"
        - "DynamicInput_40"
        - "Formula_44_0"
        - "Join_43_inner"
        - "Join_75_inner"
      PartNumber:
        isCollapsed: true
        height: 72
        width: 532
        nodes:
        - "AlteryxSelect_37"
        - "TextInput_33"
        - "TextInput_33_cast"
      Transactions:
        isCollapsed: true
        height: 72
        width: 768
        nodes:
        - "AlteryxSelect_59"
        - "AlteryxSelect_62"
        - "AlteryxSelect_66"
        - "AppendFields_60"
        - "Directory_57"
        - "Directory_57_reformat"
        - "DynamicInput_63"
        - "Filter_61"
        - "Formula_58_0"
        - "Join_64_inner"
        - "Join_81_inner"
      UserInput:
        isCollapsed: false
        height: 654
        width: 772
        nodes:
        - "PartNumber"
        - "Validation"
      Validation:
        isCollapsed: true
        height: 72
        width: 674
        nodes:
        - "AlteryxSelect_12"
        - "AppendFields_16"
        - "Directory_11"
        - "Directory_11_reformat"
        - "Filter_15"
        - "Formula_13_0"
        - "Summarize_14"
        - "Test_18"
  subject_workflow:
    visualGroups:
      ALLSUBJECTDATA:
        isCollapsed: false
        height: 6273
        width: 4585
        nodes:
        - "ActiveTreatmentDate"
        - "AllStudySubjectCombinations"
        - "AlteryxSelect_213"
        - "AlteryxSelect_343"
        - "C459Specific"
        - "CohortStrataRaceEnthnicityGenderIRTrecords"
        - "CompletedDate"
        - "DiscontinuedDate"
        - "EnrolledDate"
        - "Filter_306"
        - "IRTandEDCSubjectStatuses"
        - "JoinMultiple_341"
        - "Join_210_inner"
        - "Join_210_left"
        - "TextInput_212"
        - "TextInput_212_cast"
      ActiveTreatmentDate:
        isCollapsed: false
        height: 891
        width: 1658
        nodes:
        - "AlteryxSelect_312"
        - "AlteryxSelect_316"
        - "Filter_308"
        - "Filter_314"
        - "Filter_315"
        - "Join_313_left_UnionFullOuter"
        - "Sample_309"
        - "Sample_310"
      AllStudySubjectCombinations:
        isCollapsed: false
        height: 546
        width: 526
        nodes:
        - "AlteryxSelect_232"
        - "Unique_233"
      C459Specific:
        isCollapsed: false
        height: 399
        width: 308
        nodes:
        - "Formula_208_0"
      CDMSubjectview:
        isCollapsed: false
        height: 774
        width: 700
        nodes:
        - "AlteryxSelect_438"
        - "Formula_439_0"
        - "aka_GPDIP_EDLUD_437"
      CohortStrataRaceEnthnicityGenderIRTrecords:
        isCollapsed: false
        height: 651
        width: 964
        nodes:
        - "AlteryxSelect_32"
        - "Filter_31_to_Filter_142"
        - "Sample_143"
      CohortsfromOverrideTableAquiredStudies:
        isCollapsed: false
        height: 1044
        width: 1898
        nodes:
        - "AlteryxSelect_421"
        - "AlteryxSelect_423"
        - "Formula_425_0"
        - "Join_420_inner"
        - "Join_422_inner"
        - "Summarize_416"
        - "Unique_424"
        - "aka_GPDIP_EDLUD_418"
        - "aka_enip164_Que_419"
      CompletedDate:
        isCollapsed: false
        height: 891
        width: 1658
        nodes:
        - "AlteryxSelect_323"
        - "AlteryxSelect_327"
        - "Filter_319"
        - "Filter_325"
        - "Filter_326"
        - "Join_324_left_UnionFullOuter"
        - "Sample_320"
        - "Sample_321"
      Container350:
        isCollapsed: false
        height: 900
        width: 1226
        nodes:
        - "AlteryxSelect_20"
        - "AlteryxSelect_25"
        - "AlteryxSelect_26"
        - "DynamicRename_22"
        - "DynamicRename_24"
        - "Filter_21"
        - "Filter_23"
      Container387:
        isCollapsed: false
        height: 630
        width: 316
        nodes:
        - "aka_GPD_UDDL_Wr_373"
      CountryNamefromSiteTable:
        isCollapsed: false
        height: 495
        width: 496
        nodes:
        - "aka_GPDIP_EDLUD_376"
      DATACLEANUP:
        isCollapsed: false
        height: 447
        width: 338
        nodes:
        - "Formula_433_to_Formula_380_0"
      DetermineOriginalSiteNumber:
        isCollapsed: false
        height: 822
        width: 2006
        nodes:
        - "AlteryxSelect_249"
        - "Filter_245_to_Filter_247"
        - "Formula_246_to_Formula_250_0"
        - "Formula_246_to_Formula_250_1"
        - "Join_242_left_UnionFullOuter"
        - "Join_367_inner"
        - "Unique_248"
        - "aka_GPDIP_EDLUD_368"
      DiscontinuedDate:
        isCollapsed: false
        height: 891
        width: 1658
        nodes:
        - "AlteryxSelect_334"
        - "AlteryxSelect_338"
        - "Filter_330"
        - "Filter_336"
        - "Filter_337"
        - "Join_335_left_UnionFullOuter"
        - "Sample_331"
        - "Sample_332"
      EDCSiteNumber:
        isCollapsed: false
        height: 1566
        width: 3986
        nodes:
        - "AlteryxSelect_267"
        - "Filter_252"
        - "Filter_254"
        - "Filter_259"
        - "Filter_259_reject"
        - "Formula_263_0"
        - "Join_255_inner"
        - "Join_255_left"
        - "Join_258_inner_formula"
        - "Sample_261"
        - "Sample_262"
        - "Sample_264"
        - "Summarize_253"
        - "Summarize_257"
        - "Summarize_257_filter"
        - "Transpose_256"
        - "Transpose_256_schemaTransform_0"
        - "Union_265"
      EnrolledDate:
        isCollapsed: false
        height: 891
        width: 1658
        nodes:
        - "AlteryxSelect_300"
        - "AlteryxSelect_304"
        - "Filter_295"
        - "Filter_302"
        - "Filter_303"
        - "Join_301_left_UnionFullOuter"
        - "Sample_297"
        - "Sample_298"
      ForceOverride:
        isCollapsed: false
        height: 798
        width: 482
        nodes:
        - "AlteryxSelect_444"
        - "Filter_446"
      GetSiteNumbersforSujectsfromSESOverrideTable:
        isCollapsed: false
        height: 399
        width: 752
        nodes:
        - "Summarize_402"
      IRTSiteNumber:
        isCollapsed: false
        height: 1566
        width: 3986
        nodes:
        - "AlteryxSelect_285"
        - "Filter_270"
        - "Filter_272"
        - "Filter_277"
        - "Filter_277_reject"
        - "Formula_281_0"
        - "Join_273_inner"
        - "Join_273_left"
        - "Join_276_inner_formula"
        - "Sample_279"
        - "Sample_280"
        - "Sample_282"
        - "Summarize_271"
        - "Summarize_275"
        - "Summarize_275_filter"
        - "Transpose_274"
        - "Transpose_274_schemaTransform_0"
        - "Union_283"
      IRTandEDCSubjectStatuses:
        isCollapsed: false
        height: 891
        width: 1970
        nodes:
        - "AlteryxSelect_149"
        - "AlteryxSelect_154"
        - "Filter_151"
        - "Filter_152"
        - "Filter_237"
        - "Join_153_left_UnionFullOuter"
        - "Sample_159"
        - "Sample_160"
      NotFoundinSubjectVisit:
        isCollapsed: false
        height: 792
        width: 962
        nodes:
        - "Join_347_inner"
        - "Sort_348"
        - "Summarize_215"
      SubjectCohorts:
        isCollapsed: false
        height: 2280
        width: 4251
        nodes:
        - "CohortsfromOverrideTableAquiredStudies"
        - "Filter_410"
        - "Filter_410_reject"
        - "Filter_411"
        - "Filter_411_reject"
        - "Filter_430"
        - "ForceOverride"
        - "Join_412_inner"
        - "Join_412_left"
        - "Join_413_inner"
        - "Join_413_left"
        - "Join_414_inner"
        - "Join_414_left"
        - "Join_427_left_UnionLeftOuter"
        - "Join_431_inner"
        - "Union_415"
        - "aka_GPDIP_EDLUD_443"
        - "replacedbysescohortmapping4302025csp"
      SubjectDatafromSUBJECTVISITtable:
        isCollapsed: false
        height: 3024
        width: 4242
        nodes:
        - "AlteryxSelect_10"
        - "AlteryxSelect_12"
        - "AlteryxSelect_14"
        - "AlteryxSelect_292"
        - "AlteryxSelect_3"
        - "AlteryxSelect_7"
        - "Container350"
        - "CrossTab_11"
        - "CrossTab_13"
        - "CrossTab_6"
        - "CrossTab_8"
        - "DynamicRename_351"
        - "Filter_381"
        - "Filter_381_reject"
        - "Formula_4_0"
        - "GetSiteNumbersforSujectsfromSESOverrideTable"
        - "JoinMultiple_15"
        - "aka_GPDIP_EDLUD_369"
      replacedbysescohortmapping4302025csp:
        isCollapsed: true
        height: 72
        width: 724
        nodes:
        - "AlteryxSelect_429"
        - "aka_GPDIP_EDLUD_428"
