---
version: 2
models:
- name: "Barrier_Bend_Monitoring_1_dgdvf__AlteryxSelect_80"
  tags:
  - "prophecy_temp"
- name: "Barrier_Bend_Monitoring_1_dgdvf__AlteryxSelect_84"
  tags:
  - "prophecy_temp"
- name: "Barrier_Bend_Monitoring_1_dgdvf__Formula_72_3"
  tags:
  - "prophecy_temp"
- name: "Barrier_Bend_Monitoring_1_dgdvf__Formula_85_0"
  tags:
  - "prophecy_temp"
