
name: "tb11"

config-version: 2
version: '0.1'

profile: 'prophecy-default'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  "+tblproperties":
    delta.columnMapping.mode: "name"
    delta.minReaderVersion: "2"
    delta.minWriterVersion: "5"

