---
version: 2
models:
- name: "LU_Document_Selection_Disabled__Join_308_inner"
  tags:
  - "prophecy_temp"
- name: "LU_Document_Selection_Disabled__Join_320_inner"
  tags:
  - "prophecy_temp"
- name: "LU_Document_Selection_Disabled__aka_GPD_UDDL_Wr_295"
  tags:
  - "prophecy_temp"
