entityType: ""
providerType: "BigQuery"
fields:
- name: "CASE_MGT_STTUS_DT"
  dataType:
    type: "Date"
- name: "MBR_INDV_BE_KEY"
  dataType:
    type: "String"
- name: "SUB_ID"
  dataType:
    type: "String"
- name: "PROC_CD_DESC"
  dataType:
    type: "String"
- name: "PROGRAM STATUS SCREENED"
  dataType:
    type: "String"
- name: "SECONDARY_MARA"
  dataType:
    type: "String"
- name: "SRC_SYS_CD"
  dataType:
    type: "String"
- name: "DSCHG_DT"
  dataType:
    type: "Date"
- name: "UM_SK"
  dataType:
    type: "Float"
- name: "UM_IP_CARE_TYP_NM"
  dataType:
    type: "String"
- name: "Reason 3 Strength"
  dataType:
    type: "String"
- name: "Prediction Score"
  dataType:
    type: "String"
- name: "MEMBER_TOUCH_AFTER_DISCHARGE_30"
  dataType:
    type: "String"
- name: "Reason 1 Feature"
  dataType:
    type: "String"
- name: "Prediction Value"
  dataType:
    type: "Float"
- name: "MBR_GNDR_NM"
  dataType:
    type: "String"
- name: "ER_COUNT"
  dataType:
    type: "Float"
- name: "Reason 2 Value"
  dataType:
    type: "String"
- name: "Reason 2 Feature"
  dataType:
    type: "String"
- name: "GRP_NM"
  dataType:
    type: "String"
- name: "GRP_ID"
  dataType:
    type: "String"
- name: "HYPERTENSION"
  dataType:
    type: "Float"
- name: "DIAG_CD_DESC"
  dataType:
    type: "String"
- name: "AGE"
  dataType:
    type: "Float"
- name: "Reason 3 Feature"
  dataType:
    type: "String"
- name: "Reason 2 Strength"
  dataType:
    type: "String"
- name: "EXPRNC_CAT_CD"
  dataType:
    type: "String"
- name: "TERTIARY_MARA"
  dataType:
    type: "String"
- name: "UM_IP_DSCHG_STTUS_NM"
  dataType:
    type: "String"
- name: "Congestive_Heart_Failure"
  dataType:
    type: "Float"
- name: "AMB_ISSUES"
  dataType:
    type: "String"
- name: "FULLY_INSURED"
  dataType:
    type: "String"
- name: "ATTRIBUTED"
  dataType:
    type: "String"
- name: "MBR_FULL_NM"
  dataType:
    type: "String"
- name: "Lngth_of_Hsptl_Stay"
  dataType:
    type: "String"
- name: "MEMBER_TOUCH_DAYS"
  dataType:
    type: "Float"
- name: "TOT_ALLW_AMT"
  dataType:
    type: "Float"
- name: "Chronic_Obstructive_Pulmonary_Disease"
  dataType:
    type: "Float"
- name: "PROGRAM STATUS ENROLLED"
  dataType:
    type: "String"
- name: "UM_REF_ID"
  dataType:
    type: "String"
- name: "Reason 3 Value"
  dataType:
    type: "String"
- name: "Reason 1 Strength"
  dataType:
    type: "String"
- name: "Model_Info"
  dataType:
    type: "String"
- name: "PAIN"
  dataType:
    type: "Float"
- name: "POPULATION_TYPE"
  dataType:
    type: "String"
- name: "DIABETES"
  dataType:
    type: "Float"
- name: "PRIMARY_MARA"
  dataType:
    type: "String"
- name: "Today_Date"
  dataType:
    type: "String"
- name: "UNIQUE_DRUG_CT_CURRENT"
  dataType:
    type: "Float"
- name: "FACILITY"
  dataType:
    type: "String"
- name: "IP_COUNT"
  dataType:
    type: "Float"
- name: "DM_CM_IN"
  dataType:
    type: "String"
- name: "Reason 1 Value"
  dataType:
    type: "String"
- name: "SPIRA_BENEFIT"
  dataType:
    type: "String"
