entityType: ""
providerType: "BigQuery"
fields:
- name: "ED Prediction Value"
  dataType:
    type: "Float"
- name: "LATEST_ED_DX"
  dataType:
    type: "String"
- name: "ER_COUNT"
  dataType:
    type: "Float"
- name: "ER_COUNT_PAST_3_MONTHS"
  dataType:
    type: "Float"
- name: "Member Individual Business Entity Key"
  dataType:
    type: "Float"
- name: "NONEMERGENT_COUNT_PAST_60"
  dataType:
    type: "Float"
- name: "ED_DSCHG_DT"
  dataType:
    type: "String"
- name: "NONEMERGENT_RATE"
  dataType:
    type: "Float"
- name: "ED Prediction Score"
  dataType:
    type: "String"
- name: "Rating Date"
  dataType:
    type: "String"
- name: "ER_COUNT_PAST_2_MONTHS"
  dataType:
    type: "Float"
- name: "FREQUENT_FLYER"
  dataType:
    type: "Float"
