---
version: 2
models:
- name: "4PL_Inventory_Report_1___AlteryxSelect_127"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___AlteryxSelect_139"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___CrossTab_67_1"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___Formula_119_0"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___LockInFilter_128"
  tags:
  - "prophecy_temp"
