---
version: 2
models:
- name: "m_mmrt_credit_card_cal_hist_sum_load_sunday__SM_ACCOUNT_GOOD_BAD"
  tags:
  - "prophecy_temp"
- name: "m_mmrt_credit_card_cal_hist_sum_load_sunday__SM_CREDIT_CARD_CAL_MTH_END_HIS"
  tags:
  - "prophecy_temp"
