# ==================
# Project Details
# ==================
name: "test_pandas_code"
config-version: 2
require-dbt-version:
- ">=1.0.0"
- "<2.0.0"
version: "0.1"
profile: "prophecy-default"

# ==================
# File Path Configs
# ==================
clean-targets:
- "target"
- "dbt_modules"
- "logs"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  ItemNumberUploa_75: ""
  MajorCodes_w_Bu_126: ""
  Source_File__ex_1: ""
  db_name: ""
  schema_name: ""
