---
version: 2
models:
- name: "Record_ID_sample_all__RecordID_124"
  tags:
  - "prophecy_temp"
- name: "Record_ID_sample_all__RecordID_125"
  tags:
  - "prophecy_temp"
- name: "Record_ID_sample_all__RecordID_138"
  tags:
  - "prophecy_temp"
- name: "Record_ID_sample_all__TextInput_123_cast"
  tags:
  - "prophecy_temp"
