{{
  config({    
    "materialized": "table",
    "alias": "SM_CREDIT_CARD_TRAN_MTH_END",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH SQ_DUMMY AS (

  SELECT *
  
  FROM {{ ref('m_mmrt_month_end_table_truncate__SQ_DUMMY')}}

),

SM_CREDIT_CARD_TRAN_MTH_END_EXP AS (

  SELECT 
    CAST(NULL AS NUMERIC) AS CLIENTID,
    VARCHAR2_COL AS HOUSEID,
    CAST(NULL AS STRING) AS CC_ACCOUNT_NUMBER,
    CAST(NULL AS NUMERIC) AS CC_TRANSACTION_ID,
    CAST(NULL AS STRING) AS CC_CARD_NUMBER,
    CAST(NULL AS STRING) AS CC_EFFECTIVE_DATE,
    CAST(NULL AS STRING) AS CC_TYPE,
    CAST(NULL AS NUMERIC) AS CC_MONETARY_CODE,
    CAST(NULL AS NUMERIC) AS CC_BILLED_AMOUNT,
    CAST(NULL AS STRING) AS CC_POSTING_DATE,
    CAST(NULL AS STRING) AS CC_AUTHORISATION_CODE,
    CAST(NULL AS NUMERIC) AS CC_PLAN_NUMBER,
    CAST(NULL AS STRING) AS CC_TRAMS_TYPE,
    CAST(NULL AS NUMERIC) AS CC_MERCHANT_CATEGORY,
    CAST(NULL AS NUMERIC) AS CC_INCOMING_INDICATOR,
    CAST(NULL AS STRING) AS CC_CARD_ACCEPTOR_ID,
    CAST(NULL AS STRING) AS CC_COUNTRY_CODE,
    CAST(NULL AS STRING) AS CC_TRANSACTION_GROUPING,
    CAST(NULL AS STRING) AS CC_MS_SPEND_INDICATOR,
    CAST(NULL AS STRING) AS CC_RETAILER_DESCRIPTION,
    CAST(NULL AS STRING) AS CC_DCA_RECOVERY_METHOD
  
  FROM SQ_DUMMY AS in0

)

SELECT *

FROM SM_CREDIT_CARD_TRAN_MTH_END_EXP
