---
version: 2
models:
- name: "m_mmrt_month_end_table_truncate__SM_CREDIT_CARD_TRAN_MTH_END"
  tags:
  - "prophecy_temp"
- name: "m_mmrt_month_end_table_truncate__SM_STORECARD_TRAN_MTH_END"
  tags:
  - "prophecy_temp"
- name: "m_mmrt_month_end_table_truncate__SQ_DUMMY"
  tags:
  - "prophecy_temp"
