{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH SQ_CARD_DETAILS_STAGING AS (

  SELECT *
  
  FROM {{ ref('m_rep_ohc_card_detail_closure__SQ_CARD_DETAILS_STAGING')}}

),

RTR_CHECK_EXISTS_ACCID_out1 AS (

  SELECT * 
  
  FROM SQ_CARD_DETAILS_STAGING AS in0
  
  WHERE (ACCID IS NOT NULL)

),

DBATTRIBUTE AS (

  SELECT * 
  
  FROM {{ source('transpiled_sources', 'DBATTRIBUTE') }}

),

RTR_CHECK_EXISTS_ACCID_EXPR_DEFAULT AS (

  SELECT 
    CARD_NUMBER AS CARD_NUMBER,
    ACCOUNT_NUMBER AS ACCOUNT_NUMBER2,
    ACTIVE_DATE AS ACTIVE_DATE,
    BLOCK_CODE AS BLOCK_CODE,
    EXPIRY_DATE AS EXPIRY_DATE,
    CARDHOLDER_FLAG AS CARDHOLDER_FLAG,
    NUMBER_CARDS AS NUMBER_CARDS,
    ACTV_RQD_CURR AS ACTV_RQD_CURR,
    ACTV_RQD_PREV AS ACTV_RQD_PREV,
    EMBOSSER_NAME1 AS EMBOSSER_NAME1,
    PRIOR_CARD_EXPIRY AS PRIOR_CARD_EXPIRY,
    PRY_SDY_IND AS PRY_SDY_IND,
    CURR_PREV_IND AS CURR_PREV_IND,
    ACTUAL_PROGRAM_ID AS ACTUAL_PROGRAM_ID,
    PREVIOUS_PROGRAM_ID AS PREVIOUS_PROGRAM_ID,
    ACCID AS ACCID,
    (ROW_NUMBER() OVER ()) AS prophecy_sk
  
  FROM RTR_CHECK_EXISTS_ACCID_out1 AS in0

),

EXP_CONSTRUCT_CARD_DETAIL_LOOKUP_124 AS (

  SELECT 
    in0.CURRVALUE AS LOOKUP_VARIABLE_4,
    in0.NAME AS NAME,
    in0.CURRVALUE AS CURRVALUE,
    in1.PREVIOUS_PROGRAM_ID AS PREVIOUS_PROGRAM_ID,
    in1.CARD_NUMBER AS CARD_NUMBER,
    in1.ACTIVE_DATE AS ACTIVE_DATE,
    in1.BLOCK_CODE AS BLOCK_CODE,
    in1.EXPIRY_DATE AS EXPIRY_DATE,
    in1.CARDHOLDER_FLAG AS CARDHOLDER_FLAG,
    in1.NUMBER_CARDS AS NUMBER_CARDS,
    in1.ACTV_RQD_CURR AS ACTV_RQD_CURR,
    in1.ACTV_RQD_PREV AS ACTV_RQD_PREV,
    in1.EMBOSSER_NAME1 AS EMBOSSER_NAME1,
    in1.PRIOR_CARD_EXPIRY AS PRIOR_CARD_EXPIRY,
    in1.PRY_SDY_IND AS PRY_SDY_IND,
    in1.CURR_PREV_IND AS CURR_PREV_IND,
    in1.ACCID AS ACCID,
    in1.ACTUAL_PROGRAM_ID AS ACTUAL_PROGRAM_ID,
    in1.prophecy_sk AS prophecy_sk
  
  FROM DBATTRIBUTE AS in0
  LEFT JOIN RTR_CHECK_EXISTS_ACCID_EXPR_DEFAULT AS in1
     ON (in0.NAME = 'businessdate')

),

EXP_CONSTRUCT_CARD_DETAIL_VARS_0 AS (

  SELECT 
    LOOKUP_VARIABLE_4 AS BUSINESS_DATE_STRING__find_business_date_lkp_1,
    *
  
  FROM EXP_CONSTRUCT_CARD_DETAIL_LOOKUP_124 AS in0

)

SELECT *

FROM EXP_CONSTRUCT_CARD_DETAIL_VARS_0
