{{
  config({    
    "materialized": "table",
    "alias": "MINERVA_EXCEPTION",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH SQ_CARD_DETAILS_STAGING AS (

  SELECT *
  
  FROM {{ ref('m_rep_ohc_card_detail_closure__SQ_CARD_DETAILS_STAGING')}}

),

DBATTRIBUTE AS (

  SELECT * 
  
  FROM {{ source('transpiled_sources', 'DBATTRIBUTE') }}

),

RTR_CHECK_EXISTS_ACCID_out0 AS (

  SELECT * 
  
  FROM SQ_CARD_DETAILS_STAGING AS in0
  
  WHERE (ACCID IS NULL)

),

RTR_CHECK_EXISTS_ACCID_EXPR_IS_NULL_ACCID AS (

  SELECT 
    CARD_NUMBER AS CARD_NUMBER1,
    ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
    ACTIVE_DATE AS ACTIVE_DATE1,
    BLOCK_CODE AS BLOCK_CODE1,
    EXPIRY_DATE AS EXPIRY_DATE1,
    CARDHOLDER_FLAG AS CARDHOLDER_FLAG1,
    NUMBER_CARDS AS NUMBER_CARDS1,
    ACTV_RQD_CURR AS ACTV_RQD_CURR1,
    ACTV_RQD_PREV AS ACTV_RQD_PREV1,
    EMBOSSER_NAME1 AS EMBOSSER_NAME11,
    PRIOR_CARD_EXPIRY AS PRIOR_CARD_EXPIRY1,
    PRY_SDY_IND AS PRY_SDY_IND1,
    CURR_PREV_IND AS CURR_PREV_IND1,
    ACTUAL_PROGRAM_ID AS ACTUAL_PROGRAM_ID1,
    PREVIOUS_PROGRAM_ID AS PREVIOUS_PROGRAM_ID1,
    ACCID AS ACCID1
  
  FROM RTR_CHECK_EXISTS_ACCID_out0 AS in0

),

EXP_CONSTRUCT_MINERVA_EXCEPTION_LOOKUP_125 AS (

  SELECT 
    in0.CURRVALUE AS LOOKUP_VARIABLE_5,
    in0.NAME AS NAME,
    in0.CURRVALUE AS CURRVALUE,
    in1.ACCOUNT_NUMBER AS ACCOUNT_NUMBER
  
  FROM DBATTRIBUTE AS in0
  LEFT JOIN RTR_CHECK_EXISTS_ACCID_EXPR_IS_NULL_ACCID AS in1
     ON (in0.NAME = 'businessdate')

),

EXP_CONSTRUCT_MINERVA_EXCEPTION_VARS_0 AS (

  SELECT 
    LOOKUP_VARIABLE_5 AS BUSINESS_DATE_STRING__find_business_date_lkp_2,
    *
  
  FROM EXP_CONSTRUCT_MINERVA_EXCEPTION_LOOKUP_125 AS in0

),

EXP_CONSTRUCT_MINERVA_EXCEPTION AS (

  SELECT 
    ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
    5052 AS CLASS,
    'm_rep_gems_card_detail_update' AS PROCESS_NAME,
    'Account not found for Gems Card Detail record' AS COMMENT,
    'rtr_check_exists_accid' AS FUNCTION_NAME,
    (
      CASE
        WHEN (
          (
            (
              CASE
                WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                  THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_2
                ELSE CAST(NULL AS STRING)
              END
            ) IS NULL
          )
          OR (
               (
                 LENGTH(
                   CAST((
                     CASE
                       WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                         THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_2
                       ELSE CAST(NULL AS STRING)
                     END
                   ) AS STRING))
               ) = 0
             )
        )
          THEN (ERROR('No Business date found on DBATTRIBUTE'))
        ELSE (
          PARSE_TIMESTAMP(
            '%Y%m%d', 
            CAST(SUBSTRING(
              (
                CASE
                  WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                    THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_2
                  ELSE CAST(NULL AS STRING)
                END
              ), 
              0, 
              8) AS STRING))
        )
      END
    ) AS BUSINESS_DATE,
    'N' AS LOAD_INDICATOR,
    'G' AS SOURCE_SYSTEM_CODE,
    1 AS ERROR_NUMBER
  
  FROM EXP_CONSTRUCT_MINERVA_EXCEPTION_VARS_0 AS in0

),

MINERVA_EXCEPTION_EXP AS (

  SELECT 
    CLASS AS CLASS,
    BUSINESS_DATE AS BUSINESS_DATE,
    CAST(NULL AS NUMERIC) AS CLID,
    CAST(NULL AS NUMERIC) AS ACCID,
    CAST(NULL AS NUMERIC) AS ADID,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    CAST(NULL AS STRING) AS SOURCE_CLIENT_REF,
    ACCOUNT_NUMBER AS ACCOUNT_ALIAS_ID,
    ERROR_NUMBER AS ERROR_NUMBER,
    PROCESS_NAME AS PROCESS_NAME,
    FUNCTION_NAME AS FUNCTION_NAME,
    CAST(NULL AS STRING) AS ADDITIONAL_IDENTIFIER,
    CAST(NULL AS NUMERIC) AS ADDITIONAL_IDENTIFIER_TYPE,
    LOAD_INDICATOR AS LOAD_INDICATOR,
    COMMENT AS EXCEPTION_COMMENT
  
  FROM EXP_CONSTRUCT_MINERVA_EXCEPTION AS in0

)

SELECT *

FROM MINERVA_EXCEPTION_EXP
