---
version: 2
models:
- name: "m_rep_ohc_card_detail_closure__CLOSE_CARD_DETAIL"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_card_detail_closure__EXP_CONSTRUCT_CARD_DETAIL_VARS_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_card_detail_closure__MINERVA_EXCEPTION"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_card_detail_closure__SQ_CARD_DETAILS_STAGING"
  tags:
  - "prophecy_temp"
