{{
  config({    
    "materialized": "table",
    "alias": "WORK_CARDS_ORIG_STAGING",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH MinervaRepository AS (

  SELECT * 
  
  FROM {{ source('transpiled_sources', 'MinervaRepository') }}

),

exp_trim AS (

  SELECT 
    (LTRIM((RTRIM(PRODUCT_CODE)))) AS OUT_PRODUCT_CODE,
    (LTRIM((RTRIM(UPPER(PRODUCT))))) AS OUT_PRODUCT,
    (LTRIM((RTRIM(PRODUCT_NUMBER)))) AS OUT_PRODUCT_NUMBER,
    (LTRIM((RTRIM(APPLICATION_NUMBER)))) AS OUT_APPLICATION_NUMBER,
    (LTRIM((RTRIM(CUSTOMER_NUMBER)))) AS OUT_CUSTOMER_NUMBER,
    (LTRIM((RTRIM(APPLICATION_SOURCE_CODE)))) AS OUT_APPLICATION_SOURCE_CODE,
    (LTRIM((RTRIM(UPPER(APPLICATION_TYPE))))) AS OUT_APPLICATION_TYPE,
    (LTRIM((RTRIM(APPLICATION_STORE_NUMBER)))) AS OUT_APPLICATION_STORE_NUMBER,
    (LTRIM((RTRIM(OFFER_ID)))) AS OUT_OFFER_ID,
    CASE
      WHEN (ltrim(rtrim(LAST_ACTION_DATE)) = NULL)
        THEN NULL
      WHEN (ltrim(rtrim(LAST_ACTION_DATE)) = '')
        THEN NULL
      ELSE to_timestamp(LAST_ACTION_DATE, 'yyyy-MM-dd"\'T\'"HH:mm:ss')
    END AS OUT_LAST_ACTION_DATE,
    CASE
      WHEN (ltrim(rtrim(LAST_DECISION_DATE)) = NULL)
        THEN NULL
      WHEN (ltrim(rtrim(LAST_DECISION_DATE)) = '')
        THEN NULL
      ELSE to_timestamp(LAST_DECISION_DATE, 'yyyy-MM-dd"\'T\'"HH:mm:ss')
    END AS OUT_LAST_DECISION_DATE,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(APPLICATION_DATE)))) AS STRING) = '')
          THEN NULL
        ELSE (PARSE_DATE('%Y-%m-%d"T"%H24:MI:%f%f.M%f"%%z"', APPLICATION_DATE))
      END
    ) AS OUT_APPLICATION_DATE,
    (LTRIM((RTRIM(APPLICATION_STATUS)))) AS OUT_APPLICATION_STATUS,
    (LTRIM((RTRIM(APPLICATION_ID)))) AS OUT_APPLICATION_ID,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(APPLICATION_EXPIRY_DATETIME)))) AS STRING) = '')
          THEN NULL
        ELSE (PARSE_DATE('%Y-%m-%d"T"%H24:MI:%f%f.M%f"%%z"', APPLICATION_EXPIRY_DATETIME))
      END
    ) AS OUT_APPLICATION_EXPIRY_DATETIME,
    (LTRIM((RTRIM(CREATE_CUSTOMER_RESULT)))) AS OUT_CREATE_CUSTOMER_RESULT,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(ACCOUNT_NUMBER)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(ACCOUNT_NUMBER AS STRING)
      END
    ) AS OUT_ACCOUNT_NUMBER,
    (LTRIM((RTRIM(CARD_CREATION_STATUS)))) AS OUT_CARD_CREATION_STATUS,
    (LTRIM((RTRIM(CARD_SYNC_STATUS)))) AS OUT_CARD_SYNC_STATUS,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(CARD_EXPIRY_DATE)))) AS STRING) = '')
          THEN NULL
        ELSE (PARSE_DATE('%Y-%m-%d"T"%H24:MI:%f%f.M%f"%%z"', CARD_EXPIRY_DATE))
      END
    ) AS OUT_CARD_EXPIRY_DATE,
    (LTRIM((RTRIM(CARD_TOKENIZATION_RESULT)))) AS OUT_CARD_TOKENIZATION_RESULT,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(TERMS_AND_CONDITIONS_ACCEPTANCE_TIMESTAMP)))) AS STRING) = '')
          THEN NULL
        ELSE (PARSE_DATE('%Y-%m-%d"T"%H24:MI:%f%f.M%f"%%z"', TERMS_AND_CONDITIONS_ACCEPTANCE_TIMESTAMP))
      END
    ) AS OUT_TERMS_AND_CONDITIONS_ACCEPTANCE_TIMESTAMP,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(AGREEMENT_SIGNED_TIMESTAMP)))) AS STRING) = '')
          THEN NULL
        ELSE (PARSE_DATE('%Y-%m-%d"T"%H24:MI:%f%f.M%f"%%z"', AGREEMENT_SIGNED_TIMESTAMP))
      END
    ) AS OUT_AGREEMENT_SIGNED_TIMESTAMP,
    (LTRIM((RTRIM(INITIAL_OVERALL_DECISION)))) AS OUT_INITIAL_OVERALL_DECISION,
    (LTRIM((RTRIM(INITIAL_OVERALL_DECISION_REASON_CODES)))) AS OUT_INITIAL_OVERALL_DECISION_REASON_CODES,
    (LTRIM((RTRIM(FINAL_CREDIT_DECISION_RESULT)))) AS OUT_FINAL_CREDIT_DECISION_RESULT,
    (LTRIM((RTRIM(FINAL_CREDIT_DECISION_REASON_CODES)))) AS OUT_FINAL_CREDIT_DECISION_REASON_CODES,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(FINAL_DECISION_DATE)))) AS STRING) = '')
          THEN NULL
        ELSE (PARSE_DATE('%Y-%m-%d"T"%H24:MI:%f%f', FINAL_DECISION_DATE))
      END
    ) AS OUT_FINAL_DECISION_DATE,
    (LTRIM((RTRIM(DUPLICATE_CUSTOMER)))) AS OUT_DUPLICATE_CUSTOMER,
    (LTRIM((RTRIM(RTS_TRANSACTION_STATUS)))) AS OUT_RTS_TRANSACTION_STATUS,
    (LTRIM((RTRIM(RTS_RSS_TRANSACTION_ID)))) AS OUT_RTS_RSS_TRANSACTION_ID,
    (LTRIM((RTRIM(IDENTITIY_VERIFICATION_MECHANISM)))) AS OUT_IDENTITIY_VERIFICATION_MECHANISM,
    (LTRIM((RTRIM(IDENTITY_VERIFICATION_STATUS)))) AS OUT_IDENTITY_VERIFICATION_STATUS,
    (LTRIM((RTRIM(IDENTITY_VERIFICATION_STATUS_REASON_DESCRIPTION)))) AS OUT_IDENTITY_VERIFICATION_STATUS_REASON_DESCRIPTION,
    (LTRIM((RTRIM(DIGITAL_VERIFICATION_MECHANISM)))) AS OUT_DIGITAL_VERIFICATION_MECHANISM,
    (LTRIM((RTRIM(DIGITAL_VERIFICATION_CHECK)))) AS OUT_DIGITAL_VERIFICATION_CHECK,
    (LTRIM((RTRIM(DIGITAL_VERIFICATION_CHECK_REASON_DESCRIPTION)))) AS OUT_DIGITAL_VERIFICATION_CHECK_REASON_DESCRIPTION,
    (LTRIM((RTRIM(BANK_VERIFICATION_CHECK_MECHANISM)))) AS OUT_BANK_VERIFICATION_CHECK_MECHANISM,
    (LTRIM((RTRIM(BANK_VERIFICATION_CHECK)))) AS OUT_BANK_VERIFICATION_CHECK,
    (LTRIM((RTRIM(BANK_VERIFICATION_CHECK_REASON_DESCRIPTION)))) AS OUT_BANK_VERIFICATION_CHECK_REASON_DESCRIPTION,
    (LTRIM((RTRIM(FRAUD_RESULT)))) AS OUT_FRAUD_RESULT,
    (LTRIM((RTRIM(FRAUD_REASON)))) AS OUT_FRAUD_REASON,
    (LTRIM((RTRIM(CREDIT_DECISION_RESULT)))) AS OUT_CREDIT_DECISION_RESULT,
    (LTRIM((RTRIM(CREDIT_DECISION_REASONS)))) AS OUT_CREDIT_DECISION_REASONS,
    (LTRIM((RTRIM(CREDIT_DECISION_OFFERID_REQUESTED)))) AS OUT_CREDIT_DECISION_OFFERID_REQUESTED,
    (LTRIM((RTRIM(CREDIT_DECISION_OFFERID_APPROVED)))) AS OUT_CREDIT_DECISION_OFFERID_APPROVED,
    (LTRIM((RTRIM(CREDIT_DECISION_TOTAL_AMOUNT_TO_PAY)))) AS OUT_CREDIT_DECISION_TOTAL_AMOUNT_TO_PAY,
    (LTRIM((RTRIM(CREDIT_DECISION_BASE_PRICING_CODE)))) AS OUT_CREDIT_DECISION_BASE_PRICING_CODE,
    (LTRIM((RTRIM(CREDIT_DECISION_OFFER_PRICING_CODE)))) AS OUT_CREDIT_DECISION_OFFER_PRICING_CODE,
    (LTRIM((RTRIM(CDD_PROFILEID)))) AS OUT_CDD_PROFILEID,
    (LTRIM((RTRIM(CDD_RESULT)))) AS OUT_CDD_RESULT,
    (LTRIM((RTRIM(CDD_INFORMATION_DETAILS_RISK_RATING)))) AS OUT_CDD_INFORMATION_DETAILS_RISK_RATING,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(APPLICATION_SCORE)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(APPLICATION_SCORE AS STRING)
      END
    ) AS OUT_APPLICATION_SCORE,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(FIRST_PARTY_FRAUD_SCORE)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(FIRST_PARTY_FRAUD_SCORE AS STRING)
      END
    ) AS OUT_FIRST_PARTY_FRAUD_SCORE,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(CIISCORE)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(CIISCORE AS STRING)
      END
    ) AS OUT_CIISCORE,
    (LTRIM((RTRIM(TITLE)))) AS OUT_TITLE,
    (LTRIM((RTRIM(FIRSTNAMES)))) AS OUT_FIRSTNAMES,
    (LTRIM((RTRIM(LASTNAME)))) AS OUT_LASTNAME,
    (LTRIM((RTRIM(HAS_PREVIOUS_NAMES)))) AS OUT_HAS_PREVIOUS_NAMES,
    (LTRIM((RTRIM(ORIGINAL_FIRSTNAME)))) AS OUT_ORIGINAL_FIRSTNAME,
    (LTRIM((RTRIM(ORIGINAL_LASTNAME)))) AS OUT_ORIGINAL_LASTNAME,
    (LTRIM((RTRIM(PREVIOUS_TITLE)))) AS OUT_PREVIOUS_TITLE,
    (LTRIM((RTRIM(PREVIOUS_FIRSTNAMES)))) AS OUT_PREVIOUS_FIRSTNAMES,
    (LTRIM((RTRIM(PREVIOUS_LASTNAMES)))) AS OUT_PREVIOUS_LASTNAMES,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(DATE_OF_BIRTH)))) AS STRING) = '')
          THEN NULL
        ELSE (PARSE_TIMESTAMP('%Y-%m-%d', DATE_OF_BIRTH))
      END
    ) AS OUT_DATE_OF_BIRTH,
    (LTRIM((RTRIM(GENDER)))) AS OUT_GENDER,
    (LTRIM((RTRIM(NATIONALITIES)))) AS OUT_NATIONALITIES,
    (LTRIM((RTRIM(NATIONALITY1)))) AS OUT_NATIONALITY1,
    (LTRIM((RTRIM(NATIONALITY2)))) AS OUT_NATIONALITY2,
    (LTRIM((RTRIM(NATIONALITY3)))) AS OUT_NATIONALITY3,
    (LTRIM((RTRIM(MARITAL_STATUS)))) AS OUT_MARITAL_STATUS,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(NUMBER_OF_DEPENDENTS)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(NUMBER_OF_DEPENDENTS AS STRING)
      END
    ) AS OUT_NUMBER_OF_DEPENDENTS,
    (LTRIM((RTRIM(EMAIL)))) AS OUT_EMAIL,
    (LTRIM((RTRIM(TELEPHONE_NUMBER)))) AS OUT_TELEPHONE_NUMBER,
    (LTRIM((RTRIM(ADDRESSLINE1)))) AS OUT_ADDRESSLINE1,
    (LTRIM((RTRIM(ADDRESSLINE2)))) AS OUT_ADDRESSLINE2,
    (LTRIM((RTRIM(ADDRESSLINE3)))) AS OUT_ADDRESSLINE3,
    (LTRIM((RTRIM(ADDRESSLINE4)))) AS OUT_ADDRESSLINE4,
    (LTRIM((RTRIM(ADDRESSLINE5)))) AS OUT_ADDRESSLINE5,
    (LTRIM((RTRIM(ADDRESSLINE6)))) AS OUT_ADDRESSLINE6,
    (LTRIM((RTRIM(POSTCODE)))) AS OUT_POSTCODE,
    (LTRIM((RTRIM(COUNTRY)))) AS OUT_COUNTRY,
    (LTRIM((RTRIM(PREVIOUS_ADDRESSES_ADDRESS_LINE1)))) AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE1,
    (LTRIM((RTRIM(PREVIOUS_ADDRESSES_ADDRESS_LINE2)))) AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE2,
    (LTRIM((RTRIM(PREVIOUS_ADDRESSES_ADDRESS_LINE3)))) AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE3,
    (LTRIM((RTRIM(PREVIOUS_ADDRESSES_ADDRESS_LINE4)))) AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE4,
    (LTRIM((RTRIM(PREVIOUS_ADDRESSES_ADDRESS_LINE5)))) AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE5,
    (LTRIM((RTRIM(PREVIOUS_ADDRESSES_ADDRESS_LINE6)))) AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE6,
    (LTRIM((RTRIM(PREVIOUS_ADDRESSES_POSTCODE)))) AS OUT_PREVIOUS_ADDRESSES_POSTCODE,
    (LTRIM((RTRIM(PREVIOUS_ADDRESSES_COUNTRY)))) AS OUT_PREVIOUS_ADDRESSES_COUNTRY,
    (LTRIM((RTRIM((REGEXP_REPLACE(PREVIOUS_ADDRESSES_MOVED_IN_DATE, '(?i)[', '')))))) AS OUT_PREVIOUS_ADDRESSES_MOVED_IN_DATE,
    (LTRIM((RTRIM(RESIDENTIAL_STATUS)))) AS OUT_RESIDENTIAL_STATUS,
    (LTRIM((RTRIM((REGEXP_REPLACE(RESIDENTIAL_MOVED_IN_DATE, '(?i)[', '')))))) AS OUT_RESIDENTIAL_MOVED_IN_DATE,
    (LTRIM((RTRIM(EMPLOYMENT_STATUS)))) AS OUT_EMPLOYMENT_STATUS,
    (LTRIM((RTRIM(OCCUPATION)))) AS OUT_OCCUPATION,
    (LTRIM((RTRIM(EMPLOYMENT_ROLE)))) AS OUT_EMPLOYMENT_ROLE,
    (LTRIM((RTRIM(BUSINESSNAME)))) AS OUT_BUSINESSNAME,
    (LTRIM((RTRIM(CREDIT_LIMIT_INCREASE_OPTION)))) AS OUT_CREDIT_LIMIT_INCREASE_OPTION,
    (LTRIM((RTRIM(FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES)))) AS OUT_FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES,
    (LTRIM((RTRIM(CREDIT_REQUESTED_CURRENCY)))) AS OUT_CREDIT_REQUESTED_CURRENCY,
    (LTRIM((RTRIM(DIRECT_DEBIT_SORT_CODE)))) AS OUT_DIRECT_DEBIT_SORT_CODE,
    (LTRIM((RTRIM(DIRECT_DEBIT_ACCOUNT_NUMBER)))) AS OUT_DIRECT_DEBIT_ACCOUNT_NUMBER,
    (LTRIM((RTRIM(DIRECT_DEBIT_BALANCE_PAYMENT_OPTION)))) AS OUT_DIRECT_DEBIT_BALANCE_PAYMENT_OPTION,
    (LTRIM((RTRIM(DIRECT_DEBIT_SETUP_STATUS)))) AS OUT_DIRECT_DEBIT_SETUP_STATUS,
    (LTRIM((RTRIM(DIRECT_DEBIT_SETUP_REPAYMENTS)))) AS OUT_DIRECT_DEBIT_SETUP_REPAYMENTS,
    (LTRIM((RTRIM(DIRECT_DEBIT_ACCOUNT_HOLDER_FULLNAME)))) AS OUT_DIRECT_DEBIT_ACCOUNT_HOLDER_FULLNAME,
    (LTRIM((RTRIM(MARKETING_PREFERENCES_OPT_INFORMATION)))) AS OUT_MARKETING_PREFERENCES_OPT_INFORMATION,
    (LTRIM((RTRIM((REGEXP_REPLACE(MARKETING_PREFERENCES_PREFERRED_CHANNELS, '(?i)[', NULL)))))) AS OUT_MARKETING_PREFERENCES_PREFERRED_CHANNELS,
    (LTRIM((RTRIM((REGEXP_REPLACE(EMPLOYMENT_MAIN_STARTDATE, '(?i)[', '')))))) AS OUT_EMPLOYMENT_MAIN_STARTDATE,
    (LTRIM((RTRIM((REGEXP_REPLACE(EMPLOYMENT_PART_TIME_STARTDATE, '(?i)[', '')))))) AS OUT_EMPLOYMENT_PART_TIME_STARTDATE,
    (ROW_NUMBER() OVER ()) AS prophecy_sk
  
  FROM MinervaRepository AS in0

),

exp_trim_decimal AS (

  SELECT 
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(OFFERED_LIMIT_AMOUNT)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(OFFERED_LIMIT_AMOUNT AS STRING)
      END
    ) AS OUT_OFFERED_LIMIT_AMOUNT,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(ANNUAL_SALARY_AMOUNT)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(ANNUAL_SALARY_AMOUNT AS STRING)
      END
    ) AS OUT_ANNUAL_SALARY_AMOUNT,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(ANNUAL_INCOME_AMOUNT)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(ANNUAL_INCOME_AMOUNT AS STRING)
      END
    ) AS OUT_ANNUAL_INCOME_AMOUNT,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER AS STRING)
      END
    ) AS OUT_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE AS STRING)
      END
    ) AS OUT_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(DELPHI_SCORE)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(DELPHI_SCORE AS STRING)
      END
    ) AS OUT_DELPHI_SCORE,
    (
      CASE
        WHEN (CAST((LTRIM((RTRIM(CREDIT_REQUESTED_AMOUNT)))) AS STRING) = '')
          THEN NULL
        ELSE CAST(CREDIT_REQUESTED_AMOUNT AS STRING)
      END
    ) AS OUT_CREDIT_REQUESTED_AMOUNT,
    (ROW_NUMBER() OVER ()) AS prophecy_sk
  
  FROM MinervaRepository AS in0

),

WORK_CARDS_ORIG_STAGING_EXP_JOIN AS (

  SELECT 
    in0.OUT_OFFERED_LIMIT_AMOUNT AS OUT_OFFERED_LIMIT_AMOUNT,
    in1.OUT_RESIDENTIAL_MOVED_IN_DATE AS OUT_RESIDENTIAL_MOVED_IN_DATE,
    in1.OUT_OFFER_ID AS OUT_OFFER_ID,
    in1.OUT_ACCOUNT_NUMBER AS OUT_ACCOUNT_NUMBER,
    in1.OUT_EMPLOYMENT_MAIN_STARTDATE AS OUT_EMPLOYMENT_MAIN_STARTDATE,
    in1.OUT_FRAUD_RESULT AS OUT_FRAUD_RESULT,
    in1.OUT_NATIONALITY1 AS OUT_NATIONALITY1,
    in1.OUT_CREDIT_DECISION_REASONS AS OUT_CREDIT_DECISION_REASONS,
    in0.OUT_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER AS OUT_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER,
    in1.OUT_BUSINESSNAME AS OUT_BUSINESSNAME,
    in1.OUT_FINAL_CREDIT_DECISION_REASON_CODES AS OUT_FINAL_CREDIT_DECISION_REASON_CODES,
    in1.OUT_DUPLICATE_CUSTOMER AS OUT_DUPLICATE_CUSTOMER,
    in1.OUT_NATIONALITIES AS OUT_NATIONALITIES,
    in1.OUT_DIRECT_DEBIT_ACCOUNT_NUMBER AS OUT_DIRECT_DEBIT_ACCOUNT_NUMBER,
    in1.OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE2 AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE2,
    in1.OUT_EMPLOYMENT_PART_TIME_STARTDATE AS OUT_EMPLOYMENT_PART_TIME_STARTDATE,
    in1.OUT_ADDRESSLINE6 AS OUT_ADDRESSLINE6,
    in1.OUT_FIRST_PARTY_FRAUD_SCORE AS OUT_FIRST_PARTY_FRAUD_SCORE,
    in1.OUT_CDD_PROFILEID AS OUT_CDD_PROFILEID,
    in1.OUT_CARD_EXPIRY_DATE AS OUT_CARD_EXPIRY_DATE,
    in0.OUT_ANNUAL_INCOME_AMOUNT AS OUT_ANNUAL_INCOME_AMOUNT,
    in1.OUT_PRODUCT_CODE AS OUT_PRODUCT_CODE,
    in1.OUT_IDENTITY_VERIFICATION_STATUS_REASON_DESCRIPTION AS OUT_IDENTITY_VERIFICATION_STATUS_REASON_DESCRIPTION,
    in1.OUT_ADDRESSLINE2 AS OUT_ADDRESSLINE2,
    in1.OUT_CREDIT_DECISION_RESULT AS OUT_CREDIT_DECISION_RESULT,
    in1.OUT_CARD_CREATION_STATUS AS OUT_CARD_CREATION_STATUS,
    in1.OUT_CARD_TOKENIZATION_RESULT AS OUT_CARD_TOKENIZATION_RESULT,
    in1.OUT_PREVIOUS_TITLE AS OUT_PREVIOUS_TITLE,
    in1.OUT_DIGITAL_VERIFICATION_MECHANISM AS OUT_DIGITAL_VERIFICATION_MECHANISM,
    in1.OUT_PREVIOUS_ADDRESSES_COUNTRY AS OUT_PREVIOUS_ADDRESSES_COUNTRY,
    in1.OUT_CREDIT_DECISION_OFFERID_REQUESTED AS OUT_CREDIT_DECISION_OFFERID_REQUESTED,
    in1.OUT_MARKETING_PREFERENCES_OPT_INFORMATION AS OUT_MARKETING_PREFERENCES_OPT_INFORMATION,
    in1.OUT_FINAL_CREDIT_DECISION_RESULT AS OUT_FINAL_CREDIT_DECISION_RESULT,
    in1.OUT_FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES AS OUT_FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES,
    in1.OUT_PREVIOUS_ADDRESSES_POSTCODE AS OUT_PREVIOUS_ADDRESSES_POSTCODE,
    in1.OUT_APPLICATION_SCORE AS OUT_APPLICATION_SCORE,
    in1.OUT_NATIONALITY2 AS OUT_NATIONALITY2,
    in1.OUT_INITIAL_OVERALL_DECISION AS OUT_INITIAL_OVERALL_DECISION,
    in1.OUT_APPLICATION_NUMBER AS OUT_APPLICATION_NUMBER,
    in1.OUT_DIRECT_DEBIT_ACCOUNT_HOLDER_FULLNAME AS OUT_DIRECT_DEBIT_ACCOUNT_HOLDER_FULLNAME,
    in1.OUT_CARD_SYNC_STATUS AS OUT_CARD_SYNC_STATUS,
    in1.OUT_DIRECT_DEBIT_SETUP_REPAYMENTS AS OUT_DIRECT_DEBIT_SETUP_REPAYMENTS,
    in1.OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE3 AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE3,
    in1.OUT_CDD_RESULT AS OUT_CDD_RESULT,
    in1.OUT_EMPLOYMENT_STATUS AS OUT_EMPLOYMENT_STATUS,
    in1.OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE4 AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE4,
    in1.OUT_CREATE_CUSTOMER_RESULT AS OUT_CREATE_CUSTOMER_RESULT,
    in1.OUT_COUNTRY AS OUT_COUNTRY,
    in1.OUT_APPLICATION_EXPIRY_DATETIME AS OUT_APPLICATION_EXPIRY_DATETIME,
    in1.OUT_APPLICATION_SOURCE_CODE AS OUT_APPLICATION_SOURCE_CODE,
    in1.OUT_NUMBER_OF_DEPENDENTS AS OUT_NUMBER_OF_DEPENDENTS,
    in1.OUT_ADDRESSLINE5 AS OUT_ADDRESSLINE5,
    in1.OUT_DIRECT_DEBIT_BALANCE_PAYMENT_OPTION AS OUT_DIRECT_DEBIT_BALANCE_PAYMENT_OPTION,
    in1.OUT_LAST_DECISION_DATE AS OUT_LAST_DECISION_DATE,
    in1.OUT_IDENTITY_VERIFICATION_STATUS AS OUT_IDENTITY_VERIFICATION_STATUS,
    in1.OUT_PRODUCT_NUMBER AS OUT_PRODUCT_NUMBER,
    in1.OUT_BANK_VERIFICATION_CHECK_MECHANISM AS OUT_BANK_VERIFICATION_CHECK_MECHANISM,
    in1.OUT_APPLICATION_DATE AS OUT_APPLICATION_DATE,
    in1.OUT_TITLE AS OUT_TITLE,
    in1.OUT_FINAL_DECISION_DATE AS OUT_FINAL_DECISION_DATE,
    in1.OUT_FIRSTNAMES AS OUT_FIRSTNAMES,
    in1.OUT_DIGITAL_VERIFICATION_CHECK_REASON_DESCRIPTION AS OUT_DIGITAL_VERIFICATION_CHECK_REASON_DESCRIPTION,
    in1.OUT_CIISCORE AS OUT_CIISCORE,
    in1.OUT_MARKETING_PREFERENCES_PREFERRED_CHANNELS AS OUT_MARKETING_PREFERENCES_PREFERRED_CHANNELS,
    in1.OUT_APPLICATION_STATUS AS OUT_APPLICATION_STATUS,
    in1.OUT_ORIGINAL_FIRSTNAME AS OUT_ORIGINAL_FIRSTNAME,
    in1.OUT_APPLICATION_TYPE AS OUT_APPLICATION_TYPE,
    in1.OUT_EMPLOYMENT_ROLE AS OUT_EMPLOYMENT_ROLE,
    in1.OUT_IDENTITIY_VERIFICATION_MECHANISM AS OUT_IDENTITIY_VERIFICATION_MECHANISM,
    in1.OUT_PREVIOUS_FIRSTNAMES AS OUT_PREVIOUS_FIRSTNAMES,
    in1.OUT_NATIONALITY3 AS OUT_NATIONALITY3,
    in1.OUT_TERMS_AND_CONDITIONS_ACCEPTANCE_TIMESTAMP AS OUT_TERMS_AND_CONDITIONS_ACCEPTANCE_TIMESTAMP,
    in1.OUT_RTS_RSS_TRANSACTION_ID AS OUT_RTS_RSS_TRANSACTION_ID,
    in1.OUT_ADDRESSLINE4 AS OUT_ADDRESSLINE4,
    in0.OUT_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE AS OUT_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE,
    in1.OUT_CREDIT_DECISION_TOTAL_AMOUNT_TO_PAY AS OUT_CREDIT_DECISION_TOTAL_AMOUNT_TO_PAY,
    in1.OUT_FRAUD_REASON AS OUT_FRAUD_REASON,
    in1.OUT_BANK_VERIFICATION_CHECK_REASON_DESCRIPTION AS OUT_BANK_VERIFICATION_CHECK_REASON_DESCRIPTION,
    in1.OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE6 AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE6,
    in0.prophecy_sk AS prophecy_sk,
    in1.OUT_OCCUPATION AS OUT_OCCUPATION,
    in1.OUT_DIRECT_DEBIT_SORT_CODE AS OUT_DIRECT_DEBIT_SORT_CODE,
    in0.OUT_DELPHI_SCORE AS OUT_DELPHI_SCORE,
    in1.OUT_CREDIT_DECISION_OFFER_PRICING_CODE AS OUT_CREDIT_DECISION_OFFER_PRICING_CODE,
    in1.OUT_PRODUCT AS OUT_PRODUCT,
    in1.OUT_CREDIT_DECISION_BASE_PRICING_CODE AS OUT_CREDIT_DECISION_BASE_PRICING_CODE,
    in1.OUT_INITIAL_OVERALL_DECISION_REASON_CODES AS OUT_INITIAL_OVERALL_DECISION_REASON_CODES,
    in1.OUT_LAST_ACTION_DATE AS OUT_LAST_ACTION_DATE,
    in1.OUT_HAS_PREVIOUS_NAMES AS OUT_HAS_PREVIOUS_NAMES,
    in1.OUT_DATE_OF_BIRTH AS OUT_DATE_OF_BIRTH,
    in1.OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE1 AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE1,
    in1.OUT_RESIDENTIAL_STATUS AS OUT_RESIDENTIAL_STATUS,
    in1.OUT_PREVIOUS_ADDRESSES_MOVED_IN_DATE AS OUT_PREVIOUS_ADDRESSES_MOVED_IN_DATE,
    in1.OUT_CUSTOMER_NUMBER AS OUT_CUSTOMER_NUMBER,
    in1.OUT_AGREEMENT_SIGNED_TIMESTAMP AS OUT_AGREEMENT_SIGNED_TIMESTAMP,
    in1.OUT_DIRECT_DEBIT_SETUP_STATUS AS OUT_DIRECT_DEBIT_SETUP_STATUS,
    in1.OUT_APPLICATION_STORE_NUMBER AS OUT_APPLICATION_STORE_NUMBER,
    in1.OUT_RTS_TRANSACTION_STATUS AS OUT_RTS_TRANSACTION_STATUS,
    in1.OUT_PREVIOUS_LASTNAMES AS OUT_PREVIOUS_LASTNAMES,
    in1.OUT_EMAIL AS OUT_EMAIL,
    in1.OUT_ADDRESSLINE1 AS OUT_ADDRESSLINE1,
    in1.OUT_LASTNAME AS OUT_LASTNAME,
    in1.OUT_APPLICATION_ID AS OUT_APPLICATION_ID,
    in1.OUT_DIGITAL_VERIFICATION_CHECK AS OUT_DIGITAL_VERIFICATION_CHECK,
    in1.OUT_CREDIT_DECISION_OFFERID_APPROVED AS OUT_CREDIT_DECISION_OFFERID_APPROVED,
    in1.OUT_ORIGINAL_LASTNAME AS OUT_ORIGINAL_LASTNAME,
    in1.OUT_CDD_INFORMATION_DETAILS_RISK_RATING AS OUT_CDD_INFORMATION_DETAILS_RISK_RATING,
    in1.OUT_GENDER AS OUT_GENDER,
    in0.OUT_CREDIT_REQUESTED_AMOUNT AS OUT_CREDIT_REQUESTED_AMOUNT,
    in1.OUT_TELEPHONE_NUMBER AS OUT_TELEPHONE_NUMBER,
    in1.OUT_ADDRESSLINE3 AS OUT_ADDRESSLINE3,
    in1.OUT_POSTCODE AS OUT_POSTCODE,
    in1.OUT_BANK_VERIFICATION_CHECK AS OUT_BANK_VERIFICATION_CHECK,
    in0.OUT_ANNUAL_SALARY_AMOUNT AS OUT_ANNUAL_SALARY_AMOUNT,
    in1.OUT_MARITAL_STATUS AS OUT_MARITAL_STATUS,
    in1.OUT_CREDIT_LIMIT_INCREASE_OPTION AS OUT_CREDIT_LIMIT_INCREASE_OPTION,
    in1.OUT_CREDIT_REQUESTED_CURRENCY AS OUT_CREDIT_REQUESTED_CURRENCY,
    in1.OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE5 AS OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE5
  
  FROM exp_trim_decimal AS in0
  INNER JOIN exp_trim AS in1
     ON (in0.prophecy_sk = in1.prophecy_sk)

),

WORK_CARDS_ORIG_STAGING_EXP_JOIN_EXPR_75 AS (

  SELECT 
    OUT_OFFERED_LIMIT_AMOUNT AS OFFERED_LIMIT_AMOUNT,
    OUT_ANNUAL_SALARY_AMOUNT AS ANNUAL_SALARY_AMOUNT,
    OUT_ANNUAL_INCOME_AMOUNT AS ANNUAL_INCOME_AMOUNT,
    OUT_CREDIT_REQUESTED_AMOUNT AS CREDIT_REQUESTED_AMOUNT,
    OUT_DELPHI_SCORE AS DELPHI_SCORE,
    OUT_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER AS CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER,
    OUT_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE AS CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE,
    prophecy_sk AS prophecy_sk,
    OUT_APPLICATION_ID AS APPLICATION_ID,
    OUT_CREATE_CUSTOMER_RESULT AS CREATE_CUSTOMER_RESULT,
    OUT_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
    OUT_CARD_CREATION_STATUS AS CARD_CREATION_STATUS,
    OUT_CARD_SYNC_STATUS AS CARD_SYNC_STATUS,
    OUT_CARD_TOKENIZATION_RESULT AS CARD_TOKENIZATION_RESULT,
    OUT_INITIAL_OVERALL_DECISION AS INITIAL_OVERALL_DECISION,
    OUT_INITIAL_OVERALL_DECISION_REASON_CODES AS INITIAL_OVERALL_DECISION_REASON_CODES,
    OUT_FINAL_CREDIT_DECISION_RESULT AS FINAL_CREDIT_DECISION_RESULT,
    OUT_FINAL_CREDIT_DECISION_REASON_CODES AS FINAL_CREDIT_DECISION_REASON_CODES,
    OUT_DUPLICATE_CUSTOMER AS DUPLICATE_CUSTOMER,
    OUT_RTS_TRANSACTION_STATUS AS RTS_TRANSACTION_STATUS,
    OUT_RTS_RSS_TRANSACTION_ID AS RTS_RSS_TRANSACTION_ID,
    OUT_IDENTITIY_VERIFICATION_MECHANISM AS IDENTITIY_VERIFICATION_MECHANISM,
    OUT_IDENTITY_VERIFICATION_STATUS AS IDENTITY_VERIFICATION_STATUS,
    OUT_IDENTITY_VERIFICATION_STATUS_REASON_DESCRIPTION AS IDENTITY_VERIFICATION_STATUS_REASON_DESCRIPTION,
    OUT_DIGITAL_VERIFICATION_MECHANISM AS DIGITAL_VERIFICATION_MECHANISM,
    OUT_DIGITAL_VERIFICATION_CHECK AS DIGITAL_VERIFICATION_CHECK,
    OUT_DIGITAL_VERIFICATION_CHECK_REASON_DESCRIPTION AS DIGITAL_VERIFICATION_CHECK_REASON_DESCRIPTION,
    OUT_BANK_VERIFICATION_CHECK_MECHANISM AS BANK_VERIFICATION_CHECK_MECHANISM,
    OUT_BANK_VERIFICATION_CHECK AS BANK_VERIFICATION_CHECK,
    OUT_BANK_VERIFICATION_CHECK_REASON_DESCRIPTION AS BANK_VERIFICATION_CHECK_REASON_DESCRIPTION,
    OUT_FRAUD_RESULT AS FRAUD_RESULT,
    OUT_FRAUD_REASON AS FRAUD_REASON,
    OUT_CREDIT_DECISION_RESULT AS CREDIT_DECISION_RESULT,
    OUT_CREDIT_DECISION_REASONS AS CREDIT_DECISION_REASONS,
    OUT_CREDIT_DECISION_OFFERID_REQUESTED AS CREDIT_DECISION_OFFERID_REQUESTED,
    OUT_CREDIT_DECISION_OFFERID_APPROVED AS CREDIT_DECISION_OFFERID_APPROVED,
    OUT_CREDIT_DECISION_TOTAL_AMOUNT_TO_PAY AS CREDIT_DECISION_TOTAL_AMOUNT_TO_PAY,
    OUT_CREDIT_DECISION_BASE_PRICING_CODE AS CREDIT_DECISION_BASE_PRICING_CODE,
    OUT_CREDIT_DECISION_OFFER_PRICING_CODE AS CREDIT_DECISION_OFFER_PRICING_CODE,
    OUT_CDD_PROFILEID AS CDD_PROFILEID,
    OUT_ADDRESSLINE6 AS ADDRESSLINE6,
    OUT_POSTCODE AS POSTCODE,
    OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE6 AS PREVIOUS_ADDRESSES_ADDRESS_LINE6,
    OUT_PREVIOUS_ADDRESSES_POSTCODE AS PREVIOUS_ADDRESSES_POSTCODE,
    OUT_COUNTRY AS COUNTRY,
    OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE1 AS PREVIOUS_ADDRESSES_ADDRESS_LINE1,
    OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE2 AS PREVIOUS_ADDRESSES_ADDRESS_LINE2,
    OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE3 AS PREVIOUS_ADDRESSES_ADDRESS_LINE3,
    OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE4 AS PREVIOUS_ADDRESSES_ADDRESS_LINE4,
    OUT_PREVIOUS_ADDRESSES_ADDRESS_LINE5 AS PREVIOUS_ADDRESSES_ADDRESS_LINE5,
    OUT_PREVIOUS_ADDRESSES_COUNTRY AS PREVIOUS_ADDRESSES_COUNTRY,
    OUT_RESIDENTIAL_STATUS AS RESIDENTIAL_STATUS,
    OUT_EMPLOYMENT_STATUS AS EMPLOYMENT_STATUS,
    OUT_OCCUPATION AS OCCUPATION,
    OUT_EMPLOYMENT_ROLE AS EMPLOYMENT_ROLE,
    OUT_BUSINESSNAME AS BUSINESSNAME,
    OUT_CREDIT_LIMIT_INCREASE_OPTION AS CREDIT_LIMIT_INCREASE_OPTION,
    OUT_FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES AS FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES,
    OUT_CREDIT_REQUESTED_CURRENCY AS CREDIT_REQUESTED_CURRENCY,
    OUT_DIRECT_DEBIT_SORT_CODE AS DIRECT_DEBIT_SORT_CODE,
    OUT_DIRECT_DEBIT_ACCOUNT_NUMBER AS DIRECT_DEBIT_ACCOUNT_NUMBER,
    OUT_DIRECT_DEBIT_BALANCE_PAYMENT_OPTION AS DIRECT_DEBIT_BALANCE_PAYMENT_OPTION,
    OUT_DIRECT_DEBIT_ACCOUNT_HOLDER_FULLNAME AS DIRECT_DEBIT_ACCOUNT_HOLDER_FULLNAME,
    OUT_DIRECT_DEBIT_SETUP_STATUS AS DIRECT_DEBIT_SETUP_STATUS,
    OUT_DIRECT_DEBIT_SETUP_REPAYMENTS AS DIRECT_DEBIT_SETUP_REPAYMENTS,
    OUT_MARKETING_PREFERENCES_OPT_INFORMATION AS MARKETING_PREFERENCES_OPT_INFORMATION,
    OUT_MARKETING_PREFERENCES_PREFERRED_CHANNELS AS MARKETING_PREFERENCES_PREFERRED_CHANNELS,
    OUT_LAST_ACTION_DATE AS LAST_ACTION_DATE,
    OUT_LAST_DECISION_DATE AS LAST_DECISION_DATE,
    OUT_APPLICATION_DATE AS APPLICATION_DATE,
    OUT_APPLICATION_EXPIRY_DATETIME AS APPLICATION_EXPIRY_DATETIME,
    OUT_TERMS_AND_CONDITIONS_ACCEPTANCE_TIMESTAMP AS TERMS_AND_CONDITIONS_ACCEPTANCE_TIMESTAMP,
    OUT_AGREEMENT_SIGNED_TIMESTAMP AS AGREEMENT_SIGNED_TIMESTAMP,
    OUT_EMPLOYMENT_MAIN_STARTDATE AS EMPLOYMENT_MAIN_STARTDATE,
    OUT_EMPLOYMENT_PART_TIME_STARTDATE AS EMPLOYMENT_PART_TIME_STARTDATE,
    OUT_CARD_EXPIRY_DATE AS CARD_EXPIRY_DATE,
    OUT_PREVIOUS_ADDRESSES_MOVED_IN_DATE AS PREVIOUS_ADDRESSES_MOVED_IN_DATE,
    OUT_RESIDENTIAL_MOVED_IN_DATE AS RESIDENTIAL_MOVED_IN_DATE,
    OUT_FINAL_DECISION_DATE AS FINAL_DECISION_DATE,
    OUT_DATE_OF_BIRTH AS DATE_OF_BIRTH,
    OUT_CDD_RESULT AS CDD_RESULT,
    OUT_CDD_INFORMATION_DETAILS_RISK_RATING AS CDD_INFORMATION_DETAILS_RISK_RATING,
    OUT_APPLICATION_SCORE AS APPLICATION_SCORE,
    OUT_FIRST_PARTY_FRAUD_SCORE AS FIRST_PARTY_FRAUD_SCORE,
    OUT_CIISCORE AS CIISCORE,
    OUT_TITLE AS TITLE,
    OUT_FIRSTNAMES AS FIRSTNAMES,
    OUT_LASTNAME AS LASTNAME,
    OUT_HAS_PREVIOUS_NAMES AS HAS_PREVIOUS_NAMES,
    OUT_ORIGINAL_FIRSTNAME AS ORIGINAL_FIRSTNAME,
    OUT_ORIGINAL_LASTNAME AS ORIGINAL_LASTNAME,
    OUT_PREVIOUS_TITLE AS PREVIOUS_TITLE,
    OUT_PREVIOUS_FIRSTNAMES AS PREVIOUS_FIRSTNAMES,
    OUT_PREVIOUS_LASTNAMES AS PREVIOUS_LASTNAMES,
    OUT_GENDER AS GENDER,
    OUT_NATIONALITIES AS NATIONALITIES,
    OUT_NATIONALITY1 AS NATIONALITY1,
    OUT_NATIONALITY2 AS NATIONALITY2,
    OUT_NATIONALITY3 AS NATIONALITY3,
    OUT_MARITAL_STATUS AS MARITAL_STATUS,
    OUT_NUMBER_OF_DEPENDENTS AS NUMBER_OF_DEPENDENTS,
    OUT_EMAIL AS EMAIL,
    OUT_TELEPHONE_NUMBER AS TELEPHONE_NUMBER,
    OUT_ADDRESSLINE1 AS ADDRESSLINE1,
    OUT_ADDRESSLINE2 AS ADDRESSLINE2,
    OUT_ADDRESSLINE3 AS ADDRESSLINE3,
    OUT_ADDRESSLINE4 AS ADDRESSLINE4,
    OUT_ADDRESSLINE5 AS ADDRESSLINE5,
    OUT_PRODUCT_CODE AS PRODUCT_CODE,
    OUT_PRODUCT AS PRODUCT,
    OUT_PRODUCT_NUMBER AS PRODUCT_NUMBER,
    OUT_APPLICATION_NUMBER AS APPLICATION_NUMBER,
    OUT_APPLICATION_SOURCE_CODE AS APPLICATION_SOURCE_CODE,
    OUT_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    OUT_APPLICATION_TYPE AS APPLICATION_TYPE,
    OUT_APPLICATION_STORE_NUMBER AS APPLICATION_STORE_NUMBER,
    OUT_OFFER_ID AS OFFER_ID,
    OUT_APPLICATION_STATUS AS APPLICATION_STATUS
  
  FROM WORK_CARDS_ORIG_STAGING_EXP_JOIN AS in0

)

SELECT *

FROM WORK_CARDS_ORIG_STAGING_EXP_JOIN_EXPR_75
