{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_CARDSORIG_CLIENT_EXPR_30 AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_client_staging_update__EXP_CARDSORIG_CLIENT_EXPR_30')}}

),

RTR_CARDSORIG_CLIENT_out2 AS (

  SELECT * 
  
  FROM EXP_CARDSORIG_CLIENT_EXPR_30 AS in0
  
  WHERE (((CLID_LKP IS NOT NULL) AND (TOTAL_COMPARE <> 0)) AND (BUSINESS_DATE_CHK <> 0))

),

RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT AS (

  SELECT 
    CLID AS CLID4,
    MERGE_CLID AS MERGE_CLID4,
    EFROM AS EFROM4,
    CLID_LKP AS CLID_LKP4,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER4,
    OUTPUT_TITLE AS OUTPUT_TITLE4,
    INITIALS AS INITIALS4,
    FORENAMES AS FORENAMES4,
    SURNAME AS SURNAME4,
    DOB AS DOB4,
    GENDER AS GENDER4,
    CLIENT_CLASS AS CLIENT_CLASS4,
    SOURCE_TYPE AS SOURCE_TYPE4,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE4,
    SOURCE_RECORD_TYPE AS SOURCE_RECORD_TYPE4,
    CLIENT_STATUS AS CLIENT_STATUS4,
    feed_update_id AS feed_update_id4,
    business_date AS business_date4,
    business_date_minus_1 AS business_date_minus_14,
    TOTAL_COMPARE AS TOTAL_COMPARE4,
    TITLE_LKP AS TITLE_LKP4,
    SURNAME_LKP AS SURNAME_LKP4,
    BUSINESS_DATE_CHK AS BUSINESS_DATE_CHK4,
    CLIENT_CLASS AS CLIENT_CLASS,
    DOB AS DOB,
    CLID AS CLID,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    OUTPUT_TITLE AS TITLE,
    SURNAME AS SURNAME,
    CUSTOMER_NUMBER AS SOURCE_CLIENT_REF,
    CLIENT_STATUS AS CLIENT_STATUS,
    GENDER AS GENDER,
    INITIALS AS INITIALS,
    SOURCE_RECORD_TYPE AS SOURCE_RECORD_TYPE,
    FORENAMES AS FORENAMES
  
  FROM RTR_CARDSORIG_CLIENT_out2 AS in0

)

SELECT *

FROM RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT
