{{
  config({    
    "materialized": "table",
    "alias": "CLIENT_STAGING_UPDATE_SAME_DAY",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_CARDSORIG_CLIENT_EXPR_30 AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_client_staging_update__EXP_CARDSORIG_CLIENT_EXPR_30')}}

),

RTR_CARDSORIG_CLIENT_out1 AS (

  SELECT * 
  
  FROM EXP_CARDSORIG_CLIENT_EXPR_30 AS in0
  
  WHERE (((CLID_LKP IS NOT NULL) AND (TOTAL_COMPARE <> 0)) AND (BUSINESS_DATE_CHK = 0))

),

RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_SAME_DATE_UPDATE AS (

  SELECT 
    CLID AS CLID,
    CUSTOMER_NUMBER AS SOURCE_CLIENT_REF,
    OUTPUT_TITLE AS TITLE,
    INITIALS AS INITIALS,
    FORENAMES AS FORENAMES,
    SURNAME AS SURNAME,
    DOB AS DOB,
    GENDER AS GENDER,
    CLIENT_CLASS AS CLIENT_CLASS,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    SOURCE_RECORD_TYPE AS SOURCE_RECORD_TYPE,
    CLIENT_STATUS AS CLIENT_STATUS
  
  FROM RTR_CARDSORIG_CLIENT_out1 AS in0

)

SELECT *

FROM RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_SAME_DATE_UPDATE
