{{
  config({    
    "materialized": "table",
    "alias": "MINERVA_EXCEPTION_NEW_RECORD",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_CARDSORIG_CLIENT_reformat AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_client_staging_update__EXP_CARDSORIG_CLIENT_reformat')}}

),

EXP_CARDSORIG_CLIENT_EXPR_32 AS (

  SELECT 
    SURNAME AS SURNAME,
    CLID AS CLID,
    business_date AS business_date,
    CUSTOMER_NUMBER AS SOURCE_CUSTOMER_REF,
    lookup_string AS lookup_string,
    business_date_string__find_business_date_lkp_3 AS business_date_string__find_business_date_lkp_3,
    MERGE_CLID AS MERGE_CLID,
    EFROM AS EFROM,
    GENDER AS GENDER,
    CLID_LKP AS CLID_LKP,
    TITLE_LKP AS TITLE_LKP,
    SURNAME_LKP AS SURNAME_LKP,
    TITLE AS TITLE,
    INITIALS AS INITIALS,
    FORENAMES AS FORENAMES,
    DOB AS DOB,
    CLIENT_CLASS AS CLIENT_CLASS,
    SOURCE_TYPE AS SOURCE_TYPE,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    SOURCE_RECORD_TYPE AS SOURCE_RECORD_TYPE,
    CLIENT_STATUS AS CLIENT_STATUS,
    feed_update_id AS feed_update_id,
    business_date_minus_1 AS business_date_minus_1,
    TOTAL_COMPARE AS TOTAL_COMPARE,
    BUSINESS_DATE_CHK AS BUSINESS_DATE_CHK,
    prophecy_sk AS prophecy_sk
  
  FROM EXP_CARDSORIG_CLIENT_reformat AS in0

),

FLT_FORENAMES_TEST1 AS (

  SELECT * 
  
  FROM EXP_CARDSORIG_CLIENT_EXPR_32 AS in0
  
  WHERE CAST((SURNAME = 'Customer') AS BOOL)

),

EXP_CONV_2 AS (

  SELECT 
    5003 AS CLASS,
    CLID AS CLID,
    business_date AS BUSINESS_DATE,
    'U' AS SOURCE_SYSTEM_CODE,
    SOURCE_CUSTOMER_REF AS SOURCE_CLIENT_REF,
    16 AS ERROR_NUMBER,
    'm_rep_cards_orig_client_staging_update' AS PROCESS_NAME,
    'EXP_GENERIC_NAME_REFORMAT' AS FUNCTION_NAME,
    'Y' AS LOAD_INDICATOR,
    (CONCAT('Salacious Surname', SURNAME)) AS EXCEPTION_COMMENT
  
  FROM FLT_FORENAMES_TEST1 AS in0

),

MINERVA_EXCEPTION_NEW_RECORD_EXP AS (

  SELECT 
    CLASS AS CLASS,
    BUSINESS_DATE AS BUSINESS_DATE,
    CLID AS CLID,
    CAST(NULL AS NUMERIC) AS ACCID,
    CAST(NULL AS NUMERIC) AS ADID,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    SOURCE_CLIENT_REF AS SOURCE_CLIENT_REF,
    CAST(NULL AS STRING) AS ACCOUNT_ALIAS_ID,
    ERROR_NUMBER AS ERROR_NUMBER,
    PROCESS_NAME AS PROCESS_NAME,
    FUNCTION_NAME AS FUNCTION_NAME,
    CAST(NULL AS STRING) AS ADDITIONAL_IDENTIFIER,
    CAST(NULL AS NUMERIC) AS ADDITIONAL_IDENTIFIER_TYPE,
    LOAD_INDICATOR AS LOAD_INDICATOR,
    EXCEPTION_COMMENT AS EXCEPTION_COMMENT
  
  FROM EXP_CONV_2 AS in0

)

SELECT *

FROM MINERVA_EXCEPTION_NEW_RECORD_EXP
