{{
  config({    
    "materialized": "table",
    "alias": "CLIENT_STAGING_EXISTING_CLIENT_DIFF_DATE",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_client_staging_update__RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT')}}

),

CLIENT_STAGING_EXISTING_CLIENT_DIFF_DATE_EXP AS (

  SELECT 
    CLID AS CLID,
    SOURCE_CLIENT_REF AS SOURCE_CLIENT_REF,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    SOURCE_RECORD_TYPE AS SOURCE_RECORD_TYPE,
    TITLE AS TITLE,
    FORENAMES AS FORENAMES,
    INITIALS AS INITIALS,
    SURNAME AS SURNAME,
    GENDER AS GENDER,
    DOB AS DOB,
    CLIENT_STATUS AS CLIENT_STATUS,
    CLIENT_CLASS AS CLIENT_CLASS
  
  FROM RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT AS in0

)

SELECT *

FROM CLIENT_STAGING_EXISTING_CLIENT_DIFF_DATE_EXP
