entityType: ""
providerType: "Databricks"
fields:
- name: "Config_File"
  dataType:
    type: "String"
- name: "MasterFile"
  dataType:
    type: "String"
- name: "Output Folder"
  dataType:
    type: "String"
