---
version: 2
models:
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_1046"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_1894"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_2490"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_2609"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_2718"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_2834"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_2840"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_2960"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_3078"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_3090"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_3233"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_3256"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_3276"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_3280"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__AlteryxSelect_3342"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__CrossTab_3266"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__CrossTab_3267"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_1840"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_2309"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_2313"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_2580"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_2789"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_2789_reject"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_2914"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_2914_reject"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_3068"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_3079"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_3079_reject"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_3315"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Filter_588"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_1183"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_1280"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_1893_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_1972_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_2006_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_2616_to_Formula_2612_1"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_2787"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_2788"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_2790_to_Formula_2826_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_2820_to_Formula_2806_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_2872_to_Formula_2871_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_3125_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Formula_708_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__FullStack_Stati_2305"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__FullStack_Stati_3115"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_1012_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_1012_right"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_1016_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_1016_left"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_1947_left"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_2437_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_2621_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_267_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_2782_inner_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_2786_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_2793_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_2969_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_3005_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_3009_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_3076_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_3162_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_387_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_595_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_595_left"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_700_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Join_884_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__MultiFieldFormula_1895"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__MultiFieldFormula_2966"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__RecordID_3003"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__RecordID_833"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Sort_2642"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Sort_2643"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Sort_2646"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Sort_3016"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Sort_3064"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Sort_3065"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_1027"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_1067"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_121"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_1660"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2541"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2597"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2779"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2780"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2781"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2812"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2813"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2814"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2815"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2816"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2817"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2823"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2824"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2841"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2842"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_2940"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_3004"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_3128"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_608"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Summarize_842"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__TadpolesQBandSa_2520"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__TextInput_1948_cast"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__TextInput_596_cast"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Union_1837"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Union_1980"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Union_2799"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Union_3183"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Union_3307"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Union_677"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Unique_1094"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__Unique_123"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__table_3118_Input_macro_ip"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM__table_3124_Engine_Records_macro_ip"
  tags:
  - "prophecy_temp"
