{{
  config({    
    "materialized": "table",
    "alias": "INS_ACCOUNT_HISTORY",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_GET_DATES_AND_FEED_NUMBER_EXPR_1 AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_account_history_update__EXP_GET_DATES_AND_FEED_NUMBER_EXPR_1')}}

),

RTR_ACCOUNT_HISTORY_CHANGE_out2 AS (

  SELECT * 
  
  FROM EXP_GET_DATES_AND_FEED_NUMBER_EXPR_1 AS in0
  
  WHERE (ACCID_TGT IS NULL)

),

INS_ACCOUNT_HISTORY_EXP AS (

  SELECT 
    CAST(NULL AS STRING) AS CONTRA_RESCHEDULE_FLAG,
    CAST(NULL AS NUMERIC) AS CREDIT_LIMIT,
    CAST(NULL AS STRING) AS DD_AMOUNT_PERCENT_FLAG,
    CAST(NULL AS STRING) AS DD_PAYMENT_FLAG,
    ACCID_ACCOUNT_ALIAS AS ACCID,
    BUSINESS_DATE AS EFROM,
    CAST(NULL AS STRING) AS ETO,
    CAST(NULL AS STRING) AS DATE_FINAL_PREMIUM,
    CAST(NULL AS NUMERIC) AS GBP_COMMISSION_AMOUNT,
    CAST(NULL AS NUMERIC) AS GBP_GROSS_ANNUAL_PREMIUM,
    CAST(NULL AS NUMERIC) AS GBP_GROSS_ANNUAL_PREMIUM_IPT,
    CAST(NULL AS NUMERIC) AS GBP_INSTALLMENT_CHARGE,
    CAST(NULL AS NUMERIC) AS GBP_SUM_ASSURED,
    CAST(NULL AS NUMERIC) AS GBP_WRITTEN_PREMIUM,
    CAST(NULL AS NUMERIC) AS GBP_WRITTEN_PREMIUM_IPT,
    CAST(NULL AS STRING) AS INS_IND,
    CAST(NULL AS STRING) AS LAST_RENEWAL_DATE,
    CAST(NULL AS STRING) AS PAYMENT_FREQUENCY,
    CAST(NULL AS STRING) AS PAYMENT_METHOD,
    CAST(NULL AS NUMERIC) AS PREMIUM_INDEX_RATE,
    CAST(NULL AS STRING) AS PRODUCT_CODE,
    STATUS_SRC AS STATUS,
    STATUS_DATE_SRC AS STATUS_DATE,
    CAST(NULL AS NUMERIC) AS SUM_ASSURED_INDEX_RATE,
    CAST(NULL AS STRING) AS TRANSACTION_DATE,
    CAST(NULL AS NUMERIC) AS WESCORE,
    CAST(NULL AS NUMERIC) AS CYCLE_DAY,
    CAST(NULL AS NUMERIC) AS TOTAL_NUMBER_OF_CARDS,
    CAST(NULL AS STRING) AS INSURANCE_STATUS,
    CAST(NULL AS NUMERIC) AS ACCOUNT_CREDIT_LIMIT,
    CAST(NULL AS NUMERIC) AS CREDIT_LIMIT_CASH,
    CAST(NULL AS STRING) AS BLOCK_CODE,
    CAST(NULL AS STRING) AS ALT_BLOCK_CODE,
    CAST(NULL AS STRING) AS LOYALTY_IND,
    CAST(NULL AS NUMERIC) AS GBP_AMT_WRITE_OFF,
    CAST(NULL AS STRING) AS CHARGE_OFF_STATUS,
    CAST(NULL AS STRING) AS CHARGE_OFF_DATE,
    CAST(NULL AS NUMERIC) AS GBP_AMT_CHARGE_OFF,
    CAST(NULL AS STRING) AS FRAUD_TYPE,
    CAST(NULL AS NUMERIC) AS PAST_DUE,
    CAST(NULL AS NUMERIC) AS DELQ_120_DAYS,
    CAST(NULL AS NUMERIC) AS DELQ_150_DAYS,
    CAST(NULL AS NUMERIC) AS DELQ_180_DAYS,
    CAST(NULL AS NUMERIC) AS DELQ_210_DAYS,
    CAST(NULL AS NUMERIC) AS DELQ_30_DAYS,
    CAST(NULL AS NUMERIC) AS DELQ_60_DAYS,
    CAST(NULL AS NUMERIC) AS DELQ_90_DAYS,
    CAST(NULL AS STRING) AS BUREAU_SCORE,
    CAST(NULL AS STRING) AS DELINQUENCY_STATUS,
    CAST(NULL AS NUMERIC) AS CURR_BALANCE,
    CAST(NULL AS NUMERIC) AS ACHOLDER_NOMINATED_AMOUNT,
    CAST(NULL AS STRING) AS AMBER_PRI_CODE,
    APPLICATION_STORE_NUMBER_SRC AS DOMICILE_BRANCH,
    CAST(NULL AS STRING) AS INS_CODE,
    CAST(NULL AS NUMERIC) AS CURR_DUE,
    CAST(NULL AS STRING) AS DATE_LAST_PURCH,
    CAST(NULL AS STRING) AS DATE_LAST_PYMT,
    CAST(NULL AS NUMERIC) AS GBP_FIXED_PYMT_AMT,
    CAST(NULL AS STRING) AS GOOD_BAD_ACCT
  
  FROM RTR_ACCOUNT_HISTORY_CHANGE_out2 AS in0

)

SELECT *

FROM INS_ACCOUNT_HISTORY_EXP
