---
version: 2
models:
- name: "m_rep_cards_orig_account_history_update__CLOSE_ACCOUNT_HISTORY_CHANGE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_history_update__EXP_GET_DATES_AND_FEED_NUMBER_EXPR_1"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_history_update__EXP_GET_DATES_AND_FEED_NUMBER_VARS_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_history_update__INS_ACCOUNT_HISTORY"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_history_update__NEW_MAINTAINS"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_history_update__OPEN_ACCOUNT_HISTORY_CHANGE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_history_update__RTR_ACCOUNT_HISTORY_CHANGE_EXPR_ACCOUNT_HISTORY_CHANGE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_history_update__UPD_ACCOUNT_HISTORY_SAME_DATE_CHANGE"
  tags:
  - "prophecy_temp"
