{{
  config({    
    "materialized": "table",
    "alias": "MINERVA_EXCEPTION",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH SQ_CARDS_ORIG_DECISION_HISTORY AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_decision_history__SQ_CARDS_ORIG_DECISION_HISTORY')}}

),

DBATTRIBUTE AS (

  SELECT * 
  
  FROM {{ ref('s1')}}

),

RTR_CARDS_ORIG_DECISION_HISTORY_out1 AS (

  SELECT * 
  
  FROM SQ_CARDS_ORIG_DECISION_HISTORY AS in0
  
  WHERE ((LAST_ACTION_DATE IS NULL) OR ((LENGTH(CAST(LAST_ACTION_DATE AS STRING))) = 0))

),

RTR_CARDS_ORIG_DECISION_HISTORY_EXPR_DATE_NOT_PRESENT AS (

  SELECT 
    ACCID AS ACCID3,
    APPLICATION_NUMBER AS APPLICATION_NUMBER,
    APPLICATION_STATUS AS APPLICATION_STATUS3,
    LAST_ACTION_DATE AS LAST_ACTION_DATE3
  
  FROM RTR_CARDS_ORIG_DECISION_HISTORY_out1 AS in0

),

EXP_GET_BUSINESS_DATE_LOOKUP_18 AS (

  SELECT 
    in0.CURRVALUE AS LOOKUP_VARIABLE_2,
    in0.NAME AS NAME,
    in0.CURRVALUE AS CURRVALUE,
    in1.APPLICATION_NUMBER AS APPLICATION_NUMBER,
    in1.ACCID3 AS ACCID3
  
  FROM DBATTRIBUTE AS in0
  LEFT JOIN RTR_CARDS_ORIG_DECISION_HISTORY_EXPR_DATE_NOT_PRESENT AS in1
     ON (in0.NAME = 'businessdate')

),

EXP_GET_BUSINESS_DATE_VARS_0 AS (

  SELECT 
    LOOKUP_VARIABLE_2 AS business_date_string__find_business_date_lkp_1,
    *
  
  FROM EXP_GET_BUSINESS_DATE_LOOKUP_18 AS in0

),

EXP_GET_BUSINESS_DATE AS (

  SELECT 
    ACCID3 AS ACCID3,
    APPLICATION_NUMBER AS APPLICATION_NUMBER,
    (
      CASE
        WHEN CAST((
          (
            CASE
              WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_1
              ELSE CAST(NULL AS STRING)
            END
          ) IS NULL
        ) AS BOOL)
          THEN NULL
        ELSE (
          PARSE_TIMESTAMP(
            '%Y%m%d', 
            CAST(SUBSTRING(
              (
                CASE
                  WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                    THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_1
                  ELSE CAST(NULL AS STRING)
                END
              ), 
              0, 
              8) AS STRING))
        )
      END
    ) AS business_date,
    'm_rep_cards_orig_decision_history' AS PROCESS_NAME,
    'Last Action Date not Present in Cards Origination record' AS COMMENT,
    'RTR_CHECK_ACTION_DATE' AS FUNCTION_NAME,
    'N' AS LOAD_INDICATOR,
    'U' AS SOURCE_SYSTEM_CODE,
    18 AS ERROR_NUMBER,
    5053 AS CLASS
  
  FROM EXP_GET_BUSINESS_DATE_VARS_0 AS in0

),

MINERVA_EXCEPTION_EXP AS (

  SELECT 
    CLASS AS CLASS,
    business_date AS BUSINESS_DATE,
    CAST(NULL AS NUMERIC) AS CLID,
    ACCID3 AS ACCID,
    CAST(NULL AS NUMERIC) AS ADID,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    CAST(NULL AS STRING) AS SOURCE_CLIENT_REF,
    APPLICATION_NUMBER AS ACCOUNT_ALIAS_ID,
    ERROR_NUMBER AS ERROR_NUMBER,
    PROCESS_NAME AS PROCESS_NAME,
    FUNCTION_NAME AS FUNCTION_NAME,
    CAST(NULL AS STRING) AS ADDITIONAL_IDENTIFIER,
    CAST(NULL AS NUMERIC) AS ADDITIONAL_IDENTIFIER_TYPE,
    LOAD_INDICATOR AS LOAD_INDICATOR,
    COMMENT AS EXCEPTION_COMMENT
  
  FROM EXP_GET_BUSINESS_DATE AS in0

)

SELECT *

FROM MINERVA_EXCEPTION_EXP
