entityType: ""
providerType: "Databricks"
fields:
- name: "Month"
  dataType:
    type: "Date"
- name: "Weights"
  dataType:
    type: "Double"
- name: "Number of Working Days"
  dataType:
    type: "Double"
