{{
  config({    
    "materialized": "ephemeral",
    "database": "sony",
    "schema": "orch_test"
  })
}}

WITH Source__User_Db_45 AS (

  SELECT 
    ldgr_acru_sts_in,
    accrual_type,
    acct_gen1_nm,
    acct_gen1_alias_nm,
    acct_gen10_nm,
    acct_gen10_alias_nm,
    acct_gen17_nm,
    acct_gen17_alias_nm,
    acct_gen2_nm,
    acct_gen2_alias_nm,
    acct_gen3_nm,
    acct_gen3_alias_nm,
    acct_gen4_nm,
    acct_gen4_alias_nm,
    acct_gen5_nm,
    acct_gen5_alias_nm,
    acct_gen6_nm,
    acct_gen6_alias_nm,
    acct_gen7_nm,
    acct_gen7_alias_nm,
    acct_gen8_nm,
    acct_gen8_alias_nm,
    acct_gen9_nm,
    acct_gen9_alias_nm,
    arm_int_rt_max_life_ceil_rt,
    arm_int_rt_max_life_flr_rt,
    bal_am,
    bal_sub_type,
    bal_type,
    rcc_call_cd,
    call_cd,
    cat_cd,
    chrgf_type,
    co_nb,
    construction_in,
    cnsmr_loan_in,
    ctnt_nm,
    business_status,
    cc_nb,
    org_alias_nm,
    cntry_ad_cd,
    cntry_nm,
    credit_impaired,
    ots_delq_gp_cd,
    acct_trtm_cd,
    FICO_RANGE,
    frst_prin_cc_nb,
    frcls_in,
    frgn_ad_in,
    GEO_REGION,
    gl_acct_nb,
    govt_ins_in,
    hfs_in,
    heritage,
    hfs_hfi,
    int_only_in,
    int_only_expr_dt,
    note_int_rt,
    ivst_id,
    ivst_type_cd,
    ivst_type_sbsd_cd,
    jmbo_cfrm_id,
    bnk_nonbnk_flag,
    lien_prrty_cd,
    lien_pstn_cd,
    line_item,
    loan_type,
    loan_type_desc,
    loan_nb,
    lob,
    LTV_RANGE,
    arm_mrgn_rt,
    loan_mtr_dt,
    loan_mtr_sts,
    org_cd,
    neg_amz_in,
    nxt_pymt_due_dt,
    nxt_rt_chg_dt,
    nre_in,
    opt_arm_in,
    gen2_nm,
    gen2_alias_nm,
    gen3_nm,
    gen3_alias_nm,
    gen4_nm,
    gen4_alias_nm,
    gen9_nm,
    orgn_dt,
    otst_in,
    own_srcvd_frst_cd,
    payee_id,
    product,
    reo_in,
    rmn_term,
    lob_desc,
    orgn_sys_cd,
    std_adj_in,
    prop_state_cd,
    stop_advn_in,
    sub_lob_desc,
    sys_acru_sts_in,
    tdr_in,
    loan_term,
    var_rt_in,
    ci_nci_cd,
    pldg_loan_to_cd,
    max_neg_amz_rmn_am,
    nxt_rprc_sts_rpt_cd,
    sub_lob_id,
    tot_neg_amz_rmn_incur_am,
    bus_mo,
    bus_dt,
    user_03_position_field_6c,
    loan_loss_shar_agrm_in,
    fdic_loan_nb,
    loan_loss_shar_agrm_cd
  
  FROM 90278_ctg_prod.fdi_refined_mb_srvc_datamart_schema.mb_own_loan_rpt
  
  WHERE bus_mo BETWEEN from_unixtime(unix_timestamp(add_months(now(), -6)), 'yyyyMM') AND from_unixtime(unix_timestamp(add_months(now(), -4)), 'yyyyMM')

),

Source__User_Db_42 AS (

  SELECT 
    ldgr_acru_sts_in,
    accrual_type,
    acct_gen1_nm,
    acct_gen1_alias_nm,
    acct_gen10_nm,
    acct_gen10_alias_nm,
    acct_gen17_nm,
    acct_gen17_alias_nm,
    acct_gen2_nm,
    acct_gen2_alias_nm,
    acct_gen3_nm,
    acct_gen3_alias_nm,
    acct_gen4_nm,
    acct_gen4_alias_nm,
    acct_gen5_nm,
    acct_gen5_alias_nm,
    acct_gen6_nm,
    acct_gen6_alias_nm,
    acct_gen7_nm,
    acct_gen7_alias_nm,
    acct_gen8_nm,
    acct_gen8_alias_nm,
    acct_gen9_nm,
    acct_gen9_alias_nm,
    arm_int_rt_max_life_ceil_rt,
    arm_int_rt_max_life_flr_rt,
    bal_am,
    bal_sub_type,
    bal_type,
    rcc_call_cd,
    call_cd,
    cat_cd,
    chrgf_type,
    co_nb,
    construction_in,
    cnsmr_loan_in,
    ctnt_nm,
    business_status,
    cc_nb,
    org_alias_nm,
    cntry_ad_cd,
    cntry_nm,
    credit_impaired,
    ots_delq_gp_cd,
    acct_trtm_cd,
    FICO_RANGE,
    frst_prin_cc_nb,
    frcls_in,
    frgn_ad_in,
    GEO_REGION,
    gl_acct_nb,
    govt_ins_in,
    hfs_in,
    heritage,
    hfs_hfi,
    int_only_in,
    int_only_expr_dt,
    note_int_rt,
    ivst_id,
    ivst_type_cd,
    ivst_type_sbsd_cd,
    jmbo_cfrm_id,
    bnk_nonbnk_flag,
    lien_prrty_cd,
    lien_pstn_cd,
    line_item,
    loan_type,
    loan_type_desc,
    loan_nb,
    lob,
    LTV_RANGE,
    arm_mrgn_rt,
    loan_mtr_dt,
    loan_mtr_sts,
    org_cd,
    neg_amz_in,
    nxt_pymt_due_dt,
    nxt_rt_chg_dt,
    nre_in,
    opt_arm_in,
    gen2_nm,
    gen2_alias_nm,
    gen3_nm,
    gen3_alias_nm,
    gen4_nm,
    gen4_alias_nm,
    gen9_nm,
    orgn_dt,
    otst_in,
    own_srcvd_frst_cd,
    payee_id,
    product,
    reo_in,
    rmn_term,
    lob_desc,
    orgn_sys_cd,
    std_adj_in,
    prop_state_cd,
    stop_advn_in,
    sub_lob_desc,
    sys_acru_sts_in,
    tdr_in,
    loan_term,
    var_rt_in,
    ci_nci_cd,
    pldg_loan_to_cd,
    max_neg_amz_rmn_am,
    nxt_rprc_sts_rpt_cd,
    sub_lob_id,
    tot_neg_amz_rmn_incur_am,
    bus_mo,
    bus_dt,
    user_03_position_field_6c,
    loan_loss_shar_agrm_in,
    fdic_loan_nb,
    loan_loss_shar_agrm_cd
  
  FROM 90278_ctg_prod.fdi_refined_mb_srvc_datamart_schema.mb_own_loan_rpt
  
  WHERE bus_mo >= from_unixtime(unix_timestamp(add_months(now(), -3)), 'yyyyMM')

),

Union_39 AS (

  {{
    prophecy_basics.UnionByName(
      ['Source__User_Db_42', 'Source__User_Db_45'], 
      ['[]', '[]'], 
      'allowMissingColumns'
    )
  }}

),

Formula_41_0 AS (

  SELECT 
    (TO_TIMESTAMP(CURRENT_TIMESTAMP)) AS Data_Refresh_Date,
    *
  
  FROM Union_39 AS in0

)

SELECT *

FROM Formula_41_0
