---
version: 2
models:
- name: "FDI_HL_Owned_Loans_Tertiary_Monthly__AlteryxSelect_33"
  tags:
  - "prophecy_temp"
- name: "FDI_HL_Owned_Loans_Tertiary_Monthly__Formula_41_0"
  tags:
  - "prophecy_temp"
- name: "FDI_HL_Owned_Loans_Tertiary_Monthly__Macro_29"
  tags:
  - "prophecy_temp"
- name: "FDI_HL_Owned_Loans_Tertiary_Monthly__Macro_35"
  tags:
  - "prophecy_temp"
- name: "FDI_HL_Owned_Loans_Tertiary_Monthly__Macro_48"
  tags:
  - "prophecy_temp"
- name: "FDI_HL_Owned_Loans_Tertiary_Monthly__Macro_50"
  tags:
  - "prophecy_temp"
