pipelines:
  facility_master_wf_updated_macro_paths:
    visualGroups:
      sitefacilityfulldataset:
        isCollapsed: false
        height: 3732
        nodes:
        - "AlteryxSelect_27"
        - "AlteryxSelect_30"
        - "AlteryxSelect_53"
        - "AlteryxSelect_8"
        - "Cleanse_968"
        - "Filter_145"
        - "Filter_221"
        - "Formula_148_0"
        - "Join_31_left_UnionLeftOuter"
        - "Join_37_left_UnionLeftOuter"
        - "Join_47_left_UnionLeftOuter"
        - "MultiRowFormula_1046_0"
        - "MultiRowFormula_1046_1"
        - "MultiRowFormula_1046_row_id_0"
        - "MultiRowFormula_1046_row_id_drop_0"
        - "Summarize_21"
        - "Summarize_236"
        - "Summarize_45"
        - "contact_informa_2"
        - "contact_org_csv_24"
        - "contact_person__28"
        - "contactaddresswithstatefipscodeadd"
        - "regexdisabled_1"
        width: 8908
        colorPreset: "gray-blue"
      orgthatappearsmostfrequenctlyidentified:
        isCollapsed: false
        height: 3897
        nodes:
        - "AlteryxSelect_882"
        - "Cleanse_886"
        - "ExcludeStreetNameforOrgwithmostfrequentdisplayed"
        - "Filter_879"
        - "Filter_887"
        - "Filter_888"
        - "Filter_888_reject"
        - "Filter_894"
        - "Filter_894_reject"
        - "Join_880_inner"
        - "Join_880_right"
        - "Join_884_inner"
        - "Join_890_inner"
        - "Join_895_inner"
        - "Join_896_inner"
        - "Summarize_878"
        - "Summarize_883"
        - "Summarize_889"
        - "Summarize_892"
        - "Summarize_893"
        - "Union_881"
        - "Union_891"
        - "Union_897"
        - "dealwithmultipleuniquenameandexcludestreetorgname"
        - "dealwithmultipleuniquenameandexcludestreetorgname_1"
        width: 10242
        colorPreset: "gray-blue"
      regexdisabled:
        isCollapsed: false
        height: 540
        nodes:
        - "MultiFieldFormula_1035"
        width: 322
        colorPreset: "gray-blue"
      Grouponlycontain1Org:
        isCollapsed: false
        height: 399
        nodes:
        - "Formula_870_0"
        - "Join_869_inner"
        width: 794
        colorPreset: "gray-blue"
      dealwithmultipleuniquenameandexcludestreetorgname:
        isCollapsed: false
        height: 831
        nodes:
        - "Filter_915"
        - "Filter_915_reject"
        - "Filter_918"
        - "Filter_918_reject"
        - "Formula_922_0"
        - "Join_913_inner"
        - "Join_916_inner"
        - "MultiRowFormula_924_0"
        - "MultiRowFormula_924_window"
        - "MultiRowFormula_925_0"
        - "MultiRowFormula_925_1"
        - "MultiRowFormula_925_row_id_0"
        - "MultiRowFormula_925_row_id_drop_0"
        - "RegEx_926"
        - "RegEx_926_typeCastGem"
        - "Summarize_917"
        - "Summarize_919"
        - "Summarize_920"
        - "Union_914"
        - "Union_921"
        width: 3758
        colorPreset: "gray-blue"
      Container411:
        isCollapsed: false
        height: 630
        nodes:
        - "aka_GPD_UDDL_Wr_788"
        width: 316
        colorPreset: "gray-blue"
      assignnewgroupid:
        isCollapsed: false
        height: 1263
        nodes:
        - "AlteryxSelect_628"
        - "AlteryxSelect_629"
        - "AlteryxSelect_631"
        - "AlteryxSelect_846"
        - "Filter_627"
        - "Filter_627_reject"
        - "Summarize_840"
        - "Union_630"
        - "Union_630_reformat_0"
        - "Union_630_reformat_1"
        - "Union_632"
        - "Union_632_reformat_0"
        - "Union_632_reformat_1"
        - "Union_848"
        - "Union_848_reformat_0"
        - "Union_848_reformat_1"
        - "Unique_850"
        width: 2018
        colorPreset: "gray-blue"
      regexdisabled_1:
        isCollapsed: true
        height: 72
        nodes:
        - "MultiFieldFormula_528"
        width: 322
        colorPreset: "gray-blue"
      citytownvillageclean:
        isCollapsed: false
        height: 4509
        nodes:
        - "AlteryxSelect_474"
        - "Cleanse_476"
        - "Union_515"
        - "Union_516"
        - "Unique_521"
        - "Unique_987"
        - "filterunusedorgname"
        - "getonecitytownvillageforuniqueoriginalgeotag"
        - "getonecitytownvillageforuniqueoriginalgeotag_1"
        width: 5782
        colorPreset: "gray-blue"
      GetGroupIDbyGeoandDistance:
        isCollapsed: false
        height: 975
        width: 1608
        nodes:
        - "AlteryxSelect_778"
        - "Join_779_inner"
        - "RecordID_776"
        - "Unique_783"
      writebasedataintotable:
        isCollapsed: false
        height: 996
        width: 2108
        nodes:
        - "AlteryxSelect_388"
        - "Cleanse_982"
        - "Container411"
        - "Formula_394_0"
        - "MultiFieldFormula_399"
        - "MultiFieldFormula_983"
        - "disableregex"
      grouporgnamewithgeotag:
        isCollapsed: false
        height: 1227
        nodes:
        - "AlteryxSelect_252"
        - "Filter_240"
        - "Filter_240_reject"
        - "Join_247_inner"
        - "Join_248_inner"
        - "Summarize_239"
        width: 2008
        colorPreset: "gray-blue"
      disableregex:
        isCollapsed: false
        height: 540
        nodes:
        - "MultiFieldFormula_1037"
        width: 312
        colorPreset: "gray-blue"
      unionalldataintoatable:
        isCollapsed: false
        height: 1464
        width: 3100
        nodes:
        - "AlteryxSelect_407"
        - "AlteryxSelect_413"
        - "AlteryxSelect_525"
        - "Formula_1006_0"
        - "Formula_522_0"
        - "Formula_793_to_Formula_1078_0"
        - "Join_414_left_UnionLeftOuter"
        - "Union_405"
        - "Unique_419"
        - "Unique_424"
        - "site_studysite__412"
      orgwithmulticities:
        isCollapsed: false
        height: 819
        nodes:
        - "AlteryxSelect_939"
        - "Cleanse_933"
        - "Filter_936"
        - "Formula_938_0"
        - "Join_935_right_UnionRightOuter"
        - "Summarize_934"
        width: 1418
        colorPreset: "gray-blue"
      joinbacktogetorgname:
        isCollapsed: false
        height: 543
        nodes:
        - "AlteryxSelect_659"
        - "Filter_764"
        - "Join_642_inner"
        - "Unique_661"
        width: 1590
        colorPreset: "gray-blue"
      dealwithmultineworgnamewithin1latlonggroup:
        isCollapsed: false
        height: 723
        nodes:
        - "AlteryxSelect_952"
        - "AlteryxSelect_953"
        - "Filter_951"
        - "Join_946"
        - "Join_948_inner_formula_0"
        - "Summarize_944"
        - "Summarize_945"
        - "Summarize_945_filter"
        - "Summarize_950"
        - "Union_947"
        - "Unique_949"
        width: 2582
        colorPreset: "gray-blue"
      fuzzylogic:
        isCollapsed: false
        height: 4185
        width: 20096
        nodes:
        - "AlteryxSelect_858"
        - "AlteryxSelect_957"
        - "AlteryxSelect_958"
        - "Cleanse_860"
        - "Formula_961_0"
        - "GroupCorrdinates"
        - "Groupcontainsmultipleorgfuzzymatchorgname"
        - "Grouponlycontain1Org"
        - "Union_862"
        - "Union_862_reformat_0"
        - "Union_862_reformat_1"
        - "Unique_859"
        - "Unique_959"
        - "Unique_960"
        - "dealwithmultineworgnamewithin1latlonggroup"
        - "keywordmatch"
        - "orgthatappearsmostfrequenctlyidentified"
        - "orgwithmulticities"
        - "regexdisabled"
      GeocodedAddressesUpdated19DEC2022:
        isCollapsed: false
        height: 807
        width: 1898
        nodes:
        - "AlteryxSelect_1054"
        - "AlteryxSelect_1060"
        - "AlteryxSelect_1061"
        - "Cleanse_1055"
        - "Formula_1059_0"
        - "Join_1057_left_UnionLeftOuter"
        - "contact_address_1053"
        - "continuity_geoc_1056"
      USCensusStateShapesandInfo:
        isCollapsed: false
        height: 495
        nodes:
        - "AlteryxSelect_208"
        - "cb_2018_us_stat_207"
        width: 566
        colorPreset: "gray-blue"
      USCensusCountyShapesInfo:
        isCollapsed: false
        height: 495
        nodes:
        - "AlteryxSelect_205"
        - "cb_2018_us_coun_204"
        width: 522
        colorPreset: "gray-blue"
      getonecitytownvillageforuniqueoriginalgeotag:
        isCollapsed: false
        height: 1515
        nodes:
        - "Filter_499"
        - "Filter_499_reject"
        - "Join_500_inner"
        - "Join_502_inner"
        - "Join_506_inner_formula_0"
        - "Join_509_inner"
        - "Sample_512"
        - "Summarize_498"
        - "Summarize_504"
        - "Summarize_505"
        - "Summarize_505_filter"
        width: 3182
        colorPreset: "gray-blue"
      Container1005:
        isCollapsed: false
        height: 399
        nodes:
        - "Join_993_inner"
        width: 722
        colorPreset: "gray-blue"
      calculatethedistancerowbyrow:
        isCollapsed: false
        height: 2163
        width: 7118
        nodes:
        - "AlteryxSelect_607"
        - "AlteryxSelect_617"
        - "AlteryxSelect_622"
        - "AlteryxSelect_623"
        - "CreatePoints_601"
        - "CreatePoints_601_cast_lonlat"
        - "CreatePoints_602"
        - "CreatePoints_602_cast_lonlat"
        - "Distance_605"
        - "Filter_657"
        - "Formula_610_0"
        - "Formula_621_0"
        - "Join_603_inner"
        - "Join_624_left_UnionLeftOuter"
        - "RecordID_620"
        - "Summarize_791"
        - "Unique_612"
        - "Unique_619"
        - "Unique_851"
        - "assignnewgroupid"
      keywordmatch:
        isCollapsed: false
        height: 939
        width: 3050
        nodes:
        - "AlteryxSelect_1077"
        - "BatchMacroOutputBoundaryTruncate_Macro_1070"
        - "Filter_1022"
        - "Filter_1022_reject"
        - "Join_1023_inner"
        - "Macro_1070"
        - "Summarize_1020"
        - "Union_1024"
        - "Union_1024_reformat_0"
        - "Union_1024_reformat_1"
        - "Unique_1018"
        - "Unique_1021"
        - "Unique_1025"
        - "table_1070_Input12_macro_ip"
        - "table_1070_Output17_macro_op"
      GroupCorrdinates:
        isCollapsed: false
        height: 540
        nodes:
        - "Filter_867"
        - "Filter_867_reject"
        - "Formula_864_0"
        - "Join_863_inner"
        - "Summarize_866"
        width: 1126
        colorPreset: "gray-blue"
      dealwithmultipleuniquenameandexcludestreetorgname_1:
        isCollapsed: false
        height: 723
        nodes:
        - "Filter_900"
        - "Filter_900_reject"
        - "Filter_903"
        - "Filter_903_reject"
        - "Formula_907_0"
        - "Join_898_inner"
        - "Join_901_inner"
        - "MultiRowFormula_909_0"
        - "MultiRowFormula_909_window"
        - "MultiRowFormula_910_0"
        - "MultiRowFormula_910_1"
        - "MultiRowFormula_910_row_id_0"
        - "MultiRowFormula_910_row_id_drop_0"
        - "RegEx_911"
        - "RegEx_911_typeCastGem"
        - "Summarize_902"
        - "Summarize_904"
        - "Summarize_905"
        - "Union_899"
        - "Union_906"
        width: 3902
        colorPreset: "gray-blue"
      getonecitytownvillageforuniqueoriginalgeotag_1:
        isCollapsed: false
        height: 1443
        nodes:
        - "Filter_481"
        - "Filter_481_reject"
        - "Join_482_inner"
        - "Join_484_inner"
        - "Join_488_inner_formula_0"
        - "Join_491_inner"
        - "Sample_494"
        - "Summarize_480"
        - "Summarize_486"
        - "Summarize_487"
        - "Summarize_487_filter"
        width: 3182
        colorPreset: "gray-blue"
      ExcludeStreetNameforOrgwithmostfrequentdisplayed:
        isCollapsed: false
        height: 720
        nodes:
        - "Filter_928"
        - "RegEx_929"
        - "RegEx_929_typeCastGem"
        width: 1058
        colorPreset: "gray-blue"
      filterunusedorgname:
        isCollapsed: false
        height: 495
        width: 512
        nodes:
        - "Filter_475"
        - "Filter_475_reject"
        - "Filter_478"
      Groupcontainsmultipleorgfuzzymatchorgname:
        isCollapsed: false
        height: 399
        nodes:
        - "BatchMacroOutputBoundaryTruncate_Macro_1004"
        - "Macro_1004"
        - "table_1004_Input43_macro_ip"
        - "table_1004_Output6_macro_op"
        width: 1306
        colorPreset: "gray-blue"
      contactaddresswithstatefipscodeadd:
        isCollapsed: false
        height: 2235
        nodes:
        - "AlteryxSelect_196"
        - "CreatePoints_199"
        - "CreatePoints_199_cast_lonlat"
        - "GeocodedAddressesUpdated19DEC2022"
        - "Join_195_inner"
        - "SpatialMatch_200"
        - "USCensusCountyShapesInfo"
        - "USCensusStateShapesandInfo"
        - "Union_201"
        width: 3436
        colorPreset: "gray-blue"
