---
version: 2
models:
- name: "Day4Scott__AlteryxSelect_11"
  tags:
  - "prophecy_temp"
- name: "Day4Scott__AlteryxSelect_33"
  tags:
  - "prophecy_temp"
- name: "Day4Scott__Filter_22"
  tags:
  - "prophecy_temp"
- name: "Day4Scott__Filter_43"
  tags:
  - "prophecy_temp"
- name: "Day4Scott__Sort_23"
  tags:
  - "prophecy_temp"
- name: "Day4Scott__Sort_44"
  tags:
  - "prophecy_temp"
- name: "Day4Scott__Sort_64"
  tags:
  - "prophecy_temp"
- name: "Day4Scott__Sort_83"
  tags:
  - "prophecy_temp"
