{{
  config({    
    "materialized": "table",
    "alias": "SM_APPLICATION_CAL_MTH_END",
    "database": "tanmay",
    "schema": "default"
  })
}}

WITH `{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_application_mth_end_SQTRANS` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      'm_mmrt_application_mth_end', 
      '{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_application_mth_end_SQTRANS'
    )
  }}

),

SQTRANS_EXPR_2 AS (

  SELECT 
    CLIENTID AS CLIENTID,
    PERIODID AS PERIODID,
    APPLICATION_DATE AS CA_APPLICATION_DATE,
    ACCID AS CA_APPLICATION_ID,
    APPLICATION_TYPE AS CA_APPLICATION_TYPE,
    CARD_PROTECTION AS CA_CARD_PROTECTION,
    CARDSAFE AS CA_CARDSAFE,
    CUSTOMER_NUMBER AS CA_CUSTOMER_NUMBER,
    DISPLAY_ACCOUNT_NUMBER AS CA_DISPLAY_ACCOUNT_NUMBER,
    EMBOSSER_NUMBER AS CA_EMBOSSER_NUMBER,
    ACC_NUM AS CA_EQA_NUMBER,
    FINAL_DECISION_COARSE AS CA_FINAL_DECISION_COARSE,
    STATUS AS CA_FINAL_EQA_STATUS,
    INITIAL_DECISION_COARSE AS CA_INITIAL_DECISION_COARSE,
    PRODUCT_CODE AS CA_PRODUCT_CODE,
    MIGRATION_FLAG AS CA_MIGRATION_FLAG,
    OFFER_CODE AS CA_OFFER_CODE,
    PRODUCT AS CA_PRODUCT,
    SOURCE_CODE AS CA_SOURCE_CODE,
    LAST_DECISION_DATE AS CA_LAST_DECISION_DATE,
    FINAL_DECISION_PRIMARY AS CA_FINAL_DECISION_PRIMARY,
    SYSTEM_CREDIT_LIMIT AS CA_SYSTEM_CREDIT_LIMIT,
    CARD_ORIGIN AS CA_CARD_ORIGIN
  
  FROM `{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_application_mth_end_SQTRANS` AS in0

)

SELECT *

FROM SQTRANS_EXPR_2
