---
version: 2
models:
- name: "p1__AlteryxSelect_228"
  tags:
  - "prophecy_temp"
- name: "p1__AlteryxSelect_338"
  tags:
  - "prophecy_temp"
- name: "p1__AlteryxSelect_533"
  tags:
  - "prophecy_temp"
- name: "p1__AlteryxSelect_547"
  tags:
  - "prophecy_temp"
- name: "p1__AlteryxSelect_551"
  tags:
  - "prophecy_temp"
- name: "p1__Cleanse_214"
  tags:
  - "prophecy_temp"
- name: "p1__Cleanse_316"
  tags:
  - "prophecy_temp"
- name: "p1__Cleanse_317"
  tags:
  - "prophecy_temp"
- name: "p1__Filter_480"
  tags:
  - "prophecy_temp"
- name: "p1__Formula_215_0"
  tags:
  - "prophecy_temp"
- name: "p1__Formula_237_0"
  tags:
  - "prophecy_temp"
- name: "p1__Formula_282_0"
  tags:
  - "prophecy_temp"
- name: "p1__Formula_347_1"
  tags:
  - "prophecy_temp"
- name: "p1__Formula_350_0"
  tags:
  - "prophecy_temp"
- name: "p1__Join_195_left"
  tags:
  - "prophecy_temp"
- name: "p1__Join_202_left"
  tags:
  - "prophecy_temp"
- name: "p1__Join_339_left"
  tags:
  - "prophecy_temp"
- name: "p1__SelectRecords_386_cleanup_0"
  tags:
  - "prophecy_temp"
- name: "p1__Summarize_355"
  tags:
  - "prophecy_temp"
- name: "p1__Union_198"
  tags:
  - "prophecy_temp"
- name: "p1__Union_449"
  tags:
  - "prophecy_temp"
