{{
  config({    
    "materialized": "table",
    "alias": "SM_DRMS_CAL_MTH_END_HIST",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH SQ_DRMS_DETAIL AS (

  SELECT 
    /*+ parallel(DTL) parallel(CAL) parallel(AMA) use_hash(DTL CAL AMA)*/
    SUBSTR('$$MP_BUSDATE', 1, 6) PERIODID,
    DTL.ACCOUNT_NUM,
    DTL.ACCOUNT_BALANCE,
    DTL.ACCOUNT_STATUS,
    DTL.ASSOCIATED_COSTS,
    DTL.JUDGEMENT_ARREARS,
    DTL.JUDGEMENT_SOLICITOR_COSTS,
    DTL.LAST_PAYMENT_DATE,
    DTL.ORDER_FEE,
    DTL.PAID_SINCE_JUDGEMENT,
    DTL.PAYMENT_AMOUNT,
    DTL.PAYMENT_DUE_AMOUNT,
    DTL.RECOVERY_COSTS,
    DTL.RECOVERY_INTEREST,
    DTL.RECOVERY_PRINCIPAL,
    DTL.SUMMONS_AMOUNT,
    DTL.SUMMONS_FEE,
    DTL.SUMMONS_SOLICITOR_COSTS,
    DTL.WARRANT_COSTS,
    DTL.EFROM,
    DTL.LOAN_TYPE_CODE,
    DTL.CHARGE_OFF_AMOUNT,
    DTL.CHARGE_OFF_DATE
  
  FROM DRMS_DETAIL AS DTL, ALL_MONTHLY_ACCOUNTS AS AMA
  
  WHERE TO_DATE('$$MP_BUSDATE', 'YYYYMMDD') BETWEEN DTL.EFROM AND NVL(DTL.ETO, TO_DATE('40001231', 'YYYYMMDD'))
        AND AMA.ACCID = DTL.ACCID

),

SQ_DRMS_DETAIL_EXPR_94 AS (

  SELECT 
    WARRANT_COSTS AS DR_WARRANT_COSTS,
    EFROM AS DR_DETAIL_EFROM,
    LOAN_TYPE_CODE AS DR_LOAN_TYPE_CODE,
    CHARGE_OFF_AMOUNT AS DR_CHARGE_OFF_AMOUNT,
    CHARGE_OFF_DATE AS DR_CHARGE_OFF_DATE,
    PERIODID AS PERIODID,
    ACCOUNT_NUM AS DR_ACCOUNT_NUMBER,
    ACCOUNT_BALANCE AS DR_ACCOUNT_BALANCE,
    ACCOUNT_STATUS AS DR_ACCOUNT_STATUS,
    ASSOCIATED_COSTS AS DR_ASSOCIATED_COSTS,
    JUDGEMENT_ARREARS AS DR_JUDGEMENT_ARREARS,
    JUDGEMENT_SOLICITOR_COSTS AS DR_JUDGEMENT_SOLICITOR_COSTS,
    LAST_PAYMENT_DATE AS DR_LAST_PAYMENT_DATE,
    ORDER_FEE AS DR_ORDER_FEE,
    PAID_SINCE_JUDGEMENT AS DR_PAID_SINCE_JUDGEMENT,
    PAYMENT_AMOUNT AS DR_PAYMENT_AMOUNT,
    PAYMENT_DUE_AMOUNT AS DR_PAYMENT_DUE_AMOUNT,
    RECOVERY_COSTS AS DR_RECOVERY_COSTS,
    RECOVERY_INTEREST AS DR_RECOVERY_INTEREST,
    RECOVERY_PRINCIPAL AS DR_RECOVERY_PRINCIPAL,
    SUMMONS_AMOUNT AS DR_SUMMONS_AMOUNT,
    SUMMONS_FEE AS DR_SUMMONS_FEE,
    SUMMONS_SOLICITOR_COSTS AS DR_SUMMONS_SOLICITOR_COSTS
  
  FROM SQ_DRMS_DETAIL AS in0

)

SELECT *

FROM SQ_DRMS_DETAIL_EXPR_94
