---
version: 2
models:
- name: "1_challenge_1__CrossTab_45_rename"
  tags:
  - "prophecy_temp"
- name: "1_challenge_1__Formula_29_1"
  tags:
  - "prophecy_temp"
- name: "1_challenge_1__Formula_56_0"
  tags:
  - "prophecy_temp"
- name: "1_challenge_1__Summarize_40"
  tags:
  - "prophecy_temp"
- name: "1_challenge_1__Summarize_47"
  tags:
  - "prophecy_temp"
