---
version: 2
models:
- name: "APRA_Processes__AppendFields_641"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__DSN_SnowflakeNP_404"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Email_514_attach"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Filter_580"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Filter_582"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Filter_631"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_249_to_Formula_258_2"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_446_0"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_532_0"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_538_0"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_539_to_Formula_246_1"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_579_0"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_615_1"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_618_1"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_630_0"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_8_to_Formula_23_1"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Formula_99_to_Formula_183_2"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Join_477_inner"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Join_494_inner"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__NoAPRAUnmapped__598"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__PLACEHOLDER_488"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Summarize_413"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Summarize_426"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Union_482"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Unique_489"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__Unique_495"
  tags:
  - "prophecy_temp"
- name: "APRA_Processes__aka_SnowflakePR_445"
  tags:
  - "prophecy_temp"
