{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH Download_21_21 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('Billboard_Webscraping_App_1_', 'Download_21_21') }}

),

Download_21_21_cleanup_0 AS (

  SELECT 
    API_DATA AS DOWNLOADDATA,
    NULL AS DOWNLOADHEADERS,
    * EXCLUDE ("_PARAMSORDATA", "_PROCESSEDURL", "API_DATA")
  
  FROM Download_21_21 AS in0

),

RegEx_22 AS (

  {{
    prophecy_basics.Regex(
      ['Download_21_21_cleanup_0'], 
      [{ 'columnName': 'HASH1 SONG', 'dataType': 'String', 'rgxExpression': '(.+?)' }], 
      '[{"name": "DOWNLOADDATA", "dataType": "String"}, {"name": "DOWNLOADHEADERS", "dataType": "String"}, {"name": "URL", "dataType": "String"}]', 
      'DOWNLOADDATA', 
      'u-letter-spacing-0028@tablet">(.+?)</h3>', 
      'parse', 
      true, 
      false, 
      '', 
      false, 
      'splitColumns', 
      1, 
      'dropExtraWithoutWarning', 
      '', 
      '', 
      false, 
      '_REPLACED'
    )
  }}

),

RegEx_23 AS (

  {{
    prophecy_basics.Regex(
      ['RegEx_22'], 
      [{ 'columnName': 'HASH1 ARTIST', 'dataType': 'String', 'rgxExpression': '(.+?)' }], 
      '[{"name": "DOWNLOADDATA", "dataType": "String"}, {"name": "DOWNLOADHEADERS", "dataType": "String"}, {"name": "URL", "dataType": "String"}, {"name": "HASH1 SONG", "dataType": "String"}]', 
      'DOWNLOADDATA', 
      'u-font-size-20@tablet"\s>(.+?)</span>', 
      'parse', 
      true, 
      false, 
      '', 
      false, 
      'splitColumns', 
      1, 
      'dropExtraWithoutWarning', 
      '', 
      '', 
      false, 
      '_REPLACED'
    )
  }}

),

RegEx_24 AS (

  {{
    prophecy_basics.Regex(
      ['RegEx_23'], 
      [{ 'columnName': 'regex_col1', 'dataType': 'string', 'rgxExpression': '(.+?)' }], 
      '[{"name": "DOWNLOADDATA", "dataType": "String"}, {"name": "DOWNLOADHEADERS", "dataType": "String"}, {"name": "URL", "dataType": "String"}, {"name": "HASH1 SONG", "dataType": "String"}, {"name": "HASH1 ARTIST", "dataType": "String"}]', 
      'DOWNLOADDATA', 
      'u-max-width-230@tablet-only">(.+?)</h3>', 
      'tokenize', 
      true, 
      false, 
      '', 
      false, 
      'splitColumns', 
      99, 
      'dropExtraWithoutWarning', 
      'SONG', 
      '', 
      false, 
      '_REPLACED'
    )
  }}

),

RegEx_25 AS (

  {{
    prophecy_basics.Regex(
      ['RegEx_24'], 
      [{ 'columnName': 'regex_col1', 'dataType': 'string', 'rgxExpression': '(.+?)' }], 
      '[{"name": "DOWNLOADDATA", "dataType": "String"}, {"name": "DOWNLOADHEADERS", "dataType": "String"}, {"name": "URL", "dataType": "String"}, {"name": "HASH1 SONG", "dataType": "String"}, {"name": "HASH1 ARTIST", "dataType": "String"}, {"name": "SONG1", "dataType": "String"}, {"name": "SONG2", "dataType": "String"}, {"name": "SONG3", "dataType": "String"}, {"name": "SONG4", "dataType": "String"}, {"name": "SONG5", "dataType": "String"}, {"name": "SONG6", "dataType": "String"}, {"name": "SONG7", "dataType": "String"}, {"name": "SONG8", "dataType": "String"}, {"name": "SONG9", "dataType": "String"}, {"name": "SONG10", "dataType": "String"}, {"name": "SONG11", "dataType": "String"}, {"name": "SONG12", "dataType": "String"}, {"name": "SONG13", "dataType": "String"}, {"name": "SONG14", "dataType": "String"}, {"name": "SONG15", "dataType": "String"}, {"name": "SONG16", "dataType": "String"}, {"name": "SONG17", "dataType": "String"}, {"name": "SONG18", "dataType": "String"}, {"name": "SONG19", "dataType": "String"}, {"name": "SONG20", "dataType": "String"}, {"name": "SONG21", "dataType": "String"}, {"name": "SONG22", "dataType": "String"}, {"name": "SONG23", "dataType": "String"}, {"name": "SONG24", "dataType": "String"}, {"name": "SONG25", "dataType": "String"}, {"name": "SONG26", "dataType": "String"}, {"name": "SONG27", "dataType": "String"}, {"name": "SONG28", "dataType": "String"}, {"name": "SONG29", "dataType": "String"}, {"name": "SONG30", "dataType": "String"}, {"name": "SONG31", "dataType": "String"}, {"name": "SONG32", "dataType": "String"}, {"name": "SONG33", "dataType": "String"}, {"name": "SONG34", "dataType": "String"}, {"name": "SONG35", "dataType": "String"}, {"name": "SONG36", "dataType": "String"}, {"name": "SONG37", "dataType": "String"}, {"name": "SONG38", "dataType": "String"}, {"name": "SONG39", "dataType": "String"}, {"name": "SONG40", "dataType": "String"}, {"name": "SONG41", "dataType": "String"}, {"name": "SONG42", "dataType": "String"}, {"name": "SONG43", "dataType": "String"}, {"name": "SONG44", "dataType": "String"}, {"name": "SONG45", "dataType": "String"}, {"name": "SONG46", "dataType": "String"}, {"name": "SONG47", "dataType": "String"}, {"name": "SONG48", "dataType": "String"}, {"name": "SONG49", "dataType": "String"}, {"name": "SONG50", "dataType": "String"}, {"name": "SONG51", "dataType": "String"}, {"name": "SONG52", "dataType": "String"}, {"name": "SONG53", "dataType": "String"}, {"name": "SONG54", "dataType": "String"}, {"name": "SONG55", "dataType": "String"}, {"name": "SONG56", "dataType": "String"}, {"name": "SONG57", "dataType": "String"}, {"name": "SONG58", "dataType": "String"}, {"name": "SONG59", "dataType": "String"}, {"name": "SONG60", "dataType": "String"}, {"name": "SONG61", "dataType": "String"}, {"name": "SONG62", "dataType": "String"}, {"name": "SONG63", "dataType": "String"}, {"name": "SONG64", "dataType": "String"}, {"name": "SONG65", "dataType": "String"}, {"name": "SONG66", "dataType": "String"}, {"name": "SONG67", "dataType": "String"}, {"name": "SONG68", "dataType": "String"}, {"name": "SONG69", "dataType": "String"}, {"name": "SONG70", "dataType": "String"}, {"name": "SONG71", "dataType": "String"}, {"name": "SONG72", "dataType": "String"}, {"name": "SONG73", "dataType": "String"}, {"name": "SONG74", "dataType": "String"}, {"name": "SONG75", "dataType": "String"}, {"name": "SONG76", "dataType": "String"}, {"name": "SONG77", "dataType": "String"}, {"name": "SONG78", "dataType": "String"}, {"name": "SONG79", "dataType": "String"}, {"name": "SONG80", "dataType": "String"}, {"name": "SONG81", "dataType": "String"}, {"name": "SONG82", "dataType": "String"}, {"name": "SONG83", "dataType": "String"}, {"name": "SONG84", "dataType": "String"}, {"name": "SONG85", "dataType": "String"}, {"name": "SONG86", "dataType": "String"}, {"name": "SONG87", "dataType": "String"}, {"name": "SONG88", "dataType": "String"}, {"name": "SONG89", "dataType": "String"}, {"name": "SONG90", "dataType": "String"}, {"name": "SONG91", "dataType": "String"}, {"name": "SONG92", "dataType": "String"}, {"name": "SONG93", "dataType": "String"}, {"name": "SONG94", "dataType": "String"}, {"name": "SONG95", "dataType": "String"}, {"name": "SONG96", "dataType": "String"}, {"name": "SONG97", "dataType": "String"}, {"name": "SONG98", "dataType": "String"}, {"name": "SONG99", "dataType": "String"}]', 
      'DOWNLOADDATA', 
      'u-max-width-230@tablet-only"\s>(.+?)</span>', 
      'tokenize', 
      true, 
      false, 
      '', 
      false, 
      'splitColumns', 
      99, 
      'dropExtraWithoutWarning', 
      'ARTIST', 
      '', 
      false, 
      '_REPLACED'
    )
  }}

),

Cleanse_26 AS (

  {{
    prophecy_basics.DataCleansing(
      ['RegEx_25'], 
      [
        { "name": "DOWNLOADDATA", "dataType": "String" }, 
        { "name": "DOWNLOADHEADERS", "dataType": "String" }, 
        { "name": "URL", "dataType": "String" }, 
        { "name": "HASH1 SONG", "dataType": "String" }, 
        { "name": "HASH1 ARTIST", "dataType": "String" }, 
        { "name": "SONG1", "dataType": "String" }, 
        { "name": "SONG2", "dataType": "String" }, 
        { "name": "SONG3", "dataType": "String" }, 
        { "name": "SONG4", "dataType": "String" }, 
        { "name": "SONG5", "dataType": "String" }, 
        { "name": "SONG6", "dataType": "String" }, 
        { "name": "SONG7", "dataType": "String" }, 
        { "name": "SONG8", "dataType": "String" }, 
        { "name": "SONG9", "dataType": "String" }, 
        { "name": "SONG10", "dataType": "String" }, 
        { "name": "SONG11", "dataType": "String" }, 
        { "name": "SONG12", "dataType": "String" }, 
        { "name": "SONG13", "dataType": "String" }, 
        { "name": "SONG14", "dataType": "String" }, 
        { "name": "SONG15", "dataType": "String" }, 
        { "name": "SONG16", "dataType": "String" }, 
        { "name": "SONG17", "dataType": "String" }, 
        { "name": "SONG18", "dataType": "String" }, 
        { "name": "SONG19", "dataType": "String" }, 
        { "name": "SONG20", "dataType": "String" }, 
        { "name": "SONG21", "dataType": "String" }, 
        { "name": "SONG22", "dataType": "String" }, 
        { "name": "SONG23", "dataType": "String" }, 
        { "name": "SONG24", "dataType": "String" }, 
        { "name": "SONG25", "dataType": "String" }, 
        { "name": "SONG26", "dataType": "String" }, 
        { "name": "SONG27", "dataType": "String" }, 
        { "name": "SONG28", "dataType": "String" }, 
        { "name": "SONG29", "dataType": "String" }, 
        { "name": "SONG30", "dataType": "String" }, 
        { "name": "SONG31", "dataType": "String" }, 
        { "name": "SONG32", "dataType": "String" }, 
        { "name": "SONG33", "dataType": "String" }, 
        { "name": "SONG34", "dataType": "String" }, 
        { "name": "SONG35", "dataType": "String" }, 
        { "name": "SONG36", "dataType": "String" }, 
        { "name": "SONG37", "dataType": "String" }, 
        { "name": "SONG38", "dataType": "String" }, 
        { "name": "SONG39", "dataType": "String" }, 
        { "name": "SONG40", "dataType": "String" }, 
        { "name": "SONG41", "dataType": "String" }, 
        { "name": "SONG42", "dataType": "String" }, 
        { "name": "SONG43", "dataType": "String" }, 
        { "name": "SONG44", "dataType": "String" }, 
        { "name": "SONG45", "dataType": "String" }, 
        { "name": "SONG46", "dataType": "String" }, 
        { "name": "SONG47", "dataType": "String" }, 
        { "name": "SONG48", "dataType": "String" }, 
        { "name": "SONG49", "dataType": "String" }, 
        { "name": "SONG50", "dataType": "String" }, 
        { "name": "SONG51", "dataType": "String" }, 
        { "name": "SONG52", "dataType": "String" }, 
        { "name": "SONG53", "dataType": "String" }, 
        { "name": "SONG54", "dataType": "String" }, 
        { "name": "SONG55", "dataType": "String" }, 
        { "name": "SONG56", "dataType": "String" }, 
        { "name": "SONG57", "dataType": "String" }, 
        { "name": "SONG58", "dataType": "String" }, 
        { "name": "SONG59", "dataType": "String" }, 
        { "name": "SONG60", "dataType": "String" }, 
        { "name": "SONG61", "dataType": "String" }, 
        { "name": "SONG62", "dataType": "String" }, 
        { "name": "SONG63", "dataType": "String" }, 
        { "name": "SONG64", "dataType": "String" }, 
        { "name": "SONG65", "dataType": "String" }, 
        { "name": "SONG66", "dataType": "String" }, 
        { "name": "SONG67", "dataType": "String" }, 
        { "name": "SONG68", "dataType": "String" }, 
        { "name": "SONG69", "dataType": "String" }, 
        { "name": "SONG70", "dataType": "String" }, 
        { "name": "SONG71", "dataType": "String" }, 
        { "name": "SONG72", "dataType": "String" }, 
        { "name": "SONG73", "dataType": "String" }, 
        { "name": "SONG74", "dataType": "String" }, 
        { "name": "SONG75", "dataType": "String" }, 
        { "name": "SONG76", "dataType": "String" }, 
        { "name": "SONG77", "dataType": "String" }, 
        { "name": "SONG78", "dataType": "String" }, 
        { "name": "SONG79", "dataType": "String" }, 
        { "name": "SONG80", "dataType": "String" }, 
        { "name": "SONG81", "dataType": "String" }, 
        { "name": "SONG82", "dataType": "String" }, 
        { "name": "SONG83", "dataType": "String" }, 
        { "name": "SONG84", "dataType": "String" }, 
        { "name": "SONG85", "dataType": "String" }, 
        { "name": "SONG86", "dataType": "String" }, 
        { "name": "SONG87", "dataType": "String" }, 
        { "name": "SONG88", "dataType": "String" }, 
        { "name": "SONG89", "dataType": "String" }, 
        { "name": "SONG90", "dataType": "String" }, 
        { "name": "SONG91", "dataType": "String" }, 
        { "name": "SONG92", "dataType": "String" }, 
        { "name": "SONG93", "dataType": "String" }, 
        { "name": "SONG94", "dataType": "String" }, 
        { "name": "SONG95", "dataType": "String" }, 
        { "name": "SONG96", "dataType": "String" }, 
        { "name": "SONG97", "dataType": "String" }, 
        { "name": "SONG98", "dataType": "String" }, 
        { "name": "SONG99", "dataType": "String" }, 
        { "name": "ARTIST1", "dataType": "String" }, 
        { "name": "ARTIST2", "dataType": "String" }, 
        { "name": "ARTIST3", "dataType": "String" }, 
        { "name": "ARTIST4", "dataType": "String" }, 
        { "name": "ARTIST5", "dataType": "String" }, 
        { "name": "ARTIST6", "dataType": "String" }, 
        { "name": "ARTIST7", "dataType": "String" }, 
        { "name": "ARTIST8", "dataType": "String" }, 
        { "name": "ARTIST9", "dataType": "String" }, 
        { "name": "ARTIST10", "dataType": "String" }, 
        { "name": "ARTIST11", "dataType": "String" }, 
        { "name": "ARTIST12", "dataType": "String" }, 
        { "name": "ARTIST13", "dataType": "String" }, 
        { "name": "ARTIST14", "dataType": "String" }, 
        { "name": "ARTIST15", "dataType": "String" }, 
        { "name": "ARTIST16", "dataType": "String" }, 
        { "name": "ARTIST17", "dataType": "String" }, 
        { "name": "ARTIST18", "dataType": "String" }, 
        { "name": "ARTIST19", "dataType": "String" }, 
        { "name": "ARTIST20", "dataType": "String" }, 
        { "name": "ARTIST21", "dataType": "String" }, 
        { "name": "ARTIST22", "dataType": "String" }, 
        { "name": "ARTIST23", "dataType": "String" }, 
        { "name": "ARTIST24", "dataType": "String" }, 
        { "name": "ARTIST25", "dataType": "String" }, 
        { "name": "ARTIST26", "dataType": "String" }, 
        { "name": "ARTIST27", "dataType": "String" }, 
        { "name": "ARTIST28", "dataType": "String" }, 
        { "name": "ARTIST29", "dataType": "String" }, 
        { "name": "ARTIST30", "dataType": "String" }, 
        { "name": "ARTIST31", "dataType": "String" }, 
        { "name": "ARTIST32", "dataType": "String" }, 
        { "name": "ARTIST33", "dataType": "String" }, 
        { "name": "ARTIST34", "dataType": "String" }, 
        { "name": "ARTIST35", "dataType": "String" }, 
        { "name": "ARTIST36", "dataType": "String" }, 
        { "name": "ARTIST37", "dataType": "String" }, 
        { "name": "ARTIST38", "dataType": "String" }, 
        { "name": "ARTIST39", "dataType": "String" }, 
        { "name": "ARTIST40", "dataType": "String" }, 
        { "name": "ARTIST41", "dataType": "String" }, 
        { "name": "ARTIST42", "dataType": "String" }, 
        { "name": "ARTIST43", "dataType": "String" }, 
        { "name": "ARTIST44", "dataType": "String" }, 
        { "name": "ARTIST45", "dataType": "String" }, 
        { "name": "ARTIST46", "dataType": "String" }, 
        { "name": "ARTIST47", "dataType": "String" }, 
        { "name": "ARTIST48", "dataType": "String" }, 
        { "name": "ARTIST49", "dataType": "String" }, 
        { "name": "ARTIST50", "dataType": "String" }, 
        { "name": "ARTIST51", "dataType": "String" }, 
        { "name": "ARTIST52", "dataType": "String" }, 
        { "name": "ARTIST53", "dataType": "String" }, 
        { "name": "ARTIST54", "dataType": "String" }, 
        { "name": "ARTIST55", "dataType": "String" }, 
        { "name": "ARTIST56", "dataType": "String" }, 
        { "name": "ARTIST57", "dataType": "String" }, 
        { "name": "ARTIST58", "dataType": "String" }, 
        { "name": "ARTIST59", "dataType": "String" }, 
        { "name": "ARTIST60", "dataType": "String" }, 
        { "name": "ARTIST61", "dataType": "String" }, 
        { "name": "ARTIST62", "dataType": "String" }, 
        { "name": "ARTIST63", "dataType": "String" }, 
        { "name": "ARTIST64", "dataType": "String" }, 
        { "name": "ARTIST65", "dataType": "String" }, 
        { "name": "ARTIST66", "dataType": "String" }, 
        { "name": "ARTIST67", "dataType": "String" }, 
        { "name": "ARTIST68", "dataType": "String" }, 
        { "name": "ARTIST69", "dataType": "String" }, 
        { "name": "ARTIST70", "dataType": "String" }, 
        { "name": "ARTIST71", "dataType": "String" }, 
        { "name": "ARTIST72", "dataType": "String" }, 
        { "name": "ARTIST73", "dataType": "String" }, 
        { "name": "ARTIST74", "dataType": "String" }, 
        { "name": "ARTIST75", "dataType": "String" }, 
        { "name": "ARTIST76", "dataType": "String" }, 
        { "name": "ARTIST77", "dataType": "String" }, 
        { "name": "ARTIST78", "dataType": "String" }, 
        { "name": "ARTIST79", "dataType": "String" }, 
        { "name": "ARTIST80", "dataType": "String" }, 
        { "name": "ARTIST81", "dataType": "String" }, 
        { "name": "ARTIST82", "dataType": "String" }, 
        { "name": "ARTIST83", "dataType": "String" }, 
        { "name": "ARTIST84", "dataType": "String" }, 
        { "name": "ARTIST85", "dataType": "String" }, 
        { "name": "ARTIST86", "dataType": "String" }, 
        { "name": "ARTIST87", "dataType": "String" }, 
        { "name": "ARTIST88", "dataType": "String" }, 
        { "name": "ARTIST89", "dataType": "String" }, 
        { "name": "ARTIST90", "dataType": "String" }, 
        { "name": "ARTIST91", "dataType": "String" }, 
        { "name": "ARTIST92", "dataType": "String" }, 
        { "name": "ARTIST93", "dataType": "String" }, 
        { "name": "ARTIST94", "dataType": "String" }, 
        { "name": "ARTIST95", "dataType": "String" }, 
        { "name": "ARTIST96", "dataType": "String" }, 
        { "name": "ARTIST97", "dataType": "String" }, 
        { "name": "ARTIST98", "dataType": "String" }, 
        { "name": "ARTIST99", "dataType": "String" }
      ], 
      'keepOriginal', 
      [
        'HASH1 SONG', 
        'HASH1 ARTIST', 
        'SONG1', 
        'SONG2', 
        'SONG3', 
        'SONG4', 
        'SONG5', 
        'SONG6', 
        'SONG7', 
        'SONG8', 
        'SONG9', 
        'SONG10', 
        'SONG11', 
        'SONG12', 
        'SONG13', 
        'SONG14', 
        'SONG15', 
        'SONG16', 
        'SONG17', 
        'SONG18', 
        'SONG19', 
        'SONG20', 
        'SONG21', 
        'SONG22', 
        'SONG23', 
        'SONG24', 
        'SONG25', 
        'SONG26', 
        'SONG27', 
        'SONG28', 
        'SONG29', 
        'SONG30', 
        'SONG31', 
        'SONG32', 
        'SONG33', 
        'SONG34', 
        'SONG35', 
        'SONG36', 
        'SONG37', 
        'SONG38', 
        'SONG39', 
        'SONG40', 
        'SONG41', 
        'SONG42', 
        'SONG43', 
        'SONG44', 
        'SONG45', 
        'SONG46', 
        'SONG47', 
        'SONG48', 
        'SONG49', 
        'SONG50', 
        'SONG51', 
        'SONG52', 
        'SONG53', 
        'SONG54', 
        'SONG55', 
        'SONG56', 
        'SONG57', 
        'SONG58', 
        'SONG59', 
        'SONG60', 
        'SONG61', 
        'SONG62', 
        'SONG63', 
        'SONG64', 
        'SONG65', 
        'SONG66', 
        'SONG67', 
        'SONG68', 
        'SONG69', 
        'SONG70', 
        'SONG71', 
        'SONG72', 
        'SONG73', 
        'SONG74', 
        'SONG75', 
        'SONG76', 
        'SONG77', 
        'SONG78', 
        'SONG79', 
        'SONG80', 
        'SONG81', 
        'SONG82', 
        'SONG83', 
        'SONG84', 
        'SONG85', 
        'SONG86', 
        'SONG87', 
        'SONG88', 
        'SONG89', 
        'SONG90', 
        'SONG91', 
        'SONG92', 
        'SONG93', 
        'SONG94', 
        'SONG95', 
        'SONG96', 
        'SONG97', 
        'SONG98', 
        'SONG99', 
        'ARTIST1', 
        'ARTIST2', 
        'ARTIST3', 
        'ARTIST4', 
        'ARTIST5', 
        'ARTIST6', 
        'ARTIST7', 
        'ARTIST8', 
        'ARTIST9', 
        'ARTIST10', 
        'ARTIST11', 
        'ARTIST12', 
        'ARTIST13', 
        'ARTIST14', 
        'ARTIST15', 
        'ARTIST16', 
        'ARTIST17', 
        'ARTIST18', 
        'ARTIST19', 
        'ARTIST20', 
        'ARTIST21', 
        'ARTIST22', 
        'ARTIST23', 
        'ARTIST24', 
        'ARTIST25', 
        'ARTIST26', 
        'ARTIST27', 
        'ARTIST28', 
        'ARTIST29', 
        'ARTIST30', 
        'ARTIST31', 
        'ARTIST32', 
        'ARTIST33', 
        'ARTIST34', 
        'ARTIST35', 
        'ARTIST36', 
        'ARTIST37', 
        'ARTIST38', 
        'ARTIST39', 
        'ARTIST40', 
        'ARTIST41', 
        'ARTIST42', 
        'ARTIST43', 
        'ARTIST44', 
        'ARTIST45', 
        'ARTIST46', 
        'ARTIST47', 
        'ARTIST48', 
        'ARTIST49', 
        'ARTIST50', 
        'ARTIST51', 
        'ARTIST52', 
        'ARTIST53', 
        'ARTIST54', 
        'ARTIST55', 
        'ARTIST56', 
        'ARTIST57', 
        'ARTIST58', 
        'ARTIST59', 
        'ARTIST60', 
        'ARTIST61', 
        'ARTIST62', 
        'ARTIST63', 
        'ARTIST64', 
        'ARTIST65', 
        'ARTIST66', 
        'ARTIST67', 
        'ARTIST68', 
        'ARTIST69', 
        'ARTIST70', 
        'ARTIST71', 
        'ARTIST72', 
        'ARTIST73', 
        'ARTIST74', 
        'ARTIST75', 
        'ARTIST76', 
        'ARTIST77', 
        'ARTIST78', 
        'ARTIST79', 
        'ARTIST80', 
        'ARTIST81', 
        'ARTIST82', 
        'ARTIST83', 
        'ARTIST84', 
        'ARTIST85', 
        'ARTIST86', 
        'ARTIST87', 
        'ARTIST88', 
        'ARTIST89', 
        'ARTIST90', 
        'ARTIST91', 
        'ARTIST92', 
        'ARTIST93', 
        'ARTIST94', 
        'ARTIST95', 
        'ARTIST96', 
        'ARTIST97', 
        'ARTIST98', 
        'ARTIST99'
      ], 
      true, 
      '', 
      true, 
      0, 
      true, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

MultiFieldFormula_27 AS (

  {{
    prophecy_basics.MultiColumnEdit(
      ['Cleanse_26'], 
      "regexp_replace(column_value, '&#039;', '\')", 
      [
        'DOWNLOADDATA', 
        'DOWNLOADHEADERS', 
        'URL', 
        'HASH1 SONG', 
        'HASH1 ARTIST', 
        'SONG1', 
        'SONG2', 
        'SONG3', 
        'SONG4', 
        'SONG5', 
        'SONG6', 
        'SONG7', 
        'SONG8', 
        'SONG9', 
        'SONG10', 
        'SONG11', 
        'SONG12', 
        'SONG13', 
        'SONG14', 
        'SONG15', 
        'SONG16', 
        'SONG17', 
        'SONG18', 
        'SONG19', 
        'SONG20', 
        'SONG21', 
        'SONG22', 
        'SONG23', 
        'SONG24', 
        'SONG25', 
        'SONG26', 
        'SONG27', 
        'SONG28', 
        'SONG29', 
        'SONG30', 
        'SONG31', 
        'SONG32', 
        'SONG33', 
        'SONG34', 
        'SONG35', 
        'SONG36', 
        'SONG37', 
        'SONG38', 
        'SONG39', 
        'SONG40', 
        'SONG41', 
        'SONG42', 
        'SONG43', 
        'SONG44', 
        'SONG45', 
        'SONG46', 
        'SONG47', 
        'SONG48', 
        'SONG49', 
        'SONG50', 
        'SONG51', 
        'SONG52', 
        'SONG53', 
        'SONG54', 
        'SONG55', 
        'SONG56', 
        'SONG57', 
        'SONG58', 
        'SONG59', 
        'SONG60', 
        'SONG61', 
        'SONG62', 
        'SONG63', 
        'SONG64', 
        'SONG65', 
        'SONG66', 
        'SONG67', 
        'SONG68', 
        'SONG69', 
        'SONG70', 
        'SONG71', 
        'SONG72', 
        'SONG73', 
        'SONG74', 
        'SONG75', 
        'SONG76', 
        'SONG77', 
        'SONG78', 
        'SONG79', 
        'SONG80', 
        'SONG81', 
        'SONG82', 
        'SONG83', 
        'SONG84', 
        'SONG85', 
        'SONG86', 
        'SONG87', 
        'SONG88', 
        'SONG89', 
        'SONG90', 
        'SONG91', 
        'SONG92', 
        'SONG93', 
        'SONG94', 
        'SONG95', 
        'SONG96', 
        'SONG97', 
        'SONG98', 
        'SONG99', 
        'ARTIST1', 
        'ARTIST2', 
        'ARTIST3', 
        'ARTIST4', 
        'ARTIST5', 
        'ARTIST6', 
        'ARTIST7', 
        'ARTIST8', 
        'ARTIST9', 
        'ARTIST10', 
        'ARTIST11', 
        'ARTIST12', 
        'ARTIST13', 
        'ARTIST14', 
        'ARTIST15', 
        'ARTIST16', 
        'ARTIST17', 
        'ARTIST18', 
        'ARTIST19', 
        'ARTIST20', 
        'ARTIST21', 
        'ARTIST22', 
        'ARTIST23', 
        'ARTIST24', 
        'ARTIST25', 
        'ARTIST26', 
        'ARTIST27', 
        'ARTIST28', 
        'ARTIST29', 
        'ARTIST30', 
        'ARTIST31', 
        'ARTIST32', 
        'ARTIST33', 
        'ARTIST34', 
        'ARTIST35', 
        'ARTIST36', 
        'ARTIST37', 
        'ARTIST38', 
        'ARTIST39', 
        'ARTIST40', 
        'ARTIST41', 
        'ARTIST42', 
        'ARTIST43', 
        'ARTIST44', 
        'ARTIST45', 
        'ARTIST46', 
        'ARTIST47', 
        'ARTIST48', 
        'ARTIST49', 
        'ARTIST50', 
        'ARTIST51', 
        'ARTIST52', 
        'ARTIST53', 
        'ARTIST54', 
        'ARTIST55', 
        'ARTIST56', 
        'ARTIST57', 
        'ARTIST58', 
        'ARTIST59', 
        'ARTIST60', 
        'ARTIST61', 
        'ARTIST62', 
        'ARTIST63', 
        'ARTIST64', 
        'ARTIST65', 
        'ARTIST66', 
        'ARTIST67', 
        'ARTIST68', 
        'ARTIST69', 
        'ARTIST70', 
        'ARTIST71', 
        'ARTIST72', 
        'ARTIST73', 
        'ARTIST74', 
        'ARTIST75', 
        'ARTIST76', 
        'ARTIST77', 
        'ARTIST78', 
        'ARTIST79', 
        'ARTIST80', 
        'ARTIST81', 
        'ARTIST82', 
        'ARTIST83', 
        'ARTIST84', 
        'ARTIST85', 
        'ARTIST86', 
        'ARTIST87', 
        'ARTIST88', 
        'ARTIST89', 
        'ARTIST90', 
        'ARTIST91', 
        'ARTIST92', 
        'ARTIST93', 
        'ARTIST94', 
        'ARTIST95', 
        'ARTIST96', 
        'ARTIST97', 
        'ARTIST98', 
        'ARTIST99'
      ], 
      [
        'HASH1 SONG', 
        'HASH1 ARTIST', 
        'SONG1', 
        'SONG2', 
        'SONG3', 
        'SONG4', 
        'SONG5', 
        'SONG6', 
        'SONG7', 
        'SONG8', 
        'SONG9', 
        'SONG10', 
        'SONG11', 
        'SONG12', 
        'SONG13', 
        'SONG14', 
        'SONG15', 
        'SONG16', 
        'SONG17', 
        'SONG18', 
        'SONG19', 
        'SONG20', 
        'SONG21', 
        'SONG22', 
        'SONG23', 
        'SONG24', 
        'SONG25', 
        'SONG26', 
        'SONG27', 
        'SONG28', 
        'SONG29', 
        'SONG30', 
        'SONG31', 
        'SONG32', 
        'SONG33', 
        'SONG34', 
        'SONG35', 
        'SONG36', 
        'SONG37', 
        'SONG38', 
        'SONG39', 
        'SONG40', 
        'SONG41', 
        'SONG42', 
        'SONG43', 
        'SONG44', 
        'SONG45', 
        'SONG46', 
        'SONG47', 
        'SONG48', 
        'SONG49', 
        'SONG50', 
        'SONG51', 
        'SONG52', 
        'SONG53', 
        'SONG54', 
        'SONG55', 
        'SONG56', 
        'SONG57', 
        'SONG58', 
        'SONG59', 
        'SONG60', 
        'SONG61', 
        'SONG62', 
        'SONG63', 
        'SONG64', 
        'SONG65', 
        'SONG66', 
        'SONG67', 
        'SONG68', 
        'SONG69', 
        'SONG70', 
        'SONG71', 
        'SONG72', 
        'SONG73', 
        'SONG74', 
        'SONG75', 
        'SONG76', 
        'SONG77', 
        'SONG78', 
        'SONG79', 
        'SONG80', 
        'SONG81', 
        'SONG82', 
        'SONG83', 
        'SONG84', 
        'SONG85', 
        'SONG86', 
        'SONG87', 
        'SONG88', 
        'SONG89', 
        'SONG90', 
        'SONG91', 
        'SONG92', 
        'SONG93', 
        'SONG94', 
        'SONG95', 
        'SONG96', 
        'SONG97', 
        'SONG98', 
        'SONG99', 
        'ARTIST1', 
        'ARTIST2', 
        'ARTIST3', 
        'ARTIST4', 
        'ARTIST5', 
        'ARTIST6', 
        'ARTIST7', 
        'ARTIST8', 
        'ARTIST9', 
        'ARTIST10', 
        'ARTIST11', 
        'ARTIST12', 
        'ARTIST13', 
        'ARTIST14', 
        'ARTIST15', 
        'ARTIST16', 
        'ARTIST17', 
        'ARTIST18', 
        'ARTIST19', 
        'ARTIST20', 
        'ARTIST21', 
        'ARTIST22', 
        'ARTIST23', 
        'ARTIST24', 
        'ARTIST25', 
        'ARTIST26', 
        'ARTIST27', 
        'ARTIST28', 
        'ARTIST29', 
        'ARTIST30', 
        'ARTIST31', 
        'ARTIST32', 
        'ARTIST33', 
        'ARTIST34', 
        'ARTIST35', 
        'ARTIST36', 
        'ARTIST37', 
        'ARTIST38', 
        'ARTIST39', 
        'ARTIST40', 
        'ARTIST41', 
        'ARTIST42', 
        'ARTIST43', 
        'ARTIST44', 
        'ARTIST45', 
        'ARTIST46', 
        'ARTIST47', 
        'ARTIST48', 
        'ARTIST49', 
        'ARTIST50', 
        'ARTIST51', 
        'ARTIST52', 
        'ARTIST53', 
        'ARTIST54', 
        'ARTIST55', 
        'ARTIST56', 
        'ARTIST57', 
        'ARTIST58', 
        'ARTIST59', 
        'ARTIST60', 
        'ARTIST61', 
        'ARTIST62', 
        'ARTIST63', 
        'ARTIST64', 
        'ARTIST65', 
        'ARTIST66', 
        'ARTIST67', 
        'ARTIST68', 
        'ARTIST69', 
        'ARTIST70', 
        'ARTIST71', 
        'ARTIST72', 
        'ARTIST73', 
        'ARTIST74', 
        'ARTIST75', 
        'ARTIST76', 
        'ARTIST77', 
        'ARTIST78', 
        'ARTIST79', 
        'ARTIST80', 
        'ARTIST81', 
        'ARTIST82', 
        'ARTIST83', 
        'ARTIST84', 
        'ARTIST85', 
        'ARTIST86', 
        'ARTIST87', 
        'ARTIST88', 
        'ARTIST89', 
        'ARTIST90', 
        'ARTIST91', 
        'ARTIST92', 
        'ARTIST93', 
        'ARTIST94', 
        'ARTIST95', 
        'ARTIST96', 
        'ARTIST97', 
        'ARTIST98', 
        'ARTIST99'
      ], 
      false, 
      'Suffix', 
      ''
    )
  }}

),

MultiFieldFormula_34 AS (

  {{
    prophecy_basics.MultiColumnEdit(
      ['MultiFieldFormula_27'], 
      "(REGEXP_REPLACE(column_value, '&amp;', '&'))", 
      [
        'DOWNLOADDATA', 
        'DOWNLOADHEADERS', 
        'URL', 
        'HASH1 SONG', 
        'HASH1 ARTIST', 
        'SONG1', 
        'SONG2', 
        'SONG3', 
        'SONG4', 
        'SONG5', 
        'SONG6', 
        'SONG7', 
        'SONG8', 
        'SONG9', 
        'SONG10', 
        'SONG11', 
        'SONG12', 
        'SONG13', 
        'SONG14', 
        'SONG15', 
        'SONG16', 
        'SONG17', 
        'SONG18', 
        'SONG19', 
        'SONG20', 
        'SONG21', 
        'SONG22', 
        'SONG23', 
        'SONG24', 
        'SONG25', 
        'SONG26', 
        'SONG27', 
        'SONG28', 
        'SONG29', 
        'SONG30', 
        'SONG31', 
        'SONG32', 
        'SONG33', 
        'SONG34', 
        'SONG35', 
        'SONG36', 
        'SONG37', 
        'SONG38', 
        'SONG39', 
        'SONG40', 
        'SONG41', 
        'SONG42', 
        'SONG43', 
        'SONG44', 
        'SONG45', 
        'SONG46', 
        'SONG47', 
        'SONG48', 
        'SONG49', 
        'SONG50', 
        'SONG51', 
        'SONG52', 
        'SONG53', 
        'SONG54', 
        'SONG55', 
        'SONG56', 
        'SONG57', 
        'SONG58', 
        'SONG59', 
        'SONG60', 
        'SONG61', 
        'SONG62', 
        'SONG63', 
        'SONG64', 
        'SONG65', 
        'SONG66', 
        'SONG67', 
        'SONG68', 
        'SONG69', 
        'SONG70', 
        'SONG71', 
        'SONG72', 
        'SONG73', 
        'SONG74', 
        'SONG75', 
        'SONG76', 
        'SONG77', 
        'SONG78', 
        'SONG79', 
        'SONG80', 
        'SONG81', 
        'SONG82', 
        'SONG83', 
        'SONG84', 
        'SONG85', 
        'SONG86', 
        'SONG87', 
        'SONG88', 
        'SONG89', 
        'SONG90', 
        'SONG91', 
        'SONG92', 
        'SONG93', 
        'SONG94', 
        'SONG95', 
        'SONG96', 
        'SONG97', 
        'SONG98', 
        'SONG99', 
        'ARTIST1', 
        'ARTIST2', 
        'ARTIST3', 
        'ARTIST4', 
        'ARTIST5', 
        'ARTIST6', 
        'ARTIST7', 
        'ARTIST8', 
        'ARTIST9', 
        'ARTIST10', 
        'ARTIST11', 
        'ARTIST12', 
        'ARTIST13', 
        'ARTIST14', 
        'ARTIST15', 
        'ARTIST16', 
        'ARTIST17', 
        'ARTIST18', 
        'ARTIST19', 
        'ARTIST20', 
        'ARTIST21', 
        'ARTIST22', 
        'ARTIST23', 
        'ARTIST24', 
        'ARTIST25', 
        'ARTIST26', 
        'ARTIST27', 
        'ARTIST28', 
        'ARTIST29', 
        'ARTIST30', 
        'ARTIST31', 
        'ARTIST32', 
        'ARTIST33', 
        'ARTIST34', 
        'ARTIST35', 
        'ARTIST36', 
        'ARTIST37', 
        'ARTIST38', 
        'ARTIST39', 
        'ARTIST40', 
        'ARTIST41', 
        'ARTIST42', 
        'ARTIST43', 
        'ARTIST44', 
        'ARTIST45', 
        'ARTIST46', 
        'ARTIST47', 
        'ARTIST48', 
        'ARTIST49', 
        'ARTIST50', 
        'ARTIST51', 
        'ARTIST52', 
        'ARTIST53', 
        'ARTIST54', 
        'ARTIST55', 
        'ARTIST56', 
        'ARTIST57', 
        'ARTIST58', 
        'ARTIST59', 
        'ARTIST60', 
        'ARTIST61', 
        'ARTIST62', 
        'ARTIST63', 
        'ARTIST64', 
        'ARTIST65', 
        'ARTIST66', 
        'ARTIST67', 
        'ARTIST68', 
        'ARTIST69', 
        'ARTIST70', 
        'ARTIST71', 
        'ARTIST72', 
        'ARTIST73', 
        'ARTIST74', 
        'ARTIST75', 
        'ARTIST76', 
        'ARTIST77', 
        'ARTIST78', 
        'ARTIST79', 
        'ARTIST80', 
        'ARTIST81', 
        'ARTIST82', 
        'ARTIST83', 
        'ARTIST84', 
        'ARTIST85', 
        'ARTIST86', 
        'ARTIST87', 
        'ARTIST88', 
        'ARTIST89', 
        'ARTIST90', 
        'ARTIST91', 
        'ARTIST92', 
        'ARTIST93', 
        'ARTIST94', 
        'ARTIST95', 
        'ARTIST96', 
        'ARTIST97', 
        'ARTIST98', 
        'ARTIST99'
      ], 
      [
        'HASH1 SONG', 
        'HASH1 ARTIST', 
        'SONG1', 
        'SONG2', 
        'SONG3', 
        'SONG4', 
        'SONG5', 
        'SONG6', 
        'SONG7', 
        'SONG8', 
        'SONG9', 
        'SONG10', 
        'SONG11', 
        'SONG12', 
        'SONG13', 
        'SONG14', 
        'SONG15', 
        'SONG16', 
        'SONG17', 
        'SONG18', 
        'SONG19', 
        'SONG20', 
        'SONG21', 
        'SONG22', 
        'SONG23', 
        'SONG24', 
        'SONG25', 
        'SONG26', 
        'SONG27', 
        'SONG28', 
        'SONG29', 
        'SONG30', 
        'SONG31', 
        'SONG32', 
        'SONG33', 
        'SONG34', 
        'SONG35', 
        'SONG36', 
        'SONG37', 
        'SONG38', 
        'SONG39', 
        'SONG40', 
        'SONG41', 
        'SONG42', 
        'SONG43', 
        'SONG44', 
        'SONG45', 
        'SONG46', 
        'SONG47', 
        'SONG48', 
        'SONG49', 
        'SONG50', 
        'SONG51', 
        'SONG52', 
        'SONG53', 
        'SONG54', 
        'SONG55', 
        'SONG56', 
        'SONG57', 
        'SONG58', 
        'SONG59', 
        'SONG60', 
        'SONG61', 
        'SONG62', 
        'SONG63', 
        'SONG64', 
        'SONG65', 
        'SONG66', 
        'SONG67', 
        'SONG68', 
        'SONG69', 
        'SONG70', 
        'SONG71', 
        'SONG72', 
        'SONG73', 
        'SONG74', 
        'SONG75', 
        'SONG76', 
        'SONG77', 
        'SONG78', 
        'SONG79', 
        'SONG80', 
        'SONG81', 
        'SONG82', 
        'SONG83', 
        'SONG84', 
        'SONG85', 
        'SONG86', 
        'SONG87', 
        'SONG88', 
        'SONG89', 
        'SONG90', 
        'SONG91', 
        'SONG92', 
        'SONG93', 
        'SONG94', 
        'SONG95', 
        'SONG96', 
        'SONG97', 
        'SONG98', 
        'SONG99', 
        'ARTIST1', 
        'ARTIST2', 
        'ARTIST3', 
        'ARTIST4', 
        'ARTIST5', 
        'ARTIST6', 
        'ARTIST7', 
        'ARTIST8', 
        'ARTIST9', 
        'ARTIST10', 
        'ARTIST11', 
        'ARTIST12', 
        'ARTIST13', 
        'ARTIST14', 
        'ARTIST15', 
        'ARTIST16', 
        'ARTIST17', 
        'ARTIST18', 
        'ARTIST19', 
        'ARTIST20', 
        'ARTIST21', 
        'ARTIST22', 
        'ARTIST23', 
        'ARTIST24', 
        'ARTIST25', 
        'ARTIST26', 
        'ARTIST27', 
        'ARTIST28', 
        'ARTIST29', 
        'ARTIST30', 
        'ARTIST31', 
        'ARTIST32', 
        'ARTIST33', 
        'ARTIST34', 
        'ARTIST35', 
        'ARTIST36', 
        'ARTIST37', 
        'ARTIST38', 
        'ARTIST39', 
        'ARTIST40', 
        'ARTIST41', 
        'ARTIST42', 
        'ARTIST43', 
        'ARTIST44', 
        'ARTIST45', 
        'ARTIST46', 
        'ARTIST47', 
        'ARTIST48', 
        'ARTIST49', 
        'ARTIST50', 
        'ARTIST51', 
        'ARTIST52', 
        'ARTIST53', 
        'ARTIST54', 
        'ARTIST55', 
        'ARTIST56', 
        'ARTIST57', 
        'ARTIST58', 
        'ARTIST59', 
        'ARTIST60', 
        'ARTIST61', 
        'ARTIST62', 
        'ARTIST63', 
        'ARTIST64', 
        'ARTIST65', 
        'ARTIST66', 
        'ARTIST67', 
        'ARTIST68', 
        'ARTIST69', 
        'ARTIST70', 
        'ARTIST71', 
        'ARTIST72', 
        'ARTIST73', 
        'ARTIST74', 
        'ARTIST75', 
        'ARTIST76', 
        'ARTIST77', 
        'ARTIST78', 
        'ARTIST79', 
        'ARTIST80', 
        'ARTIST81', 
        'ARTIST82', 
        'ARTIST83', 
        'ARTIST84', 
        'ARTIST85', 
        'ARTIST86', 
        'ARTIST87', 
        'ARTIST88', 
        'ARTIST89', 
        'ARTIST90', 
        'ARTIST91', 
        'ARTIST92', 
        'ARTIST93', 
        'ARTIST94', 
        'ARTIST95', 
        'ARTIST96', 
        'ARTIST97', 
        'ARTIST98', 
        'ARTIST99'
      ], 
      false, 
      'Suffix', 
      ''
    )
  }}

),

MultiFieldFormula_40 AS (

  {{ prophecy_basics.MultiColumnEdit(['MultiFieldFormula_34'],"(REGEXP_REPLACE(column_value, '"', '"'))",['DOWNLOADDATA', 'DOWNLOADHEADERS', 'URL', 'HASH1 SONG', 'HASH1 ARTIST', 'SONG1', 'SONG2', 'SONG3', 'SONG4', 'SONG5', 'SONG6', 'SONG7', 'SONG8', 'SONG9', 'SONG10', 'SONG11', 'SONG12', 'SONG13', 'SONG14', 'SONG15', 'SONG16', 'SONG17', 'SONG18', 'SONG19', 'SONG20', 'SONG21', 'SONG22', 'SONG23', 'SONG24', 'SONG25', 'SONG26', 'SONG27', 'SONG28', 'SONG29', 'SONG30', 'SONG31', 'SONG32', 'SONG33', 'SONG34', 'SONG35', 'SONG36', 'SONG37', 'SONG38', 'SONG39', 'SONG40', 'SONG41', 'SONG42', 'SONG43', 'SONG44', 'SONG45', 'SONG46', 'SONG47', 'SONG48', 'SONG49', 'SONG50', 'SONG51', 'SONG52', 'SONG53', 'SONG54', 'SONG55', 'SONG56', 'SONG57', 'SONG58', 'SONG59', 'SONG60', 'SONG61', 'SONG62', 'SONG63', 'SONG64', 'SONG65', 'SONG66', 'SONG67', 'SONG68', 'SONG69', 'SONG70', 'SONG71', 'SONG72', 'SONG73', 'SONG74', 'SONG75', 'SONG76', 'SONG77', 'SONG78', 'SONG79', 'SONG80', 'SONG81', 'SONG82', 'SONG83', 'SONG84', 'SONG85', 'SONG86', 'SONG87', 'SONG88', 'SONG89', 'SONG90', 'SONG91', 'SONG92', 'SONG93', 'SONG94', 'SONG95', 'SONG96', 'SONG97', 'SONG98', 'SONG99', 'ARTIST1', 'ARTIST2', 'ARTIST3', 'ARTIST4', 'ARTIST5', 'ARTIST6', 'ARTIST7', 'ARTIST8', 'ARTIST9', 'ARTIST10', 'ARTIST11', 'ARTIST12', 'ARTIST13', 'ARTIST14', 'ARTIST15', 'ARTIST16', 'ARTIST17', 'ARTIST18', 'ARTIST19', 'ARTIST20', 'ARTIST21', 'ARTIST22', 'ARTIST23', 'ARTIST24', 'ARTIST25', 'ARTIST26', 'ARTIST27', 'ARTIST28', 'ARTIST29', 'ARTIST30', 'ARTIST31', 'ARTIST32', 'ARTIST33', 'ARTIST34', 'ARTIST35', 'ARTIST36', 'ARTIST37', 'ARTIST38', 'ARTIST39', 'ARTIST40', 'ARTIST41', 'ARTIST42', 'ARTIST43', 'ARTIST44', 'ARTIST45', 'ARTIST46', 'ARTIST47', 'ARTIST48', 'ARTIST49', 'ARTIST50', 'ARTIST51', 'ARTIST52', 'ARTIST53', 'ARTIST54', 'ARTIST55', 'ARTIST56', 'ARTIST57', 'ARTIST58', 'ARTIST59', 'ARTIST60', 'ARTIST61', 'ARTIST62', 'ARTIST63', 'ARTIST64', 'ARTIST65', 'ARTIST66', 'ARTIST67', 'ARTIST68', 'ARTIST69', 'ARTIST70', 'ARTIST71', 'ARTIST72', 'ARTIST73', 'ARTIST74', 'ARTIST75', 'ARTIST76', 'ARTIST77', 'ARTIST78', 'ARTIST79', 'ARTIST80', 'ARTIST81', 'ARTIST82', 'ARTIST83', 'ARTIST84', 'ARTIST85', 'ARTIST86', 'ARTIST87', 'ARTIST88', 'ARTIST89', 'ARTIST90', 'ARTIST91', 'ARTIST92', 'ARTIST93', 'ARTIST94', 'ARTIST95', 'ARTIST96', 'ARTIST97', 'ARTIST98', 'ARTIST99'],['HASH1 SONG', 'HASH1 ARTIST', 'SONG1', 'SONG2', 'SONG3', 'SONG4', 'SONG5', 'SONG6', 'SONG7', 'SONG8', 'SONG9', 'SONG10', 'SONG11', 'SONG12', 'SONG13', 'SONG14', 'SONG15', 'SONG16', 'SONG17', 'SONG18', 'SONG19', 'SONG20', 'SONG21', 'SONG22', 'SONG23', 'SONG24', 'SONG25', 'SONG26', 'SONG27', 'SONG28', 'SONG29', 'SONG30', 'SONG31', 'SONG32', 'SONG33', 'SONG34', 'SONG35', 'SONG36', 'SONG37', 'SONG38', 'SONG39', 'SONG40', 'SONG41', 'SONG42', 'SONG43', 'SONG44', 'SONG45', 'SONG46', 'SONG47', 'SONG48', 'SONG49', 'SONG50', 'SONG51', 'SONG52', 'SONG53', 'SONG54', 'SONG55', 'SONG56', 'SONG57', 'SONG58', 'SONG59', 'SONG60', 'SONG61', 'SONG62', 'SONG63', 'SONG64', 'SONG65', 'SONG66', 'SONG67', 'SONG68', 'SONG69', 'SONG70', 'SONG71', 'SONG72', 'SONG73', 'SONG74', 'SONG75', 'SONG76', 'SONG77', 'SONG78', 'SONG79', 'SONG80', 'SONG81', 'SONG82', 'SONG83', 'SONG84', 'SONG85', 'SONG86', 'SONG87', 'SONG88', 'SONG89', 'SONG90', 'SONG91', 'SONG92', 'SONG93', 'SONG94', 'SONG95', 'SONG96', 'SONG97', 'SONG98', 'SONG99', 'ARTIST1', 'ARTIST2', 'ARTIST3', 'ARTIST4', 'ARTIST5', 'ARTIST6', 'ARTIST7', 'ARTIST8', 'ARTIST9', 'ARTIST10', 'ARTIST11', 'ARTIST12', 'ARTIST13', 'ARTIST14', 'ARTIST15', 'ARTIST16', 'ARTIST17', 'ARTIST18', 'ARTIST19', 'ARTIST20', 'ARTIST21', 'ARTIST22', 'ARTIST23', 'ARTIST24', 'ARTIST25', 'ARTIST26', 'ARTIST27', 'ARTIST28', 'ARTIST29', 'ARTIST30', 'ARTIST31', 'ARTIST32', 'ARTIST33', 'ARTIST34', 'ARTIST35', 'ARTIST36', 'ARTIST37', 'ARTIST38', 'ARTIST39', 'ARTIST40', 'ARTIST41', 'ARTIST42', 'ARTIST43', 'ARTIST44', 'ARTIST45', 'ARTIST46', 'ARTIST47', 'ARTIST48', 'ARTIST49', 'ARTIST50', 'ARTIST51', 'ARTIST52', 'ARTIST53', 'ARTIST54', 'ARTIST55', 'ARTIST56', 'ARTIST57', 'ARTIST58', 'ARTIST59', 'ARTIST60', 'ARTIST61', 'ARTIST62', 'ARTIST63', 'ARTIST64', 'ARTIST65', 'ARTIST66', 'ARTIST67', 'ARTIST68', 'ARTIST69', 'ARTIST70', 'ARTIST71', 'ARTIST72', 'ARTIST73', 'ARTIST74', 'ARTIST75', 'ARTIST76', 'ARTIST77', 'ARTIST78', 'ARTIST79', 'ARTIST80', 'ARTIST81', 'ARTIST82', 'ARTIST83', 'ARTIST84', 'ARTIST85', 'ARTIST86', 'ARTIST87', 'ARTIST88', 'ARTIST89', 'ARTIST90', 'ARTIST91', 'ARTIST92', 'ARTIST93', 'ARTIST94', 'ARTIST95', 'ARTIST96', 'ARTIST97', 'ARTIST98', 'ARTIST99'],false,'Suffix','') }}

),

AlteryxSelect_28 AS (

  SELECT 
    "HASH1 SONG" AS SONG0,
    "HASH1 ARTIST" AS ARTIST0,
    * EXCLUDE ("URL", "DOWNLOADDATA", "DOWNLOADHEADERS", "HASH1 SONG", "HASH1 ARTIST")
  
  FROM MultiFieldFormula_40 AS in0

),

Transpose_29 AS (

  {{
    prophecy_basics.Transpose(
      ['AlteryxSelect_28'], 
      [], 
      [
        'SONG0', 
        'ARTIST0', 
        'SONG1', 
        'SONG2', 
        'SONG3', 
        'SONG4', 
        'SONG5', 
        'SONG6', 
        'SONG7', 
        'SONG8', 
        'SONG9', 
        'SONG10', 
        'SONG11', 
        'SONG12', 
        'SONG13', 
        'SONG14', 
        'SONG15', 
        'SONG16', 
        'SONG17', 
        'SONG18', 
        'SONG19', 
        'SONG20', 
        'SONG21', 
        'SONG22', 
        'SONG23', 
        'SONG24', 
        'SONG25', 
        'SONG26', 
        'SONG27', 
        'SONG28', 
        'SONG29', 
        'SONG30', 
        'SONG31', 
        'SONG32', 
        'SONG33', 
        'SONG34', 
        'SONG35', 
        'SONG36', 
        'SONG37', 
        'SONG38', 
        'SONG39', 
        'SONG40', 
        'SONG41', 
        'SONG42', 
        'SONG43', 
        'SONG44', 
        'SONG45', 
        'SONG46', 
        'SONG47', 
        'SONG48', 
        'SONG49', 
        'SONG50', 
        'SONG51', 
        'SONG52', 
        'SONG53', 
        'SONG54', 
        'SONG55', 
        'SONG56', 
        'SONG57', 
        'SONG58', 
        'SONG59', 
        'SONG60', 
        'SONG61', 
        'SONG62', 
        'SONG63', 
        'SONG64', 
        'SONG65', 
        'SONG66', 
        'SONG67', 
        'SONG68', 
        'SONG69', 
        'SONG70', 
        'SONG71', 
        'SONG72', 
        'SONG73', 
        'SONG74', 
        'SONG75', 
        'SONG76', 
        'SONG77', 
        'SONG78', 
        'SONG79', 
        'SONG80', 
        'SONG81', 
        'SONG82', 
        'SONG83', 
        'SONG84', 
        'SONG85', 
        'SONG86', 
        'SONG87', 
        'SONG88', 
        'SONG89', 
        'SONG90', 
        'SONG91', 
        'SONG92', 
        'SONG93', 
        'SONG94', 
        'SONG95', 
        'SONG96', 
        'SONG97', 
        'SONG98', 
        'SONG99', 
        'ARTIST1', 
        'ARTIST2', 
        'ARTIST3', 
        'ARTIST4', 
        'ARTIST5', 
        'ARTIST6', 
        'ARTIST7', 
        'ARTIST8', 
        'ARTIST9', 
        'ARTIST10', 
        'ARTIST11', 
        'ARTIST12', 
        'ARTIST13', 
        'ARTIST14', 
        'ARTIST15', 
        'ARTIST16', 
        'ARTIST17', 
        'ARTIST18', 
        'ARTIST19', 
        'ARTIST20', 
        'ARTIST21', 
        'ARTIST22', 
        'ARTIST23', 
        'ARTIST24', 
        'ARTIST25', 
        'ARTIST26', 
        'ARTIST27', 
        'ARTIST28', 
        'ARTIST29', 
        'ARTIST30', 
        'ARTIST31', 
        'ARTIST32', 
        'ARTIST33', 
        'ARTIST34', 
        'ARTIST35', 
        'ARTIST36', 
        'ARTIST37', 
        'ARTIST38', 
        'ARTIST39', 
        'ARTIST40', 
        'ARTIST41', 
        'ARTIST42', 
        'ARTIST43', 
        'ARTIST44', 
        'ARTIST45', 
        'ARTIST46', 
        'ARTIST47', 
        'ARTIST48', 
        'ARTIST49', 
        'ARTIST50', 
        'ARTIST51', 
        'ARTIST52', 
        'ARTIST53', 
        'ARTIST54', 
        'ARTIST55', 
        'ARTIST56', 
        'ARTIST57', 
        'ARTIST58', 
        'ARTIST59', 
        'ARTIST60', 
        'ARTIST61', 
        'ARTIST62', 
        'ARTIST63', 
        'ARTIST64', 
        'ARTIST65', 
        'ARTIST66', 
        'ARTIST67', 
        'ARTIST68', 
        'ARTIST69', 
        'ARTIST70', 
        'ARTIST71', 
        'ARTIST72', 
        'ARTIST73', 
        'ARTIST74', 
        'ARTIST75', 
        'ARTIST76', 
        'ARTIST77', 
        'ARTIST78', 
        'ARTIST79', 
        'ARTIST80', 
        'ARTIST81', 
        'ARTIST82', 
        'ARTIST83', 
        'ARTIST84', 
        'ARTIST85', 
        'ARTIST86', 
        'ARTIST87', 
        'ARTIST88', 
        'ARTIST89', 
        'ARTIST90', 
        'ARTIST91', 
        'ARTIST92', 
        'ARTIST93', 
        'ARTIST94', 
        'ARTIST95', 
        'ARTIST96', 
        'ARTIST97', 
        'ARTIST98', 
        'ARTIST99'
      ], 
      'NAME', 
      'VALUE', 
      [
        'SONG0', 
        'ARTIST0', 
        'SONG1', 
        'SONG2', 
        'SONG3', 
        'SONG4', 
        'SONG5', 
        'SONG6', 
        'SONG7', 
        'SONG8', 
        'SONG9', 
        'SONG10', 
        'SONG11', 
        'SONG12', 
        'SONG13', 
        'SONG14', 
        'SONG15', 
        'SONG16', 
        'SONG17', 
        'SONG18', 
        'SONG19', 
        'SONG20', 
        'SONG21', 
        'SONG22', 
        'SONG23', 
        'SONG24', 
        'SONG25', 
        'SONG26', 
        'SONG27', 
        'SONG28', 
        'SONG29', 
        'SONG30', 
        'SONG31', 
        'SONG32', 
        'SONG33', 
        'SONG34', 
        'SONG35', 
        'SONG36', 
        'SONG37', 
        'SONG38', 
        'SONG39', 
        'SONG40', 
        'SONG41', 
        'SONG42', 
        'SONG43', 
        'SONG44', 
        'SONG45', 
        'SONG46', 
        'SONG47', 
        'SONG48', 
        'SONG49', 
        'SONG50', 
        'SONG51', 
        'SONG52', 
        'SONG53', 
        'SONG54', 
        'SONG55', 
        'SONG56', 
        'SONG57', 
        'SONG58', 
        'SONG59', 
        'SONG60', 
        'SONG61', 
        'SONG62', 
        'SONG63', 
        'SONG64', 
        'SONG65', 
        'SONG66', 
        'SONG67', 
        'SONG68', 
        'SONG69', 
        'SONG70', 
        'SONG71', 
        'SONG72', 
        'SONG73', 
        'SONG74', 
        'SONG75', 
        'SONG76', 
        'SONG77', 
        'SONG78', 
        'SONG79', 
        'SONG80', 
        'SONG81', 
        'SONG82', 
        'SONG83', 
        'SONG84', 
        'SONG85', 
        'SONG86', 
        'SONG87', 
        'SONG88', 
        'SONG89', 
        'SONG90', 
        'SONG91', 
        'SONG92', 
        'SONG93', 
        'SONG94', 
        'SONG95', 
        'SONG96', 
        'SONG97', 
        'SONG98', 
        'SONG99', 
        'ARTIST1', 
        'ARTIST2', 
        'ARTIST3', 
        'ARTIST4', 
        'ARTIST5', 
        'ARTIST6', 
        'ARTIST7', 
        'ARTIST8', 
        'ARTIST9', 
        'ARTIST10', 
        'ARTIST11', 
        'ARTIST12', 
        'ARTIST13', 
        'ARTIST14', 
        'ARTIST15', 
        'ARTIST16', 
        'ARTIST17', 
        'ARTIST18', 
        'ARTIST19', 
        'ARTIST20', 
        'ARTIST21', 
        'ARTIST22', 
        'ARTIST23', 
        'ARTIST24', 
        'ARTIST25', 
        'ARTIST26', 
        'ARTIST27', 
        'ARTIST28', 
        'ARTIST29', 
        'ARTIST30', 
        'ARTIST31', 
        'ARTIST32', 
        'ARTIST33', 
        'ARTIST34', 
        'ARTIST35', 
        'ARTIST36', 
        'ARTIST37', 
        'ARTIST38', 
        'ARTIST39', 
        'ARTIST40', 
        'ARTIST41', 
        'ARTIST42', 
        'ARTIST43', 
        'ARTIST44', 
        'ARTIST45', 
        'ARTIST46', 
        'ARTIST47', 
        'ARTIST48', 
        'ARTIST49', 
        'ARTIST50', 
        'ARTIST51', 
        'ARTIST52', 
        'ARTIST53', 
        'ARTIST54', 
        'ARTIST55', 
        'ARTIST56', 
        'ARTIST57', 
        'ARTIST58', 
        'ARTIST59', 
        'ARTIST60', 
        'ARTIST61', 
        'ARTIST62', 
        'ARTIST63', 
        'ARTIST64', 
        'ARTIST65', 
        'ARTIST66', 
        'ARTIST67', 
        'ARTIST68', 
        'ARTIST69', 
        'ARTIST70', 
        'ARTIST71', 
        'ARTIST72', 
        'ARTIST73', 
        'ARTIST74', 
        'ARTIST75', 
        'ARTIST76', 
        'ARTIST77', 
        'ARTIST78', 
        'ARTIST79', 
        'ARTIST80', 
        'ARTIST81', 
        'ARTIST82', 
        'ARTIST83', 
        'ARTIST84', 
        'ARTIST85', 
        'ARTIST86', 
        'ARTIST87', 
        'ARTIST88', 
        'ARTIST89', 
        'ARTIST90', 
        'ARTIST91', 
        'ARTIST92', 
        'ARTIST93', 
        'ARTIST94', 
        'ARTIST95', 
        'ARTIST96', 
        'ARTIST97', 
        'ARTIST98', 
        'ARTIST99'
      ], 
      true
    )
  }}

),

Formula_30_0 AS (

  SELECT 
    CAST((REGEXP_REPLACE("NAME", 'Song', '')) AS STRING) AS "NAME",
    * EXCLUDE ("NAME")
  
  FROM Transpose_29 AS in0

),

Formula_30_1 AS (

  SELECT 
    CAST((REGEXP_REPLACE("NAME", 'Artist', '')) AS STRING) AS "NAME",
    * EXCLUDE ("NAME")
  
  FROM Formula_30_0 AS in0

),

CrossTab_31_listagg_concat AS (

  SELECT 
    "NAME" AS "NAME",
    (LISTAGG("VALUE", ',')) AS CONCAT_VALUE
  
  FROM Formula_30_1 AS in0
  
  GROUP BY "NAME"

),

CrossTab_31_pivot_concat AS (

  SELECT 
    "'45'" AS CONCAT_45,
    "'98'" AS CONCAT_98,
    "'34'" AS CONCAT_34,
    "'67'" AS CONCAT_67,
    "'93'" AS CONCAT_93,
    "'12'" AS CONCAT_12,
    "'66'" AS CONCAT_66,
    "'89'" AS CONCAT_89,
    "'51'" AS CONCAT_51,
    "'84'" AS CONCAT_84,
    "'8'" AS CONCAT_8,
    "'73'" AS CONCAT_73,
    "'78'" AS CONCAT_78,
    "'19'" AS CONCAT_19,
    "'23'" AS CONCAT_23,
    "'62'" AS CONCAT_62,
    "'4'" AS CONCAT_4,
    "'88'" AS CONCAT_88,
    "'77'" AS CONCAT_77,
    "'40'" AS CONCAT_40,
    "'15'" AS CONCAT_15,
    "'11'" AS CONCAT_11,
    "'90'" AS CONCAT_90,
    "'9'" AS CONCAT_9,
    "'44'" AS CONCAT_44,
    "'33'" AS CONCAT_33,
    "'22'" AS CONCAT_22,
    "'56'" AS CONCAT_56,
    "'55'" AS CONCAT_55,
    "'26'" AS CONCAT_26,
    "'50'" AS CONCAT_50,
    "'37'" AS CONCAT_37,
    "'68'" AS CONCAT_68,
    "'61'" AS CONCAT_61,
    "'13'" AS CONCAT_13,
    "'46'" AS CONCAT_46,
    "'99'" AS CONCAT_99,
    "'24'" AS CONCAT_24,
    "'94'" AS CONCAT_94,
    "'83'" AS CONCAT_83,
    "'35'" AS CONCAT_35,
    "'16'" AS CONCAT_16,
    "'79'" AS CONCAT_79,
    "'5'" AS CONCAT_5,
    "'72'" AS CONCAT_72,
    "'10'" AS CONCAT_10,
    "'59'" AS CONCAT_59,
    "'87'" AS CONCAT_87,
    "'48'" AS CONCAT_48,
    "'21'" AS CONCAT_21,
    "'76'" AS CONCAT_76,
    "'54'" AS CONCAT_54,
    "'43'" AS CONCAT_43,
    "'65'" AS CONCAT_65,
    "'71'" AS CONCAT_71,
    "'57'" AS CONCAT_57,
    "'32'" AS CONCAT_32,
    "'80'" AS CONCAT_80,
    "'82'" AS CONCAT_82,
    "'49'" AS CONCAT_49,
    "'6'" AS CONCAT_6,
    "'36'" AS CONCAT_36,
    "'1'" AS CONCAT_1,
    "'39'" AS CONCAT_39,
    "'17'" AS CONCAT_17,
    "'25'" AS CONCAT_25,
    "'60'" AS CONCAT_60,
    "'14'" AS CONCAT_14,
    "'47'" AS CONCAT_47,
    "'31'" AS CONCAT_31,
    "'96'" AS CONCAT_96,
    "'69'" AS CONCAT_69,
    "'95'" AS CONCAT_95,
    "'58'" AS CONCAT_58,
    "'64'" AS CONCAT_64,
    "'53'" AS CONCAT_53,
    "'42'" AS CONCAT_42,
    "'75'" AS CONCAT_75,
    "'0'" AS CONCAT_0,
    "'20'" AS CONCAT_20,
    "'27'" AS CONCAT_27,
    "'70'" AS CONCAT_70,
    "'2'" AS CONCAT_2,
    "'86'" AS CONCAT_86,
    "'38'" AS CONCAT_38,
    "'81'" AS CONCAT_81,
    "'92'" AS CONCAT_92,
    "'18'" AS CONCAT_18,
    "'30'" AS CONCAT_30,
    "'7'" AS CONCAT_7,
    "'97'" AS CONCAT_97,
    "'29'" AS CONCAT_29,
    "'41'" AS CONCAT_41,
    "'63'" AS CONCAT_63,
    "'3'" AS CONCAT_3,
    "'74'" AS CONCAT_74,
    "'91'" AS CONCAT_91,
    "'52'" AS CONCAT_52,
    "'85'" AS CONCAT_85,
    "'28'" AS CONCAT_28
  
  FROM CrossTab_31_listagg_concat AS in0
  PIVOT (
    MAX("CONCAT_VALUE")
    FOR "NAME"
    IN (
      '45', 
      '98', 
      '34', 
      '67', 
      '93', 
      '12', 
      '66', 
      '89', 
      '51', 
      '84', 
      '8', 
      '73', 
      '78', 
      '19', 
      '23', 
      '62', 
      '4', 
      '88', 
      '77', 
      '40', 
      '15', 
      '11', 
      '90', 
      '9', 
      '44', 
      '33', 
      '22', 
      '56', 
      '55', 
      '26', 
      '50', 
      '37', 
      '68', 
      '61', 
      '13', 
      '46', 
      '99', 
      '24', 
      '94', 
      '83', 
      '35', 
      '16', 
      '79', 
      '5', 
      '72', 
      '10', 
      '59', 
      '87', 
      '48', 
      '21', 
      '76', 
      '54', 
      '43', 
      '65', 
      '71', 
      '57', 
      '32', 
      '80', 
      '82', 
      '49', 
      '6', 
      '36', 
      '1', 
      '39', 
      '17', 
      '25', 
      '60', 
      '14', 
      '47', 
      '31', 
      '96', 
      '69', 
      '95', 
      '58', 
      '64', 
      '53', 
      '42', 
      '75', 
      '0', 
      '20', 
      '27', 
      '70', 
      '2', 
      '86', 
      '38', 
      '81', 
      '92', 
      '18', 
      '30', 
      '7', 
      '97', 
      '29', 
      '41', 
      '63', 
      '3', 
      '74', 
      '91', 
      '52', 
      '85', 
      '28'
    )
  )

),

CrossTab_31_rename AS (

  SELECT 
    CONCAT_45 AS "45",
    CONCAT_98 AS "98",
    CONCAT_34 AS "34",
    CONCAT_67 AS "67",
    CONCAT_93 AS "93",
    CONCAT_12 AS "12",
    CONCAT_66 AS "66",
    CONCAT_89 AS "89",
    CONCAT_51 AS "51",
    CONCAT_84 AS "84",
    CONCAT_8 AS "8",
    CONCAT_73 AS "73",
    CONCAT_78 AS "78",
    CONCAT_19 AS "19",
    CONCAT_23 AS "23",
    CONCAT_62 AS "62",
    CONCAT_4 AS "4",
    CONCAT_88 AS "88",
    CONCAT_77 AS "77",
    CONCAT_40 AS "40",
    CONCAT_15 AS "15",
    CONCAT_11 AS "11",
    CONCAT_90 AS "90",
    CONCAT_9 AS "9",
    CONCAT_44 AS "44",
    CONCAT_33 AS "33",
    CONCAT_22 AS "22",
    CONCAT_56 AS "56",
    CONCAT_55 AS "55",
    CONCAT_26 AS "26",
    CONCAT_50 AS "50",
    CONCAT_37 AS "37",
    CONCAT_68 AS "68",
    CONCAT_61 AS "61",
    CONCAT_13 AS "13",
    CONCAT_46 AS "46",
    CONCAT_99 AS "99",
    CONCAT_24 AS "24",
    CONCAT_94 AS "94",
    CONCAT_83 AS "83",
    CONCAT_35 AS "35",
    CONCAT_16 AS "16",
    CONCAT_79 AS "79",
    CONCAT_5 AS "5",
    CONCAT_72 AS "72",
    CONCAT_10 AS "10",
    CONCAT_59 AS "59",
    CONCAT_87 AS "87",
    CONCAT_48 AS "48",
    CONCAT_21 AS "21",
    CONCAT_76 AS "76",
    CONCAT_54 AS "54",
    CONCAT_43 AS "43",
    CONCAT_65 AS "65",
    CONCAT_71 AS "71",
    CONCAT_57 AS "57",
    CONCAT_32 AS "32",
    CONCAT_80 AS "80",
    CONCAT_82 AS "82",
    CONCAT_49 AS "49",
    CONCAT_6 AS "6",
    CONCAT_36 AS "36",
    CONCAT_1 AS "1",
    CONCAT_39 AS "39",
    CONCAT_17 AS "17",
    CONCAT_25 AS "25",
    CONCAT_60 AS "60",
    CONCAT_14 AS "14",
    CONCAT_47 AS "47",
    CONCAT_31 AS "31",
    CONCAT_96 AS "96",
    CONCAT_69 AS "69",
    CONCAT_95 AS "95",
    CONCAT_58 AS "58",
    CONCAT_64 AS "64",
    CONCAT_53 AS "53",
    CONCAT_42 AS "42",
    CONCAT_75 AS "75",
    CONCAT_0 AS "0",
    CONCAT_20 AS "20",
    CONCAT_27 AS "27",
    CONCAT_70 AS "70",
    CONCAT_2 AS "2",
    CONCAT_86 AS "86",
    CONCAT_38 AS "38",
    CONCAT_81 AS "81",
    CONCAT_92 AS "92",
    CONCAT_18 AS "18",
    CONCAT_30 AS "30",
    CONCAT_7 AS "7",
    CONCAT_97 AS "97",
    CONCAT_29 AS "29",
    CONCAT_41 AS "41",
    CONCAT_63 AS "63",
    CONCAT_3 AS "3",
    CONCAT_74 AS "74",
    CONCAT_91 AS "91",
    CONCAT_52 AS "52",
    CONCAT_85 AS "85",
    CONCAT_28 AS "28"
  
  FROM CrossTab_31_pivot_concat AS in0

),

Transpose_32 AS (

  {{
    prophecy_basics.Transpose(
      ['CrossTab_31_rename'], 
      [], 
      [
        '0', 
        '1', 
        '2', 
        '3', 
        '4', 
        '5', 
        '6', 
        '7', 
        '8', 
        '9', 
        '10', 
        '11', 
        '12', 
        '13', 
        '14', 
        '15', 
        '16', 
        '17', 
        '18', 
        '19', 
        '20', 
        '21', 
        '22', 
        '23', 
        '24', 
        '25', 
        '26', 
        '27', 
        '28', 
        '29', 
        '30', 
        '31', 
        '32', 
        '33', 
        '34', 
        '35', 
        '36', 
        '37', 
        '38', 
        '39', 
        '40', 
        '41', 
        '42', 
        '43', 
        '44', 
        '45', 
        '46', 
        '47', 
        '48', 
        '49', 
        '50', 
        '51', 
        '52', 
        '53', 
        '54', 
        '55', 
        '56', 
        '57', 
        '58', 
        '59', 
        '60', 
        '61', 
        '62', 
        '63', 
        '64', 
        '65', 
        '66', 
        '67', 
        '68', 
        '69', 
        '70', 
        '71', 
        '72', 
        '73', 
        '74', 
        '75', 
        '76', 
        '77', 
        '78', 
        '79', 
        '80', 
        '81', 
        '82', 
        '83', 
        '84', 
        '85', 
        '86', 
        '87', 
        '88', 
        '89', 
        '90', 
        '91', 
        '92', 
        '93', 
        '94', 
        '95', 
        '96', 
        '97', 
        '98', 
        '99'
      ], 
      'NAME', 
      'VALUE', 
      [
        '45', 
        '98', 
        '34', 
        '67', 
        '93', 
        '12', 
        '66', 
        '89', 
        '51', 
        '84', 
        '8', 
        '73', 
        '78', 
        '19', 
        '23', 
        '62', 
        '4', 
        '88', 
        '77', 
        '40', 
        '15', 
        '11', 
        '90', 
        '9', 
        '44', 
        '33', 
        '22', 
        '56', 
        '55', 
        '26', 
        '50', 
        '37', 
        '68', 
        '61', 
        '13', 
        '46', 
        '99', 
        '24', 
        '94', 
        '83', 
        '35', 
        '16', 
        '79', 
        '5', 
        '72', 
        '10', 
        '59', 
        '87', 
        '48', 
        '21', 
        '76', 
        '54', 
        '43', 
        '65', 
        '71', 
        '57', 
        '32', 
        '80', 
        '82', 
        '49', 
        '6', 
        '36', 
        '1', 
        '39', 
        '17', 
        '25', 
        '60', 
        '14', 
        '47', 
        '31', 
        '96', 
        '69', 
        '95', 
        '58', 
        '64', 
        '53', 
        '42', 
        '75', 
        '0', 
        '20', 
        '27', 
        '70', 
        '2', 
        '86', 
        '38', 
        '81', 
        '92', 
        '18', 
        '30', 
        '7', 
        '97', 
        '29', 
        '41', 
        '63', 
        '3', 
        '74', 
        '91', 
        '52', 
        '85', 
        '28'
      ], 
      true
    )
  }}

),

TextToColumns_33 AS (

  {{
    prophecy_basics.TextToColumns(
      ['Transpose_32'], 
      'VALUE', 
      ";", 
      'splitColumns', 
      2, 
      'leaveExtraCharLastCol', 
      'VALUE', 
      'VALUE', 
      'GENERATEDCOLUMNNAME'
    )
  }}

),

TextToColumns_33_dropGem_0 AS (

  SELECT 
    VALUE_1_VALUE AS VALUE1,
    VALUE_2_VALUE AS VALUE2,
    *
  
  FROM TextToColumns_33 AS in0

),

AlteryxSelect_35 AS (

  SELECT 
    CAST("NAME" AS INTEGER) AS RANK,
    VALUE1 AS SONG,
    VALUE2 AS ARTIST,
    * EXCLUDE ("VALUE", "NAME", "VALUE1", "VALUE2")
  
  FROM TextToColumns_33_dropGem_0 AS in0

),

Formula_36_0 AS (

  SELECT 
    CAST(((coalesce(CAST(RANK AS FLOAT), (REGEXP_SUBSTR(RANK, '^[0-9]+')), 0)) + 1) AS INTEGER) AS RANK,
    * EXCLUDE ("RANK")
  
  FROM AlteryxSelect_35 AS in0

),

Sample_44 AS (

  {{
    prophecy_basics.Sample(
      ['Formula_36_0'], 
      '[{"name": "RANK", "dataType": "Number"}, {"name": "SONG", "dataType": "String"}, {"name": "ARTIST", "dataType": "String"}, {"name": "VALUE_1_VALUE", "dataType": "String"}, {"name": "VALUE_2_VALUE", "dataType": "String"}]', 
      'sampleDataset', 
      [], 
      1002, 
      'firstN', 
      100
    )
  }}

)

SELECT *

FROM Sample_44
