---
version: 2
models:
- name: "DRP_VQF_Concat__AlteryxSelect_33"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__AlteryxSelect_34"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__Cleanse_16"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__Cleanse_21"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__Cleanse_24"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__Formula_26_0"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__Formula_27_0"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__Join_12_inner"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__TextInput_8_cast"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__Union_69_postRename"
  tags:
  - "prophecy_temp"
- name: "DRP_VQF_Concat__vqf_avro_55"
  tags:
  - "prophecy_temp"
