{{
  config({    
    "materialized": "table",
    "alias": "SM_CREDIT_CARD_CAL_MTH_END_HIS",
    "database": "tanmay",
    "schema": "default"
  })
}}

WITH `{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_credit_card_cal_hist_sum_load_SQTRANS` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      'm_mmrt_credit_card_cal_hist_sum_load', 
      '{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_credit_card_cal_hist_sum_load_SQTRANS'
    )
  }}

),

SQTRANS_EXPR_20 AS (

  SELECT 
    CHARGE_OFF_REASON_2 AS CC_CHARGE_OFF_REASON_2,
    DUE_LAST_STMT AS CC_DUE_LAST_STMT,
    CREDIT_LIMIT_CASH AS CC_CASH_LIMIT,
    INSURANCE_STATUS AS CC_INSURANCE_STATUS,
    PREVIOUS_CREDIT_LIMIT AS CC_PREVIOUS_CREDIT_LIMIT,
    PERIODID AS PERIODID,
    ARREARS_VALUE AS CC_ARREARS_VALUE,
    BT_BALANCE AS CC_BT_CURRENT_BALANCE,
    CASH_BALANCE AS CC_CASH_CURRENT_BALANCE,
    RETAIL_BALANCE AS CC_RETAIL_CURRENT_BALANCE,
    BLOCK_CODE_2 AS CC_BLOCK_CODE_2,
    DD_PAYMENT_FLAG AS CC_DD_PAYMENT_FLAG,
    EMPLOYEE_CODE AS CC_EMPLOYEE_CODE,
    PAYROLL_NO AS CC_PAYROLL_NO,
    STMT_FLAG AS CC_STMT_FLAG,
    USER_CODE_9 AS CC_USER_CODE_9,
    CURRENT_DELINQUENCY AS CC_CURRENT_DELINQUENCY,
    GOOD_BAD_FLAG AS CC_GOOD_BAD_FLAG,
    INFLIGHT_SPEND_FLAG AS CC_INFLIGHT_FLAG,
    NUMBER_OF_POINTS AS CC_LOYALTY_POINTS_BALANCE,
    RETAIL_FLAG AS CC_RETAIL_FLAG,
    TOTAL_NUMBER_OF_CARDS AS CC_NUMBER_OF_UNBLOCKED_CARDS,
    CARDSAFE_TYPE AS CC_CARDSAFE_INDICATOR,
    CURR_BALANCE AS CC_CURRENT_BALANCE,
    CREDIT_LIMIT_CHANGE_DATE AS CC_DATE_CREDIT_LIMIT,
    PAYMENT_METHOD AS CC_PAYMENT_METHOD,
    ACCOUNT_MONTHLY_USAGE AS CC_ACCOUNT_MONTHLY_USAGE,
    ACCOUNT_YEARLY_USAGE AS CC_ACCOUNT_YEARLY_USAGE,
    STATUS AS CC_ACCOUNT_STATUS,
    BLOCK_CODE AS CC_BLOCK_CODE_1,
    BALANCE_TRANSFER_FLAG AS CC_BT_FLAG,
    LAST_30_DAYS_CASH_COUNT AS CC_NO_CASH_TRANS_LAST_30_DAY,
    LAST_90_DAYS_CASH_COUNT AS CC_NO_CASH_TRANS_LAST_90_DAY,
    LAST_180_DAYS_CASH_COUNT AS CC_NO_CASH_TRANS_LAST_180_DAY,
    LAST_365_DAYS_CASH_COUNT AS CC_NO_CASH_TRANS_LAST_365_DAY,
    LAST_30_DAYS_CASH_VALUE AS CC_VAL_CASH_TRANS_LAST_30_DAY,
    LAST_90_DAYS_CASH_VALUE AS CC_VAL_CASH_TRANS_LAST_90_DAY,
    LAST_180_DAYS_CASH_VALUE AS CC_VAL_CASH_TRANS_LAST_180_DAY,
    LAST_365_DAYS_CASH_VALUE AS CC_VAL_CASH_TRANS_LAST_365_DAY,
    LAST_30_DAYS_RET_INF_COUNT AS CC_NO_RETINF_TRAN_LST_30_DAY,
    LAST_90_DAYS_RET_INF_COUNT AS CC_NO_RETINF_TRAN_LST_90_DAY,
    LAST_180_DAYS_RET_INF_COUNT AS CC_NO_RETINF_TRAN_LST_180_DAY,
    LAST_365_DAYS_RET_INF_COUNT AS CC_NO_RETINF_TRAN_LST_365_DAY,
    LAST_30_DAYS_RET_INF_VALUE AS CC_VAL_RETINF_TRAN_LST_30_DAY,
    LAST_90_DAYS_RET_INF_VALUE AS CC_VAL_RETINF_TRAN_LST_90_DAY,
    LAST_180_DAYS_RET_INF_VALUE AS CC_VAL_RETINF_TRAN_LST_180_DAY,
    LAST_365_DAYS_RET_INF_VALUE AS CC_VAL_RETINF_TRAN_LST_365_DAY,
    LAST_30_DAYS_BAL_TFR_COUNT AS CC_NO_BT_TRANS_LAST_30_DAY,
    LAST_90_DAYS_BAL_TFR_COUNT AS CC_NO_BT_TRANS_LAST_90_DAY,
    LAST_180_DAYS_BAL_TFR_COUNT AS CC_NO_BT_TRANS_LAST_180_DAY,
    LAST_365_DAYS_BAL_TFR_COUNT AS CC_NO_BT_TRANS_LAST_365_DAY,
    LAST_30_DAYS_BAL_TFR_VALUE AS CC_VAL_BT_TRANS_LAST_30_DAY,
    LAST_90_DAYS_BAL_TFR_VALUE AS CC_VAL_BT_TRANS_LAST_90_DAY,
    LAST_180_DAYS_BAL_TFR_VALUE AS CC_VAL_BT_TRANS_LAST_180_DAY,
    LAST_365_DAYS_BAL_TFR_VALUE AS CC_VAL_BT_TRANS_LAST_365_DAY,
    CASH_FLAG AS CC_CASH_FLAG,
    GBP_AMT_CHARGE_OFF AS CC_CHARGE_OFF_AMOUNT,
    ACCOUNT_CREDIT_LIMIT AS CC_CREDIT_LIMIT,
    SCHEME_ACTIVE AS CC_SCHEME_ACTIVE,
    CHARGE_OFF_DATE AS CC_CHARGE_OFF_DATE,
    ACCOUNT_ACTIVATED AS CC_ACCOUNT_ACTIVATED,
    INS_IND AS CC_INSURANCE_INDICATOR,
    SEGMENT AS CC_SEGMENT,
    DATE_OF_LAST_CREDIT_CARD_PURCHASE AS CC_DATE_OF_LAST_CRDCARD_PURCH,
    SCORE_1 AS CC_SCORE,
    TOTAL_STATEMENT_BALANCE AS CC_TOTAL_STATEMENT_BALANCE,
    ACCOUNT_ORIGIN AS CC_ACCOUNT_ORIGIN,
    NUMBER_OF_CARDS AS CC_NUMBER_OF_CARDS,
    CHARGE_OFF_REASON_1 AS CC_CHARGE_OFF_REASON_1,
    ACC_NUM AS CC_ACCOUNT_NUMBER,
    ACHOLDER_NOMINATED_AMOUNT AS CC_DD_NOMINATED_AMOUNT
  
  FROM `{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_credit_card_cal_hist_sum_load_SQTRANS` AS in0

)

SELECT *

FROM SQTRANS_EXPR_20
