---
version: 2
sources:
- name: "avpreet_qa_avpreettables"
  database: "avpreet_qa"
  schema: "avpreettables"
  tables:
  - name: "table_test"
    config:
      tags:
      - "pipeline:p1"
      - "pipeline:p2"
    columns:
    - name: "ID"
      dataType:
        type: "Integer"
    - name: "Name"
      dataType:
        type: "String"
    - name: "Department"
      dataType:
        type: "String"
    type: "table"
