{{
  config({    
    "materialized": "table",
    "alias": "INS_CLIENT_PREFERENCE",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_CARDS_ORIG_CLIENT_PREFERENCE AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_client_preference_update__EXP_CARDS_ORIG_CLIENT_PREFERENCE')}}

),

RTR_CARDS_ORIG_CLIENT_PREFERENCE_out0 AS (

  SELECT * 
  
  FROM EXP_CARDS_ORIG_CLIENT_PREFERENCE AS in0
  
  WHERE ((CLID_CLIENT_PREFERENCE IS NULL) AND (ROW_NUMBER = 1))

),

RTR_CARDS_ORIG_CLIENT_PREFERENCE_EXPR_NEW_CLIENT_PREFERENCE AS (

  SELECT 
    CLID_CLIENT_ALIAS AS CLID_CLIENT_ALIAS1,
    CLID_CLIENT_PREFERENCE AS CLID_CLIENT_PREFERENCE1,
    MARKETING_OPT_IN_TEL AS MARKETING_OPT_IN_TEL1,
    MARKETING_OPT_IN_EMAIL AS MARKETING_OPT_IN_EMAIL1,
    MARKETING_OPT_IN_TEXT AS MARKETING_OPT_IN_TEXT1,
    MARKETING_OPT_IN_POST AS MARKETING_OPT_IN_POST1,
    MAIL_PREFERENCE AS MAIL_PREFERENCE1,
    MAIL_PREFERENCE_DATE AS MAIL_PREFERENCE_DATE1,
    PHONE_PREFERENCE AS PHONE_PREFERENCE1,
    PHONE_PREFERENCE_DATE AS PHONE_PREFERENCE_DATE1,
    EMAIL_PREFERENCE AS EMAIL_PREFERENCE1,
    EMAIL_PREFERENCE_DATE AS EMAIL_PREFERENCE_DATE1,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE1,
    business_date AS business_date1,
    ROW_NUMBER AS ROW_NUMBER1,
    TOTAL_COMPARE AS TOTAL_COMPARE1
  
  FROM RTR_CARDS_ORIG_CLIENT_PREFERENCE_out0 AS in0

),

INS_CLIENT_PREFERENCE1_add_missing_column_0 AS (

  SELECT 
    CAST(NULL AS STRING) AS MPS_PREFERENCE,
    CAST(NULL AS TIMESTAMP) AS MPS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS TPS_PREFERENCE,
    CAST(NULL AS TIMESTAMP) AS TPS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS ICOS_PREFERENCE,
    CAST(NULL AS TIMESTAMP) AS ICOS_PREFERENCE_DATE,
    *
  
  FROM RTR_CARDS_ORIG_CLIENT_PREFERENCE_EXPR_NEW_CLIENT_PREFERENCE AS in0

),

INS_CLIENT_PREFERENCE_EXP AS (

  SELECT 
    CLID_CLIENT_ALIAS1 AS CLID,
    SOURCE_SYSTEM_CODE1 AS SOURCE_SYSTEM_CODE,
    MARKETING_OPT_IN_POST1 AS MAIL_PREFERENCE,
    business_date1 AS MAIL_PREFERENCE_DATE,
    MARKETING_OPT_IN_TEL1 AS PHONE_PREFERENCE,
    business_date1 AS PHONE_PREFERENCE_DATE,
    MARKETING_OPT_IN_EMAIL1 AS EMAIL_PREFERENCE,
    business_date1 AS EMAIL_PREFERENCE_DATE,
    MARKETING_OPT_IN_TEXT1 AS SMS_PREFERENCE,
    business_date1 AS SMS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS MPS_PREFERENCE,
    CAST(NULL AS STRING) AS MPS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS TPS_PREFERENCE,
    CAST(NULL AS STRING) AS TPS_PREFERENCE_DATE,
    CAST(NULL AS STRING) AS ICOS_PREFERENCE,
    CAST(NULL AS STRING) AS ICOS_PREFERENCE_DATE
  
  FROM INS_CLIENT_PREFERENCE1_add_missing_column_0 AS in0

)

SELECT *

FROM INS_CLIENT_PREFERENCE_EXP
