---
version: 2
models:
- name: "m_rep_cards_orig_client_preference_update__EXP_CARDS_ORIG_CLIENT_PREFERENCE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_preference_update__INS_CLIENT_PREFERENCE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_preference_update__UPD_CLIENT_PREFERENCE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_preference_update__find_business_date"
  tags:
  - "prophecy_temp"
