{{
  config({    
    "materialized": "table",
    "alias": "UPD_CREDIT_APPLICATION",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_WORK_CARDS_ORIG_STAGING_EXPR_18 AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_credit_application_update__EXP_WORK_CARDS_ORIG_STAGING_EXPR_18')}}

),

RTR_CREDIT_APPLICATION_out1 AS (

  SELECT * 
  
  FROM EXP_WORK_CARDS_ORIG_STAGING_EXPR_18 AS in0
  
  WHERE (
          (ACCID_TGT IS NOT NULL)
          AND (
                (
                  CASE
                    WHEN ((DATE_DIFF(CAST(EFROM_TGT AS DATE), CAST(BUSINESS_DATE AS DATE), DAY)) > 0)
                      THEN 1
                    WHEN ((DATE_DIFF(CAST(EFROM_TGT AS DATE), CAST(BUSINESS_DATE AS DATE), DAY)) < 0)
                      THEN -1
                    ELSE (DATE_DIFF(CAST(EFROM_TGT AS DATE), CAST(BUSINESS_DATE AS DATE), DAY))
                  END
                ) = 0
              )
        )

),

UPD_CREDIT_APPLICATION_EXP AS (

  SELECT 
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    PRODUCT_NUMBER AS PRODUCT_CODE_2,
    ACCID_TGT AS ACCID,
    EFROM_TGT AS EFROM,
    CAST(NULL AS STRING) AS ETO,
    CAST(NULL AS STRING) AS ACTION_CODE,
    o_LAST_ACTION_DATE AS ACTION_DATE,
    EMPLOYMENT_STATUS AS EMPLOYMENT_STATUS,
    o_FINAL_DECISION_COARSE AS FINAL_DECISION_COARSE,
    o_FINAL_DECISION_PRIMARY AS FINAL_DECISION_PRIMARY,
    INITIAL_DECISION_2 AS INITIAL_DECISION_2,
    INITIAL_DECISION_3 AS INITIAL_DECISION_3,
    INITIAL_DECISION_4 AS INITIAL_DECISION_4,
    INITIAL_DECISION_5 AS INITIAL_DECISION_5,
    INITIAL_DECISION_6 AS INITIAL_DECISION_6,
    INITIAL_DECISION_COARSE_TGT AS INITIAL_DECISION_COARSE,
    INITIAL_DECISION_PRIMARY_TGT AS INITIAL_DECISION_PRIMARY,
    MARITAL_STATUS AS MARITAL_STATUS,
    CAST(NULL AS STRING) AS REASON_CODES,
    CAST(NULL AS STRING) AS REPROCESS_DECISION_2,
    CAST(NULL AS STRING) AS REPROCESS_DECISION_3,
    CAST(NULL AS STRING) AS REPROCESS_DECISION_4,
    CAST(NULL AS STRING) AS REPROCESS_DECISION_5,
    CAST(NULL AS STRING) AS REPROCESS_DECISION_6,
    CAST(NULL AS STRING) AS REPROCESS_DECISION_COARSE,
    CAST(NULL AS STRING) AS REPROCESS_DECISION_PRIMARY,
    APPLICATION_STORE_NUMBER AS STORE_NUMBER,
    APPLICATION_DATE AS APPLICATION_DATE,
    CAST(NULL AS STRING) AS CARD_PROTECTION,
    CAST(NULL AS STRING) AS CARDSAFE,
    CAST(NULL AS STRING) AS LOAN_PURPOSE,
    CAST(NULL AS NUMERIC) AS CONTRA_EXTRA_BORROWING,
    CAST(NULL AS NUMERIC) AS CONTRA_TOTAL,
    ACCOUNT_NUMBER AS DISPLAY_ACCOUNT_NUMBER,
    CAST(NULL AS STRING) AS INSURANCE_ELIGABILITY,
    CAST(NULL AS STRING) AS INSURANCE_REQUIRED,
    CAST(NULL AS STRING) AS INSURED_PERSON,
    CAST(NULL AS NUMERIC) AS LOAN_AMOUNT_REQUESTED,
    CAST(NULL AS NUMERIC) AS LOAN_TERM_REQUESTED,
    CAST(NULL AS NUMERIC) AS TOTAL_MONTHLY_REPAYMT_REQD,
    CAST(NULL AS STRING) AS INSURANCE_REQUESTED,
    CAST(NULL AS NUMERIC) AS LOAN_AMOUNT_OFFERED,
    CAST(NULL AS NUMERIC) AS LOAN_TERM_OFFERED,
    CAST(NULL AS NUMERIC) AS TOTAL_MONTHLY_REPAYMT_OFFERED,
    CAST(NULL AS STRING) AS INSURANCE_OFFERED,
    CAST(NULL AS NUMERIC) AS LOAN_AMOUNT_ACCEPTED,
    CAST(NULL AS NUMERIC) AS LOAN_TERM_ACCEPTED,
    CAST(NULL AS NUMERIC) AS TOTAL_MONTHLY_REPAYMT_ACCD,
    CAST(NULL AS STRING) AS INSURANCE_ACCEPTED,
    CAST(NULL AS NUMERIC) AS MONTHLY_DISCRETIONARY_SPEND,
    CAST(NULL AS STRING) AS OPERATOR_ID,
    PRODUCT AS PRODUCT_CODE,
    APPLICATION_SOURCE_CODE AS SOURCE_CODE,
    APPLICATION_SCORE AS TOTAL_APPLICATION_SCORE,
    CAST(NULL AS STRING) AS PRE_BUREAU_SCORE,
    CAST(NULL AS STRING) AS UNDERWRITER_SCORE,
    FIRST_PARTY_FRAUD_SCORE AS FRAUD_SCORE_NEW,
    CAST(NULL AS STRING) AS FRAUD_SCORE_OLD,
    CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE AS INITIAL_APR_REQUESTED,
    CAST(NULL AS NUMERIC) AS TOTAL_AMT_PAYABLE_WITH_INS,
    CAST(NULL AS NUMERIC) AS TOTAL_AMT_PAYABLE_WITHOUT_INS,
    CAST(NULL AS NUMERIC) AS ACCEPT_TOTAL_MONTHLY_REPAYMT,
    CAST(NULL AS STRING) AS INITIAL_OPERATOR_ID,
    CAST(NULL AS STRING) AS PENULTIMATE_OPERATOR_ID,
    o_TIME_STAMP_OF_ACTION AS TIME_STAMP_OF_ACTION,
    CAST(NULL AS NUMERIC) AS INITIAL_LOAN_AMOUNT,
    CAST(NULL AS NUMERIC) AS INITIAL_MONTHLY_AFFORD_AMOUNT,
    CAST(NULL AS NUMERIC) AS OFFER_INDICATOR,
    CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE AS OFFERED_ADJUSTED_APR,
    CAST(NULL AS NUMERIC) AS ACCEPT_INDICATOR,
    CAST(NULL AS NUMERIC) AS ACCEPTED_ADJUSTED_APR,
    RESIDENTIAL_STATUS AS OCCUPANCY_RESIDENTIAL_STATUS,
    ANNUAL_INCOME_AMOUNT AS GROSS_ANNUAL_INCOME,
    o_RESIDENTIAL_MOVED_IN_DATE AS TIME_AT_CURRENT_ADDRESS,
    o_TIME_AT_PREVIOUS_ADDRESS AS TIME_AT_PREVIOUS_ADDRESS,
    OCCUPATION AS EMPLOYMENT_TYPE,
    o_EMPLOYMENT_MAIN_STARTDATE AS TIME_IN_EMPLOYMENT,
    CAST(NULL AS STRING) AS TIME_WITH_BANK_BSOC,
    APPLICATION_TYPE AS APPLICATION_TYPE,
    CAST(NULL AS NUMERIC) AS PARTNERS_INCOME,
    CAST(NULL AS NUMERIC) AS DUPLICATE_COUNT,
    CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER AS FINAL_CREDIT_LIMIT,
    CAST(NULL AS NUMERIC) AS ORIGINAL_RANDOM_NUMBER,
    CAST(NULL AS STRING) AS BANK_SORT_NAME_PART,
    CAST(NULL AS STRING) AS EMBOSSED_ACCOUNT_NUMBER,
    CAST(NULL AS STRING) AS CLIENT_REFERENCE,
    CAST(NULL AS NUMERIC) AS DEFER_PERIOD,
    CAST(NULL AS STRING) AS COURIER_ADDRESS_IND,
    CAST(NULL AS STRING) AS COURIER_DELIVERY_CATEGORY,
    CAST(NULL AS STRING) AS COURIER_PAY_METHOD,
    CAST(NULL AS NUMERIC) AS COURIER_COST,
    CAST(NULL AS STRING) AS MI_INDIVIDUAL,
    CAST(NULL AS STRING) AS MI_ORGANISATION,
    CAST(NULL AS STRING) AS MI_LOCATION,
    CAST(NULL AS STRING) AS MI_MARKETING_CHANNEL,
    CAST(NULL AS STRING) AS ADDITIONAL_LOAN_PURPOSE,
    ANNUAL_HOUSEHOLD_INCOME AS ANNUAL_HOUSEHOLD_INCOME,
    CAST(NULL AS STRING) AS CHANNEL_OVERRIDE_INDICATOR,
    OFFER_ID AS CAMPAIGN_TYPE,
    CAST(NULL AS NUMERIC) AS COMBINED_BEHAVIOUR_SCORE,
    CAST(NULL AS NUMERIC) AS COMBINED_WESCORE,
    CAST(NULL AS NUMERIC) AS ACC_BALANCE_INC_INT,
    CUSTOMER_ROLE AS CUSTOMER_ROLE,
    CAST(NULL AS NUMERIC) AS MSFS_TOTAL_EXPOSURE,
    CAST(NULL AS NUMERIC) AS NUMBER_OF_CREDIT_CARDS,
    NUMBER_OF_CHILDREN AS NUMBER_OF_CHILDREN,
    OFFERED_LIMIT_AMOUNT AS SYSTEM_CREDIT_LIMIT,
    CAST(NULL AS NUMERIC) AS CUST_REQUESTED_LIMIT,
    CAST(NULL AS STRING) AS PARTNER_TIME_IN_EMPLOY,
    CAST(NULL AS NUMERIC) AS TIME_ON_BOOKS,
    CAST(NULL AS NUMERIC) AS TOTAL_MSFS_BALANCE,
    CAST(NULL AS STRING) AS CARD_EXPIRY_DATE,
    CAST(NULL AS STRING) AS REQUESTED_PRODUCT,
    CAST(NULL AS STRING) AS OFFERED_PRODUCT,
    CAST(NULL AS STRING) AS ACCEPTED_PRODUCT,
    EMAIL AS EMAIL_ADDRESS,
    CAST(NULL AS STRING) AS BUSINESS_CONFIRMATION_CALL,
    CAST(NULL AS STRING) AS EMBOSSER_NUMBER_AU,
    CAST(NULL AS STRING) AS OFFER_CODE,
    CAST(NULL AS STRING) AS CLOSE_CHARGECARD_INDICATOR,
    CAST(NULL AS STRING) AS CHARGECARD_NUMBER,
    CAST(NULL AS NUMERIC) AS CHARGECARD_TRANSFER_AMOUNT,
    CAST(NULL AS STRING) AS CHARGECARD_TRANSFER_ALLOWED,
    CAST(NULL AS STRING) AS CLOSE_BUDGETCARD_INDICATOR,
    CAST(NULL AS STRING) AS BUDGETCARD_NUMBER,
    CAST(NULL AS NUMERIC) AS BUDGETCARD_TRANSFER_AMOUNT,
    CAST(NULL AS STRING) AS BUDGETCARD_TRANSFER_ALLOWED,
    CAST(NULL AS NUMERIC) AS BALANCE_TRANSFER_CREDIT_LIMIT,
    CAST(NULL AS NUMERIC) AS BALANCE_TRANSFER_TOTAL_AMOUNT,
    CAST(NULL AS NUMERIC) AS BALANCE_TRANSFER_COUNT,
    CAST(NULL AS STRING) AS BALANCE_TRANSFER_REQUIRED,
    CHANNEL_PREFERENCE_INDICATOR AS CHANNEL_PREFERENCE_INDICATOR,
    POSTCODE AS CUSTOMER_POSTCODE,
    CAST(NULL AS STRING) AS MIGRATION_FLAG,
    DATE_OF_BIRTH AS CUSTOMER_DOB,
    CAST(NULL AS STRING) AS EXPERIAN_REFERENCE,
    CAST(NULL AS NUMERIC) AS DNB_SCORE,
    CAST(NULL AS NUMERIC) AS DCM_SCORE,
    FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES AS SUSTAINIBILITY,
    DELPHI_SCORE AS DELPHI_SCORE,
    CIISCORE AS CII_SCORE,
    CARD_ORIGIN AS CARD_ORIGIN
  
  FROM RTR_CREDIT_APPLICATION_out1 AS in0

)

SELECT *

FROM UPD_CREDIT_APPLICATION_EXP
