{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_WORK_CARDS_ORIG_STAGING AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('m_rep_cards_orig_credit_application_update', 'EXP_WORK_CARDS_ORIG_STAGING') }}

),

EXP_WORK_CARDS_ORIG_STAGING_EXPR_18 AS (

  SELECT 
    o_FRAUD_RESULT AS INITIAL_DECISION_5,
    o_in_CREDIT_DECISION_RESULT AS INITIAL_DECISION_6,
    o_MARITAL_STATUS AS MARITAL_STATUS,
    APPLICATION_STORE_NUMBER AS APPLICATION_STORE_NUMBER,
    APPLICATION_SOURCE_CODE AS APPLICATION_SOURCE_CODE,
    APPLICATION_SCORE AS APPLICATION_SCORE,
    CIISCORE AS CIISCORE,
    DELPHI_SCORE AS DELPHI_SCORE,
    FIRST_PARTY_FRAUD_SCORE AS FIRST_PARTY_FRAUD_SCORE,
    LAST_ACTION_DATE AS LAST_ACTION_DATE1,
    o_RESIDENTIAL_STATUS AS RESIDENTIAL_STATUS,
    OCCUPATION1 AS OCCUPATION,
    APPLICATION_TYPE AS APPLICATION_TYPE,
    OFFER_ID AS OFFER_ID,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    o_EMPLOYMENT_ROLE AS CUSTOMER_ROLE,
    PRODUCT_NUMBER AS PRODUCT_NUMBER,
    o_PRODUCT AS PRODUCT,
    NUMBER_OF_CHILDREN AS NUMBER_OF_CHILDREN,
    CREDIT_REQUESTED_AMOUNT AS CREDIT_REQUESTED_AMOUNT,
    EMAIL AS EMAIL,
    o_CHANNEL_PREFERENCE_INDICATOR AS CHANNEL_PREFERENCE_INDICATOR,
    POSTCODE AS POSTCODE,
    DATE_OF_BIRTH AS DATE_OF_BIRTH,
    FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES AS FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES,
    ANNUAL_INCOME_AMOUNT AS ANNUAL_INCOME_AMOUNT,
    out_ANNUAL_SALARY_AMOUNT AS ANNUAL_HOUSEHOLD_INCOME,
    ACCID_TGT AS ACCID_TGT,
    BUSINESS_DATE AS BUSINESS_DATE,
    BUSINESS_DATE_MINUS_1 AS BUSINESS_DATE_MINUS_1,
    o_INITIAL_DECISION_COARSE_SRC AS INITIAL_DECISION_COARSE_SRC,
    o_INITIAL_DECISION_PRIMARY_SRC AS INITIAL_DECISION_PRIMARY_SRC,
    INITIAL_DECISION_COARSE_TGT AS INITIAL_DECISION_COARSE_TGT,
    INITIAL_DECISION_PRIMARY_TGT AS INITIAL_DECISION_PRIMARY_TGT,
    o_FINAL_DECISION_COARSE AS o_FINAL_DECISION_COARSE,
    o_FINAL_DECISION_PRIMARY AS o_FINAL_DECISION_PRIMARY,
    LAST_ACTION_DATE AS LAST_ACTION_DATE,
    EFROM_TGT AS EFROM_TGT,
    o_LAST_ACTION_DATE AS o_LAST_ACTION_DATE,
    ACCID_SRC AS ACCID_SRC,
    APPLICATION_DATE AS APPLICATION_DATE,
    o_EMPLOYMENT_STATUS AS EMPLOYMENT_STATUS,
    o_CDD_RESULT AS INITIAL_DECISION_2,
    o_RTS_TRANSACTION_STATUS AS INITIAL_DECISION_3,
    o_in_IDENTITY_VERIFICATION_STATUS AS INITIAL_DECISION_4,
    o_TIME_AT_PREVIOUS_ADDRESS AS o_TIME_AT_PREVIOUS_ADDRESS,
    o_EMPLOYMENT_MAIN_STARTDATE AS o_EMPLOYMENT_MAIN_STARTDATE,
    o_RESIDENTIAL_MOVED_IN_DATE AS o_RESIDENTIAL_MOVED_IN_DATE,
    TIME_STAMP_OF_ACTION AS o_TIME_STAMP_OF_ACTION,
    o_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER AS CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER,
    o_OFFERED_LIMIT_AMOUNT AS OFFERED_LIMIT_AMOUNT,
    o_in_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE AS CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE,
    ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
    CARD_ORIGIN AS CARD_ORIGIN,
    lookup_string AS lookup_string,
    business_date_string__find_business_date_lkp_1 AS business_date_string__find_business_date_lkp_1,
    APPLICATION_NUMBER AS APPLICATION_NUMBER,
    APPLICATION_STATUS AS APPLICATION_STATUS,
    RESIDENTIAL_MOVED_IN_DATE AS RESIDENTIAL_MOVED_IN_DATE,
    in_PREVIOUS_ADDRESSES_MOVED_IN_DATE AS in_PREVIOUS_ADDRESSES_MOVED_IN_DATE,
    EMPLOYMENT_MAIN_STARTDATE AS EMPLOYMENT_MAIN_STARTDATE,
    ROW_NUM AS ROW_NUM,
    FEED_UPDATE_ID AS FEED_UPDATE_ID,
    APPLICATION_STATUS1 AS APPLICATION_STATUS1,
    APPLICATION_STATUS2 AS APPLICATION_STATUS2,
    FINAL_DECISION_COARSE_TGT AS FINAL_DECISION_COARSE_TGT,
    FINAL_DECISION_PRIMARY_TGT AS FINAL_DECISION_PRIMARY_TGT,
    ACTION_DATE_TGT AS ACTION_DATE_TGT
  
  FROM EXP_WORK_CARDS_ORIG_STAGING AS in0

)

SELECT *

FROM EXP_WORK_CARDS_ORIG_STAGING_EXPR_18
