{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_WORK_CARDS_ORIG_STAGING_sp AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('m_rep_cards_orig_credit_application_update', 'EXP_WORK_CARDS_ORIG_STAGING_sp') }}

),

EXP_WORK_CARDS_ORIG_STAGING_reformat AS (

  SELECT 
    ACCID_SRC AS ACCID_SRC,
    APPLICATION_DATE AS APPLICATION_DATE,
    APPLICATION_STORE_NUMBER AS APPLICATION_STORE_NUMBER,
    (
      CASE
        WHEN (CDD_RESULT = 'PASSED')
          THEN 'PASS'
        WHEN (CDD_RESULT = 'REFER')
          THEN 'REFE'
        WHEN (CDD_RESULT = 'FINALCOMPLETE')
          THEN 'FINA'
        WHEN (CDD_RESULT = 'DECLINED')
          THEN 'DECL'
        WHEN (CDD_RESULT = 'TIMEOUT')
          THEN 'TIMO'
        WHEN (CDD_RESULT = 'PEPAPPROVED')
          THEN 'PEPA'
        WHEN (CDD_RESULT = 'OPSTIMEOUT')
          THEN 'OPST'
        WHEN (CDD_RESULT = 'INPROGRESS')
          THEN 'INPR'
        WHEN (CDD_RESULT = 'INERROR')
          THEN 'INER'
        WHEN (CDD_RESULT = 'NOT_CHECKED')
          THEN 'NOTC'
        WHEN (CDD_RESULT = 'NOT_APPLICABLE')
          THEN 'NOTA'
        ELSE SUBSTRING(CDD_RESULT, 0, 4)
      END
    ) AS o_CDD_RESULT,
    (
      CASE
        WHEN (RTS_TRANSACTION_STATUS = 'PASSED')
          THEN 'PASS'
        WHEN (RTS_TRANSACTION_STATUS = 'REFER')
          THEN 'REFE'
        WHEN (RTS_TRANSACTION_STATUS = 'FINALCOMPLETE')
          THEN 'FINA'
        WHEN (RTS_TRANSACTION_STATUS = 'DECLINED')
          THEN 'DECL'
        WHEN (RTS_TRANSACTION_STATUS = 'TIMEOUT')
          THEN 'TIMO'
        WHEN (RTS_TRANSACTION_STATUS = 'PEPAPPROVED')
          THEN 'PEPA'
        WHEN (RTS_TRANSACTION_STATUS = 'OPSTIMEOUT')
          THEN 'OPST'
        WHEN (RTS_TRANSACTION_STATUS = 'INPROGRESS')
          THEN 'INPR'
        WHEN (RTS_TRANSACTION_STATUS = 'INERROR')
          THEN 'INER'
        WHEN (RTS_TRANSACTION_STATUS = 'NOT_CHECKED')
          THEN 'NOTC'
        WHEN (RTS_TRANSACTION_STATUS = 'NOT_APPLICABLE')
          THEN 'NOTA'
        ELSE SUBSTRING(RTS_TRANSACTION_STATUS, 0, 4)
      END
    ) AS o_RTS_TRANSACTION_STATUS,
    (
      CASE
        WHEN (IDENTITY_VERIFICATION_STATUS = 'PASSED')
          THEN 'PASS'
        WHEN (IDENTITY_VERIFICATION_STATUS = 'REFER')
          THEN 'REFE'
        WHEN (IDENTITY_VERIFICATION_STATUS = 'FAILED')
          THEN 'FAIL'
        WHEN (IDENTITY_VERIFICATION_STATUS = 'DECLINED')
          THEN 'DECL'
        WHEN (IDENTITY_VERIFICATION_STATUS = 'IN_PROGRESS')
          THEN 'INPR'
        WHEN (IDENTITY_VERIFICATION_STATUS = 'ERROR')
          THEN 'ERRO'
        WHEN (IDENTITY_VERIFICATION_STATUS = 'NOT_CHECKED')
          THEN 'NOTC'
        ELSE SUBSTRING(IDENTITY_VERIFICATION_STATUS, 0, 4)
      END
    ) AS o_in_IDENTITY_VERIFICATION_STATUS,
    (
      CASE
        WHEN (FRAUD_RESULT = 'PASSED')
          THEN 'PASS'
        WHEN (FRAUD_RESULT = 'REFER')
          THEN 'REFE'
        WHEN (FRAUD_RESULT = 'DECLINE')
          THEN 'DECL'
        ELSE SUBSTRING(FRAUD_RESULT, 0, 4)
      END
    ) AS o_FRAUD_RESULT,
    (
      CASE
        WHEN (CREDIT_DECISION_RESULT = 'ACCEPT')
          THEN 'ACCE'
        WHEN (CREDIT_DECISION_RESULT = 'REFER')
          THEN 'REFE'
        WHEN (CREDIT_DECISION_RESULT = 'REJECT')
          THEN 'REJE'
        WHEN (CREDIT_DECISION_RESULT = 'NOT_CHECKED')
          THEN 'NOTC'
        ELSE SUBSTRING(CREDIT_DECISION_RESULT, 0, 4)
      END
    ) AS o_in_CREDIT_DECISION_RESULT,
    ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
    APPLICATION_NUMBER AS APPLICATION_NUMBER,
    APPLICATION_STATUS AS APPLICATION_STATUS,
    'MS' AS o_PRODUCT,
    APPLICATION_SOURCE_CODE AS APPLICATION_SOURCE_CODE,
    DATE_OF_BIRTH AS DATE_OF_BIRTH,
    POSTCODE AS POSTCODE,
    (
      CASE
        WHEN CAST((ANNUAL_INCOME_AMOUNT1 IS NULL) AS BOOL)
          THEN 0
        ELSE ANNUAL_INCOME_AMOUNT1
      END
    ) AS ANNUAL_INCOME_AMOUNT,
    'T' AS APPLICATION_TYPE,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    (
      CASE
        WHEN (EMPLOYMENT_ROLE = 'BUSINESS_OWNER')
          THEN 'B'
        WHEN (EMPLOYMENT_ROLE = 'KEY_CONTROLLER')
          THEN 'K'
        WHEN (EMPLOYMENT_ROLE = 'EMPLOYEE')
          THEN 'E'
        WHEN (EMPLOYMENT_ROLE = 'SOLE_TRADER')
          THEN 'S'
        ELSE SUBSTRING(EMPLOYMENT_ROLE, 0, 1)
      END
    ) AS o_EMPLOYMENT_ROLE,
    (
      CASE
        WHEN (EMPLOYMENT_STATUS = 'AT_HOME')
          THEN 'AH'
        WHEN (EMPLOYMENT_STATUS = 'EMPLOYED_FULL_TIME')
          THEN 'EF'
        WHEN (EMPLOYMENT_STATUS = 'EMPLOYED_PART_TIME')
          THEN 'EP'
        WHEN (EMPLOYMENT_STATUS = 'SELF_EMPLOYED')
          THEN 'SE'
        WHEN (EMPLOYMENT_STATUS = 'RETIRED')
          THEN 'RT'
        WHEN (EMPLOYMENT_STATUS = 'DISABLED')
          THEN 'DI'
        WHEN (EMPLOYMENT_STATUS = 'STUDENT')
          THEN 'ST'
        WHEN (EMPLOYMENT_STATUS = 'UNEMPLOYED')
          THEN 'UN'
        ELSE SUBSTRING(EMPLOYMENT_STATUS, 0, 2)
      END
    ) AS o_EMPLOYMENT_STATUS,
    (
      CASE
        WHEN (MARITAL_STATUS = 'MARRIED')
          THEN 'M'
        WHEN (MARITAL_STATUS = 'SINGLE')
          THEN 'S'
        WHEN (MARITAL_STATUS = 'DIVORCED')
          THEN 'D'
        WHEN (MARITAL_STATUS = 'LIVING_WITH_PARTNER')
          THEN 'P'
        WHEN (MARITAL_STATUS = 'WIDOWED')
          THEN 'W'
        ELSE SUBSTRING(MARITAL_STATUS, 0, 1)
      END
    ) AS o_MARITAL_STATUS,
    (
      CASE
        WHEN CAST((NUMBER_OF_DEPENDENTS IS NULL) AS BOOL)
          THEN 0
        ELSE NUMBER_OF_DEPENDENTS
      END
    ) AS NUMBER_OF_CHILDREN,
    (
      CASE
        WHEN (RESIDENTIAL_STATUS = 'OTHER')
          THEN 'O'
        WHEN (RESIDENTIAL_STATUS = 'OWNER')
          THEN 'W'
        WHEN (RESIDENTIAL_STATUS = 'TENANT')
          THEN 'T'
        WHEN (RESIDENTIAL_STATUS = 'WITH_PARENTS')
          THEN 'P'
        ELSE SUBSTRING(RESIDENTIAL_STATUS, 0, 1)
      END
    ) AS o_RESIDENTIAL_STATUS,
    CAST(NULL AS STRING) AS OCCUPATION,
    PRODUCT_NUMBER AS PRODUCT_NUMBER,
    EMAIL AS EMAIL,
    (
      CASE
        WHEN (MARKETING_PREFERENCES_PREFERRED_CHANNELS = 'EMAIL')
          THEN 'E'
        WHEN (MARKETING_PREFERENCES_PREFERRED_CHANNELS = 'SMS')
          THEN 'S'
        WHEN (MARKETING_PREFERENCES_PREFERRED_CHANNELS = 'CALL')
          THEN 'C'
        WHEN (MARKETING_PREFERENCES_PREFERRED_CHANNELS = 'POST')
          THEN 'P'
        ELSE SUBSTRING(MARKETING_PREFERENCES_PREFERRED_CHANNELS, 0, 1)
      END
    ) AS o_CHANNEL_PREFERENCE_INDICATOR,
    APPLICATION_SCORE AS APPLICATION_SCORE,
    CIISCORE AS CIISCORE,
    DELPHI_SCORE AS DELPHI_SCORE,
    FIRST_PARTY_FRAUD_SCORE AS FIRST_PARTY_FRAUD_SCORE,
    (
      CASE
        WHEN CAST((IN_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE IS NULL) AS BOOL)
          THEN 0
        ELSE IN_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE
      END
    ) AS o_in_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE,
    RESIDENTIAL_MOVED_IN_DATE AS RESIDENTIAL_MOVED_IN_DATE,
    (
      CASE
        WHEN CAST((RESIDENTIAL_MOVED_IN_DATE IS NULL) AS BOOL)
          THEN ''
        WHEN (
          (
            LENGTH(
              CAST(DATE_DIFF(
                (
                  PARSE_TIMESTAMP(
                    '%Y%m%d', 
                    CAST((
                      CASE
                        WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                          THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_1
                        ELSE CAST(NULL AS STRING)
                      END
                    ) AS STRING))
                ), 
                (PARSE_TIMESTAMP('%Y%m%d', CAST((CONCAT(RESIDENTIAL_MOVED_IN_DATE, '01')) AS STRING))), 
                DAY) AS STRING))
          ) > 4
        )
          THEN '9999'
        ELSE CAST(DATE_DIFF(
          (
            PARSE_TIMESTAMP(
              '%Y%m%d', 
              CAST((
                CASE
                  WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                    THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_1
                  ELSE CAST(NULL AS STRING)
                END
              ) AS STRING))
          ), 
          (PARSE_TIMESTAMP('%Y%m%d', CAST((CONCAT(RESIDENTIAL_MOVED_IN_DATE, '01')) AS STRING))), 
          DAY) AS STRING)
      END
    ) AS o_RESIDENTIAL_MOVED_IN_DATE,
    in_PREVIOUS_ADDRESSES_MOVED_IN_DATE AS in_PREVIOUS_ADDRESSES_MOVED_IN_DATE,
    (
      CASE
        WHEN CAST((IN_PREVIOUS_ADDRESSES_MOVED_IN_DATE IS NULL) AS BOOL)
          THEN ''
        WHEN (
          (
            LENGTH(
              CAST(DATE_DIFF(
                (PARSE_TIMESTAMP('%Y%m%d', CAST((CONCAT(RESIDENTIAL_MOVED_IN_DATE, '01')) AS STRING))), 
                (PARSE_TIMESTAMP('%Y%m%d', CAST((CONCAT(IN_PREVIOUS_ADDRESSES_MOVED_IN_DATE, '01')) AS STRING))), 
                DAY) AS STRING))
          ) > 4
        )
          THEN '9999'
        ELSE CAST(DATE_DIFF(
          (PARSE_TIMESTAMP('%Y%m%d', CAST((CONCAT(RESIDENTIAL_MOVED_IN_DATE, '01')) AS STRING))), 
          (PARSE_TIMESTAMP('%Y%m%d', CAST((CONCAT(IN_PREVIOUS_ADDRESSES_MOVED_IN_DATE, '01')) AS STRING))), 
          DAY) AS STRING)
      END
    ) AS o_TIME_AT_PREVIOUS_ADDRESS,
    EMPLOYMENT_MAIN_STARTDATE AS EMPLOYMENT_MAIN_STARTDATE,
    (
      CASE
        WHEN CAST((EMPLOYMENT_MAIN_STARTDATE IS NULL) AS BOOL)
          THEN ''
        WHEN (
          (
            LENGTH(
              CAST(DATE_DIFF(
                (
                  PARSE_TIMESTAMP(
                    '%Y%m%d', 
                    CAST((
                      CASE
                        WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                          THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_1
                        ELSE CAST(NULL AS STRING)
                      END
                    ) AS STRING))
                ), 
                (PARSE_TIMESTAMP('%Y%m%d', CAST((CONCAT(EMPLOYMENT_MAIN_STARTDATE, '01')) AS STRING))), 
                DAY) AS STRING))
          ) > 4
        )
          THEN '9999'
        ELSE CAST(DATE_DIFF(
          (
            PARSE_TIMESTAMP(
              '%Y%m%d', 
              CAST((
                CASE
                  WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                    THEN BUSINESS_DATE_STRING__FIND_BUSINESS_DATE_LKP_1
                  ELSE CAST(NULL AS STRING)
                END
              ) AS STRING))
          ), 
          (PARSE_TIMESTAMP('%Y%m%d', CAST((CONCAT(EMPLOYMENT_MAIN_STARTDATE, '01')) AS STRING))), 
          DAY) AS STRING)
      END
    ) AS o_EMPLOYMENT_MAIN_STARTDATE,
    (
      CASE
        WHEN CAST((IN_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER IS NULL) AS BOOL)
          THEN 0
        ELSE IN_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER
      END
    ) AS o_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER,
    OCCUPATION1 AS OCCUPATION1,
    (
      CASE
        WHEN CAST((IN_OFFERED_LIMIT_AMOUNT IS NULL) AS BOOL)
          THEN 0
        ELSE IN_OFFERED_LIMIT_AMOUNT
      END
    ) AS o_OFFERED_LIMIT_AMOUNT,
    (
      CASE
        WHEN CAST((ANNUAL_SALARY_AMOUNT IS NULL) AS BOOL)
          THEN 0
        ELSE ANNUAL_SALARY_AMOUNT
      END
    ) AS out_ANNUAL_SALARY_AMOUNT,
    OFFER_ID AS OFFER_ID,
    CREDIT_REQUESTED_AMOUNT AS CREDIT_REQUESTED_AMOUNT,
    FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES AS FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES,
    ROW_NUM AS ROW_NUM,
    '1' AS BUSINESS_DATE,
    '1' AS BUSINESS_DATE_MINUS_1,
    (
      CASE
        WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) = 1)
          THEN output_sp
        ELSE NULL
      END
    ) AS FEED_UPDATE_ID,
    ACCID_TGT AS ACCID_TGT,
    APPLICATION_STATUS1 AS APPLICATION_STATUS1,
    (
      CASE
        WHEN (APPLICATION_STATUS1 = 'CANCELLED')
          THEN 'C'
        WHEN (APPLICATION_STATUS1 = 'APPROVED')
          THEN 'A'
        WHEN (APPLICATION_STATUS1 = 'ABORTED')
          THEN 'X'
        WHEN (APPLICATION_STATUS1 = 'REFERRED')
          THEN 'R'
        WHEN (APPLICATION_STATUS1 = 'DECLINED')
          THEN 'D'
        ELSE NULL
      END
    ) AS o_INITIAL_DECISION_COARSE_SRC,
    (
      CASE
        WHEN (APPLICATION_STATUS1 = 'CANCELLED')
          THEN 'CANC'
        WHEN (APPLICATION_STATUS1 = 'APPROVED')
          THEN 'APPR'
        WHEN (APPLICATION_STATUS1 = 'ABORTED')
          THEN 'ABOR'
        WHEN (APPLICATION_STATUS1 = 'REFERRED')
          THEN 'REFE'
        WHEN (APPLICATION_STATUS1 = 'DECLINED')
          THEN 'DECL'
        ELSE NULL
      END
    ) AS o_INITIAL_DECISION_PRIMARY_SRC,
    APPLICATION_STATUS2 AS APPLICATION_STATUS2,
    INITIAL_DECISION_COARSE_TGT AS INITIAL_DECISION_COARSE_TGT,
    INITIAL_DECISION_PRIMARY_TGT AS INITIAL_DECISION_PRIMARY_TGT,
    FINAL_DECISION_COARSE_TGT AS FINAL_DECISION_COARSE_TGT,
    FINAL_DECISION_PRIMARY_TGT AS FINAL_DECISION_PRIMARY_TGT,
    (
      CASE
        WHEN (
          (
            (
              CASE
                WHEN (APPLICATION_STATUS2 = 'CANCELLED')
                  THEN 'C'
                WHEN (APPLICATION_STATUS2 = 'APPROVED')
                  THEN 'A'
                WHEN (APPLICATION_STATUS2 = 'ABORTED')
                  THEN 'X'
                WHEN (APPLICATION_STATUS2 = 'REFERRED')
                  THEN 'R'
                WHEN (APPLICATION_STATUS2 = 'DECLINED')
                  THEN 'D'
                ELSE NULL
              END
            ) IS NULL
          )
          AND (FINAL_DECISION_COARSE_TGT IS NOT NULL)
        )
          THEN FINAL_DECISION_COARSE_TGT
        WHEN (
          (
            (
              CASE
                WHEN (APPLICATION_STATUS2 = 'CANCELLED')
                  THEN 'C'
                WHEN (APPLICATION_STATUS2 = 'APPROVED')
                  THEN 'A'
                WHEN (APPLICATION_STATUS2 = 'ABORTED')
                  THEN 'X'
                WHEN (APPLICATION_STATUS2 = 'REFERRED')
                  THEN 'R'
                WHEN (APPLICATION_STATUS2 = 'DECLINED')
                  THEN 'D'
                ELSE NULL
              END
            ) IS NULL
          )
          AND (FINAL_DECISION_COARSE_TGT IS NULL)
        )
          THEN CAST((
            CASE
              WHEN (APPLICATION_STATUS1 = 'CANCELLED')
                THEN 'C'
              WHEN (APPLICATION_STATUS1 = 'APPROVED')
                THEN 'A'
              WHEN (APPLICATION_STATUS1 = 'ABORTED')
                THEN 'X'
              WHEN (APPLICATION_STATUS1 = 'REFERRED')
                THEN 'R'
              WHEN (APPLICATION_STATUS1 = 'DECLINED')
                THEN 'D'
              ELSE NULL
            END
          ) AS STRING)
        WHEN (APPLICATION_STATUS2 = 'CANCELLED')
          THEN 'C'
        WHEN (APPLICATION_STATUS2 = 'APPROVED')
          THEN 'A'
        WHEN (APPLICATION_STATUS2 = 'ABORTED')
          THEN 'X'
        WHEN (APPLICATION_STATUS2 = 'REFERRED')
          THEN 'R'
        WHEN (APPLICATION_STATUS2 = 'DECLINED')
          THEN 'D'
        ELSE NULL
      END
    ) AS o_FINAL_DECISION_COARSE,
    (
      CASE
        WHEN (
          (
            (
              CASE
                WHEN (APPLICATION_STATUS2 = 'CANCELLED')
                  THEN 'CANC'
                WHEN (APPLICATION_STATUS2 = 'APPROVED')
                  THEN 'APPR'
                WHEN (APPLICATION_STATUS2 = 'ABORTED')
                  THEN 'ABOR'
                WHEN (APPLICATION_STATUS2 = 'REFERRED')
                  THEN 'REFE'
                WHEN (APPLICATION_STATUS2 = 'DECLINED')
                  THEN 'DECL'
                ELSE NULL
              END
            ) IS NULL
          )
          AND (FINAL_DECISION_PRIMARY_TGT IS NOT NULL)
        )
          THEN FINAL_DECISION_PRIMARY_TGT
        WHEN (
          (
            (
              CASE
                WHEN (APPLICATION_STATUS2 = 'CANCELLED')
                  THEN 'CANC'
                WHEN (APPLICATION_STATUS2 = 'APPROVED')
                  THEN 'APPR'
                WHEN (APPLICATION_STATUS2 = 'ABORTED')
                  THEN 'ABOR'
                WHEN (APPLICATION_STATUS2 = 'REFERRED')
                  THEN 'REFE'
                WHEN (APPLICATION_STATUS2 = 'DECLINED')
                  THEN 'DECL'
                ELSE NULL
              END
            ) IS NULL
          )
          AND (FINAL_DECISION_PRIMARY_TGT IS NULL)
        )
          THEN CAST((
            CASE
              WHEN (APPLICATION_STATUS1 = 'CANCELLED')
                THEN 'CANC'
              WHEN (APPLICATION_STATUS1 = 'APPROVED')
                THEN 'APPR'
              WHEN (APPLICATION_STATUS1 = 'ABORTED')
                THEN 'ABOR'
              WHEN (APPLICATION_STATUS1 = 'REFERRED')
                THEN 'REFE'
              WHEN (APPLICATION_STATUS1 = 'DECLINED')
                THEN 'DECL'
              ELSE NULL
            END
          ) AS STRING)
        WHEN (APPLICATION_STATUS2 = 'CANCELLED')
          THEN 'CANC'
        WHEN (APPLICATION_STATUS2 = 'APPROVED')
          THEN 'APPR'
        WHEN (APPLICATION_STATUS2 = 'ABORTED')
          THEN 'ABOR'
        WHEN (APPLICATION_STATUS2 = 'REFERRED')
          THEN 'REFE'
        WHEN (APPLICATION_STATUS2 = 'DECLINED')
          THEN 'DECL'
        ELSE NULL
      END
    ) AS o_FINAL_DECISION_PRIMARY,
    LAST_ACTION_DATE AS LAST_ACTION_DATE,
    TIME_STAMP_OF_ACTION AS TIME_STAMP_OF_ACTION,
    (
      CONCAT(
        SUBSTRING(CAST(LAST_ACTION_DATE AS STRING), 10, 2), 
        SUBSTRING(CAST(LAST_ACTION_DATE AS STRING), 13, 2), 
        SUBSTRING(CAST(LAST_ACTION_DATE AS STRING), 16, 2))
    ) AS o_TIME_STAMP_OF_ACTION,
    ACTION_DATE_TGT AS ACTION_DATE_TGT,
    (
      CASE
        WHEN CAST((
          (
            CASE
              WHEN (APPLICATION_STATUS2 = 'CANCELLED')
                THEN 'CANC'
              WHEN (APPLICATION_STATUS2 = 'APPROVED')
                THEN 'APPR'
              WHEN (APPLICATION_STATUS2 = 'ABORTED')
                THEN 'ABOR'
              WHEN (APPLICATION_STATUS2 = 'REFERRED')
                THEN 'REFE'
              WHEN (APPLICATION_STATUS2 = 'DECLINED')
                THEN 'DECL'
              ELSE NULL
            END
          ) IS NULL
        ) AS BOOL)
          THEN ACTION_DATE_TGT
        WHEN (
          (
            CASE
              WHEN (APPLICATION_STATUS2 = 'CANCELLED')
                THEN 'CANC'
              WHEN (APPLICATION_STATUS2 = 'APPROVED')
                THEN 'APPR'
              WHEN (APPLICATION_STATUS2 = 'ABORTED')
                THEN 'ABOR'
              WHEN (APPLICATION_STATUS2 = 'REFERRED')
                THEN 'REFE'
              WHEN (APPLICATION_STATUS2 = 'DECLINED')
                THEN 'DECL'
              ELSE NULL
            END
          ) = FINAL_DECISION_PRIMARY_TGT
        )
          THEN ACTION_DATE_TGT
        ELSE LAST_ACTION_DATE
      END
    ) AS o_LAST_ACTION_DATE,
    EFROM_TGT AS EFROM_TGT,
    2 AS CARD_ORIGIN
  
  FROM EXP_WORK_CARDS_ORIG_STAGING_sp AS in0

),

EXP_WORK_CARDS_ORIG_STAGING_EXPR_1 AS (

  SELECT 
    o_FRAUD_RESULT AS INITIAL_DECISION_5,
    o_in_CREDIT_DECISION_RESULT AS INITIAL_DECISION_6,
    o_MARITAL_STATUS AS MARITAL_STATUS,
    APPLICATION_STORE_NUMBER AS APPLICATION_STORE_NUMBER,
    APPLICATION_SOURCE_CODE AS APPLICATION_SOURCE_CODE,
    APPLICATION_SCORE AS APPLICATION_SCORE,
    CIISCORE AS CIISCORE,
    DELPHI_SCORE AS DELPHI_SCORE,
    FIRST_PARTY_FRAUD_SCORE AS FIRST_PARTY_FRAUD_SCORE,
    LAST_ACTION_DATE AS LAST_ACTION_DATE1,
    o_RESIDENTIAL_STATUS AS RESIDENTIAL_STATUS,
    OCCUPATION1 AS OCCUPATION,
    APPLICATION_TYPE AS APPLICATION_TYPE,
    OFFER_ID AS OFFER_ID,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    o_EMPLOYMENT_ROLE AS CUSTOMER_ROLE,
    PRODUCT_NUMBER AS PRODUCT_NUMBER,
    o_PRODUCT AS PRODUCT,
    NUMBER_OF_CHILDREN AS NUMBER_OF_CHILDREN,
    CREDIT_REQUESTED_AMOUNT AS CREDIT_REQUESTED_AMOUNT,
    EMAIL AS EMAIL,
    o_CHANNEL_PREFERENCE_INDICATOR AS CHANNEL_PREFERENCE_INDICATOR,
    POSTCODE AS POSTCODE,
    DATE_OF_BIRTH AS DATE_OF_BIRTH,
    FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES AS FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES,
    ANNUAL_INCOME_AMOUNT AS ANNUAL_INCOME_AMOUNT,
    out_ANNUAL_SALARY_AMOUNT AS ANNUAL_HOUSEHOLD_INCOME,
    ACCID_TGT AS ACCID_TGT,
    BUSINESS_DATE AS BUSINESS_DATE,
    BUSINESS_DATE_MINUS_1 AS BUSINESS_DATE_MINUS_1,
    o_INITIAL_DECISION_COARSE_SRC AS INITIAL_DECISION_COARSE_SRC,
    o_INITIAL_DECISION_PRIMARY_SRC AS INITIAL_DECISION_PRIMARY_SRC,
    INITIAL_DECISION_COARSE_TGT AS INITIAL_DECISION_COARSE_TGT,
    INITIAL_DECISION_PRIMARY_TGT AS INITIAL_DECISION_PRIMARY_TGT,
    o_FINAL_DECISION_COARSE AS o_FINAL_DECISION_COARSE,
    o_FINAL_DECISION_PRIMARY AS o_FINAL_DECISION_PRIMARY,
    LAST_ACTION_DATE AS LAST_ACTION_DATE,
    EFROM_TGT AS EFROM_TGT,
    o_LAST_ACTION_DATE AS o_LAST_ACTION_DATE,
    ACCID_SRC AS ACCID_SRC,
    APPLICATION_DATE AS APPLICATION_DATE,
    o_EMPLOYMENT_STATUS AS EMPLOYMENT_STATUS,
    o_CDD_RESULT AS INITIAL_DECISION_2,
    o_RTS_TRANSACTION_STATUS AS INITIAL_DECISION_3,
    o_in_IDENTITY_VERIFICATION_STATUS AS INITIAL_DECISION_4,
    o_TIME_AT_PREVIOUS_ADDRESS AS o_TIME_AT_PREVIOUS_ADDRESS,
    o_EMPLOYMENT_MAIN_STARTDATE AS o_EMPLOYMENT_MAIN_STARTDATE,
    o_RESIDENTIAL_MOVED_IN_DATE AS o_RESIDENTIAL_MOVED_IN_DATE,
    TIME_STAMP_OF_ACTION AS o_TIME_STAMP_OF_ACTION,
    o_CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER AS CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER,
    o_OFFERED_LIMIT_AMOUNT AS OFFERED_LIMIT_AMOUNT,
    o_in_CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE AS CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE,
    ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
    CARD_ORIGIN AS CARD_ORIGIN,
    APPLICATION_NUMBER AS APPLICATION_NUMBER,
    APPLICATION_STATUS AS APPLICATION_STATUS,
    RESIDENTIAL_MOVED_IN_DATE AS RESIDENTIAL_MOVED_IN_DATE,
    in_PREVIOUS_ADDRESSES_MOVED_IN_DATE AS in_PREVIOUS_ADDRESSES_MOVED_IN_DATE,
    EMPLOYMENT_MAIN_STARTDATE AS EMPLOYMENT_MAIN_STARTDATE,
    ROW_NUM AS ROW_NUM,
    FEED_UPDATE_ID AS FEED_UPDATE_ID,
    APPLICATION_STATUS1 AS APPLICATION_STATUS1,
    APPLICATION_STATUS2 AS APPLICATION_STATUS2,
    FINAL_DECISION_COARSE_TGT AS FINAL_DECISION_COARSE_TGT,
    FINAL_DECISION_PRIMARY_TGT AS FINAL_DECISION_PRIMARY_TGT,
    ACTION_DATE_TGT AS ACTION_DATE_TGT
  
  FROM EXP_WORK_CARDS_ORIG_STAGING_reformat AS in0

)

SELECT *

FROM EXP_WORK_CARDS_ORIG_STAGING_EXPR_1
