{{
  config({    
    "materialized": "table",
    "alias": "SM_DRMS_CAL_MTH_END_HIST",
    "database": "tanmay",
    "schema": "default"
  })
}}

WITH `{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_drms_cal_hist_sum_load_SQ_DRMS_DETAIL` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      'm_mmrt_drms_cal_hist_sum_load', 
      '{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_drms_cal_hist_sum_load_SQ_DRMS_DETAIL'
    )
  }}

),

SQ_DRMS_DETAIL_EXPR_5 AS (

  SELECT 
    WARRANT_COSTS AS DR_WARRANT_COSTS,
    EFROM AS DR_DETAIL_EFROM,
    LOAN_TYPE_CODE AS DR_LOAN_TYPE_CODE,
    CHARGE_OFF_AMOUNT AS DR_CHARGE_OFF_AMOUNT,
    CHARGE_OFF_DATE AS DR_CHARGE_OFF_DATE,
    PERIODID AS PERIODID,
    ACCOUNT_NUM AS DR_ACCOUNT_NUMBER,
    ACCOUNT_BALANCE AS DR_ACCOUNT_BALANCE,
    ACCOUNT_STATUS AS DR_ACCOUNT_STATUS,
    ASSOCIATED_COSTS AS DR_ASSOCIATED_COSTS,
    JUDGEMENT_ARREARS AS DR_JUDGEMENT_ARREARS,
    JUDGEMENT_SOLICITOR_COSTS AS DR_JUDGEMENT_SOLICITOR_COSTS,
    LAST_PAYMENT_DATE AS DR_LAST_PAYMENT_DATE,
    ORDER_FEE AS DR_ORDER_FEE,
    PAID_SINCE_JUDGEMENT AS DR_PAID_SINCE_JUDGEMENT,
    PAYMENT_AMOUNT AS DR_PAYMENT_AMOUNT,
    PAYMENT_DUE_AMOUNT AS DR_PAYMENT_DUE_AMOUNT,
    RECOVERY_COSTS AS DR_RECOVERY_COSTS,
    RECOVERY_INTEREST AS DR_RECOVERY_INTEREST,
    RECOVERY_PRINCIPAL AS DR_RECOVERY_PRINCIPAL,
    SUMMONS_AMOUNT AS DR_SUMMONS_AMOUNT,
    SUMMONS_FEE AS DR_SUMMONS_FEE,
    SUMMONS_SOLICITOR_COSTS AS DR_SUMMONS_SOLICITOR_COSTS
  
  FROM `{11_0_1}_Database___Generate_Monthly_Financialsm_mmrt_drms_cal_hist_sum_load_SQ_DRMS_DETAIL` AS in0

)

SELECT *

FROM SQ_DRMS_DETAIL_EXPR_5
