{{
  config({    
    "materialized": "table",
    "alias": "aka_GPD_UDDL_Wr_216",
    "database": "sony",
    "schema": "orch_test"
  })
}}

WITH DynamicRename_219 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('1_CRIS_Get_Source_Data', 'DynamicRename_219') }}

),

AlteryxSelect_223 AS (

  SELECT 
    business_unit AS BUSINESS_UNIT,
    email AS EMAIL,
    dept_code AS DEPT_CODE,
    division AS DIVISION,
    country AS COUNTRY,
    empl_class AS EMPL_CLASS,
    empl_type AS EMPL_TYPE,
    full_part_time AS FULL_PART_TIME,
    reg_temp AS REG_TEMP,
    empl_status AS EMPL_STATUS,
    per_status_code AS PER_STATUS_CODE,
    vendor_id AS VENDOR_ID,
    vendor_name AS VENDOR_NAME,
    manager_id AS MANAGER_ID,
    manager_name AS MANAGER_NAME,
    dpt_id_path AS DPT_ID_PATH,
    dept_descr AS DEPT_DESCR,
    emplid AS EMPLID,
    name AS NAME,
    empl_status_descr AS EMPL_STATUS_DESCR,
    location_descr AS LOCATION_DESCR,
    logon_id AS LOGON_ID,
    position_nbr AS POSITION_NBR,
    costcenter AS COSTCENTER,
    weekly_hours AS WEEKLY_HOURS,
    logon_domain AS LOGON_DOMAIN,
    per_type_descr AS PER_TYPE_DESCR,
    job_level AS JOB_LEVEL,
    fte AS FTE,
    job_requisition_id AS JOB_REQUISITION_ID,
    job_requisition_status AS JOB_REQUISITION_STATUS,
    hiring_manager AS HIRING_MANAGER,
    position_status AS POSITION_STATUS,
    compensation_grade_id AS COMPENSATION_GRADE_ID,
    target_hire_date AS TARGET_HIRE_DATE,
    recruiting_start_date AS RECRUITING_START_DATE,
    job_posting_title AS JOB_POSTING_TITLE,
    management_level AS MANAGEMENT_LEVEL,
    position_type AS POSITION_TYPE,
    CAST(days_from_rec_date AS INTEGER) AS DAYS_FROM_REC_DATE,
    replacement_for AS REPLACEMENT_FOR,
    POSITION_NAME AS POSITION_NAME,
    CATEGORY AS CATEGORY,
    VOL_INVOL AS VOL_INVOL,
    HIRE_DATE AS HIRE_DATE,
    POSITION_FILL_DATE AS POSITION_FILL_DATE,
    position_worker_type AS POSITION_WORKER_TYPE,
    supervisory_organization_name AS SUPERVISORY_ORGANIZATION_NAME,
    exit_reason AS EXIT_REASON,
    exit_detailed_reason AS EXIT_DETAILED_REASON,
    exit_date AS EXIT_DATE,
    * EXCEPT (`JOBCODE_DESCR`, 
    `LOCATION_CODE`, 
    `SUB_DIVISION`, 
    `SUPERVISORY_ORGANIZATION_ID`, 
    `BUSINESS_UNIT`, 
    `EMAIL`, 
    `DEPT_CODE`, 
    `DIVISION`, 
    `COUNTRY`, 
    `EMPL_CLASS`, 
    `EMPL_TYPE`, 
    `FULL_PART_TIME`, 
    `REG_TEMP`, 
    `EMPL_STATUS`, 
    `PER_STATUS_CODE`, 
    `VENDOR_ID`, 
    `VENDOR_NAME`, 
    `MANAGER_ID`, 
    `MANAGER_NAME`, 
    `DPT_ID_PATH`, 
    `DEPT_DESCR`, 
    `EMPLID`, 
    `NAME`, 
    `EMPL_STATUS_DESCR`, 
    `LOCATION_DESCR`, 
    `LOGON_ID`, 
    `POSITION_NBR`, 
    `COSTCENTER`, 
    `WEEKLY_HOURS`, 
    `LOGON_DOMAIN`, 
    `PER_TYPE_DESCR`, 
    `JOB_LEVEL`, 
    `FTE`, 
    `JOB_REQUISITION_ID`, 
    `JOB_REQUISITION_STATUS`, 
    `HIRING_MANAGER`, 
    `POSITION_STATUS`, 
    `COMPENSATION_GRADE_ID`, 
    `TARGET_HIRE_DATE`, 
    `RECRUITING_START_DATE`, 
    `JOB_POSTING_TITLE`, 
    `MANAGEMENT_LEVEL`, 
    `POSITION_TYPE`, 
    `DAYS_FROM_REC_DATE`, 
    `REPLACEMENT_FOR`, 
    `POSITION_NAME`, 
    `CATEGORY`, 
    `VOL_INVOL`, 
    `HIRE_DATE`, 
    `POSITION_FILL_DATE`, 
    `POSITION_WORKER_TYPE`, 
    `SUPERVISORY_ORGANIZATION_NAME`, 
    `EXIT_REASON`, 
    `EXIT_DETAILED_REASON`, 
    `EXIT_DATE`)
  
  FROM DynamicRename_219 AS in0

),

Cleanse_224 AS (

  {{
    prophecy_basics.DataCleansing(
      ['AlteryxSelect_223'], 
      [
        { "name": "BUSINESS_UNIT", "dataType": "String" }, 
        { "name": "EMAIL", "dataType": "String" }, 
        { "name": "DEPT_CODE", "dataType": "String" }, 
        { "name": "DIVISION", "dataType": "String" }, 
        { "name": "COUNTRY", "dataType": "String" }, 
        { "name": "EMPL_CLASS", "dataType": "String" }, 
        { "name": "EMPL_TYPE", "dataType": "String" }, 
        { "name": "FULL_PART_TIME", "dataType": "String" }, 
        { "name": "REG_TEMP", "dataType": "String" }, 
        { "name": "EMPL_STATUS", "dataType": "String" }, 
        { "name": "PER_STATUS_CODE", "dataType": "String" }, 
        { "name": "VENDOR_ID", "dataType": "String" }, 
        { "name": "VENDOR_NAME", "dataType": "String" }, 
        { "name": "MANAGER_ID", "dataType": "String" }, 
        { "name": "MANAGER_NAME", "dataType": "String" }, 
        { "name": "DPT_ID_PATH", "dataType": "String" }, 
        { "name": "DEPT_DESCR", "dataType": "String" }, 
        { "name": "EMPLID", "dataType": "String" }, 
        { "name": "NAME", "dataType": "String" }, 
        { "name": "EMPL_STATUS_DESCR", "dataType": "String" }, 
        { "name": "LOCATION_DESCR", "dataType": "String" }, 
        { "name": "LOGON_ID", "dataType": "String" }, 
        { "name": "POSITION_NBR", "dataType": "String" }, 
        { "name": "COSTCENTER", "dataType": "String" }, 
        { "name": "WEEKLY_HOURS", "dataType": "Decimal" }, 
        { "name": "LOGON_DOMAIN", "dataType": "String" }, 
        { "name": "PER_TYPE_DESCR", "dataType": "String" }, 
        { "name": "JOB_LEVEL", "dataType": "String" }, 
        { "name": "FTE", "dataType": "Decimal" }, 
        { "name": "JOB_REQUISITION_ID", "dataType": "String" }, 
        { "name": "JOB_REQUISITION_STATUS", "dataType": "String" }, 
        { "name": "HIRING_MANAGER", "dataType": "String" }, 
        { "name": "POSITION_STATUS", "dataType": "String" }, 
        { "name": "COMPENSATION_GRADE_ID", "dataType": "String" }, 
        { "name": "TARGET_HIRE_DATE", "dataType": "Date" }, 
        { "name": "RECRUITING_START_DATE", "dataType": "Date" }, 
        { "name": "JOB_POSTING_TITLE", "dataType": "String" }, 
        { "name": "MANAGEMENT_LEVEL", "dataType": "String" }, 
        { "name": "POSITION_TYPE", "dataType": "String" }, 
        { "name": "DAYS_FROM_REC_DATE", "dataType": "Integer" }, 
        { "name": "REPLACEMENT_FOR", "dataType": "String" }, 
        { "name": "POSITION_NAME", "dataType": "String" }, 
        { "name": "CATEGORY", "dataType": "String" }, 
        { "name": "VOL_INVOL", "dataType": "String" }, 
        { "name": "HIRE_DATE", "dataType": "Timestamp" }, 
        { "name": "POSITION_FILL_DATE", "dataType": "Date" }, 
        { "name": "POSITION_WORKER_TYPE", "dataType": "String" }, 
        { "name": "SUPERVISORY_ORGANIZATION_NAME", "dataType": "String" }, 
        { "name": "EXIT_REASON", "dataType": "String" }, 
        { "name": "EXIT_DETAILED_REASON", "dataType": "String" }, 
        { "name": "EXIT_DATE", "dataType": "Timestamp" }
      ], 
      'keepOriginal', 
      [], 
      true, 
      '', 
      false, 
      0, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

Formula_226_0 AS (

  SELECT 
    (TO_TIMESTAMP((TO_UTC_TIMESTAMP(CURRENT_TIMESTAMP, 'UTC')))) AS Loaded_date,
    CAST((REGEXP_REPLACE(JOB_POSTING_TITLE, '[\\Q\\E]+$', '')) AS string) AS JOB_POSTING_TITLE,
    * EXCEPT (`job_posting_title`)
  
  FROM Cleanse_224 AS in0

),

AlteryxSelect_225 AS (

  SELECT 
    BUSINESS_UNIT AS BUSINESS_UNIT,
    EMAIL AS EMAIL,
    DEPT_CODE AS DEPT_CODE,
    DIVISION AS DIVISION,
    COUNTRY AS COUNTRY,
    EMPL_CLASS AS EMPL_CLASS,
    EMPL_TYPE AS EMPL_TYPE,
    FULL_PART_TIME AS FULL_PART_TIME,
    REG_TEMP AS REG_TEMP,
    EMPL_STATUS AS EMPL_STATUS,
    PER_STATUS_CODE AS PER_STATUS_CODE,
    VENDOR_ID AS VENDOR_ID,
    VENDOR_NAME AS VENDOR_NAME,
    MANAGER_ID AS MANAGER_ID,
    MANAGER_NAME AS MANAGER_NAME,
    DPT_ID_PATH AS DPT_ID_PATH,
    DEPT_DESCR AS DEPT_DESCR,
    EMPLID AS EMPLID,
    NAME AS NAME,
    EMPL_STATUS_DESCR AS EMPL_STATUS_DESCR,
    LOCATION_DESCR AS LOCATION_DESCR,
    LOGON_ID AS LOGON_ID,
    POSITION_NBR AS POSITION_NBR,
    COSTCENTER AS COSTCENTER,
    WEEKLY_HOURS AS WEEKLY_HOURS,
    LOGON_DOMAIN AS LOGON_DOMAIN,
    PER_TYPE_DESCR AS PER_TYPE_DESCR,
    Loaded_date AS Loaded_date,
    JOB_LEVEL AS JOB_LEVEL,
    FTE AS FTE,
    JOB_REQUISITION_ID AS JOB_REQUISITION_ID,
    JOB_REQUISITION_STATUS AS JOB_REQUISITION_STATUS,
    HIRING_MANAGER AS HIRING_MANAGER,
    POSITION_STATUS AS POSITION_STATUS,
    COMPENSATION_GRADE_ID AS COMPENSATION_GRADE_ID,
    TARGET_HIRE_DATE AS TARGET_HIRE_DATE,
    RECRUITING_START_DATE AS RECRUITING_START_DATE,
    JOB_POSTING_TITLE AS JOB_POSTING_TITLE,
    MANAGEMENT_LEVEL AS MANAGEMENT_LEVEL,
    POSITION_TYPE AS POSITION_TYPE,
    DAYS_FROM_REC_DATE AS DAYS_FROM_REC_DATE,
    REPLACEMENT_FOR AS REPLACEMENT_FOR,
    POSITION_NAME AS POSITION_NAME,
    CATEGORY AS CATEGORY,
    VOL_INVOL AS VOL_INVOL,
    HIRE_DATE AS HIRE_DATE,
    POSITION_FILL_DATE AS POSITION_FILL_DATE,
    POSITION_WORKER_TYPE AS POSITION_WORKER_TYPE,
    SUPERVISORY_ORGANIZATION_NAME AS SUPERVISORY_ORGANIZATION_NAME,
    EXIT_REASON AS EXIT_REASON,
    EXIT_DETAILED_REASON AS EXIT_DETAILED_REASON,
    EXIT_DATE AS EXIT_DATE
  
  FROM Formula_226_0 AS in0

)

SELECT *

FROM AlteryxSelect_225
