---
version: 2
models:
- name: "143_common_workflows_Text_l_update_abbreviations__CReWOnlyUnique_16"
  tags:
  - "prophecy_temp"
- name: "143_common_workflows_Text_l_update_abbreviations__CReWOnlyUnique_16_count"
  tags:
  - "prophecy_temp"
- name: "143_common_workflows_Text_l_update_abbreviations__CReWOnlyUnique_16_reject"
  tags:
  - "prophecy_temp"
- name: "143_common_workflows_Text_l_update_abbreviations__Sort_15"
  tags:
  - "prophecy_temp"
- name: "143_common_workflows_Text_l_update_abbreviations__uuidified_abbre_8"
  tags:
  - "prophecy_temp"
