---
version: 2
sources:
- name: "transpiled_sources"
  database: "tanmay"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "intermediate_productos_1_AlteryxSelect_1098"
    columns:
    - name: "Col16"
      dataType:
        type: "String"
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col12"
      dataType:
        type: "String"
    - name: "Col9"
      dataType:
        type: "String"
    - name: "Col8"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col17"
      dataType:
        type: "String"
    - name: "Col10"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "Col18"
      dataType:
        type: "String"
    - name: "Col6"
      dataType:
        type: "String"
    - name: "Col13"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "Col11"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col14"
      dataType:
        type: "String"
    - name: "Col15"
      dataType:
        type: "String"
    - name: "Col7"
      dataType:
        type: "String"
    - name: "Col2"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_AlteryxSelect_1012"
    columns:
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col9"
      dataType:
        type: "String"
    - name: "Col8"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "Col6"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col7"
      dataType:
        type: "String"
    - name: "Col2"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1033"
    columns:
    - name: "nombre_especie_valor"
      dataType:
        type: "String"
    - name: "nombre_tipo_valor"
      dataType:
        type: "String"
    - name: "codigo_valor"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_AlteryxSelect_1210"
    columns:
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col12"
      dataType:
        type: "String"
    - name: "Col9"
      dataType:
        type: "String"
    - name: "Col8"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col10"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "Col6"
      dataType:
        type: "String"
    - name: "Col13"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "Col11"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col14"
      dataType:
        type: "String"
    - name: "Col7"
      dataType:
        type: "String"
    - name: "Col2"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1039"
    columns:
    - name: "idf_pers_ods"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_AlteryxSelect_994"
    columns:
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
  - name: "intermediate_productos_1_aka_Server_UYDB_1047"
    columns:
    - name: "aplicado_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "activa"
      dataType:
        type: "Boolean"
    - name: "disponible_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "descripcion_estado"
      dataType:
        type: "String"
    - name: "idf_pers_ods_garantizante"
      dataType:
        type: "String"
    - name: "fecha_vencimiento"
      dataType:
        type: "String"
    - name: "descripcion_corta"
      dataType:
        type: "String"
    - name: "numero_garantia"
      dataType:
        type: "String"
    - name: "fecha_alta"
      dataType:
        type: "String"
    - name: "descripcion_subestado"
      dataType:
        type: "String"
    - name: "limite_arbitrado_dolares"
      dataType:
        type: "Decimal"
  - name: "intermediate_productos_1_aka_Server_UYDB_1128"
    columns:
    - name: "numero_contrato"
      dataType:
        type: "String"
    - name: "saldo_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "codigo_subproducto"
      dataType:
        type: "String"
    - name: "subrubro_cuenta_contable"
      dataType:
        type: "String"
    - name: "codigo_agrupacion_contable"
      dataType:
        type: "String"
    - name: "rubro_cuenta_contable"
      dataType:
        type: "String"
    - name: "sector_cuenta_contable"
      dataType:
        type: "String"
    - name: "capitulo_cuenta_contable"
      dataType:
        type: "String"
    - name: "divisa"
      dataType:
        type: "String"
    - name: "codigo_destino"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "saldo_moneda_origen"
      dataType:
        type: "Decimal"
    - name: "codigo_producto"
      dataType:
        type: "String"
    - name: "descripcion_producto"
      dataType:
        type: "String"
    - name: "perimetro_gestion"
      dataType:
        type: "Double"
  - name: "intermediate_productos_1_AlteryxSelect_1025"
    columns:
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col2"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1034"
    columns:
    - name: "cantidad_empleados"
      dataType:
        type: "Double"
    - name: "codigo_plan"
      dataType:
        type: "String"
    - name: "sub_tipo_producto"
      dataType:
        type: "String"
    - name: "grupo_producto"
      dataType:
        type: "String"
    - name: "tipo_producto"
      dataType:
        type: "String"
    - name: "fecha_alta"
      dataType:
        type: "Date"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_AlteryxSelect_997"
    columns:
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col8"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "Col6"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col7"
      dataType:
        type: "String"
    - name: "Col2"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_AlteryxSelect_1288"
    columns:
    - name: "Col16"
      dataType:
        type: "String"
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col12"
      dataType:
        type: "String"
    - name: "Col9"
      dataType:
        type: "String"
    - name: "Col8"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col17"
      dataType:
        type: "String"
    - name: "Col10"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "Col18"
      dataType:
        type: "String"
    - name: "Col6"
      dataType:
        type: "String"
    - name: "Col13"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "Col11"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col14"
      dataType:
        type: "String"
    - name: "Col15"
      dataType:
        type: "String"
    - name: "Col7"
      dataType:
        type: "String"
    - name: "Col2"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1038"
    columns:
    - name: "idf_pers_ods_pagador"
      dataType:
        type: "String"
    - name: "idf_pers_ods_cobrador"
      dataType:
        type: "String"
    - name: "importe_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "AAAAMM"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1035"
    columns:
    - name: "cargo_cuenta_pesos"
      dataType:
        type: "String"
    - name: "cantidad_de_pagos"
      dataType:
        type: "Integer"
    - name: "cargo_cuenta_dolares"
      dataType:
        type: "String"
    - name: "tipo_servicio"
      dataType:
        type: "String"
    - name: "esta_activo"
      dataType:
        type: "Boolean"
    - name: "fecha_alta"
      dataType:
        type: "Date"
    - name: "numero_referencia"
      dataType:
        type: "String"
    - name: "nombre_proveedor"
      dataType:
        type: "String"
    - name: "importe_abonado_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "servicio"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1048"
    columns:
    - name: "numero_persona"
      dataType:
        type: "String"
    - name: "numero_secuencial_cliente"
      dataType:
        type: "Integer"
    - name: "codigo_relacion"
      dataType:
        type: "Integer"
    - name: "numero_garantia"
      dataType:
        type: "Integer"
    - name: "idf_pers_ods_garantizado"
      dataType:
        type: "String"
    - name: "AAAAMM"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1044"
    columns:
    - name: "sobregiro_no_autorizado_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "numero_contrato"
      dataType:
        type: "String"
    - name: "codigo_sucursal_operacion"
      dataType:
        type: "String"
    - name: "sobregiro_autorizado_moneda_origen"
      dataType:
        type: "Decimal"
    - name: "sobregiro_no_autorizado_moneda_origen"
      dataType:
        type: "Decimal"
    - name: "fecha_dato"
      dataType:
        type: "Date"
    - name: "acuerdo_sobregiro_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "acuerdo_sobregiro_moneda_origen"
      dataType:
        type: "Decimal"
    - name: "sobregiro_autorizado_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "fecha_vencimiento_linea"
      dataType:
        type: "Date"
    - name: "divisa"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "sobregiro_disponible_moneda_origen"
      dataType:
        type: "Decimal"
    - name: "sobregiro_disponible_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "AAAAMM"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_AlteryxSelect_991"
    columns:
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col9"
      dataType:
        type: "String"
    - name: "Col8"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "Col6"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col7"
      dataType:
        type: "String"
    - name: "Col2"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1032"
    columns:
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "codigo_valor"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1116"
    columns:
    - name: "tipo_producto_comercial"
      dataType:
        type: "String"
    - name: "codigo_subproducto"
      dataType:
        type: "String"
    - name: "familia_producto_comercial"
      dataType:
        type: "String"
    - name: "codigo_destino"
      dataType:
        type: "String"
    - name: "descripcion_crm"
      dataType:
        type: "String"
    - name: "codigo_producto"
      dataType:
        type: "String"
    - name: "sub_tipo_producto_comercial"
      dataType:
        type: "String"
    - name: "grupo_producto_comercial"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_AlteryxSelect_1241"
    columns:
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col2"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1045"
    columns:
    - name: "numero_contrato"
      dataType:
        type: "String"
    - name: "pan_completo"
      dataType:
        type: "String"
    - name: "pan_hash"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_aka_Server_UYDB_1042"
    columns:
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "saldo_arbitrado_dolares"
      dataType:
        type: "Decimal"
  - name: "intermediate_productos_1_aka_Server_UYDB_1040"
    columns:
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "motivo_cancelacion"
      dataType:
        type: "String"
    - name: "fecha_cancelacion"
      dataType:
        type: "Date"
    - name: "fecha_cierre"
      dataType:
        type: "Date"
  - name: "intermediate_productos_1_aka_Server_UYDB_1037"
    columns:
    - name: "pan_hash"
      dataType:
        type: "String"
    - name: "tipo_transaccion"
      dataType:
        type: "String"
    - name: "monto_arbitrado_dolares"
      dataType:
        type: "Decimal"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "AAAAMM"
      dataType:
        type: "String"
  - name: "intermediate_productos_1_Formula_1161"
    columns:
    - name: "Col16"
      dataType:
        type: "String"
    - name: "Col4"
      dataType:
        type: "String"
    - name: "Col12"
      dataType:
        type: "String"
    - name: "Col9"
      dataType:
        type: "String"
    - name: "Col8"
      dataType:
        type: "String"
    - name: "Col1"
      dataType:
        type: "String"
    - name: "Col3"
      dataType:
        type: "String"
    - name: "Col17"
      dataType:
        type: "String"
    - name: "Col10"
      dataType:
        type: "String"
    - name: "Col5"
      dataType:
        type: "String"
    - name: "Col18"
      dataType:
        type: "String"
    - name: "Col6"
      dataType:
        type: "String"
    - name: "Col13"
      dataType:
        type: "String"
    - name: "idf_pers_ods"
      dataType:
        type: "String"
    - name: "Col11"
      dataType:
        type: "String"
    - name: "CodProducto"
      dataType:
        type: "Integer"
    - name: "Col14"
      dataType:
        type: "String"
    - name: "Col15"
      dataType:
        type: "String"
    - name: "Col7"
      dataType:
        type: "String"
    - name: "Col2"
      dataType:
        type: "String"
