---
version: 2
models:
- name: "32_2022_main__Cleanse_119"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Cleanse_126"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Cleanse_51"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Cleanse_52"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Cleanse_55"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Filter_62"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Formula_117_2"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Formula_21_2"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Formula_39_0"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Join_101_inner"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__MultiRowFormula_70_row_id_drop_0"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Sort_46"
  tags:
  - "prophecy_temp"
- name: "32_2022_main__Summarize_53"
  tags:
  - "prophecy_temp"
