{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_WORK_CARDS_ORIG_STAGING_EXPR_19 AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_credit_application_update__EXP_WORK_CARDS_ORIG_STAGING_EXPR_19')}}

),

RTR_CREDIT_APPLICATION_out0 AS (

  SELECT * 
  
  FROM EXP_WORK_CARDS_ORIG_STAGING_EXPR_19 AS in0
  
  WHERE (
          (ACCID_TGT IS NOT NULL)
          AND (
                (
                  CASE
                    WHEN ((DATE_DIFF(CAST(EFROM_TGT AS DATE), CAST(BUSINESS_DATE AS DATE), DAY)) > 0)
                      THEN 1
                    WHEN ((DATE_DIFF(CAST(EFROM_TGT AS DATE), CAST(BUSINESS_DATE AS DATE), DAY)) < 0)
                      THEN -1
                    ELSE (DATE_DIFF(CAST(EFROM_TGT AS DATE), CAST(BUSINESS_DATE AS DATE), DAY))
                  END
                ) <> 0
              )
        )

),

RTR_CREDIT_APPLICATION_EXPR_OTHER_DAY_GROUP AS (

  SELECT 
    ACCID_TGT AS ACCID_TGT1,
    ACCID_SRC AS ACCID_SRC1,
    EFROM_TGT AS EFROM_TGT1,
    BUSINESS_DATE AS BUSINESS_DATE1,
    BUSINESS_DATE_MINUS_1 AS BUSINESS_DATE_MINUS_11,
    INITIAL_DECISION_2 AS INITIAL_DECISION_21,
    INITIAL_DECISION_3 AS INITIAL_DECISION_31,
    INITIAL_DECISION_4 AS INITIAL_DECISION_41,
    INITIAL_DECISION_5 AS INITIAL_DECISION_51,
    INITIAL_DECISION_6 AS INITIAL_DECISION_61,
    APPLICATION_DATE AS APPLICATION_DATE1,
    ACCOUNT_NUMBER AS ACCOUNT_NUMBER1,
    PRODUCT AS PRODUCT1,
    APPLICATION_SOURCE_CODE AS APPLICATION_SOURCE_CODE1,
    APPLICATION_SCORE AS APPLICATION_SCORE1,
    CIISCORE AS CIISCORE1,
    DELPHI_SCORE AS DELPHI_SCORE1,
    FIRST_PARTY_FRAUD_SCORE AS FIRST_PARTY_FRAUD_SCORE1,
    CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE AS CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE1,
    LAST_ACTION_DATE1 AS LAST_ACTION_DATE11,
    APPLICATION_STORE_NUMBER AS APPLICATION_STORE_NUMBER1,
    ANNUAL_INCOME_AMOUNT AS ANNUAL_INCOME_AMOUNT1,
    ANNUAL_HOUSEHOLD_INCOME AS ANNUAL_HOUSEHOLD_INCOME1,
    APPLICATION_TYPE AS APPLICATION_TYPE1,
    OFFER_ID AS OFFER_ID1,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER1,
    CUSTOMER_ROLE AS CUSTOMER_ROLE1,
    EMPLOYMENT_STATUS AS EMPLOYMENT_STATUS1,
    MARITAL_STATUS AS MARITAL_STATUS1,
    NUMBER_OF_CHILDREN AS NUMBER_OF_CHILDREN1,
    RESIDENTIAL_STATUS AS RESIDENTIAL_STATUS1,
    OCCUPATION AS OCCUPATION1,
    PRODUCT_NUMBER AS PRODUCT_NUMBER1,
    OFFERED_LIMIT_AMOUNT AS OFFERED_LIMIT_AMOUNT1,
    CREDIT_REQUESTED_AMOUNT AS CREDIT_REQUESTED_AMOUNT1,
    EMAIL AS EMAIL1,
    CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER AS CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER1,
    CHANNEL_PREFERENCE_INDICATOR AS CHANNEL_PREFERENCE_INDICATOR1,
    DATE_OF_BIRTH AS DATE_OF_BIRTH1,
    POSTCODE AS POSTCODE1,
    INITIAL_DECISION_COARSE_SRC AS INITIAL_DECISION_COARSE_SRC1,
    INITIAL_DECISION_PRIMARY_SRC AS INITIAL_DECISION_PRIMARY_SRC1,
    INITIAL_DECISION_COARSE_TGT AS INITIAL_DECISION_COARSE_TGT1,
    INITIAL_DECISION_PRIMARY_TGT AS INITIAL_DECISION_PRIMARY_TGT1,
    o_FINAL_DECISION_COARSE AS o_FINAL_DECISION_COARSE1,
    o_FINAL_DECISION_PRIMARY AS o_FINAL_DECISION_PRIMARY1,
    LAST_ACTION_DATE AS LAST_ACTION_DATE2,
    o_LAST_ACTION_DATE AS o_LAST_ACTION_DATE1,
    FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES AS FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES1,
    o_TIME_STAMP_OF_ACTION AS o_TIME_STAMP_OF_ACTION1,
    o_RESIDENTIAL_MOVED_IN_DATE AS o_RESIDENTIAL_MOVED_IN_DATE1,
    o_TIME_AT_PREVIOUS_ADDRESS AS o_TIME_AT_PREVIOUS_ADDRESS1,
    o_EMPLOYMENT_MAIN_STARTDATE AS o_EMPLOYMENT_MAIN_STARTDATE1,
    CARD_ORIGIN AS CARD_ORIGIN1,
    ACCID_TGT AS ACCID,
    EFROM_TGT AS EFROM,
    BUSINESS_DATE_MINUS_1 AS ETO
  
  FROM RTR_CREDIT_APPLICATION_out0 AS in0

)

SELECT *

FROM RTR_CREDIT_APPLICATION_EXPR_OTHER_DAY_GROUP
