---
version: 2
models:
- name: "m_rep_cards_orig_credit_application_update__CLOSE_CREDIT_APPLICATION"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_credit_application_update__EXP_WORK_CARDS_ORIG_STAGING_EXPR_19"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_credit_application_update__EXP_WORK_CARDS_ORIG_STAGING_VARS_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_credit_application_update__INS_NEW_CREDIT_APPLICATION"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_credit_application_update__OPEN_CREDIT_APPLICATION"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_credit_application_update__RTR_CREDIT_APPLICATION_EXPR_OTHER_DAY_GROUP"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_credit_application_update__UPD_CREDIT_APPLICATION"
  tags:
  - "prophecy_temp"
