---
version: 2
models:
- name: "Cuadre_Fidessa__AlteryxSelect_42"
  tags:
  - "prophecy_temp"
- name: "Cuadre_Fidessa__AppendFields_82"
  tags:
  - "prophecy_temp"
- name: "Cuadre_Fidessa__AppendFields_85"
  tags:
  - "prophecy_temp"
- name: "Cuadre_Fidessa__AppendFields_89"
  tags:
  - "prophecy_temp"
- name: "Cuadre_Fidessa__Formula_46_0"
  tags:
  - "prophecy_temp"
