---
version: 2
models:
- name: "challenge_239_solution__AlteryxSelect_61"
  tags:
  - "prophecy_temp"
- name: "challenge_239_solution__GenerateRows_43_createRow"
  tags:
  - "prophecy_temp"
- name: "challenge_239_solution__GenerateRows_43_dropSeq_0"
  tags:
  - "prophecy_temp"
- name: "challenge_239_solution__Join_57_inner"
  tags:
  - "prophecy_temp"
- name: "challenge_239_solution__RecordID_52"
  tags:
  - "prophecy_temp"
- name: "challenge_239_solution__Summarize_56"
  tags:
  - "prophecy_temp"
- name: "challenge_239_solution__TextInput_42_cast"
  tags:
  - "prophecy_temp"
