{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH DynamicInput_164 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'DynamicInput_164') }}

),

Cleanse_108 AS (

  {{
    prophecy_basics.DataCleansing(
      ['DynamicInput_164'], 
      [
        { "name": "STANDARDCOST", "dataType": "String" }, 
        { "name": "STANDARDPLATINGCOST", "dataType": "String" }, 
        { "name": "CUSTOMERSUPPLIED", "dataType": "String" }, 
        { "name": "LABORCOST", "dataType": "String" }, 
        { "name": "STANDARDLABORCOST", "dataType": "String" }, 
        { "name": "PLATINGCOST", "dataType": "String" }, 
        { "name": "UNITCOST", "dataType": "String" }, 
        { "name": "ORDERPOLICY", "dataType": "String" }, 
        { "name": "PLANNERCODE", "dataType": "String" }, 
        { "name": "BUYER", "dataType": "String" }, 
        { "name": "PARTNUMBER", "dataType": "String" }
      ], 
      'keepOriginal', 
      [
        'PARTNUMBER', 
        'UNITCOST', 
        'LABORCOST', 
        'PLATINGCOST', 
        'PLANNERCODE', 
        'BUYER', 
        'ORDERPOLICY', 
        'CUSTOMERSUPPLIED'
      ], 
      true, 
      '', 
      true, 
      0, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

AlteryxSelect_109 AS (

  SELECT 
    PARTNUMBER AS PARTNUMBER,
    UNITCOST AS UNITCOST,
    LABORCOST AS LABORCOST,
    PLATINGCOST AS PLATINGCOST,
    PLANNERCODE AS PLANNERCODE,
    BUYER AS BUYER,
    ORDERPOLICY AS ORDERPOLICY,
    CUSTOMERSUPPLIED AS CUSTOMERSUPPLIED,
    STANDARDCOST AS STANDARDCOST,
    STANDARDLABORCOST AS STANDARDLABORCOST,
    STANDARDPLATINGCOST AS STANDARDPLATINGCOST
  
  FROM Cleanse_108 AS in0

),

AlteryxSelect_113 AS (

  SELECT 
    UNITCOST AS PREVIOUSQUARTERUNITCOST,
    LABORCOST AS PREVIOUSQUARTERLABORCOST,
    PLATINGCOST AS PREVIOUSQUARTERPLATINGCOST,
    PLANNERCODE AS PREVIOUSQUARTERPLANNERCODE,
    BUYER AS PREVIOUSQUARTERBUYER,
    ORDERPOLICY AS PREVIOUSQUARTERORDERPOLICY,
    CUSTOMERSUPPLIED AS PREVIOUSQUARTERCUSTOMERSUPPLIED,
    STANDARDCOST AS PREVIOUSQUARTERSTANDARDUNITCOST,
    STANDARDLABORCOST AS PREVIOUSQUARTERSTANDARDLABORCOST,
    STANDARDPLATINGCOST AS PREVIOUSQUARTERSTANDARDPLATINGCOST,
    * EXCLUDE ("UNITCOST", 
    "LABORCOST", 
    "PLATINGCOST", 
    "PLANNERCODE", 
    "BUYER", 
    "ORDERPOLICY", 
    "CUSTOMERSUPPLIED", 
    "STANDARDCOST", 
    "STANDARDLABORCOST", 
    "STANDARDPLATINGCOST")
  
  FROM AlteryxSelect_109 AS in0

),

AlteryxSelect_23 AS (

  SELECT *
  
  FROM {{ ref('perpetual_inventory__AlteryxSelect_23')}}

),

DynamicInput_33 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'DynamicInput_33') }}

),

Join_36_inner AS (

  SELECT 
    in0.*,
    in1.* EXCLUDE ("FACILITY")
  
  FROM DynamicInput_33 AS in0
  INNER JOIN AlteryxSelect_23 AS in1
     ON (in0.FACILITY = in1.FACILITY)

),

Formula_39_0 AS (

  SELECT 
    CAST((((WAREHOUSEONHANDBALANCE + BENTECONHANDBALANCE) + WIPONHANDBALANCE) + CONSIGNEDONHANDBALANCE) AS INTEGER) AS CLOSINGBALANCE,
    *
  
  FROM Join_36_inner AS in0

),

AlteryxSelect_34 AS (

  SELECT 
    FACILITY AS FACILITY,
    PLANT AS PLANT,
    PARTNUMBER AS PARTNUMBER,
    CLOSINGBALANCE AS CLOSINGBALANCE
  
  FROM Formula_39_0 AS in0

),

Summarize_158 AS (

  SELECT 
    SUM(CLOSINGBALANCE) AS CLOSINGBALANCE,
    FACILITY AS FACILITY,
    PLANT AS PLANT,
    PARTNUMBER AS PARTNUMBER
  
  FROM AlteryxSelect_34 AS in0
  
  GROUP BY 
    FACILITY, PLANT, PARTNUMBER

),

DSN_r2s_prod_ed_181 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'DSN_r2s_prod_ed_181') }}

),

AlteryxSelect_182 AS (

  SELECT 
    PART_NUMBER AS PARTNUMBER,
    REPORTING_SERIES AS REPORTINGSERIES,
    REPORTING_SERIES_ERA AS REPORTINGSERIESPRODUCTERA,
    REPORTING_SERIES_WEAVE AS REPORTINGSERIESPRODUCTWEAVE,
    REPORTING_SERIES_BLOCK AS REPORTINGSERIESPRODUCTSOLUTIONBLOCK,
    REPORTING_SERIES_SEGMENT AS REPORTINGSERIESPRODUCTSEGMENT,
    DM_ITEM_TYPE AS ITEMTYPE,
    PCMFG_ITEM_TYPE AS PCMFGITEMTYPE
  
  FROM DSN_r2s_prod_ed_181 AS in0

),

AccountingTrans_82 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'AccountingTrans_82') }}

),

CrossTab_81_rename AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'CrossTab_81_rename') }}

),

AlteryxSelect_85 AS (

  SELECT 
    FACILITY AS FACILITY,
    PLANT AS PLANT,
    PARTNUMBER AS PARTNUMBER,
    CAST(NULL AS string) AS PURCHASED,
    CAST(NULL AS string) AS PRODUCED,
    CAST(NULL AS string) AS SOLD,
    CAST(NULL AS string) AS ISSUED,
    CAST(NULL AS string) AS ADJUSTED,
    CAST(NULL AS string) AS TRANSFERREDIN,
    CAST(NULL AS string) AS TRANSFERREDOUT
  
  FROM CrossTab_81_rename AS in0

),

Union_83 AS (

  {{
    prophecy_basics.UnionByName(
      ['AccountingTrans_82', 'AlteryxSelect_85'], 
      [
        '[{"name": "ISSUED", "dataType": "Number"}, {"name": "PRODUCED", "dataType": "Number"}, {"name": "ADJUSTED", "dataType": "Number"}, {"name": "PARTNUMBER", "dataType": "String"}, {"name": "TRANSFERREDIN", "dataType": "Number"}, {"name": "TRANSFERREDOUT", "dataType": "Number"}, {"name": "SOLD", "dataType": "Number"}, {"name": "PURCHASED", "dataType": "Number"}]', 
        '[{"name": "FACILITY", "dataType": "String"}, {"name": "PLANT", "dataType": "String"}, {"name": "PARTNUMBER", "dataType": "String"}, {"name": "PURCHASED", "dataType": "String"}, {"name": "PRODUCED", "dataType": "String"}, {"name": "SOLD", "dataType": "String"}, {"name": "ISSUED", "dataType": "String"}, {"name": "ADJUSTED", "dataType": "String"}, {"name": "TRANSFERREDIN", "dataType": "String"}, {"name": "TRANSFERREDOUT", "dataType": "String"}]'
      ], 
      'allowMissingColumns'
    )
  }}

),

AlteryxSelect_86 AS (

  SELECT 
    FACILITY AS FACILITY,
    PLANT AS PLANT,
    PARTNUMBER AS PARTNUMBER,
    PURCHASED AS PURCHASED,
    PRODUCED AS PRODUCED,
    SOLD AS SOLD,
    ISSUED AS ISSUED,
    ADJUSTED AS ADJUSTED,
    TRANSFERREDIN AS TRANSFERREDIN,
    TRANSFERREDOUT AS TRANSFERREDOUT
  
  FROM Union_83 AS in0

),

Cleanse_84 AS (

  {{
    prophecy_basics.DataCleansing(
      ['AlteryxSelect_86'], 
      [
        { "name": "FACILITY", "dataType": "String" }, 
        { "name": "PLANT", "dataType": "String" }, 
        { "name": "PARTNUMBER", "dataType": "String" }, 
        { "name": "PURCHASED", "dataType": "Number" }, 
        { "name": "PRODUCED", "dataType": "Number" }, 
        { "name": "SOLD", "dataType": "Number" }, 
        { "name": "ISSUED", "dataType": "Number" }, 
        { "name": "ADJUSTED", "dataType": "Number" }, 
        { "name": "TRANSFERREDIN", "dataType": "Number" }, 
        { "name": "TRANSFERREDOUT", "dataType": "Number" }
      ], 
      'keepOriginal', 
      ['PURCHASED', 'PRODUCED', 'SOLD', 'ISSUED', 'ADJUSTED', 'TRANSFERREDIN', 'TRANSFERREDOUT'], 
      true, 
      '', 
      true, 
      0, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

DynamicInput_28 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'DynamicInput_28') }}

),

Join_31_inner AS (

  SELECT 
    in0.*,
    in1.* EXCLUDE ("FACILITY")
  
  FROM DynamicInput_28 AS in0
  INNER JOIN AlteryxSelect_23 AS in1
     ON (in0.FACILITY = in1.FACILITY)

),

Formula_38_0 AS (

  SELECT 
    CAST((((WAREHOUSEONHANDBALANCE + BENTECONHANDBALANCE) + WIPONHANDBALANCE) + CONSIGNEDONHANDBALANCE) AS INTEGER) AS OPENINGBALANCE,
    *
  
  FROM Join_31_inner AS in0

),

AlteryxSelect_29 AS (

  SELECT 
    FACILITY AS FACILITY,
    PLANT AS PLANT,
    PARTNUMBER AS PARTNUMBER,
    OPENINGBALANCE AS OPENINGBALANCE
  
  FROM Formula_38_0 AS in0

),

Summarize_157 AS (

  SELECT 
    SUM(OPENINGBALANCE) AS OPENINGBALANCE,
    FACILITY AS FACILITY,
    PLANT AS PLANT,
    PARTNUMBER AS PARTNUMBER
  
  FROM AlteryxSelect_29 AS in0
  
  GROUP BY 
    FACILITY, PLANT, PARTNUMBER

),

Join_43_left_UnionFullOuter AS (

  SELECT 
    in0.OPENINGBALANCE AS OPENINGBALANCE,
    in1.CLOSINGBALANCE AS CLOSINGBALANCE,
    (
      CASE
        WHEN (((in0.FACILITY = in1.FACILITY) AND (in0.PLANT = in1.PLANT)) AND (in0.PARTNUMBER = in1.PARTNUMBER))
          THEN NULL
        ELSE in1.PLANT
      END
    ) AS PLANT,
    (
      CASE
        WHEN (((in0.FACILITY = in1.FACILITY) AND (in0.PLANT = in1.PLANT)) AND (in0.PARTNUMBER = in1.PARTNUMBER))
          THEN NULL
        ELSE in1.PARTNUMBER
      END
    ) AS PARTNUMBER,
    (
      CASE
        WHEN (((in0.FACILITY = in1.FACILITY) AND (in0.PLANT = in1.PLANT)) AND (in0.PARTNUMBER = in1.PARTNUMBER))
          THEN NULL
        ELSE in1.FACILITY
      END
    ) AS FACILITY,
    in0.* EXCLUDE ("OPENINGBALANCE", "PLANT", "PARTNUMBER", "FACILITY"),
    in1.* EXCLUDE ("CLOSINGBALANCE", "FACILITY", "PLANT", "PARTNUMBER")
  
  FROM Summarize_157 AS in0
  FULL JOIN Summarize_158 AS in1
     ON (((in0.FACILITY = in1.FACILITY) AND (in0.PLANT = in1.PLANT)) AND (in0.PARTNUMBER = in1.PARTNUMBER))

),

Join_87_left_UnionFullOuter AS (

  SELECT 
    in0.OPENINGBALANCE AS OPENINGBALANCE,
    in0.CLOSINGBALANCE AS CLOSINGBALANCE,
    in1.PURCHASED AS PURCHASED,
    in1.PRODUCED AS PRODUCED,
    in1.SOLD AS SOLD,
    in1.ISSUED AS ISSUED,
    in1.ADJUSTED AS ADJUSTED,
    in1.TRANSFERREDIN AS TRANSFERREDIN,
    in1.TRANSFERREDOUT AS TRANSFERREDOUT,
    (
      CASE
        WHEN (((in0.FACILITY = in1.FACILITY) AND (in0.PLANT = in1.PLANT)) AND (in0.PARTNUMBER = in1.PARTNUMBER))
          THEN NULL
        ELSE in1.PLANT
      END
    ) AS PLANT,
    (
      CASE
        WHEN (((in0.FACILITY = in1.FACILITY) AND (in0.PLANT = in1.PLANT)) AND (in0.PARTNUMBER = in1.PARTNUMBER))
          THEN NULL
        ELSE in1.PARTNUMBER
      END
    ) AS PARTNUMBER,
    (
      CASE
        WHEN (((in0.FACILITY = in1.FACILITY) AND (in0.PLANT = in1.PLANT)) AND (in0.PARTNUMBER = in1.PARTNUMBER))
          THEN NULL
        ELSE in1.FACILITY
      END
    ) AS FACILITY,
    in0.* EXCLUDE ("OPENINGBALANCE", "CLOSINGBALANCE", "PLANT", "PARTNUMBER", "FACILITY"),
    in1.* EXCLUDE ("PURCHASED", 
    "PRODUCED", 
    "SOLD", 
    "ISSUED", 
    "ADJUSTED", 
    "TRANSFERREDIN", 
    "TRANSFERREDOUT", 
    "FACILITY", 
    "PLANT", 
    "PARTNUMBER")
  
  FROM Join_43_left_UnionFullOuter AS in0
  FULL JOIN Cleanse_84 AS in1
     ON (((in0.FACILITY = in1.FACILITY) AND (in0.PLANT = in1.PLANT)) AND (in0.PARTNUMBER = in1.PARTNUMBER))

),

AlteryxSelect_90 AS (

  SELECT 
    FACILITY AS FACILITY,
    PLANT AS PLANT,
    PARTNUMBER AS PARTNUMBER,
    OPENINGBALANCE AS OPENINGBALANCE,
    PURCHASED AS PURCHASED,
    PRODUCED AS PRODUCED,
    SOLD AS SOLD,
    ISSUED AS ISSUED,
    ADJUSTED AS ADJUSTED,
    TRANSFERREDIN AS TRANSFERREDIN,
    TRANSFERREDOUT AS TRANSFERREDOUT,
    CLOSINGBALANCE AS CLOSINGBALANCE
  
  FROM Join_87_left_UnionFullOuter AS in0

),

Cleanse_94 AS (

  {{
    prophecy_basics.DataCleansing(
      ['AlteryxSelect_90'], 
      [
        { "name": "FACILITY", "dataType": "String" }, 
        { "name": "PLANT", "dataType": "String" }, 
        { "name": "PARTNUMBER", "dataType": "String" }, 
        { "name": "OPENINGBALANCE", "dataType": "Number" }, 
        { "name": "PURCHASED", "dataType": "Number" }, 
        { "name": "PRODUCED", "dataType": "Number" }, 
        { "name": "SOLD", "dataType": "Number" }, 
        { "name": "ISSUED", "dataType": "Number" }, 
        { "name": "ADJUSTED", "dataType": "Number" }, 
        { "name": "TRANSFERREDIN", "dataType": "Number" }, 
        { "name": "TRANSFERREDOUT", "dataType": "Number" }, 
        { "name": "CLOSINGBALANCE", "dataType": "Number" }
      ], 
      'keepOriginal', 
      [
        'OPENINGBALANCE', 
        'PURCHASED', 
        'PRODUCED', 
        'SOLD', 
        'ISSUED', 
        'ADJUSTED', 
        'TRANSFERREDIN', 
        'TRANSFERREDOUT', 
        'CLOSINGBALANCE'
      ], 
      true, 
      '', 
      true, 
      0, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

Formula_91_0 AS (

  SELECT 
    CAST((
      ((((((OPENINGBALANCE + PURCHASED) + PRODUCED) + SOLD) + ISSUED) + ADJUSTED) + TRANSFERREDIN)
      + TRANSFERREDOUT
    ) AS INTEGER) AS TRANSACTEDCLOSINGBALANCE,
    *
  
  FROM Cleanse_94 AS in0

),

Formula_91_1 AS (

  SELECT 
    (ABS((TRANSACTEDCLOSINGBALANCE - CLOSINGBALANCE)) <= 1) AS RECONCILES,
    CAST((TRANSACTEDCLOSINGBALANCE - CLOSINGBALANCE) AS INTEGER) AS DISCREPANCY,
    *
  
  FROM Formula_91_0 AS in0

),

DynamicInput_159 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'DynamicInput_159') }}

),

Cleanse_100 AS (

  {{
    prophecy_basics.DataCleansing(
      ['DynamicInput_159'], 
      [
        { "name": "STANDARDCOST", "dataType": "String" }, 
        { "name": "STANDARDPLATINGCOST", "dataType": "String" }, 
        { "name": "CUSTOMERSUPPLIED", "dataType": "String" }, 
        { "name": "LABORCOST", "dataType": "String" }, 
        { "name": "STANDARDLABORCOST", "dataType": "String" }, 
        { "name": "PLATINGCOST", "dataType": "String" }, 
        { "name": "UNITCOST", "dataType": "String" }, 
        { "name": "ORDERPOLICY", "dataType": "String" }, 
        { "name": "PLANNERCODE", "dataType": "String" }, 
        { "name": "BUYER", "dataType": "String" }, 
        { "name": "PARTNUMBER", "dataType": "String" }
      ], 
      'keepOriginal', 
      [
        'PARTNUMBER', 
        'UNITCOST', 
        'LABORCOST', 
        'PLATINGCOST', 
        'PLANNERCODE', 
        'BUYER', 
        'ORDERPOLICY', 
        'CUSTOMERSUPPLIED'
      ], 
      true, 
      '', 
      true, 
      0, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

AccountingTrans_70 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'AccountingTrans_70') }}

),

AlteryxSelect_72 AS (

  SELECT 
    PLANNERCODE AS PLANNERCODE,
    ACCOUNTINGPLANNERCODE AS ACCOUNTINGPLANNERCODE,
    * EXCLUDE ("PLANNERCODE", "ACCOUNTINGPLANNERCODE")
  
  FROM AccountingTrans_70 AS in0

),

DynamicInput_161 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('perpetual_inventory', 'DynamicInput_161') }}

),

Cleanse_104 AS (

  {{
    prophecy_basics.DataCleansing(
      ['DynamicInput_161'], 
      [
        { "name": "STANDARDCOST", "dataType": "String" }, 
        { "name": "STANDARDPLATINGCOST", "dataType": "String" }, 
        { "name": "CUSTOMERSUPPLIED", "dataType": "String" }, 
        { "name": "LABORCOST", "dataType": "String" }, 
        { "name": "STANDARDLABORCOST", "dataType": "String" }, 
        { "name": "PLATINGCOST", "dataType": "String" }, 
        { "name": "UNITCOST", "dataType": "String" }, 
        { "name": "ORDERPOLICY", "dataType": "String" }, 
        { "name": "PLANNERCODE", "dataType": "String" }, 
        { "name": "BUYER", "dataType": "String" }, 
        { "name": "PARTNUMBER", "dataType": "String" }
      ], 
      'keepOriginal', 
      [
        'PARTNUMBER', 
        'UNITCOST', 
        'LABORCOST', 
        'PLATINGCOST', 
        'PLANNERCODE', 
        'BUYER', 
        'ORDERPOLICY', 
        'CUSTOMERSUPPLIED'
      ], 
      true, 
      '', 
      true, 
      0, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

AlteryxSelect_105 AS (

  SELECT 
    PARTNUMBER AS PARTNUMBER,
    UNITCOST AS UNITCOST,
    LABORCOST AS LABORCOST,
    PLATINGCOST AS PLATINGCOST,
    PLANNERCODE AS PLANNERCODE,
    BUYER AS BUYER,
    ORDERPOLICY AS ORDERPOLICY,
    CUSTOMERSUPPLIED AS CUSTOMERSUPPLIED,
    STANDARDCOST AS STANDARDCOST,
    STANDARDLABORCOST AS STANDARDLABORCOST,
    STANDARDPLATINGCOST AS STANDARDPLATINGCOST
  
  FROM Cleanse_104 AS in0

),

AlteryxSelect_112 AS (

  SELECT 
    UNITCOST AS CLOSINGUNITCOST,
    LABORCOST AS CLOSINGLABORCOST,
    PLATINGCOST AS CLOSTINGPLATINGCOST,
    PLANNERCODE AS CLOSINGPLANNERCODE,
    BUYER AS CLOSINGBUYER,
    ORDERPOLICY AS CLOSINGORDERPOLICY,
    CUSTOMERSUPPLIED AS CLOSINGCUSTOMERSUPPLIED,
    STANDARDCOST AS CLOSINGSTANDARDUNITCOST,
    STANDARDLABORCOST AS CLOSINGSTANDARDLABORCOST,
    STANDARDPLATINGCOST AS CLOSINGSTANDARDPLATINGCOST,
    * EXCLUDE ("UNITCOST", 
    "LABORCOST", 
    "PLATINGCOST", 
    "PLANNERCODE", 
    "BUYER", 
    "ORDERPOLICY", 
    "CUSTOMERSUPPLIED", 
    "STANDARDCOST", 
    "STANDARDLABORCOST", 
    "STANDARDPLATINGCOST")
  
  FROM AlteryxSelect_105 AS in0

),

AlteryxSelect_101 AS (

  SELECT 
    PARTNUMBER AS PARTNUMBER,
    UNITCOST AS UNITCOST,
    LABORCOST AS LABORCOST,
    PLATINGCOST AS PLATINGCOST,
    PLANNERCODE AS PLANNERCODE,
    BUYER AS BUYER,
    ORDERPOLICY AS ORDERPOLICY,
    CUSTOMERSUPPLIED AS CUSTOMERSUPPLIED,
    STANDARDCOST AS STANDARDCOST,
    STANDARDLABORCOST AS STANDARDLABORCOST,
    STANDARDPLATINGCOST AS STANDARDPLATINGCOST
  
  FROM Cleanse_100 AS in0

),

AlteryxSelect_111 AS (

  SELECT 
    UNITCOST AS OPENINGUNITCOST,
    LABORCOST AS OPENINGLABORCOST,
    PLATINGCOST AS OPENINGPLATINGCOST,
    PLANNERCODE AS OPENINGPLANNERCODE,
    BUYER AS OPENINGBUYER,
    ORDERPOLICY AS OPENINGORDERPOLICY,
    CUSTOMERSUPPLIED AS OPENINGCUSTOMERSUPPLIED,
    STANDARDCOST AS OPENINGSTANDARDUNITCOST,
    STANDARDLABORCOST AS OPENINGSTANDARDLABORCOST,
    STANDARDPLATINGCOST AS OPENINGSTANDARDPLATINGCOST,
    * EXCLUDE ("UNITCOST", 
    "LABORCOST", 
    "PLATINGCOST", 
    "PLANNERCODE", 
    "BUYER", 
    "ORDERPOLICY", 
    "CUSTOMERSUPPLIED", 
    "STANDARDCOST", 
    "STANDARDLABORCOST", 
    "STANDARDPLATINGCOST")
  
  FROM AlteryxSelect_101 AS in0

),

Join_114_left_UnionFullOuter AS (

  SELECT 
    in0.OPENINGUNITCOST AS OPENINGUNITCOST,
    in0.OPENINGLABORCOST AS OPENINGLABORCOST,
    in0.OPENINGPLANNERCODE AS OPENINGPLANNERCODE,
    in1.CLOSINGUNITCOST AS CLOSINGUNITCOST,
    in1.CLOSINGLABORCOST AS CLOSINGLABORCOST,
    in1.CLOSINGPLANNERCODE AS CLOSINGPLANNERCODE,
    in0.OPENINGPLATINGCOST AS OPENINGPLATINGCOST,
    in1.CLOSTINGPLATINGCOST AS CLOSTINGPLATINGCOST,
    in0.OPENINGBUYER AS OPENINGBUYER,
    in1.CLOSINGBUYER AS CLOSINGBUYER,
    in0.OPENINGORDERPOLICY AS OPENINGORDERPOLICY,
    in1.CLOSINGORDERPOLICY AS CLOSINGORDERPOLICY,
    in0.OPENINGCUSTOMERSUPPLIED AS OPENINGCUSTOMERSUPPLIED,
    in1.CLOSINGCUSTOMERSUPPLIED AS CLOSINGCUSTOMERSUPPLIED,
    in0.OPENINGSTANDARDUNITCOST AS OPENINGSTANDARDUNITCOST,
    in0.OPENINGSTANDARDLABORCOST AS OPENINGSTANDARDLABORCOST,
    in0.OPENINGSTANDARDPLATINGCOST AS OPENINGSTANDARDPLATINGCOST,
    in1.CLOSINGSTANDARDUNITCOST AS CLOSINGSTANDARDUNITCOST,
    in1.CLOSINGSTANDARDLABORCOST AS CLOSINGSTANDARDLABORCOST,
    in1.CLOSINGSTANDARDPLATINGCOST AS CLOSINGSTANDARDPLATINGCOST,
    (
      CASE
        WHEN (in0.PARTNUMBER = in1.PARTNUMBER)
          THEN NULL
        ELSE in1.PARTNUMBER
      END
    ) AS PARTNUMBER,
    in0.* EXCLUDE ("OPENINGUNITCOST", 
    "OPENINGLABORCOST", 
    "OPENINGPLANNERCODE", 
    "OPENINGPLATINGCOST", 
    "OPENINGBUYER", 
    "OPENINGORDERPOLICY", 
    "OPENINGCUSTOMERSUPPLIED", 
    "OPENINGSTANDARDUNITCOST", 
    "OPENINGSTANDARDLABORCOST", 
    "OPENINGSTANDARDPLATINGCOST", 
    "PARTNUMBER"),
    in1.* EXCLUDE ("CLOSINGUNITCOST", 
    "CLOSINGLABORCOST", 
    "CLOSINGPLANNERCODE", 
    "PARTNUMBER", 
    "CLOSTINGPLATINGCOST", 
    "CLOSINGBUYER", 
    "CLOSINGORDERPOLICY", 
    "CLOSINGCUSTOMERSUPPLIED", 
    "CLOSINGSTANDARDUNITCOST", 
    "CLOSINGSTANDARDLABORCOST", 
    "CLOSINGSTANDARDPLATINGCOST")
  
  FROM AlteryxSelect_111 AS in0
  FULL JOIN AlteryxSelect_112 AS in1
     ON (in0.PARTNUMBER = in1.PARTNUMBER)

),

Join_115_left_UnionFullOuter AS (

  SELECT 
    in0.OPENINGUNITCOST AS OPENINGUNITCOST,
    in0.OPENINGLABORCOST AS OPENINGLABORCOST,
    in0.OPENINGPLANNERCODE AS OPENINGPLANNERCODE,
    in0.CLOSINGUNITCOST AS CLOSINGUNITCOST,
    in0.CLOSINGLABORCOST AS CLOSINGLABORCOST,
    in0.CLOSINGPLANNERCODE AS CLOSINGPLANNERCODE,
    in1.PREVIOUSQUARTERUNITCOST AS PREVIOUSQUARTERUNITCOST,
    in1.PREVIOUSQUARTERLABORCOST AS PREVIOUSQUARTERLABORCOST,
    in1.PREVIOUSQUARTERPLANNERCODE AS PREVIOUSQUARTERPLANNERCODE,
    in0.OPENINGPLATINGCOST AS OPENINGPLATINGCOST,
    in0.CLOSTINGPLATINGCOST AS CLOSTINGPLATINGCOST,
    in1.PREVIOUSQUARTERPLATINGCOST AS PREVIOUSQUARTERPLATINGCOST,
    in0.OPENINGBUYER AS OPENINGBUYER,
    in0.CLOSINGBUYER AS CLOSINGBUYER,
    in1.PREVIOUSQUARTERBUYER AS PREVIOUSQUARTERBUYER,
    in0.OPENINGORDERPOLICY AS OPENINGORDERPOLICY,
    in0.CLOSINGORDERPOLICY AS CLOSINGORDERPOLICY,
    in1.PREVIOUSQUARTERORDERPOLICY AS PREVIOUSQUARTERORDERPOLICY,
    in0.OPENINGCUSTOMERSUPPLIED AS OPENINGCUSTOMERSUPPLIED,
    in0.CLOSINGCUSTOMERSUPPLIED AS CLOSINGCUSTOMERSUPPLIED,
    in0.OPENINGSTANDARDUNITCOST AS OPENINGSTANDARDUNITCOST,
    in0.OPENINGSTANDARDLABORCOST AS OPENINGSTANDARDLABORCOST,
    in0.OPENINGSTANDARDPLATINGCOST AS OPENINGSTANDARDPLATINGCOST,
    in0.CLOSINGSTANDARDUNITCOST AS CLOSINGSTANDARDUNITCOST,
    in0.CLOSINGSTANDARDLABORCOST AS CLOSINGSTANDARDLABORCOST,
    in0.CLOSINGSTANDARDPLATINGCOST AS CLOSINGSTANDARDPLATINGCOST,
    in1.PREVIOUSQUARTERCUSTOMERSUPPLIED AS PREVIOUSQUARTERCUSTOMERSUPPLIED,
    in1.PREVIOUSQUARTERSTANDARDUNITCOST AS PREVIOUSQUARTERSTANDARDUNITCOST,
    in1.PREVIOUSQUARTERSTANDARDLABORCOST AS PREVIOUSQUARTERSTANDARDLABORCOST,
    in1.PREVIOUSQUARTERSTANDARDPLATINGCOST AS PREVIOUSQUARTERSTANDARDPLATINGCOST,
    (
      CASE
        WHEN (in0.PARTNUMBER = in1.PARTNUMBER)
          THEN NULL
        ELSE in1.PARTNUMBER
      END
    ) AS PARTNUMBER,
    in0.* EXCLUDE ("OPENINGUNITCOST", 
    "OPENINGLABORCOST", 
    "OPENINGPLANNERCODE", 
    "CLOSINGUNITCOST", 
    "CLOSINGLABORCOST", 
    "CLOSINGPLANNERCODE", 
    "OPENINGPLATINGCOST", 
    "CLOSTINGPLATINGCOST", 
    "OPENINGBUYER", 
    "CLOSINGBUYER", 
    "OPENINGORDERPOLICY", 
    "CLOSINGORDERPOLICY", 
    "OPENINGCUSTOMERSUPPLIED", 
    "CLOSINGCUSTOMERSUPPLIED", 
    "OPENINGSTANDARDUNITCOST", 
    "OPENINGSTANDARDLABORCOST", 
    "OPENINGSTANDARDPLATINGCOST", 
    "CLOSINGSTANDARDUNITCOST", 
    "CLOSINGSTANDARDLABORCOST", 
    "CLOSINGSTANDARDPLATINGCOST", 
    "PARTNUMBER"),
    in1.* EXCLUDE ("PREVIOUSQUARTERUNITCOST", 
    "PREVIOUSQUARTERLABORCOST", 
    "PREVIOUSQUARTERPLANNERCODE", 
    "PARTNUMBER", 
    "PREVIOUSQUARTERPLATINGCOST", 
    "PREVIOUSQUARTERBUYER", 
    "PREVIOUSQUARTERORDERPOLICY", 
    "PREVIOUSQUARTERCUSTOMERSUPPLIED", 
    "PREVIOUSQUARTERSTANDARDUNITCOST", 
    "PREVIOUSQUARTERSTANDARDLABORCOST", 
    "PREVIOUSQUARTERSTANDARDPLATINGCOST")
  
  FROM Join_114_left_UnionFullOuter AS in0
  FULL JOIN AlteryxSelect_113 AS in1
     ON (in0.PARTNUMBER = in1.PARTNUMBER)

),

Cleanse_123 AS (

  {{
    prophecy_basics.DataCleansing(
      ['Join_115_left_UnionFullOuter'], 
      [
        { "name": "OPENINGUNITCOST", "dataType": "String" }, 
        { "name": "OPENINGLABORCOST", "dataType": "String" }, 
        { "name": "OPENINGPLANNERCODE", "dataType": "String" }, 
        { "name": "CLOSINGUNITCOST", "dataType": "String" }, 
        { "name": "CLOSINGLABORCOST", "dataType": "String" }, 
        { "name": "CLOSINGPLANNERCODE", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERUNITCOST", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERLABORCOST", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERPLANNERCODE", "dataType": "String" }, 
        { "name": "OPENINGPLATINGCOST", "dataType": "String" }, 
        { "name": "CLOSTINGPLATINGCOST", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERPLATINGCOST", "dataType": "String" }, 
        { "name": "OPENINGBUYER", "dataType": "String" }, 
        { "name": "CLOSINGBUYER", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERBUYER", "dataType": "String" }, 
        { "name": "OPENINGORDERPOLICY", "dataType": "String" }, 
        { "name": "CLOSINGORDERPOLICY", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERORDERPOLICY", "dataType": "String" }, 
        { "name": "OPENINGCUSTOMERSUPPLIED", "dataType": "String" }, 
        { "name": "CLOSINGCUSTOMERSUPPLIED", "dataType": "String" }, 
        { "name": "OPENINGSTANDARDUNITCOST", "dataType": "String" }, 
        { "name": "OPENINGSTANDARDLABORCOST", "dataType": "String" }, 
        { "name": "OPENINGSTANDARDPLATINGCOST", "dataType": "String" }, 
        { "name": "CLOSINGSTANDARDUNITCOST", "dataType": "String" }, 
        { "name": "CLOSINGSTANDARDLABORCOST", "dataType": "String" }, 
        { "name": "CLOSINGSTANDARDPLATINGCOST", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERCUSTOMERSUPPLIED", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERSTANDARDUNITCOST", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERSTANDARDLABORCOST", "dataType": "String" }, 
        { "name": "PREVIOUSQUARTERSTANDARDPLATINGCOST", "dataType": "String" }, 
        { "name": "PARTNUMBER", "dataType": "String" }
      ], 
      'keepOriginal', 
      [
        'PARTNUMBER', 
        'OPENINGUNITCOST', 
        'OPENINGLABORCOST', 
        'OPENINGPLANNERCODE', 
        'CLOSINGUNITCOST', 
        'CLOSINGLABORCOST', 
        'CLOSINGPLANNERCODE', 
        'PREVIOUSQUARTERUNITCOST', 
        'PREVIOUSQUARTERLABORCOST', 
        'PREVIOUSQUARTERPLANNERCODE', 
        'OPENINGPLATINGCOST', 
        'CLOSTINGPLATINGCOST', 
        'PREVIOUSQUARTERPLATINGCOST', 
        'OPENINGBUYER', 
        'CLOSINGBUYER', 
        'PREVIOUSQUARTERBUYER', 
        'OPENINGORDERPOLICY', 
        'CLOSINGORDERPOLICY', 
        'PREVIOUSQUARTERORDERPOLICY'
      ], 
      true, 
      '', 
      true, 
      0, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

Join_127_left_UnionLeftOuter AS (

  SELECT 
    in0.PARTNUMBER AS PARTNUMBER,
    in0.OPENINGUNITCOST AS OPENINGUNITCOST,
    in0.OPENINGLABORCOST AS OPENINGLABORCOST,
    in0.CLOSINGUNITCOST AS CLOSINGUNITCOST,
    in0.CLOSINGLABORCOST AS CLOSINGLABORCOST,
    in0.CLOSINGPLANNERCODE AS CLOSINGPLANNERCODE,
    in0.PREVIOUSQUARTERUNITCOST AS PREVIOUSQUARTERUNITCOST,
    in0.PREVIOUSQUARTERLABORCOST AS PREVIOUSQUARTERLABORCOST,
    in0.PREVIOUSQUARTERPLANNERCODE AS PREVIOUSQUARTERPLANNERCODE,
    in0.OPENINGPLATINGCOST AS OPENINGPLATINGCOST,
    in0.CLOSTINGPLATINGCOST AS CLOSTINGPLATINGCOST,
    in0.PREVIOUSQUARTERPLATINGCOST AS PREVIOUSQUARTERPLATINGCOST,
    in0.OPENINGBUYER AS OPENINGBUYER,
    in0.CLOSINGBUYER AS CLOSINGBUYER,
    in0.PREVIOUSQUARTERBUYER AS PREVIOUSQUARTERBUYER,
    in0.OPENINGORDERPOLICY AS OPENINGORDERPOLICY,
    in0.CLOSINGORDERPOLICY AS CLOSINGORDERPOLICY,
    in0.PREVIOUSQUARTERORDERPOLICY AS PREVIOUSQUARTERORDERPOLICY,
    (
      CASE
        WHEN (in0.OPENINGPLANNERCODE = in1.PLANNERCODE)
          THEN in1.ACCOUNTINGPLANNERCODE
        ELSE NULL
      END
    ) AS OPENINGPLANNERCODE,
    (
      (((in0.OPENINGPLANNERCODE = in1.PLANNERCODE) IS TRUE) AND in1.ISBOM)
      OR (NULL AND ((in0.OPENINGPLANNERCODE = in1.PLANNERCODE) IS NOT TRUE))
    ) AS OPENINGISBOM,
    in0.* EXCLUDE ("PARTNUMBER", 
    "OPENINGUNITCOST", 
    "OPENINGLABORCOST", 
    "CLOSINGUNITCOST", 
    "CLOSINGLABORCOST", 
    "CLOSINGPLANNERCODE", 
    "PREVIOUSQUARTERUNITCOST", 
    "PREVIOUSQUARTERLABORCOST", 
    "PREVIOUSQUARTERPLANNERCODE", 
    "OPENINGPLATINGCOST", 
    "CLOSTINGPLATINGCOST", 
    "PREVIOUSQUARTERPLATINGCOST", 
    "OPENINGBUYER", 
    "CLOSINGBUYER", 
    "PREVIOUSQUARTERBUYER", 
    "OPENINGORDERPOLICY", 
    "CLOSINGORDERPOLICY", 
    "PREVIOUSQUARTERORDERPOLICY", 
    "OPENINGPLANNERCODE"),
    in1.* EXCLUDE ("PLANNERCODE", "ISBOM", "ACCOUNTINGPLANNERCODE")
  
  FROM Cleanse_123 AS in0
  LEFT JOIN AlteryxSelect_72 AS in1
     ON (in0.OPENINGPLANNERCODE = in1.PLANNERCODE)

),

Join_129_left_UnionLeftOuter AS (

  SELECT 
    in0.PARTNUMBER AS PARTNUMBER,
    in0.OPENINGUNITCOST AS OPENINGUNITCOST,
    in0.OPENINGLABORCOST AS OPENINGLABORCOST,
    in0.OPENINGISBOM AS OPENINGISBOM,
    in0.OPENINGPLANNERCODE AS OPENINGPLANNERCODE,
    in0.CLOSINGUNITCOST AS CLOSINGUNITCOST,
    in0.CLOSINGLABORCOST AS CLOSINGLABORCOST,
    in0.PREVIOUSQUARTERUNITCOST AS PREVIOUSQUARTERUNITCOST,
    in0.PREVIOUSQUARTERLABORCOST AS PREVIOUSQUARTERLABORCOST,
    in0.PREVIOUSQUARTERPLANNERCODE AS PREVIOUSQUARTERPLANNERCODE,
    in0.OPENINGPLATINGCOST AS OPENINGPLATINGCOST,
    in0.CLOSTINGPLATINGCOST AS CLOSTINGPLATINGCOST,
    in0.PREVIOUSQUARTERPLATINGCOST AS PREVIOUSQUARTERPLATINGCOST,
    in0.OPENINGBUYER AS OPENINGBUYER,
    in0.CLOSINGBUYER AS CLOSINGBUYER,
    in0.PREVIOUSQUARTERBUYER AS PREVIOUSQUARTERBUYER,
    in0.OPENINGORDERPOLICY AS OPENINGORDERPOLICY,
    in0.CLOSINGORDERPOLICY AS CLOSINGORDERPOLICY,
    in0.PREVIOUSQUARTERORDERPOLICY AS PREVIOUSQUARTERORDERPOLICY,
    (
      CASE
        WHEN (in0.CLOSINGPLANNERCODE = in1.PLANNERCODE)
          THEN in1.ACCOUNTINGPLANNERCODE
        ELSE NULL
      END
    ) AS CLOSINGPLANNERCODE,
    (
      (((in0.CLOSINGPLANNERCODE = in1.PLANNERCODE) IS TRUE) AND in1.ISBOM)
      OR (NULL AND ((in0.CLOSINGPLANNERCODE = in1.PLANNERCODE) IS NOT TRUE))
    ) AS CLOSINGISBOM,
    in0.* EXCLUDE ("PARTNUMBER", 
    "OPENINGUNITCOST", 
    "OPENINGLABORCOST", 
    "OPENINGISBOM", 
    "OPENINGPLANNERCODE", 
    "CLOSINGUNITCOST", 
    "CLOSINGLABORCOST", 
    "PREVIOUSQUARTERUNITCOST", 
    "PREVIOUSQUARTERLABORCOST", 
    "PREVIOUSQUARTERPLANNERCODE", 
    "OPENINGPLATINGCOST", 
    "CLOSTINGPLATINGCOST", 
    "PREVIOUSQUARTERPLATINGCOST", 
    "OPENINGBUYER", 
    "CLOSINGBUYER", 
    "PREVIOUSQUARTERBUYER", 
    "OPENINGORDERPOLICY", 
    "CLOSINGORDERPOLICY", 
    "PREVIOUSQUARTERORDERPOLICY", 
    "CLOSINGPLANNERCODE"),
    in1.* EXCLUDE ("PLANNERCODE", "ISBOM", "ACCOUNTINGPLANNERCODE")
  
  FROM Join_127_left_UnionLeftOuter AS in0
  LEFT JOIN AlteryxSelect_72 AS in1
     ON (in0.CLOSINGPLANNERCODE = in1.PLANNERCODE)

),

Join_130_left_UnionLeftOuter AS (

  SELECT 
    in0.PARTNUMBER AS PARTNUMBER,
    in0.OPENINGUNITCOST AS OPENINGUNITCOST,
    in0.OPENINGLABORCOST AS OPENINGLABORCOST,
    in0.OPENINGISBOM AS OPENINGISBOM,
    in0.OPENINGPLANNERCODE AS OPENINGPLANNERCODE,
    in0.CLOSINGUNITCOST AS CLOSINGUNITCOST,
    in0.CLOSINGLABORCOST AS CLOSINGLABORCOST,
    in0.CLOSINGISBOM AS CLOSINGISBOM,
    in0.CLOSINGPLANNERCODE AS CLOSINGPLANNERCODE,
    in0.PREVIOUSQUARTERUNITCOST AS PREVIOUSQUARTERUNITCOST,
    in0.PREVIOUSQUARTERLABORCOST AS PREVIOUSQUARTERLABORCOST,
    in0.OPENINGPLATINGCOST AS OPENINGPLATINGCOST,
    in0.CLOSTINGPLATINGCOST AS CLOSTINGPLATINGCOST,
    in0.PREVIOUSQUARTERPLATINGCOST AS PREVIOUSQUARTERPLATINGCOST,
    in0.OPENINGBUYER AS OPENINGBUYER,
    in0.CLOSINGBUYER AS CLOSINGBUYER,
    in0.PREVIOUSQUARTERBUYER AS PREVIOUSQUARTERBUYER,
    in0.OPENINGORDERPOLICY AS OPENINGORDERPOLICY,
    in0.CLOSINGORDERPOLICY AS CLOSINGORDERPOLICY,
    in0.PREVIOUSQUARTERORDERPOLICY AS PREVIOUSQUARTERORDERPOLICY,
    (
      CASE
        WHEN (in0.PREVIOUSQUARTERPLANNERCODE = in1.PLANNERCODE)
          THEN in1.ACCOUNTINGPLANNERCODE
        ELSE NULL
      END
    ) AS PREVIOUSQUARTERPLANNERCODE,
    (
      (((in0.PREVIOUSQUARTERPLANNERCODE = in1.PLANNERCODE) IS TRUE) AND in1.ISBOM)
      OR (NULL AND ((in0.PREVIOUSQUARTERPLANNERCODE = in1.PLANNERCODE) IS NOT TRUE))
    ) AS PREVIOUSQUARTERISBOM,
    in0.* EXCLUDE ("PARTNUMBER", 
    "OPENINGUNITCOST", 
    "OPENINGLABORCOST", 
    "OPENINGISBOM", 
    "OPENINGPLANNERCODE", 
    "CLOSINGUNITCOST", 
    "CLOSINGLABORCOST", 
    "CLOSINGISBOM", 
    "CLOSINGPLANNERCODE", 
    "PREVIOUSQUARTERUNITCOST", 
    "PREVIOUSQUARTERLABORCOST", 
    "OPENINGPLATINGCOST", 
    "CLOSTINGPLATINGCOST", 
    "PREVIOUSQUARTERPLATINGCOST", 
    "OPENINGBUYER", 
    "CLOSINGBUYER", 
    "PREVIOUSQUARTERBUYER", 
    "OPENINGORDERPOLICY", 
    "CLOSINGORDERPOLICY", 
    "PREVIOUSQUARTERORDERPOLICY", 
    "PREVIOUSQUARTERPLANNERCODE"),
    in1.* EXCLUDE ("PLANNERCODE", "ISBOM", "ACCOUNTINGPLANNERCODE")
  
  FROM Join_129_left_UnionLeftOuter AS in0
  LEFT JOIN AlteryxSelect_72 AS in1
     ON (in0.PREVIOUSQUARTERPLANNERCODE = in1.PLANNERCODE)

),

AlteryxSelect_118 AS (

  SELECT 
    PARTNUMBER AS PARTNUMBER,
    OPENINGUNITCOST AS OPENINGUNITCOST,
    CLOSINGUNITCOST AS CLOSINGUNITCOST,
    PREVIOUSQUARTERUNITCOST AS PREVIOUSQUARTERUNITCOST,
    OPENINGLABORCOST AS OPENINGLABORCOST,
    CLOSINGLABORCOST AS CLOSINGLABORCOST,
    PREVIOUSQUARTERLABORCOST AS PREVIOUSQUARTERLABORCOST,
    OPENINGPLATINGCOST AS OPENINGPLATINGCOST,
    CLOSTINGPLATINGCOST AS CLOSTINGPLATINGCOST,
    PREVIOUSQUARTERPLATINGCOST AS PREVIOUSQUARTERPLATINGCOST,
    OPENINGPLANNERCODE AS OPENINGPLANNERCODE,
    CLOSINGPLANNERCODE AS CLOSINGPLANNERCODE,
    PREVIOUSQUARTERPLANNERCODE AS PREVIOUSQUARTERPLANNERCODE,
    OPENINGISBOM AS OPENINGISBOM,
    CLOSINGISBOM AS CLOSINGISBOM,
    PREVIOUSQUARTERISBOM AS PREVIOUSQUARTERISBOM,
    OPENINGBUYER AS OPENINGBUYER,
    CLOSINGBUYER AS CLOSINGBUYER,
    PREVIOUSQUARTERBUYER AS PREVIOUSQUARTERBUYER,
    OPENINGORDERPOLICY AS OPENINGORDERPOLICY,
    CLOSINGORDERPOLICY AS CLOSINGORDERPOLICY,
    PREVIOUSQUARTERORDERPOLICY AS PREVIOUSQUARTERORDERPOLICY,
    OPENINGCUSTOMERSUPPLIED AS OPENINGCUSTOMERSUPPLIED,
    CLOSINGCUSTOMERSUPPLIED AS CLOSINGCUSTOMERSUPPLIED,
    PREVIOUSQUARTERCUSTOMERSUPPLIED AS PREVIOUSQUARTERCUSTOMERSUPPLIED,
    OPENINGSTANDARDUNITCOST AS OPENINGSTANDARDUNITCOST,
    OPENINGSTANDARDLABORCOST AS OPENINGSTANDARDLABORCOST,
    OPENINGSTANDARDPLATINGCOST AS OPENINGSTANDARDPLATINGCOST,
    CLOSINGSTANDARDUNITCOST AS CLOSINGSTANDARDUNITCOST,
    CLOSINGSTANDARDLABORCOST AS CLOSINGSTANDARDLABORCOST,
    CLOSINGSTANDARDPLATINGCOST AS CLOSINGSTANDARDPLATINGCOST,
    PREVIOUSQUARTERSTANDARDUNITCOST AS PREVIOUSQUARTERSTANDARDUNITCOST,
    PREVIOUSQUARTERSTANDARDLABORCOST AS PREVIOUSQUARTERSTANDARDLABORCOST,
    PREVIOUSQUARTERSTANDARDPLATINGCOST AS PREVIOUSQUARTERSTANDARDPLATINGCOST
  
  FROM Join_130_left_UnionLeftOuter AS in0

),

Join_122_left_UnionLeftOuter AS (

  SELECT 
    in0.*,
    in1.* EXCLUDE ("PARTNUMBER")
  
  FROM Formula_91_1 AS in0
  LEFT JOIN AlteryxSelect_118 AS in1
     ON (in0.PARTNUMBER = in1.PARTNUMBER)

),

AlteryxSelect_74 AS (

  SELECT 
    PARTNUMBER AS PARTNUMBER,
    REPORTINGSERIES AS SERIES,
    REPORTINGSERIESPRODUCTERA AS ERA,
    REPORTINGSERIESPRODUCTWEAVE AS WEAVE,
    REPORTINGSERIESPRODUCTSOLUTIONBLOCK AS BLOCK,
    REPORTINGSERIESPRODUCTSEGMENT AS SEGMENT,
    ITEMTYPE AS ITEMTYPE,
    PCMFGITEMTYPE AS PCMFGITEMTYPE
  
  FROM AlteryxSelect_182 AS in0

),

Join_138_inner AS (

  SELECT 
    in0.*,
    in1.* EXCLUDE ("PARTNUMBER")
  
  FROM Join_122_left_UnionLeftOuter AS in0
  INNER JOIN AlteryxSelect_74 AS in1
     ON (in0.PARTNUMBER = in1.PARTNUMBER)

),

Formula_134_0 AS (

  SELECT 
    (OPENINGBALANCE * CLOSINGUNITCOST) AS OPENINGVALUE,
    (CLOSINGBALANCE * CLOSINGUNITCOST) AS CLOSINGVALUE,
    *
  
  FROM Join_138_inner AS in0

)

SELECT *

FROM Formula_134_0
