---
version: 2
models:
- name: "perpetual_inventory__AlteryxSelect_23"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__AlteryxSelect_63"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__AlteryxSelect_96"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__AlteryxSelect_97"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__AlteryxSelect_98"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__AppendFields_52"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__CrossTab_81_1"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__Filter_183"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__Filter_183_reject"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__Formula_134_0"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__Formula_2_0"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory__Formula_95_0"
  tags:
  - "prophecy_temp"
