---
version: 2
models:
- name: "Explain_ELA_with_checks__AlteryxSelect_62"
  tags:
  - "prophecy_temp"
- name: "Explain_ELA_with_checks__AlteryxSelect_73"
  tags:
  - "prophecy_temp"
- name: "Explain_ELA_with_checks__AlteryxSelect_74"
  tags:
  - "prophecy_temp"
- name: "Explain_ELA_with_checks__AlteryxSelect_81"
  tags:
  - "prophecy_temp"
- name: "Explain_ELA_with_checks__AlteryxSelect_88"
  tags:
  - "prophecy_temp"
- name: "Explain_ELA_with_checks__Formula_60_2"
  tags:
  - "prophecy_temp"
- name: "Explain_ELA_with_checks__Join_59_inner"
  tags:
  - "prophecy_temp"
