---
version: 2
sources:
- name: "transpiled_sources"
  database: "{{ var('db_name') }}"
  schema: "{{ var('schema_name') }}"
  config:
    enabled: true
  tables:
  - name: "Source__User_Db_42_ref"
    identifier: "{{ var('Source__User_Db_42') }}"
    config:
      tags:
      - "pipeline:FDI_HL_Owned_Loans_Tertiary_Monthly"
    columns: []
  - name: "Source__User_Db_45_ref"
    identifier: "{{ var('Source__User_Db_45') }}"
    config:
      tags:
      - "pipeline:FDI_HL_Owned_Loans_Tertiary_Monthly"
    columns: []
