pipelines:
  facility_master_wf_1_:
    visualGroups:
      Container1005:
        isCollapsed: false
        height: 399
        width: 722
      Container411:
        isCollapsed: false
        height: 399
        width: 316
        nodes:
        - "aka_GPD_UDDL_Wr_788"
      ExcludeStreetNameforOrgwithmostfrequentdisplayed:
        isCollapsed: false
        height: 720
        width: 1058
      GeocodedAddressesUpdated19DEC2022:
        isCollapsed: false
        height: 807
        width: 1658
        nodes:
        - "aka_GPDIP_EDLUD_1053"
        - "aka_GPDIP_EDLUD_1056"
      GetGroupIDbyGeoandDistance:
        isCollapsed: false
        height: 975
        width: 1608
      GroupCorrdinates:
        isCollapsed: false
        height: 495
        width: 1034
      Groupcontainsmultipleorgfuzzymatchorgname:
        isCollapsed: false
        height: 399
        width: 766
      Grouponlycontain1Org:
        isCollapsed: false
        height: 399
        width: 794
      USCensusCountyShapesInfo:
        isCollapsed: false
        height: 495
        width: 522
        nodes:
        - "cb_2018_us_coun_204"
      USCensusStateShapesandInfo:
        isCollapsed: false
        height: 495
        width: 566
        nodes:
        - "cb_2018_us_stat_207"
      assignnewgroupid:
        isCollapsed: false
        height: 1263
        width: 2018
      calculatethedistancerowbyrow:
        isCollapsed: false
        height: 2163
        width: 7118
        nodes:
        - "assignnewgroupid"
      citytownvillageclean:
        isCollapsed: false
        height: 4509
        width: 5782
        nodes:
        - "filterunusedorgname"
        - "getonecitytownvillageforuniqueoriginalgeotag"
        - "getonecitytownvillageforuniqueoriginalgeotag_1"
      contactaddresswithstatefipscodeadd:
        isCollapsed: false
        height: 2235
        width: 3196
        nodes:
        - "GeocodedAddressesUpdated19DEC2022"
        - "USCensusCountyShapesInfo"
        - "USCensusStateShapesandInfo"
      dealwithmultineworgnamewithin1latlonggroup:
        isCollapsed: false
        height: 723
        width: 2582
        nodes:
        - "Join_946"
        - "Union_947"
        - "Unique_949"
      dealwithmultipleuniquenameandexcludestreetorgname:
        isCollapsed: false
        height: 831
        width: 3758
      dealwithmultipleuniquenameandexcludestreetorgname_1:
        isCollapsed: false
        height: 723
        width: 3902
      disableregex:
        isCollapsed: false
        height: 399
        width: 308
        nodes:
        - "MultiFieldFormula_1037"
      filterunusedorgname:
        isCollapsed: false
        height: 495
        width: 512
      fuzzylogic:
        isCollapsed: false
        height: 4185
        width: 19464
        nodes:
        - "GroupCorrdinates"
        - "Groupcontainsmultipleorgfuzzymatchorgname"
        - "Grouponlycontain1Org"
        - "dealwithmultineworgnamewithin1latlonggroup"
        - "keywordmatch"
        - "orgthatappearsmostfrequenctlyidentified"
        - "orgwithmulticities"
        - "regexdisabled"
      getonecitytownvillageforuniqueoriginalgeotag:
        isCollapsed: false
        height: 1515
        width: 3182
      getonecitytownvillageforuniqueoriginalgeotag_1:
        isCollapsed: false
        height: 1443
        width: 3182
      grouporgnamewithgeotag:
        isCollapsed: false
        height: 1227
        width: 2008
      joinbacktogetorgname:
        isCollapsed: false
        height: 543
        width: 1590
      keywordmatch:
        isCollapsed: false
        height: 939
        width: 2510
      orgthatappearsmostfrequenctlyidentified:
        isCollapsed: false
        height: 3897
        width: 10242
        nodes:
        - "ExcludeStreetNameforOrgwithmostfrequentdisplayed"
        - "dealwithmultipleuniquenameandexcludestreetorgname"
        - "dealwithmultipleuniquenameandexcludestreetorgname_1"
      orgwithmulticities:
        isCollapsed: false
        height: 819
        width: 1418
      regexdisabled:
        isCollapsed: false
        height: 399
        width: 322
        nodes:
        - "MultiFieldFormula_1035"
      regexdisabled_1:
        isCollapsed: true
        height: 72
        width: 322
        nodes:
        - "MultiFieldFormula_528"
      sitefacilityfulldataset:
        isCollapsed: false
        height: 3732
        width: 8428
        nodes:
        - "aka_GPDIP_EDLUD_2"
        - "aka_GPDIP_EDLUD_24"
        - "aka_GPDIP_EDLUD_28"
        - "contactaddresswithstatefipscodeadd"
        - "regexdisabled_1"
      unionalldataintoatable:
        isCollapsed: false
        height: 1464
        width: 3100
        nodes:
        - "Formula_793_to_Formula_1078_0"
        - "aka_GPDIP_EDLUD_412"
      writebasedataintotable:
        isCollapsed: false
        height: 867
        width: 2104
        nodes:
        - "Container411"
        - "MultiFieldFormula_399"
        - "disableregex"
