{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH Formula_29_0 AS (

  SELECT *
  
  FROM {{ ref('13_Chicago_FI_Fact_Tables__Formula_29_0')}}

),

AlteryxSelect_30 AS (

  SELECT 
    INSPECTIONDATESK AS INSPECTIONDATESK,
    "INSPECTION ID" AS "INSPECTION ID",
    "LICENSE HASH" AS "LICENSE HASH",
    INSPECTION_DATE AS INSPECTION_DATE,
    DI_CREATEDATE AS DI_CREATEDATE,
    DI_WORKFLOWFILENAME AS DI_WORKFLOWFILENAME,
    RESTAURANTSK AS RESTAURANTSK,
    INSPECTIONTYPESK AS INSPECTIONTYPESK,
    RIGHT_RESULTSSK AS RIGHT_RESULTSSK,
    RISKSK AS RISKSK,
    FACILITYSK AS FACILITYSK,
    CAST(NULL AS STRING) AS GEOSK,
    CAST(NULL AS STRING) AS DI_WORKFLOWDIRECTORY,
    CAST(NULL AS STRING) AS LICENSESK
  
  FROM Formula_29_0 AS in0

),

Unique_32 AS (

  SELECT * 
  
  FROM AlteryxSelect_30 AS in0
  
  QUALIFY ROW_NUMBER() OVER (PARTITION BY "INSPECTION ID" ORDER BY "INSPECTION ID") = 1

)

SELECT *

FROM Unique_32
