{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH DSN_Chicago_SSM_61 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('13_Chicago_FI_Fact_Tables', 'DSN_Chicago_SSM_61') }}

),

Summarize_64 AS (

  SELECT 
    MAX(LICENSESK) AS MAX_LICENSESK,
    LICENSE_NUMBER AS LICENSE_NUMBER
  
  FROM DSN_Chicago_SSM_61 AS in0
  
  GROUP BY LICENSE_NUMBER

),

AlteryxSelect_65 AS (

  SELECT 
    MAX_LICENSESK AS MAX_LICENSESK,
    LICENSE_NUMBER AS LICENSE_NUMBER
  
  FROM Summarize_64 AS in0

),

DSN_Chicago_SSM_1 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('13_Chicago_FI_Fact_Tables', 'DSN_Chicago_SSM_1') }}

),

AlteryxSelect_4 AS (

  SELECT 
    "INSPECTION ID" AS "INSPECTION ID",
    "DBA NAME" AS "DBA NAME",
    "AKA NAME" AS "AKA NAME",
    "LICENSE HASH" AS "LICENSE HASH",
    "FACILITY TYPE" AS "FACILITY TYPE",
    RISK AS RISK,
    ADDRESS AS ADDRESS,
    CITY AS CITY,
    STATE AS STATE,
    ZIP AS ZIP,
    "INSPECTION DATE" AS "INSPECTION DATE",
    "INSPECTION TYPE" AS "INSPECTION TYPE",
    RESULTS AS RESULTS,
    VIOLATIONS AS VIOLATIONS,
    LATITUDE AS LATITUDE,
    LONGITUDE AS LONGITUDE,
    LOCATION AS LOCATION,
    INSPECTION_DATE AS INSPECTION_DATE
  
  FROM DSN_Chicago_SSM_1 AS in0

),

Unique_63 AS (

  SELECT * 
  
  FROM AlteryxSelect_4 AS in0
  
  QUALIFY ROW_NUMBER() OVER (PARTITION BY "INSPECTION ID", 
  "AKA NAME", 
  "LICENSE HASH", 
  "FACILITY TYPE", 
  RISK, 
  ADDRESS, 
  CITY, 
  STATE, 
  ZIP, 
  "INSPECTION DATE", 
  "INSPECTION TYPE", 
  RESULTS, 
  VIOLATIONS, 
  LATITUDE, 
  LONGITUDE, 
  LOCATION, 
  INSPECTION_DATE ORDER BY "INSPECTION ID", "AKA NAME", "LICENSE HASH", "FACILITY TYPE", RISK, ADDRESS, CITY, STATE, ZIP, "INSPECTION DATE", "INSPECTION TYPE", RESULTS, VIOLATIONS, LATITUDE, LONGITUDE, LOCATION, INSPECTION_DATE) = 1

),

AlteryxSelect_6 AS (

  SELECT 
    "INSPECTION ID" AS "INSPECTION ID",
    "DBA NAME" AS "DBA NAME",
    "AKA NAME" AS "AKA NAME",
    "LICENSE HASH" AS "LICENSE HASH",
    "FACILITY TYPE" AS "FACILITY TYPE",
    RISK AS RISK,
    ADDRESS AS ADDRESS,
    CITY AS CITY,
    STATE AS STATE,
    ZIP AS ZIP,
    "INSPECTION DATE" AS "INSPECTION DATE",
    "INSPECTION TYPE" AS "INSPECTION TYPE",
    RESULTS AS RESULTS,
    VIOLATIONS AS VIOLATIONS,
    LATITUDE AS LATITUDE,
    LONGITUDE AS LONGITUDE,
    LOCATION AS LOCATION,
    INSPECTION_DATE AS INSPECTION_DATE
  
  FROM Unique_63 AS in0

),

Join_7_left_UnionLeftOuter AS (

  SELECT 
    in0.*,
    in1.*
  
  FROM AlteryxSelect_6 AS in0
  LEFT JOIN AlteryxSelect_65 AS in1
     ON (in0."LICENSE HASH" = in1.LICENSE_NUMBER)

),

DSN_Chicago_SSM_10 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('13_Chicago_FI_Fact_Tables', 'DSN_Chicago_SSM_10') }}

),

Join_9_inner AS (

  SELECT 
    in1.DI_CREATEDATE AS RIGHT_DI_CREATEDATE,
    in1.DI_WORKFLOWDIRECTORY AS RIGHT_DI_WORKFLOWDIRECTORY,
    in1.DI_WORKFLOWFILENAME AS RIGHT_DI_WORKFLOWFILENAME,
    in0.*,
    in1.* EXCLUDE ("DI_CREATEDATE", "DI_WORKFLOWDIRECTORY", "DI_WORKFLOWFILENAME")
  
  FROM Join_7_left_UnionLeftOuter AS in0
  INNER JOIN DSN_Chicago_SSM_10 AS in1
     ON ((in0."DBA NAME" = in1.DBA_NAME) AND (in0."AKA NAME" = in1.AKA_NAME))

),

DSN_Chicago_SSM_12 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('13_Chicago_FI_Fact_Tables', 'DSN_Chicago_SSM_12') }}

),

DSN_Chicago_SSM_62 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('13_Chicago_FI_Fact_Tables', 'DSN_Chicago_SSM_62') }}

),

DSN_Chicago_SSM_18 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('13_Chicago_FI_Fact_Tables', 'DSN_Chicago_SSM_18') }}

),

DSN_Chicago_SSM_14 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('13_Chicago_FI_Fact_Tables', 'DSN_Chicago_SSM_14') }}

),

Join_11_inner AS (

  SELECT 
    in0.RIGHT_DI_CREATEDATE AS LEFT_RIGHT_DI_CREATEDATE,
    in0.RIGHT_DI_WORKFLOWDIRECTORY AS LEFT_RIGHT_DI_WORKFLOWDIRECTORY,
    in0.RIGHT_DI_WORKFLOWFILENAME AS LEFT_RIGHT_DI_WORKFLOWFILENAME,
    in1.DI_CREATEDATE AS RIGHT_DI_CREATEDATE,
    in1.DI_WORKFLOWDIRECTORY AS RIGHT_DI_WORKFLOWDIRECTORY,
    in1.DI_WORKFLOWFILENAME AS RIGHT_DI_WORKFLOWFILENAME,
    in0.* EXCLUDE ("RIGHT_DI_CREATEDATE", "RIGHT_DI_WORKFLOWDIRECTORY", "RIGHT_DI_WORKFLOWFILENAME"),
    in1.* EXCLUDE ("DI_CREATEDATE", "DI_WORKFLOWDIRECTORY", "DI_WORKFLOWFILENAME")
  
  FROM Join_9_inner AS in0
  INNER JOIN DSN_Chicago_SSM_12 AS in1
     ON (in0."INSPECTION TYPE" = in1.INSPECTIONTYPE)

),

Join_13_inner AS (

  SELECT 
    in0.RIGHT_DI_CREATEDATE AS LEFT_LEFT_RIGHT_DI_CREATEDATE,
    in0.RIGHT_DI_WORKFLOWDIRECTORY AS LEFT_LEFT_RIGHT_DI_WORKFLOWDIRECTORY,
    in0.RIGHT_DI_WORKFLOWFILENAME AS LEFT_LEFT_RIGHT_DI_WORKFLOWFILENAME,
    in0.RIGHT_DI_CREATEDATE AS LEFT_RIGHT_DI_CREATEDATE,
    in0.RIGHT_DI_WORKFLOWDIRECTORY AS LEFT_RIGHT_DI_WORKFLOWDIRECTORY,
    in0.RIGHT_DI_WORKFLOWFILENAME AS LEFT_RIGHT_DI_WORKFLOWFILENAME,
    in1.RESULTSSK AS RIGHT_RESULTSSK,
    in1.RESULTS AS RIGHT_RESULTS,
    in1.DI_CREATEDATE AS RIGHT_DI_CREATEDATE,
    in1.DI_WORKFLOWDIRECTORY AS RIGHT_DI_WORKFLOWDIRECTORY,
    in1.DI_WORKFLOWFILENAME AS RIGHT_DI_WORKFLOWFILENAME,
    in0.* EXCLUDE ("LEFT_RIGHT_DI_CREATEDATE", 
    "LEFT_RIGHT_DI_WORKFLOWDIRECTORY", 
    "LEFT_RIGHT_DI_WORKFLOWFILENAME", 
    "RIGHT_DI_CREATEDATE", 
    "RIGHT_DI_WORKFLOWDIRECTORY", 
    "RIGHT_DI_WORKFLOWFILENAME"),
    in1.* EXCLUDE ("RESULTSSK", "RESULTS", "DI_CREATEDATE", "DI_WORKFLOWDIRECTORY", "DI_WORKFLOWFILENAME")
  
  FROM Join_11_inner AS in0
  INNER JOIN DSN_Chicago_SSM_14 AS in1
     ON (in0.RESULTS = in1.RESULTS)

),

DSN_Chicago_SSM_16 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('13_Chicago_FI_Fact_Tables', 'DSN_Chicago_SSM_16') }}

),

Join_15_inner AS (

  SELECT 
    in1.RISK AS RIGHT_RISK,
    in1.DI_CREATEDATE AS RIGHT_DI_CREATEDATE,
    in1.DI_WORKFLOWDIRECTORY AS RIGHT_DI_WORKFLOWDIRECTORY,
    in1.DI_WORKFLOWFILENAME AS RIGHT_DI_WORKFLOWFILENAME,
    in0.* EXCLUDE ("RIGHT_DI_CREATEDATE", "RIGHT_DI_WORKFLOWDIRECTORY", "RIGHT_DI_WORKFLOWFILENAME"),
    in1.* EXCLUDE ("RISK", "DI_CREATEDATE", "DI_WORKFLOWDIRECTORY", "DI_WORKFLOWFILENAME")
  
  FROM Join_13_inner AS in0
  INNER JOIN DSN_Chicago_SSM_16 AS in1
     ON (in0.RISK = in1.RISK)

),

Join_17_inner AS (

  SELECT 
    in0.RIGHT_DI_CREATEDATE AS LEFT_RIGHT_DI_CREATEDATE,
    in0.RIGHT_DI_WORKFLOWDIRECTORY AS LEFT_RIGHT_DI_WORKFLOWDIRECTORY,
    in0.RIGHT_DI_WORKFLOWFILENAME AS LEFT_RIGHT_DI_WORKFLOWFILENAME,
    in1.DI_CREATEDATE AS RIGHT_DI_CREATEDATE,
    in1.DI_WORKFLOWDIRECTORY AS RIGHT_DI_WORKFLOWDIRECTORY,
    in1.DI_WORKFLOWFILENAME AS RIGHT_DI_WORKFLOWFILENAME,
    in0.* EXCLUDE ("RIGHT_DI_CREATEDATE", 
    "RIGHT_DI_WORKFLOWDIRECTORY", 
    "RIGHT_DI_WORKFLOWFILENAME", 
    "LEFT_RIGHT_DI_CREATEDATE", 
    "LEFT_RIGHT_DI_WORKFLOWDIRECTORY", 
    "LEFT_RIGHT_DI_WORKFLOWFILENAME"),
    in1.* EXCLUDE ("DI_CREATEDATE", "DI_WORKFLOWDIRECTORY", "DI_WORKFLOWFILENAME")
  
  FROM Join_15_inner AS in0
  INNER JOIN DSN_Chicago_SSM_18 AS in1
     ON (in0."FACILITY TYPE" = in1.FACILITYTYPE)

),

Join_27_inner AS (

  SELECT 
    in0.RIGHT_DI_CREATEDATE AS LEFT_RIGHT_DI_CREATEDATE,
    in1.STATE AS RIGHT_STATE,
    in0.CITY AS CITY,
    in0.RESTAURANTSK AS RESTAURANTSK,
    in0.FACILITYSK AS FACILITYSK,
    in1.DI_WORKFLOWDIRECTORY AS RIGHT_DI_WORKFLOWDIRECTORY,
    in0.LOCATION AS LOCATION,
    in0.LATITUDE AS LATITUDE,
    in0.ZIP AS ZIP,
    in0.STATE AS STATE,
    in0.LEFT_RIGHT_DI_WORKFLOWDIRECTORY AS LEFT_LEFT_LEFT_RIGHT_DI_WORKFLOWDIRECTORY,
    in0.RIGHT_RESULTSSK AS RIGHT_RESULTSSK,
    in0.RIGHT_DI_WORKFLOWDIRECTORY AS LEFT_RIGHT_DI_WORKFLOWDIRECTORY,
    in0."AKA NAME" AS "AKA NAME",
    in0.RIGHT_RISK AS RIGHT_RISK,
    in0.AKA_NAME AS AKA_NAME,
    in0.RISK AS RISK,
    in0.LONGITUDE AS LONGITUDE,
    in1.ZIP AS RIGHT_ZIP,
    in0.LEFT_RIGHT_DI_WORKFLOWFILENAME AS LEFT_LEFT_LEFT_RIGHT_DI_WORKFLOWFILENAME,
    in0.DBA_NAME AS DBA_NAME,
    in0."DBA NAME" AS "DBA NAME",
    in0.INSPECTIONTYPESK AS INSPECTIONTYPESK,
    in1.ADDRESS AS RIGHT_ADDRESS,
    in0."LICENSE HASH" AS "LICENSE HASH",
    in0.INSPECTION_DATE AS INSPECTION_DATE,
    in0.RESULTS AS RESULTS,
    in0.INSPECTIONTYPE AS INSPECTIONTYPE,
    in1.GEOSK AS RIGHT_GEOSK,
    in0."FACILITY TYPE" AS "FACILITY TYPE",
    in0.RIGHT_RESULTS AS RIGHT_RESULTS,
    in0."INSPECTION DATE" AS "INSPECTION DATE",
    in1.DI_WORKFLOWFILENAME AS RIGHT_DI_WORKFLOWFILENAME,
    in0.FACILITYTYPE AS FACILITYTYPE,
    in1.LOCATION AS RIGHT_LOCATION,
    in1.LONGITUDE AS RIGHT_LONGITUDE,
    in0.ADDRESS AS ADDRESS,
    in1.CITY AS RIGHT_CITY,
    in0.LEFT_RIGHT_DI_CREATEDATE AS LEFT_LEFT_LEFT_RIGHT_DI_CREATEDATE,
    in0."INSPECTION TYPE" AS "INSPECTION TYPE",
    in0.VIOLATIONS AS VIOLATIONS,
    in1.LATITUDE AS RIGHT_LATITUDE,
    in0.RIGHT_DI_WORKFLOWFILENAME AS LEFT_RIGHT_DI_WORKFLOWFILENAME,
    in0.RISKSK AS RISKSK,
    in0."INSPECTION ID" AS "INSPECTION ID",
    in1.DI_CREATEDATE AS RIGHT_DI_CREATEDATE
  
  FROM Join_17_inner AS in0
  INNER JOIN DSN_Chicago_SSM_62 AS in1
     ON (
      (
        (
          (
            (((in0.ADDRESS = in1.ADDRESS) AND (in0.CITY = in1.CITY)) AND (in0.STATE = in1.STATE))
            AND (in0.ZIP = in1.ZIP)
          )
          AND (in0.LATITUDE = in1.LATITUDE)
        )
        AND (in0.LONGITUDE = in1.LONGITUDE)
      )
      AND (in0.LOCATION = in1.LOCATION)
    )

),

RecordID_24 AS (

  {{
    prophecy_basics.RecordID(
      ['Join_27_inner'], 
      'incremental_id', 
      'INSPECTIONDATESK', 
      'integer', 
      6, 
      1, 
      'tableLevel', 
      'first_column', 
      [], 
      []
    )
  }}

),

Formula_29_0 AS (

  SELECT 
    (TO_TIMESTAMP(CURRENT_TIMESTAMP)) AS DI_CREATEDATE,
    CAST({{ var('WORKFLOW_NAME') }} AS STRING) AS DI_WORKFLOWFILENAME,
    *
  
  FROM RecordID_24 AS in0

)

SELECT *

FROM Formula_29_0
