pipelines:
  "4_CRIS_Period_Comparison":
    visualGroups:
      OpenPosition:
        isCollapsed: false
        height: 1493.1666259765625
        width: 2320
        nodes:
        - "AlteryxSelect_225"
        - "AlteryxSelect_226"
        - "AlteryxSelect_228"
        - "AlteryxSelect_233"
        - "AppendFields_229"
        - "Filter_220"
        - "Filter_227"
        - "Filter_232"
        - "FindReplace_221_0"
        - "FindReplace_221_allRules"
        - "FindReplace_221_join"
        - "FindReplace_221_reorg_0"
        - "FindReplace_222_0"
        - "FindReplace_222_allRules"
        - "FindReplace_222_join"
        - "FindReplace_222_reorg_0"
        - "FindReplace_231_0"
        - "FindReplace_231_allRules"
        - "FindReplace_231_join"
        - "FindReplace_231_reorg_0"
        - "Formula_223_0"
        - "Formula_224_0"
        - "Formula_230_0"
        - "Formula_235_0"
        - "Formula_236_0"
        - "Formula_237_0"
        - "Join_219_inner"
        - "Join_219_left"
        - "Join_219_right"
        - "Transpose_217"
        - "Transpose_217_schemaTransform_0"
        - "Transpose_218"
        - "Transpose_218_schemaTransform_0"
        - "Unique_234"
  FDI_HL_Owned_Loans_Tertiary_Monthly:
    visualGroups:
      FDIHLOwnedLoansSummary:
        isCollapsed: false
        height: 1233
        width: 1716
        nodes:
        - "First3months"
        - "Formula_41_0"
        - "Next3months"
        - "PublishtoSLF"
        - "PublishtoTableau"
        - "Union_39"
      First3months:
        isCollapsed: false
        height: 399
        width: 386
        nodes:
        - "Source__User_Db_42"
      Next3months:
        isCollapsed: false
        height: 399
        width: 386
        nodes:
        - "Source__User_Db_45"
      PublishtoSLF:
        isCollapsed: false
        height: 399
        width: 316
        nodes:
        - "Macro_50"
      PublishtoTableau:
        isCollapsed: false
        height: 399
        width: 366
        nodes:
        - "Macro_48"
  FDI_Treasury_Altx_Sol_FAS107_2025_Q1:
    visualGroups:
      CodeCurrentMonth:
        isCollapsed: false
        height: 280
        width: 1200
        nodes:
        - "DateTime_253_0"
        - "DateTime_254_0"
        - "DateTime_255_0"
        - "Formula_256_0"
        - "Formula_256_1"
        - "Formula_256_2"
      Container138:
        isCollapsed: false
        height: 555.3333129882812
        width: 2400
        nodes:
        - "AlteryxSelect_262"
        - "AlteryxSelect_264"
        - "AlteryxSelect_292"
        - "AppendFields_265"
        - "AppendFields_290"
        - "DbFileOutput_26_266"
        - "DbFileOutput_28_289"
        - "Filter_293"
        - "Formula_261_0"
        - "Formula_261_1"
        - "Formula_261_2"
        - "Formula_263_to_Formula_259_0"
        - "Formula_263_to_Formula_259_1"
        - "Formula_263_to_Formula_259_2"
        - "Formula_263_to_Formula_259_3"
        - "Formula_291_0"
        - "Formula_291_1"
        - "Formula_291_2"
        - "Summarize_260"
      SnowflakeCDDataAggregationPreviouslyRCode:
        isCollapsed: false
        height: 755.3333129882812
        width: 3885
        nodes:
        - "CodeCurrentMonth"
        - "Container138"
      SnowflakePrep:
        isCollapsed: false
        height: 315
        width: 1000
        nodes:
        - "AppendFields_252"
        - "Filter_251"
        - "Formula_248_0"
        - "Formula_248_1"
        - "Macro_243"
      SnowflakeSoxControlPull:
        isCollapsed: false
        height: 550
        width: 1860
        nodes:
        - "AlteryxSelect_271"
        - "AppendFields_282"
        - "AppendFields_283"
        - "DbFileOutput_27_277"
        - "DbFileOutput_28_281"
        - "Formula_273_0"
        - "Formula_273_1"
        - "Formula_280_0"
        - "ICDW_DEPBAL_CC__269"
        - "Join_270_left_UnionLeftOuter"
        - "RecordID_275"
        - "Summarize_274"
        - "Summarize_279"
  Op_Lease_Tax_Billing_and_Tax_Income_Prophecy_Usecase_Final:
    visualGroups:
      OpLeaseTaxBillingandTaxIncomeChangepyyyymmtocurrmonthRunSecond:
        isCollapsed: false
        height: 1914
        width: 4534
        nodes:
        - "AlteryxSelect_36"
        - "AlteryxSelect_37"
        - "AlteryxSelect_40"
        - "AlteryxSelect_41"
        - "AlteryxSelect_42"
        - "AlteryxSelect_45"
        - "Filter_39"
        - "Filter_44"
        - "Formula_38_0"
        - "Formula_43_0"
        - "Formula_56_0"
        - "Formula_57_0"
        - "Summarize_48"
        - "Summarize_49"
        - "Summarize_52"
        - "Summarize_53"
        - "Union_46"
        - "Union_46_reformat_0"
        - "Union_46_reformat_1"
        - "Union_47"
        - "Union_47_reformat_0"
        - "Union_47_reformat_1"
        - "Union_47_reformat_2"
        - "output_xlsx_Que_50"
        - "output_xlsx_Que_51"
        - "p_202504_xlsx_Q_35"
        - "state_202504_xl_34"
        - "tax_bill_202504_33"
