---
version: 2
models:
- name: "1_CRIS_Get_Source_Data__Formula_207_0"
  tags:
  - "prophecy_temp"
- name: "1_CRIS_Get_Source_Data__TextInput_218_cast"
  tags:
  - "prophecy_temp"
- name: "1_CRIS_Get_Source_Data__aka_GPD_UDDL_Wr_198"
  tags:
  - "prophecy_temp"
- name: "1_CRIS_Get_Source_Data__aka_GPD_UDDL_Wr_200"
  tags:
  - "prophecy_temp"
- name: "1_CRIS_Get_Source_Data__aka_GPD_UDDL_Wr_205"
  tags:
  - "prophecy_temp"
- name: "1_CRIS_Get_Source_Data__aka_GPD_UDDL_Wr_212"
  tags:
  - "prophecy_temp"
- name: "1_CRIS_Get_Source_Data__aka_GPD_UDDL_Wr_216"
  tags:
  - "prophecy_temp"
