{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH DBATTRIBUTE AS (

  SELECT * 
  
  FROM {{ ref('sf')}}

),

SQ_CLIENT_ALIAS AS (

  SELECT 
    /*+ parallel(C) parallel(P) use_hash(C P)*/
    DISTINCT C.CLID,
    P.CUSTOMER_NUMBER
  
  FROM CLIENT_ALIAS AS C, WORK_CARDS_ORIG_STAGING AS P
  
  WHERE ltrim(rtrim(C.SOURCE_CLIENT_REF (+))) = ltrim(rtrim(P.CUSTOMER_NUMBER))
        AND C.ETO (+) IS NULL
        AND C.SOURCE_TYPE (+) = 0
        AND C.SOURCE_SYSTEM_CODE (+) = 'U'
        AND C.CLASS (+) = '585'
        AND P.CUSTOMER_NUMBER IS NOT NULL

),

Shortcut_to_SEQ_clid_EXPR_4 AS (

  SELECT 
    CLID AS CLID,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    (((ROW_NUMBER() OVER (PARTITION BY 1)) - 1) + 1) AS GENERATED_CLID
  
  FROM SQ_CLIENT_ALIAS AS in0

),

Shortcut_to_SEQ_adid_EXPR_5 AS (

  SELECT 
    CLID AS CLID,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    GENERATED_CLID AS GENERATED_CLID,
    (((ROW_NUMBER() OVER (PARTITION BY 1)) - 1) + 1) AS ADID
  
  FROM Shortcut_to_SEQ_clid_EXPR_4 AS in0

),

EXP_CLIENT_ALIAS_LKP_LOCAL_1_LOOKUP_8 AS (

  SELECT 
    in0.CURRVALUE AS LOOKUP_VARIABLE_2,
    in0.NAME AS NAME,
    in0.CURRVALUE AS CURRVALUE,
    in1.CLID AS CLID,
    in1.CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    in1.GENERATED_CLID AS GENERATED_CLID,
    in1.ADID AS ADID
  
  FROM DBATTRIBUTE AS in0
  LEFT JOIN Shortcut_to_SEQ_adid_EXPR_5 AS in1
     ON (in0.NAME = 'businessdate')

),

EXP_CLIENT_ALIAS_LKP_LOCAL_1_VARS_0 AS (

  SELECT 
    LOOKUP_VARIABLE_2 AS business_date_string__find_business_date_lkp_1,
    'businessdate' AS lookup_string,
    *
  
  FROM EXP_CLIENT_ALIAS_LKP_LOCAL_1_LOOKUP_8 AS in0

),

EXP_CLIENT_ALIAS_LKP_LOCAL_1 AS (

  SELECT 
    GENERATED_CLID AS GENERATED_CLID,
    CLID AS CLID,
    ADID AS ADID,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER
  
  FROM EXP_CLIENT_ALIAS_LKP_LOCAL_1_VARS_0 AS in0

),

EXP_CLIENT_ALIAS AS (

  SELECT 
    NEXTVAL AS GENERATED_CLID,
    CLID AS CLID,
    NEXTVAL AS ADID,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    (LTRIM((RTRIM(CUSTOMER_NUMBER)))) AS CUSTOMER_NUMBER_SHORT,
    0 AS SOURCE_TYPE,
    'U' AS SOURCE_SYSTEM_CODE,
    585 AS CLIENT_ALIAS_CLASS,
    450 AS RESIDES_CLASS,
    businessdate AS business_date,
    (
      CASE
        WHEN (count1 = 1)
          THEN CAST((FEED_NUMBER_GENERATOR1('U', 360, business_date_string, SUBSTRING(business_date_string, 0, 8))) AS STRING)
        ELSE NULL
      END
    ) AS feed_update_id
  
  FROM EXP_CLIENT_ALIAS_LKP_LOCAL_1 AS in0

),

RTR_CLIENT_ALIAS AS (

  SELECT * 
  
  FROM EXP_CLIENT_ALIAS AS in0
  
  WHERE (CLID IS NULL)

),

RTR_CLIENT_ALIAS_EXPR_NEW_CLIENT_ALIAS AS (

  SELECT 
    GENERATED_CLID AS GENERATED_CLID1,
    CLID AS CLID1,
    ADID AS ADID1,
    CUSTOMER_NUMBER AS CUSTOMER_NUMBER1,
    CUSTOMER_NUMBER_SHORT AS CUSTOMER_NUMBER_SHORT1,
    SOURCE_TYPE AS SOURCE_TYPE1,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE1,
    CLIENT_ALIAS_CLASS AS CLIENT_ALIAS_CLASS1,
    RESIDES_CLASS AS RESIDES_CLASS1,
    business_date AS business_date1,
    feed_update_id AS feed_update_id1,
    GENERATED_CLID AS CLID,
    business_date AS CLIENT_HISTORY_EFFECT_FROM,
    feed_update_id AS FEED_UPDATE_ID
  
  FROM RTR_CLIENT_ALIAS AS in0

)

SELECT *

FROM RTR_CLIENT_ALIAS_EXPR_NEW_CLIENT_ALIAS
