---
version: 2
models:
- name: "m_rep_cards_orig_client_alias_update__CHOOSES"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_alias_update__CLIENT_ALIAS1"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_alias_update__EXP_CLIENT_ALIAS_LOOKUP_6"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_alias_update__RESIDES"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_alias_update__RTR_CLIENT_ALIAS_EXPR_NEW_CLIENT_ALIAS"
  tags:
  - "prophecy_temp"
