---
version: 2
models:
- name: "110_2015_Day_7_Main_AndrewMerrill__AppendFields_32"
  tags:
  - "prophecy_temp"
- name: "110_2015_Day_7_Main_AndrewMerrill__MultiRowFormula_25_row_id_drop_0"
  tags:
  - "prophecy_temp"
