{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "anurag_test"
  })
}}

WITH Download_21_21 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('Billboard_Webscraping_App', 'Download_21_21') }}

),

Download_21_21_cleanup_0 AS (

  SELECT 
    api_data AS DownloadData,
    NULL AS DownloadHeaders,
    * EXCEPT (`_paramsOrData`, `_processedUrl`, `api_data`)
  
  FROM Download_21_21 AS in0

),

RegEx_22 AS (

  {{
    prophecy_basics.Regex(
      ['Download_21_21_cleanup_0'], 
      [{ 'columnName': 'hash1 Song', 'dataType': 'String', 'rgxExpression': '(.+?)' }], 
      '[{"name": "DownloadData", "dataType": "String"}, {"name": "DownloadHeaders", "dataType": "Integer"}, {"name": "URL", "dataType": "String"}]', 
      'DownloadData', 
      'u-letter-spacing-0028@tablet">(.+?)</h3>', 
      'parse', 
      true, 
      false, 
      '', 
      false, 
      'splitColumns', 
      1, 
      'dropExtraWithoutWarning', 
      '', 
      '', 
      false
    )
  }}

),

RegEx_23 AS (

  {{
    prophecy_basics.Regex(
      ['RegEx_22'], 
      [{ 'columnName': 'hash1 Artist', 'dataType': 'String', 'rgxExpression': '(.+?)' }], 
      '[{"name": "DownloadData", "dataType": "String"}, {"name": "DownloadHeaders", "dataType": "Integer"}, {"name": "URL", "dataType": "String"}, {"name": "hash1 Song", "dataType": "String"}]', 
      'DownloadData', 
      'u-font-size-20@tablet"\s>(.+?)</span>', 
      'parse', 
      true, 
      false, 
      '', 
      false, 
      'splitColumns', 
      1, 
      'dropExtraWithoutWarning', 
      '', 
      '', 
      false
    )
  }}

),

RegEx_24 AS (

  {{
    prophecy_basics.Regex(
      ['RegEx_23'], 
      [{ 'columnName': 'regex_col1', 'dataType': 'string', 'rgxExpression': '(.+?)' }], 
      '[{"name": "DownloadData", "dataType": "String"}, {"name": "DownloadHeaders", "dataType": "Integer"}, {"name": "URL", "dataType": "String"}, {"name": "hash1 Song", "dataType": "String"}, {"name": "hash1 Artist", "dataType": "String"}]', 
      'DownloadData', 
      'u-max-width-230@tablet-only">(.+?)</h3>', 
      'tokenize', 
      true, 
      false, 
      '', 
      false, 
      'splitColumns', 
      99, 
      'dropExtraWithoutWarning', 
      'Song', 
      '', 
      false
    )
  }}

),

RegEx_25 AS (

  {{
    prophecy_basics.Regex(
      ['RegEx_24'], 
      [{ 'columnName': 'regex_col1', 'dataType': 'string', 'rgxExpression': '(.+?)' }], 
      '[{"name": "DownloadData", "dataType": "String"}, {"name": "DownloadHeaders", "dataType": "Integer"}, {"name": "URL", "dataType": "String"}, {"name": "hash1 Song", "dataType": "String"}, {"name": "hash1 Artist", "dataType": "String"}, {"name": "Song1", "dataType": "String"}, {"name": "Song2", "dataType": "String"}, {"name": "Song3", "dataType": "String"}, {"name": "Song4", "dataType": "String"}, {"name": "Song5", "dataType": "String"}, {"name": "Song6", "dataType": "String"}, {"name": "Song7", "dataType": "String"}, {"name": "Song8", "dataType": "String"}, {"name": "Song9", "dataType": "String"}, {"name": "Song10", "dataType": "String"}, {"name": "Song11", "dataType": "String"}, {"name": "Song12", "dataType": "String"}, {"name": "Song13", "dataType": "String"}, {"name": "Song14", "dataType": "String"}, {"name": "Song15", "dataType": "String"}, {"name": "Song16", "dataType": "String"}, {"name": "Song17", "dataType": "String"}, {"name": "Song18", "dataType": "String"}, {"name": "Song19", "dataType": "String"}, {"name": "Song20", "dataType": "String"}, {"name": "Song21", "dataType": "String"}, {"name": "Song22", "dataType": "String"}, {"name": "Song23", "dataType": "String"}, {"name": "Song24", "dataType": "String"}, {"name": "Song25", "dataType": "String"}, {"name": "Song26", "dataType": "String"}, {"name": "Song27", "dataType": "String"}, {"name": "Song28", "dataType": "String"}, {"name": "Song29", "dataType": "String"}, {"name": "Song30", "dataType": "String"}, {"name": "Song31", "dataType": "String"}, {"name": "Song32", "dataType": "String"}, {"name": "Song33", "dataType": "String"}, {"name": "Song34", "dataType": "String"}, {"name": "Song35", "dataType": "String"}, {"name": "Song36", "dataType": "String"}, {"name": "Song37", "dataType": "String"}, {"name": "Song38", "dataType": "String"}, {"name": "Song39", "dataType": "String"}, {"name": "Song40", "dataType": "String"}, {"name": "Song41", "dataType": "String"}, {"name": "Song42", "dataType": "String"}, {"name": "Song43", "dataType": "String"}, {"name": "Song44", "dataType": "String"}, {"name": "Song45", "dataType": "String"}, {"name": "Song46", "dataType": "String"}, {"name": "Song47", "dataType": "String"}, {"name": "Song48", "dataType": "String"}, {"name": "Song49", "dataType": "String"}, {"name": "Song50", "dataType": "String"}, {"name": "Song51", "dataType": "String"}, {"name": "Song52", "dataType": "String"}, {"name": "Song53", "dataType": "String"}, {"name": "Song54", "dataType": "String"}, {"name": "Song55", "dataType": "String"}, {"name": "Song56", "dataType": "String"}, {"name": "Song57", "dataType": "String"}, {"name": "Song58", "dataType": "String"}, {"name": "Song59", "dataType": "String"}, {"name": "Song60", "dataType": "String"}, {"name": "Song61", "dataType": "String"}, {"name": "Song62", "dataType": "String"}, {"name": "Song63", "dataType": "String"}, {"name": "Song64", "dataType": "String"}, {"name": "Song65", "dataType": "String"}, {"name": "Song66", "dataType": "String"}, {"name": "Song67", "dataType": "String"}, {"name": "Song68", "dataType": "String"}, {"name": "Song69", "dataType": "String"}, {"name": "Song70", "dataType": "String"}, {"name": "Song71", "dataType": "String"}, {"name": "Song72", "dataType": "String"}, {"name": "Song73", "dataType": "String"}, {"name": "Song74", "dataType": "String"}, {"name": "Song75", "dataType": "String"}, {"name": "Song76", "dataType": "String"}, {"name": "Song77", "dataType": "String"}, {"name": "Song78", "dataType": "String"}, {"name": "Song79", "dataType": "String"}, {"name": "Song80", "dataType": "String"}, {"name": "Song81", "dataType": "String"}, {"name": "Song82", "dataType": "String"}, {"name": "Song83", "dataType": "String"}, {"name": "Song84", "dataType": "String"}, {"name": "Song85", "dataType": "String"}, {"name": "Song86", "dataType": "String"}, {"name": "Song87", "dataType": "String"}, {"name": "Song88", "dataType": "String"}, {"name": "Song89", "dataType": "String"}, {"name": "Song90", "dataType": "String"}, {"name": "Song91", "dataType": "String"}, {"name": "Song92", "dataType": "String"}, {"name": "Song93", "dataType": "String"}, {"name": "Song94", "dataType": "String"}, {"name": "Song95", "dataType": "String"}, {"name": "Song96", "dataType": "String"}, {"name": "Song97", "dataType": "String"}, {"name": "Song98", "dataType": "String"}, {"name": "Song99", "dataType": "String"}]', 
      'DownloadData', 
      'u-max-width-230@tablet-only"\s>(.+?)</span>', 
      'tokenize', 
      true, 
      false, 
      '', 
      false, 
      'splitColumns', 
      99, 
      'dropExtraWithoutWarning', 
      'Artist', 
      '', 
      false
    )
  }}

),

Cleanse_26 AS (

  {{
    prophecy_basics.DataCleansing(
      ['RegEx_25'], 
      [
        { "name": "DownloadData", "dataType": "String" }, 
        { "name": "DownloadHeaders", "dataType": "Integer" }, 
        { "name": "URL", "dataType": "String" }, 
        { "name": "hash1 Song", "dataType": "String" }, 
        { "name": "hash1 Artist", "dataType": "String" }, 
        { "name": "Song1", "dataType": "String" }, 
        { "name": "Song2", "dataType": "String" }, 
        { "name": "Song3", "dataType": "String" }, 
        { "name": "Song4", "dataType": "String" }, 
        { "name": "Song5", "dataType": "String" }, 
        { "name": "Song6", "dataType": "String" }, 
        { "name": "Song7", "dataType": "String" }, 
        { "name": "Song8", "dataType": "String" }, 
        { "name": "Song9", "dataType": "String" }, 
        { "name": "Song10", "dataType": "String" }, 
        { "name": "Song11", "dataType": "String" }, 
        { "name": "Song12", "dataType": "String" }, 
        { "name": "Song13", "dataType": "String" }, 
        { "name": "Song14", "dataType": "String" }, 
        { "name": "Song15", "dataType": "String" }, 
        { "name": "Song16", "dataType": "String" }, 
        { "name": "Song17", "dataType": "String" }, 
        { "name": "Song18", "dataType": "String" }, 
        { "name": "Song19", "dataType": "String" }, 
        { "name": "Song20", "dataType": "String" }, 
        { "name": "Song21", "dataType": "String" }, 
        { "name": "Song22", "dataType": "String" }, 
        { "name": "Song23", "dataType": "String" }, 
        { "name": "Song24", "dataType": "String" }, 
        { "name": "Song25", "dataType": "String" }, 
        { "name": "Song26", "dataType": "String" }, 
        { "name": "Song27", "dataType": "String" }, 
        { "name": "Song28", "dataType": "String" }, 
        { "name": "Song29", "dataType": "String" }, 
        { "name": "Song30", "dataType": "String" }, 
        { "name": "Song31", "dataType": "String" }, 
        { "name": "Song32", "dataType": "String" }, 
        { "name": "Song33", "dataType": "String" }, 
        { "name": "Song34", "dataType": "String" }, 
        { "name": "Song35", "dataType": "String" }, 
        { "name": "Song36", "dataType": "String" }, 
        { "name": "Song37", "dataType": "String" }, 
        { "name": "Song38", "dataType": "String" }, 
        { "name": "Song39", "dataType": "String" }, 
        { "name": "Song40", "dataType": "String" }, 
        { "name": "Song41", "dataType": "String" }, 
        { "name": "Song42", "dataType": "String" }, 
        { "name": "Song43", "dataType": "String" }, 
        { "name": "Song44", "dataType": "String" }, 
        { "name": "Song45", "dataType": "String" }, 
        { "name": "Song46", "dataType": "String" }, 
        { "name": "Song47", "dataType": "String" }, 
        { "name": "Song48", "dataType": "String" }, 
        { "name": "Song49", "dataType": "String" }, 
        { "name": "Song50", "dataType": "String" }, 
        { "name": "Song51", "dataType": "String" }, 
        { "name": "Song52", "dataType": "String" }, 
        { "name": "Song53", "dataType": "String" }, 
        { "name": "Song54", "dataType": "String" }, 
        { "name": "Song55", "dataType": "String" }, 
        { "name": "Song56", "dataType": "String" }, 
        { "name": "Song57", "dataType": "String" }, 
        { "name": "Song58", "dataType": "String" }, 
        { "name": "Song59", "dataType": "String" }, 
        { "name": "Song60", "dataType": "String" }, 
        { "name": "Song61", "dataType": "String" }, 
        { "name": "Song62", "dataType": "String" }, 
        { "name": "Song63", "dataType": "String" }, 
        { "name": "Song64", "dataType": "String" }, 
        { "name": "Song65", "dataType": "String" }, 
        { "name": "Song66", "dataType": "String" }, 
        { "name": "Song67", "dataType": "String" }, 
        { "name": "Song68", "dataType": "String" }, 
        { "name": "Song69", "dataType": "String" }, 
        { "name": "Song70", "dataType": "String" }, 
        { "name": "Song71", "dataType": "String" }, 
        { "name": "Song72", "dataType": "String" }, 
        { "name": "Song73", "dataType": "String" }, 
        { "name": "Song74", "dataType": "String" }, 
        { "name": "Song75", "dataType": "String" }, 
        { "name": "Song76", "dataType": "String" }, 
        { "name": "Song77", "dataType": "String" }, 
        { "name": "Song78", "dataType": "String" }, 
        { "name": "Song79", "dataType": "String" }, 
        { "name": "Song80", "dataType": "String" }, 
        { "name": "Song81", "dataType": "String" }, 
        { "name": "Song82", "dataType": "String" }, 
        { "name": "Song83", "dataType": "String" }, 
        { "name": "Song84", "dataType": "String" }, 
        { "name": "Song85", "dataType": "String" }, 
        { "name": "Song86", "dataType": "String" }, 
        { "name": "Song87", "dataType": "String" }, 
        { "name": "Song88", "dataType": "String" }, 
        { "name": "Song89", "dataType": "String" }, 
        { "name": "Song90", "dataType": "String" }, 
        { "name": "Song91", "dataType": "String" }, 
        { "name": "Song92", "dataType": "String" }, 
        { "name": "Song93", "dataType": "String" }, 
        { "name": "Song94", "dataType": "String" }, 
        { "name": "Song95", "dataType": "String" }, 
        { "name": "Song96", "dataType": "String" }, 
        { "name": "Song97", "dataType": "String" }, 
        { "name": "Song98", "dataType": "String" }, 
        { "name": "Song99", "dataType": "String" }, 
        { "name": "Artist1", "dataType": "String" }, 
        { "name": "Artist2", "dataType": "String" }, 
        { "name": "Artist3", "dataType": "String" }, 
        { "name": "Artist4", "dataType": "String" }, 
        { "name": "Artist5", "dataType": "String" }, 
        { "name": "Artist6", "dataType": "String" }, 
        { "name": "Artist7", "dataType": "String" }, 
        { "name": "Artist8", "dataType": "String" }, 
        { "name": "Artist9", "dataType": "String" }, 
        { "name": "Artist10", "dataType": "String" }, 
        { "name": "Artist11", "dataType": "String" }, 
        { "name": "Artist12", "dataType": "String" }, 
        { "name": "Artist13", "dataType": "String" }, 
        { "name": "Artist14", "dataType": "String" }, 
        { "name": "Artist15", "dataType": "String" }, 
        { "name": "Artist16", "dataType": "String" }, 
        { "name": "Artist17", "dataType": "String" }, 
        { "name": "Artist18", "dataType": "String" }, 
        { "name": "Artist19", "dataType": "String" }, 
        { "name": "Artist20", "dataType": "String" }, 
        { "name": "Artist21", "dataType": "String" }, 
        { "name": "Artist22", "dataType": "String" }, 
        { "name": "Artist23", "dataType": "String" }, 
        { "name": "Artist24", "dataType": "String" }, 
        { "name": "Artist25", "dataType": "String" }, 
        { "name": "Artist26", "dataType": "String" }, 
        { "name": "Artist27", "dataType": "String" }, 
        { "name": "Artist28", "dataType": "String" }, 
        { "name": "Artist29", "dataType": "String" }, 
        { "name": "Artist30", "dataType": "String" }, 
        { "name": "Artist31", "dataType": "String" }, 
        { "name": "Artist32", "dataType": "String" }, 
        { "name": "Artist33", "dataType": "String" }, 
        { "name": "Artist34", "dataType": "String" }, 
        { "name": "Artist35", "dataType": "String" }, 
        { "name": "Artist36", "dataType": "String" }, 
        { "name": "Artist37", "dataType": "String" }, 
        { "name": "Artist38", "dataType": "String" }, 
        { "name": "Artist39", "dataType": "String" }, 
        { "name": "Artist40", "dataType": "String" }, 
        { "name": "Artist41", "dataType": "String" }, 
        { "name": "Artist42", "dataType": "String" }, 
        { "name": "Artist43", "dataType": "String" }, 
        { "name": "Artist44", "dataType": "String" }, 
        { "name": "Artist45", "dataType": "String" }, 
        { "name": "Artist46", "dataType": "String" }, 
        { "name": "Artist47", "dataType": "String" }, 
        { "name": "Artist48", "dataType": "String" }, 
        { "name": "Artist49", "dataType": "String" }, 
        { "name": "Artist50", "dataType": "String" }, 
        { "name": "Artist51", "dataType": "String" }, 
        { "name": "Artist52", "dataType": "String" }, 
        { "name": "Artist53", "dataType": "String" }, 
        { "name": "Artist54", "dataType": "String" }, 
        { "name": "Artist55", "dataType": "String" }, 
        { "name": "Artist56", "dataType": "String" }, 
        { "name": "Artist57", "dataType": "String" }, 
        { "name": "Artist58", "dataType": "String" }, 
        { "name": "Artist59", "dataType": "String" }, 
        { "name": "Artist60", "dataType": "String" }, 
        { "name": "Artist61", "dataType": "String" }, 
        { "name": "Artist62", "dataType": "String" }, 
        { "name": "Artist63", "dataType": "String" }, 
        { "name": "Artist64", "dataType": "String" }, 
        { "name": "Artist65", "dataType": "String" }, 
        { "name": "Artist66", "dataType": "String" }, 
        { "name": "Artist67", "dataType": "String" }, 
        { "name": "Artist68", "dataType": "String" }, 
        { "name": "Artist69", "dataType": "String" }, 
        { "name": "Artist70", "dataType": "String" }, 
        { "name": "Artist71", "dataType": "String" }, 
        { "name": "Artist72", "dataType": "String" }, 
        { "name": "Artist73", "dataType": "String" }, 
        { "name": "Artist74", "dataType": "String" }, 
        { "name": "Artist75", "dataType": "String" }, 
        { "name": "Artist76", "dataType": "String" }, 
        { "name": "Artist77", "dataType": "String" }, 
        { "name": "Artist78", "dataType": "String" }, 
        { "name": "Artist79", "dataType": "String" }, 
        { "name": "Artist80", "dataType": "String" }, 
        { "name": "Artist81", "dataType": "String" }, 
        { "name": "Artist82", "dataType": "String" }, 
        { "name": "Artist83", "dataType": "String" }, 
        { "name": "Artist84", "dataType": "String" }, 
        { "name": "Artist85", "dataType": "String" }, 
        { "name": "Artist86", "dataType": "String" }, 
        { "name": "Artist87", "dataType": "String" }, 
        { "name": "Artist88", "dataType": "String" }, 
        { "name": "Artist89", "dataType": "String" }, 
        { "name": "Artist90", "dataType": "String" }, 
        { "name": "Artist91", "dataType": "String" }, 
        { "name": "Artist92", "dataType": "String" }, 
        { "name": "Artist93", "dataType": "String" }, 
        { "name": "Artist94", "dataType": "String" }, 
        { "name": "Artist95", "dataType": "String" }, 
        { "name": "Artist96", "dataType": "String" }, 
        { "name": "Artist97", "dataType": "String" }, 
        { "name": "Artist98", "dataType": "String" }, 
        { "name": "Artist99", "dataType": "String" }
      ], 
      'keepOriginal', 
      [
        'hash1 Song', 
        'hash1 Artist', 
        'Song1', 
        'Song2', 
        'Song3', 
        'Song4', 
        'Song5', 
        'Song6', 
        'Song7', 
        'Song8', 
        'Song9', 
        'Song10', 
        'Song11', 
        'Song12', 
        'Song13', 
        'Song14', 
        'Song15', 
        'Song16', 
        'Song17', 
        'Song18', 
        'Song19', 
        'Song20', 
        'Song21', 
        'Song22', 
        'Song23', 
        'Song24', 
        'Song25', 
        'Song26', 
        'Song27', 
        'Song28', 
        'Song29', 
        'Song30', 
        'Song31', 
        'Song32', 
        'Song33', 
        'Song34', 
        'Song35', 
        'Song36', 
        'Song37', 
        'Song38', 
        'Song39', 
        'Song40', 
        'Song41', 
        'Song42', 
        'Song43', 
        'Song44', 
        'Song45', 
        'Song46', 
        'Song47', 
        'Song48', 
        'Song49', 
        'Song50', 
        'Song51', 
        'Song52', 
        'Song53', 
        'Song54', 
        'Song55', 
        'Song56', 
        'Song57', 
        'Song58', 
        'Song59', 
        'Song60', 
        'Song61', 
        'Song62', 
        'Song63', 
        'Song64', 
        'Song65', 
        'Song66', 
        'Song67', 
        'Song68', 
        'Song69', 
        'Song70', 
        'Song71', 
        'Song72', 
        'Song73', 
        'Song74', 
        'Song75', 
        'Song76', 
        'Song77', 
        'Song78', 
        'Song79', 
        'Song80', 
        'Song81', 
        'Song82', 
        'Song83', 
        'Song84', 
        'Song85', 
        'Song86', 
        'Song87', 
        'Song88', 
        'Song89', 
        'Song90', 
        'Song91', 
        'Song92', 
        'Song93', 
        'Song94', 
        'Song95', 
        'Song96', 
        'Song97', 
        'Song98', 
        'Song99', 
        'Artist1', 
        'Artist2', 
        'Artist3', 
        'Artist4', 
        'Artist5', 
        'Artist6', 
        'Artist7', 
        'Artist8', 
        'Artist9', 
        'Artist10', 
        'Artist11', 
        'Artist12', 
        'Artist13', 
        'Artist14', 
        'Artist15', 
        'Artist16', 
        'Artist17', 
        'Artist18', 
        'Artist19', 
        'Artist20', 
        'Artist21', 
        'Artist22', 
        'Artist23', 
        'Artist24', 
        'Artist25', 
        'Artist26', 
        'Artist27', 
        'Artist28', 
        'Artist29', 
        'Artist30', 
        'Artist31', 
        'Artist32', 
        'Artist33', 
        'Artist34', 
        'Artist35', 
        'Artist36', 
        'Artist37', 
        'Artist38', 
        'Artist39', 
        'Artist40', 
        'Artist41', 
        'Artist42', 
        'Artist43', 
        'Artist44', 
        'Artist45', 
        'Artist46', 
        'Artist47', 
        'Artist48', 
        'Artist49', 
        'Artist50', 
        'Artist51', 
        'Artist52', 
        'Artist53', 
        'Artist54', 
        'Artist55', 
        'Artist56', 
        'Artist57', 
        'Artist58', 
        'Artist59', 
        'Artist60', 
        'Artist61', 
        'Artist62', 
        'Artist63', 
        'Artist64', 
        'Artist65', 
        'Artist66', 
        'Artist67', 
        'Artist68', 
        'Artist69', 
        'Artist70', 
        'Artist71', 
        'Artist72', 
        'Artist73', 
        'Artist74', 
        'Artist75', 
        'Artist76', 
        'Artist77', 
        'Artist78', 
        'Artist79', 
        'Artist80', 
        'Artist81', 
        'Artist82', 
        'Artist83', 
        'Artist84', 
        'Artist85', 
        'Artist86', 
        'Artist87', 
        'Artist88', 
        'Artist89', 
        'Artist90', 
        'Artist91', 
        'Artist92', 
        'Artist93', 
        'Artist94', 
        'Artist95', 
        'Artist96', 
        'Artist97', 
        'Artist98', 
        'Artist99'
      ], 
      true, 
      '', 
      true, 
      0, 
      true, 
      true, 
      false, 
      false, 
      false, 
      false, 
      false, 
      false, 
      '1970-01-01', 
      false, 
      '1970-01-01 00:00:00.0'
    )
  }}

),

MultiFieldFormula_27 AS (

  {{
    prophecy_basics.MultiColumnEdit(
      ['Cleanse_26'], 
      "regexp_replace(column_value, '&#039;', '\'')", 
      [
        'DownloadData', 
        'DownloadHeaders', 
        'URL', 
        'hash1 Song', 
        'hash1 Artist', 
        'Song1', 
        'Song2', 
        'Song3', 
        'Song4', 
        'Song5', 
        'Song6', 
        'Song7', 
        'Song8', 
        'Song9', 
        'Song10', 
        'Song11', 
        'Song12', 
        'Song13', 
        'Song14', 
        'Song15', 
        'Song16', 
        'Song17', 
        'Song18', 
        'Song19', 
        'Song20', 
        'Song21', 
        'Song22', 
        'Song23', 
        'Song24', 
        'Song25', 
        'Song26', 
        'Song27', 
        'Song28', 
        'Song29', 
        'Song30', 
        'Song31', 
        'Song32', 
        'Song33', 
        'Song34', 
        'Song35', 
        'Song36', 
        'Song37', 
        'Song38', 
        'Song39', 
        'Song40', 
        'Song41', 
        'Song42', 
        'Song43', 
        'Song44', 
        'Song45', 
        'Song46', 
        'Song47', 
        'Song48', 
        'Song49', 
        'Song50', 
        'Song51', 
        'Song52', 
        'Song53', 
        'Song54', 
        'Song55', 
        'Song56', 
        'Song57', 
        'Song58', 
        'Song59', 
        'Song60', 
        'Song61', 
        'Song62', 
        'Song63', 
        'Song64', 
        'Song65', 
        'Song66', 
        'Song67', 
        'Song68', 
        'Song69', 
        'Song70', 
        'Song71', 
        'Song72', 
        'Song73', 
        'Song74', 
        'Song75', 
        'Song76', 
        'Song77', 
        'Song78', 
        'Song79', 
        'Song80', 
        'Song81', 
        'Song82', 
        'Song83', 
        'Song84', 
        'Song85', 
        'Song86', 
        'Song87', 
        'Song88', 
        'Song89', 
        'Song90', 
        'Song91', 
        'Song92', 
        'Song93', 
        'Song94', 
        'Song95', 
        'Song96', 
        'Song97', 
        'Song98', 
        'Song99', 
        'Artist1', 
        'Artist2', 
        'Artist3', 
        'Artist4', 
        'Artist5', 
        'Artist6', 
        'Artist7', 
        'Artist8', 
        'Artist9', 
        'Artist10', 
        'Artist11', 
        'Artist12', 
        'Artist13', 
        'Artist14', 
        'Artist15', 
        'Artist16', 
        'Artist17', 
        'Artist18', 
        'Artist19', 
        'Artist20', 
        'Artist21', 
        'Artist22', 
        'Artist23', 
        'Artist24', 
        'Artist25', 
        'Artist26', 
        'Artist27', 
        'Artist28', 
        'Artist29', 
        'Artist30', 
        'Artist31', 
        'Artist32', 
        'Artist33', 
        'Artist34', 
        'Artist35', 
        'Artist36', 
        'Artist37', 
        'Artist38', 
        'Artist39', 
        'Artist40', 
        'Artist41', 
        'Artist42', 
        'Artist43', 
        'Artist44', 
        'Artist45', 
        'Artist46', 
        'Artist47', 
        'Artist48', 
        'Artist49', 
        'Artist50', 
        'Artist51', 
        'Artist52', 
        'Artist53', 
        'Artist54', 
        'Artist55', 
        'Artist56', 
        'Artist57', 
        'Artist58', 
        'Artist59', 
        'Artist60', 
        'Artist61', 
        'Artist62', 
        'Artist63', 
        'Artist64', 
        'Artist65', 
        'Artist66', 
        'Artist67', 
        'Artist68', 
        'Artist69', 
        'Artist70', 
        'Artist71', 
        'Artist72', 
        'Artist73', 
        'Artist74', 
        'Artist75', 
        'Artist76', 
        'Artist77', 
        'Artist78', 
        'Artist79', 
        'Artist80', 
        'Artist81', 
        'Artist82', 
        'Artist83', 
        'Artist84', 
        'Artist85', 
        'Artist86', 
        'Artist87', 
        'Artist88', 
        'Artist89', 
        'Artist90', 
        'Artist91', 
        'Artist92', 
        'Artist93', 
        'Artist94', 
        'Artist95', 
        'Artist96', 
        'Artist97', 
        'Artist98', 
        'Artist99'
      ], 
      [
        'hash1 Song', 
        'hash1 Artist', 
        'Song1', 
        'Song2', 
        'Song3', 
        'Song4', 
        'Song5', 
        'Song6', 
        'Song7', 
        'Song8', 
        'Song9', 
        'Song10', 
        'Song11', 
        'Song12', 
        'Song13', 
        'Song14', 
        'Song15', 
        'Song16', 
        'Song17', 
        'Song18', 
        'Song19', 
        'Song20', 
        'Song21', 
        'Song22', 
        'Song23', 
        'Song24', 
        'Song25', 
        'Song26', 
        'Song27', 
        'Song28', 
        'Song29', 
        'Song30', 
        'Song31', 
        'Song32', 
        'Song33', 
        'Song34', 
        'Song35', 
        'Song36', 
        'Song37', 
        'Song38', 
        'Song39', 
        'Song40', 
        'Song41', 
        'Song42', 
        'Song43', 
        'Song44', 
        'Song45', 
        'Song46', 
        'Song47', 
        'Song48', 
        'Song49', 
        'Song50', 
        'Song51', 
        'Song52', 
        'Song53', 
        'Song54', 
        'Song55', 
        'Song56', 
        'Song57', 
        'Song58', 
        'Song59', 
        'Song60', 
        'Song61', 
        'Song62', 
        'Song63', 
        'Song64', 
        'Song65', 
        'Song66', 
        'Song67', 
        'Song68', 
        'Song69', 
        'Song70', 
        'Song71', 
        'Song72', 
        'Song73', 
        'Song74', 
        'Song75', 
        'Song76', 
        'Song77', 
        'Song78', 
        'Song79', 
        'Song80', 
        'Song81', 
        'Song82', 
        'Song83', 
        'Song84', 
        'Song85', 
        'Song86', 
        'Song87', 
        'Song88', 
        'Song89', 
        'Song90', 
        'Song91', 
        'Song92', 
        'Song93', 
        'Song94', 
        'Song95', 
        'Song96', 
        'Song97', 
        'Song98', 
        'Song99', 
        'Artist1', 
        'Artist2', 
        'Artist3', 
        'Artist4', 
        'Artist5', 
        'Artist6', 
        'Artist7', 
        'Artist8', 
        'Artist9', 
        'Artist10', 
        'Artist11', 
        'Artist12', 
        'Artist13', 
        'Artist14', 
        'Artist15', 
        'Artist16', 
        'Artist17', 
        'Artist18', 
        'Artist19', 
        'Artist20', 
        'Artist21', 
        'Artist22', 
        'Artist23', 
        'Artist24', 
        'Artist25', 
        'Artist26', 
        'Artist27', 
        'Artist28', 
        'Artist29', 
        'Artist30', 
        'Artist31', 
        'Artist32', 
        'Artist33', 
        'Artist34', 
        'Artist35', 
        'Artist36', 
        'Artist37', 
        'Artist38', 
        'Artist39', 
        'Artist40', 
        'Artist41', 
        'Artist42', 
        'Artist43', 
        'Artist44', 
        'Artist45', 
        'Artist46', 
        'Artist47', 
        'Artist48', 
        'Artist49', 
        'Artist50', 
        'Artist51', 
        'Artist52', 
        'Artist53', 
        'Artist54', 
        'Artist55', 
        'Artist56', 
        'Artist57', 
        'Artist58', 
        'Artist59', 
        'Artist60', 
        'Artist61', 
        'Artist62', 
        'Artist63', 
        'Artist64', 
        'Artist65', 
        'Artist66', 
        'Artist67', 
        'Artist68', 
        'Artist69', 
        'Artist70', 
        'Artist71', 
        'Artist72', 
        'Artist73', 
        'Artist74', 
        'Artist75', 
        'Artist76', 
        'Artist77', 
        'Artist78', 
        'Artist79', 
        'Artist80', 
        'Artist81', 
        'Artist82', 
        'Artist83', 
        'Artist84', 
        'Artist85', 
        'Artist86', 
        'Artist87', 
        'Artist88', 
        'Artist89', 
        'Artist90', 
        'Artist91', 
        'Artist92', 
        'Artist93', 
        'Artist94', 
        'Artist95', 
        'Artist96', 
        'Artist97', 
        'Artist98', 
        'Artist99'
      ], 
      false, 
      'Suffix', 
      ''
    )
  }}

),

MultiFieldFormula_34 AS (

  {{
    prophecy_basics.MultiColumnEdit(
      ['MultiFieldFormula_27'], 
      "(REGEXP_REPLACE(column_value, '&amp;', '&'))", 
      [
        'DownloadData', 
        'DownloadHeaders', 
        'URL', 
        'hash1 Artist', 
        'Song2', 
        'Song4', 
        'Song6', 
        'Song8', 
        'Song10', 
        'Song12', 
        'Song14', 
        'Song16', 
        'Song18', 
        'Song20', 
        'Song22', 
        'Song24', 
        'Song26', 
        'Song28', 
        'Song30', 
        'Song32', 
        'Song34', 
        'Song36', 
        'Song38', 
        'Song40', 
        'Song42', 
        'Song44', 
        'Song46', 
        'Song48', 
        'Song50', 
        'Song52', 
        'Song54', 
        'Song56', 
        'Song58', 
        'Song60', 
        'Song62', 
        'Song64', 
        'Song66', 
        'Song68', 
        'Song70', 
        'Song72', 
        'Song74', 
        'Song76', 
        'Song78', 
        'Song80', 
        'Song82', 
        'Song84', 
        'Song86', 
        'Song88', 
        'Song90', 
        'Song92', 
        'Song94', 
        'Song96', 
        'Song98', 
        'Artist1', 
        'Artist3', 
        'Artist5', 
        'Artist7', 
        'Artist9', 
        'Artist11', 
        'Artist13', 
        'Artist15', 
        'Artist17', 
        'Artist19', 
        'Artist21', 
        'Artist23', 
        'Artist25', 
        'Artist27', 
        'Artist29', 
        'Artist31', 
        'Artist33', 
        'Artist35', 
        'Artist37', 
        'Artist39', 
        'Artist41', 
        'Artist43', 
        'Artist45', 
        'Artist47', 
        'Artist49', 
        'Artist51', 
        'Artist53', 
        'Artist55', 
        'Artist57', 
        'Artist59', 
        'Artist61', 
        'Artist63', 
        'Artist65', 
        'Artist67', 
        'Artist69', 
        'Artist71', 
        'Artist73', 
        'Artist75', 
        'Artist77', 
        'Artist79', 
        'Artist81', 
        'Artist83', 
        'Artist85', 
        'Artist87', 
        'Artist89', 
        'Artist91', 
        'Artist93', 
        'Artist95', 
        'Artist97', 
        'Artist99'
      ], 
      [
        'hash1 Song', 
        'hash1 Artist', 
        'Song1', 
        'Song2', 
        'Song3', 
        'Song4', 
        'Song5', 
        'Song6', 
        'Song7', 
        'Song8', 
        'Song9', 
        'Song10', 
        'Song11', 
        'Song12', 
        'Song13', 
        'Song14', 
        'Song15', 
        'Song16', 
        'Song17', 
        'Song18', 
        'Song19', 
        'Song20', 
        'Song21', 
        'Song22', 
        'Song23', 
        'Song24', 
        'Song25', 
        'Song26', 
        'Song27', 
        'Song28', 
        'Song29', 
        'Song30', 
        'Song31', 
        'Song32', 
        'Song33', 
        'Song34', 
        'Song35', 
        'Song36', 
        'Song37', 
        'Song38', 
        'Song39', 
        'Song40', 
        'Song41', 
        'Song42', 
        'Song43', 
        'Song44', 
        'Song45', 
        'Song46', 
        'Song47', 
        'Song48', 
        'Song49', 
        'Song50', 
        'Song51', 
        'Song52', 
        'Song53', 
        'Song54', 
        'Song55', 
        'Song56', 
        'Song57', 
        'Song58', 
        'Song59', 
        'Song60', 
        'Song61', 
        'Song62', 
        'Song63', 
        'Song64', 
        'Song65', 
        'Song66', 
        'Song67', 
        'Song68', 
        'Song69', 
        'Song70', 
        'Song71', 
        'Song72', 
        'Song73', 
        'Song74', 
        'Song75', 
        'Song76', 
        'Song77', 
        'Song78', 
        'Song79', 
        'Song80', 
        'Song81', 
        'Song82', 
        'Song83', 
        'Song84', 
        'Song85', 
        'Song86', 
        'Song87', 
        'Song88', 
        'Song89', 
        'Song90', 
        'Song91', 
        'Song92', 
        'Song93', 
        'Song94', 
        'Song95', 
        'Song96', 
        'Song97', 
        'Song98', 
        'Song99', 
        'Artist1', 
        'Artist2', 
        'Artist3', 
        'Artist4', 
        'Artist5', 
        'Artist6', 
        'Artist7', 
        'Artist8', 
        'Artist9', 
        'Artist10', 
        'Artist11', 
        'Artist12', 
        'Artist13', 
        'Artist14', 
        'Artist15', 
        'Artist16', 
        'Artist17', 
        'Artist18', 
        'Artist19', 
        'Artist20', 
        'Artist21', 
        'Artist22', 
        'Artist23', 
        'Artist24', 
        'Artist25', 
        'Artist26', 
        'Artist27', 
        'Artist28', 
        'Artist29', 
        'Artist30', 
        'Artist31', 
        'Artist32', 
        'Artist33', 
        'Artist34', 
        'Artist35', 
        'Artist36', 
        'Artist37', 
        'Artist38', 
        'Artist39', 
        'Artist40', 
        'Artist41', 
        'Artist42', 
        'Artist43', 
        'Artist44', 
        'Artist45', 
        'Artist46', 
        'Artist47', 
        'Artist48', 
        'Artist49', 
        'Artist50', 
        'Artist51', 
        'Artist52', 
        'Artist53', 
        'Artist54', 
        'Artist55', 
        'Artist56', 
        'Artist57', 
        'Artist58', 
        'Artist59', 
        'Artist60', 
        'Artist61', 
        'Artist62', 
        'Artist63', 
        'Artist64', 
        'Artist65', 
        'Artist66', 
        'Artist67', 
        'Artist68', 
        'Artist69', 
        'Artist70', 
        'Artist71', 
        'Artist72', 
        'Artist73', 
        'Artist74', 
        'Artist75', 
        'Artist76', 
        'Artist77', 
        'Artist78', 
        'Artist79', 
        'Artist80', 
        'Artist81', 
        'Artist82', 
        'Artist83', 
        'Artist84', 
        'Artist85', 
        'Artist86', 
        'Artist87', 
        'Artist88', 
        'Artist89', 
        'Artist90', 
        'Artist91', 
        'Artist92', 
        'Artist93', 
        'Artist94', 
        'Artist95', 
        'Artist96', 
        'Artist97', 
        'Artist98', 
        'Artist99'
      ], 
      false, 
      'Suffix', 
      ''
    )
  }}

),

MultiFieldFormula_40 AS (

  {{ prophecy_basics.MultiColumnEdit(['MultiFieldFormula_34'],"(REGEXP_REPLACE(column_value, '"', '"'))",['DownloadData', 'DownloadHeaders', 'URL', 'hash1 Artist', 'Song2', 'Song4', 'Song6', 'Song8', 'Song10', 'Song12', 'Song14', 'Song16', 'Song18', 'Song20', 'Song22', 'Song24', 'Song26', 'Song28', 'Song30', 'Song32', 'Song34', 'Song36', 'Song38', 'Song40', 'Song42', 'Song44', 'Song46', 'Song48', 'Song50', 'Song52', 'Song54', 'Song56', 'Song58', 'Song60', 'Song62', 'Song64', 'Song66', 'Song68', 'Song70', 'Song72', 'Song74', 'Song76', 'Song78', 'Song80', 'Song82', 'Song84', 'Song86', 'Song88', 'Song90', 'Song92', 'Song94', 'Song96', 'Song98', 'Artist1', 'Artist3', 'Artist5', 'Artist7', 'Artist9', 'Artist11', 'Artist13', 'Artist15', 'Artist17', 'Artist19', 'Artist21', 'Artist23', 'Artist25', 'Artist27', 'Artist29', 'Artist31', 'Artist33', 'Artist35', 'Artist37', 'Artist39', 'Artist41', 'Artist43', 'Artist45', 'Artist47', 'Artist49', 'Artist51', 'Artist53', 'Artist55', 'Artist57', 'Artist59', 'Artist61', 'Artist63', 'Artist65', 'Artist67', 'Artist69', 'Artist71', 'Artist73', 'Artist75', 'Artist77', 'Artist79', 'Artist81', 'Artist83', 'Artist85', 'Artist87', 'Artist89', 'Artist91', 'Artist93', 'Artist95', 'Artist97', 'Artist99'],['hash1 Song', 'hash1 Artist', 'Song1', 'Song2', 'Song3', 'Song4', 'Song5', 'Song6', 'Song7', 'Song8', 'Song9', 'Song10', 'Song11', 'Song12', 'Song13', 'Song14', 'Song15', 'Song16', 'Song17', 'Song18', 'Song19', 'Song20', 'Song21', 'Song22', 'Song23', 'Song24', 'Song25', 'Song26', 'Song27', 'Song28', 'Song29', 'Song30', 'Song31', 'Song32', 'Song33', 'Song34', 'Song35', 'Song36', 'Song37', 'Song38', 'Song39', 'Song40', 'Song41', 'Song42', 'Song43', 'Song44', 'Song45', 'Song46', 'Song47', 'Song48', 'Song49', 'Song50', 'Song51', 'Song52', 'Song53', 'Song54', 'Song55', 'Song56', 'Song57', 'Song58', 'Song59', 'Song60', 'Song61', 'Song62', 'Song63', 'Song64', 'Song65', 'Song66', 'Song67', 'Song68', 'Song69', 'Song70', 'Song71', 'Song72', 'Song73', 'Song74', 'Song75', 'Song76', 'Song77', 'Song78', 'Song79', 'Song80', 'Song81', 'Song82', 'Song83', 'Song84', 'Song85', 'Song86', 'Song87', 'Song88', 'Song89', 'Song90', 'Song91', 'Song92', 'Song93', 'Song94', 'Song95', 'Song96', 'Song97', 'Song98', 'Song99', 'Artist1', 'Artist2', 'Artist3', 'Artist4', 'Artist5', 'Artist6', 'Artist7', 'Artist8', 'Artist9', 'Artist10', 'Artist11', 'Artist12', 'Artist13', 'Artist14', 'Artist15', 'Artist16', 'Artist17', 'Artist18', 'Artist19', 'Artist20', 'Artist21', 'Artist22', 'Artist23', 'Artist24', 'Artist25', 'Artist26', 'Artist27', 'Artist28', 'Artist29', 'Artist30', 'Artist31', 'Artist32', 'Artist33', 'Artist34', 'Artist35', 'Artist36', 'Artist37', 'Artist38', 'Artist39', 'Artist40', 'Artist41', 'Artist42', 'Artist43', 'Artist44', 'Artist45', 'Artist46', 'Artist47', 'Artist48', 'Artist49', 'Artist50', 'Artist51', 'Artist52', 'Artist53', 'Artist54', 'Artist55', 'Artist56', 'Artist57', 'Artist58', 'Artist59', 'Artist60', 'Artist61', 'Artist62', 'Artist63', 'Artist64', 'Artist65', 'Artist66', 'Artist67', 'Artist68', 'Artist69', 'Artist70', 'Artist71', 'Artist72', 'Artist73', 'Artist74', 'Artist75', 'Artist76', 'Artist77', 'Artist78', 'Artist79', 'Artist80', 'Artist81', 'Artist82', 'Artist83', 'Artist84', 'Artist85', 'Artist86', 'Artist87', 'Artist88', 'Artist89', 'Artist90', 'Artist91', 'Artist92', 'Artist93', 'Artist94', 'Artist95', 'Artist96', 'Artist97', 'Artist98', 'Artist99'],false,'Suffix','') }}

),

AlteryxSelect_28 AS (

  SELECT 
    Artist13 AS Artist13,
    Song73 AS Song73,
    Song53 AS Song53,
    Artist43 AS Artist43,
    Song52 AS Song52,
    Artist97 AS Artist97,
    Song9 AS Song9,
    Artist59 AS Artist59,
    Artist77 AS Artist77,
    Artist66 AS Artist66,
    Song28 AS Song28,
    Song26 AS Song26,
    Artist12 AS Artist12,
    Artist75 AS Artist75,
    Song66 AS Song66,
    Artist39 AS Artist39,
    Song55 AS Song55,
    Artist6 AS Artist6,
    Artist20 AS Artist20,
    Artist84 AS Artist84,
    Song76 AS Song76,
    Artist94 AS Artist94,
    Song36 AS Song36,
    Artist69 AS Artist69,
    Artist64 AS Artist64,
    Song93 AS Song93,
    Song67 AS Song67,
    Song32 AS Song32,
    Song90 AS Song90,
    Song71 AS Song71,
    Song92 AS Song92,
    Artist9 AS Artist9,
    Song18 AS Song18,
    Artist19 AS Artist19,
    Song4 AS Song4,
    Song13 AS Song13,
    Artist34 AS Artist34,
    Song2 AS Song2,
    Song99 AS Song99,
    Song10 AS Song10,
    Artist25 AS Artist25,
    Song12 AS Song12,
    Artist2 AS Artist2,
    Song7 AS Song7,
    Artist85 AS Artist85,
    Artist1 AS Artist1,
    Song83 AS Song83,
    Song63 AS Song63,
    Song81 AS Song81,
    Artist3 AS Artist3,
    Song49 AS Song49,
    Song8 AS Song8,
    Song25 AS Song25,
    Song16 AS Song16,
    Song24 AS Song24,
    Song1 AS Song1,
    Song88 AS Song88,
    Artist40 AS Artist40,
    Artist65 AS Artist65,
    Artist88 AS Artist88,
    Song95 AS Song95,
    Song57 AS Song57,
    Artist62 AS Artist62,
    Song50 AS Song50,
    Artist98 AS Artist98,
    Artist30 AS Artist30,
    Song54 AS Song54,
    Artist92 AS Artist92,
    Artist82 AS Artist82,
    Artist7 AS Artist7,
    Song31 AS Song31,
    Artist41 AS Artist41,
    Artist32 AS Artist32,
    Artist24 AS Artist24,
    Song91 AS Song91,
    Artist17 AS Artist17,
    Song21 AS Song21,
    Song33 AS Song33,
    Song77 AS Song77,
    Song61 AS Song61,
    Artist54 AS Artist54,
    Song47 AS Song47,
    Song30 AS Song30,
    Artist90 AS Artist90,
    Artist74 AS Artist74,
    Artist46 AS Artist46,
    Song43 AS Song43,
    Artist18 AS Artist18,
    Artist10 AS Artist10,
    Song38 AS Song38,
    Song46 AS Song46,
    Artist36 AS Artist36,
    Artist31 AS Artist31,
    Song19 AS Song19,
    Artist16 AS Artist16,
    Song15 AS Song15,
    Artist14 AS Artist14,
    Artist15 AS Artist15,
    Song56 AS Song56,
    Song69 AS Song69,
    Artist4 AS Artist4,
    Artist79 AS Artist79,
    Artist44 AS Artist44,
    Artist80 AS Artist80,
    Song85 AS Song85,
    Song6 AS Song6,
    Artist73 AS Artist73,
    Artist61 AS Artist61,
    Song14 AS Song14,
    Song44 AS Song44,
    Artist58 AS Artist58,
    Song89 AS Song89,
    Song80 AS Song80,
    Song94 AS Song94,
    Song96 AS Song96,
    Song59 AS Song59,
    Song34 AS Song34,
    Song23 AS Song23,
    Artist81 AS Artist81,
    Song79 AS Song79,
    Song68 AS Song68,
    Song64 AS Song64,
    Artist72 AS Artist72,
    Artist53 AS Artist53,
    Artist26 AS Artist26,
    Artist70 AS Artist70,
    Artist22 AS Artist22,
    Song60 AS Song60,
    Song51 AS Song51,
    Artist49 AS Artist49,
    Artist29 AS Artist29,
    Artist52 AS Artist52,
    Song29 AS Song29,
    Artist35 AS Artist35,
    Song5 AS Song5,
    Song62 AS Song62,
    Artist27 AS Artist27,
    Song65 AS Song65,
    Song41 AS Song41,
    Artist93 AS Artist93,
    Song37 AS Song37,
    Song74 AS Song74,
    Song84 AS Song84,
    Artist45 AS Artist45,
    Song11 AS Song11,
    Artist47 AS Artist47,
    Artist78 AS Artist78,
    Song40 AS Song40,
    Artist76 AS Artist76,
    Artist91 AS Artist91,
    Artist37 AS Artist37,
    Artist87 AS Artist87,
    Song97 AS Song97,
    Artist38 AS Artist38,
    Artist96 AS Artist96,
    Song22 AS Song22,
    Song75 AS Song75,
    Song82 AS Song82,
    Artist33 AS Artist33,
    Artist11 AS Artist11,
    Artist95 AS Artist95,
    Artist71 AS Artist71,
    Artist42 AS Artist42,
    Artist63 AS Artist63,
    Song39 AS Song39,
    Song58 AS Song58,
    Artist48 AS Artist48,
    Song3 AS Song3,
    Artist23 AS Artist23,
    Song35 AS Song35,
    Song27 AS Song27,
    Song70 AS Song70,
    Artist56 AS Artist56,
    Song20 AS Song20,
    Song48 AS Song48,
    Song45 AS Song45,
    Artist8 AS Artist8,
    Song86 AS Song86,
    Song72 AS Song72,
    Artist28 AS Artist28,
    Artist99 AS Artist99,
    Artist83 AS Artist83,
    Song98 AS Song98,
    Artist50 AS Artist50,
    Song17 AS Song17,
    Artist86 AS Artist86,
    Song78 AS Song78,
    Artist21 AS Artist21,
    Artist67 AS Artist67,
    Artist57 AS Artist57,
    Artist68 AS Artist68,
    Artist51 AS Artist51,
    Artist5 AS Artist5,
    Artist89 AS Artist89,
    Artist55 AS Artist55,
    Artist60 AS Artist60,
    Song42 AS Song42,
    Song87 AS Song87,
    `hash1 Song` AS Song0,
    `hash1 Artist` AS Artist0
  
  FROM MultiFieldFormula_40 AS in0

),

Transpose_29 AS (

  {{
    prophecy_basics.Transpose(
      ['AlteryxSelect_28'], 
      [], 
      [
        'Song0', 
        'Artist0', 
        'Song1', 
        'Song2', 
        'Song3', 
        'Song4', 
        'Song5', 
        'Song6', 
        'Song7', 
        'Song8', 
        'Song9', 
        'Song10', 
        'Song11', 
        'Song12', 
        'Song13', 
        'Song14', 
        'Song15', 
        'Song16', 
        'Song17', 
        'Song18', 
        'Song19', 
        'Song20', 
        'Song21', 
        'Song22', 
        'Song23', 
        'Song24', 
        'Song25', 
        'Song26', 
        'Song27', 
        'Song28', 
        'Song29', 
        'Song30', 
        'Song31', 
        'Song32', 
        'Song33', 
        'Song34', 
        'Song35', 
        'Song36', 
        'Song37', 
        'Song38', 
        'Song39', 
        'Song40', 
        'Song41', 
        'Song42', 
        'Song43', 
        'Song44', 
        'Song45', 
        'Song46', 
        'Song47', 
        'Song48', 
        'Song49', 
        'Song50', 
        'Song51', 
        'Song52', 
        'Song53', 
        'Song54', 
        'Song55', 
        'Song56', 
        'Song57', 
        'Song58', 
        'Song59', 
        'Song60', 
        'Song61', 
        'Song62', 
        'Song63', 
        'Song64', 
        'Song65', 
        'Song66', 
        'Song67', 
        'Song68', 
        'Song69', 
        'Song70', 
        'Song71', 
        'Song72', 
        'Song73', 
        'Song74', 
        'Song75', 
        'Song76', 
        'Song77', 
        'Song78', 
        'Song79', 
        'Song80', 
        'Song81', 
        'Song82', 
        'Song83', 
        'Song84', 
        'Song85', 
        'Song86', 
        'Song87', 
        'Song88', 
        'Song89', 
        'Song90', 
        'Song91', 
        'Song92', 
        'Song93', 
        'Song94', 
        'Song95', 
        'Song96', 
        'Song97', 
        'Song98', 
        'Song99', 
        'Artist1', 
        'Artist2', 
        'Artist3', 
        'Artist4', 
        'Artist5', 
        'Artist6', 
        'Artist7', 
        'Artist8', 
        'Artist9', 
        'Artist10', 
        'Artist11', 
        'Artist12', 
        'Artist13', 
        'Artist14', 
        'Artist15', 
        'Artist16', 
        'Artist17', 
        'Artist18', 
        'Artist19', 
        'Artist20', 
        'Artist21', 
        'Artist22', 
        'Artist23', 
        'Artist24', 
        'Artist25', 
        'Artist26', 
        'Artist27', 
        'Artist28', 
        'Artist29', 
        'Artist30', 
        'Artist31', 
        'Artist32', 
        'Artist33', 
        'Artist34', 
        'Artist35', 
        'Artist36', 
        'Artist37', 
        'Artist38', 
        'Artist39', 
        'Artist40', 
        'Artist41', 
        'Artist42', 
        'Artist43', 
        'Artist44', 
        'Artist45', 
        'Artist46', 
        'Artist47', 
        'Artist48', 
        'Artist49', 
        'Artist50', 
        'Artist51', 
        'Artist52', 
        'Artist53', 
        'Artist54', 
        'Artist55', 
        'Artist56', 
        'Artist57', 
        'Artist58', 
        'Artist59', 
        'Artist60', 
        'Artist61', 
        'Artist62', 
        'Artist63', 
        'Artist64', 
        'Artist65', 
        'Artist66', 
        'Artist67', 
        'Artist68', 
        'Artist69', 
        'Artist70', 
        'Artist71', 
        'Artist72', 
        'Artist73', 
        'Artist74', 
        'Artist75', 
        'Artist76', 
        'Artist77', 
        'Artist78', 
        'Artist79', 
        'Artist80', 
        'Artist81', 
        'Artist82', 
        'Artist83', 
        'Artist84', 
        'Artist85', 
        'Artist86', 
        'Artist87', 
        'Artist88', 
        'Artist89', 
        'Artist90', 
        'Artist91', 
        'Artist92', 
        'Artist93', 
        'Artist94', 
        'Artist95', 
        'Artist96', 
        'Artist97', 
        'Artist98', 
        'Artist99'
      ], 
      'Name', 
      'Value', 
      [
        'Song11', 
        'Artist73', 
        'Artist0', 
        'Artist13', 
        'Artist34', 
        'Song22', 
        'Artist62', 
        'Artist90', 
        'Song94', 
        'Song55', 
        'Artist21', 
        'Artist77', 
        'Song2', 
        'Artist27', 
        'Artist88', 
        'Song88', 
        'Song40', 
        'Artist99', 
        'Song66', 
        'Artist66', 
        'Artist5', 
        'Song77', 
        'Artist59', 
        'Artist10', 
        'Song51', 
        'Artist91', 
        'Song82', 
        'Artist56', 
        'Artist84', 
        'Song44', 
        'Artist16', 
        'Song62', 
        'Artist95', 
        'Song33', 
        'Song38', 
        'Song97', 
        'Song60', 
        'Artist80', 
        'Song19', 
        'Artist45', 
        'Song29', 
        'Artist52', 
        'Song71', 
        'Artist24', 
        'Song16', 
        'Song27', 
        'Artist30', 
        'Song49', 
        'Artist41', 
        'Song90', 
        'Artist78', 
        'Song59', 
        'Song91', 
        'Artist60', 
        'Artist33', 
        'Song23', 
        'Artist63', 
        'Artist20', 
        'Song12', 
        'Artist6', 
        'Song84', 
        'Song78', 
        'Artist1', 
        'Song30', 
        'Artist71', 
        'Song73', 
        'Artist37', 
        'Artist93', 
        'Song18', 
        'Song56', 
        'Song67', 
        'Artist67', 
        'Song3', 
        'Artist89', 
        'Artist48', 
        'Artist44', 
        'Song41', 
        'Song89', 
        'Song34', 
        'Artist82', 
        'Song9', 
        'Artist17', 
        'Song63', 
        'Song52', 
        'Artist55', 
        'Artist28', 
        'Artist40', 
        'Artist85', 
        'Song45', 
        'Artist96', 
        'Song70', 
        'Artist74', 
        'Song15', 
        'Song48', 
        'Artist51', 
        'Song96', 
        'Song74', 
        'Song26', 
        'Song37', 
        'Song81', 
        'Song68', 
        'Song35', 
        'Artist32', 
        'Song20', 
        'Artist38', 
        'Artist7', 
        'Artist94', 
        'Song92', 
        'Song7', 
        'Artist72', 
        'Song57', 
        'Artist23', 
        'Song85', 
        'Artist50', 
        'Artist25', 
        'Artist14', 
        'Song46', 
        'Artist61', 
        'Song31', 
        'Song24', 
        'Artist83', 
        'Song79', 
        'Artist49', 
        'Artist43', 
        'Artist2', 
        'Song0', 
        'Song13', 
        'Artist54', 
        'Song42', 
        'Artist9', 
        'Artist97', 
        'Song75', 
        'Artist57', 
        'Artist69', 
        'Song8', 
        'Artist46', 
        'Artist12', 
        'Song86', 
        'Artist86', 
        'Song64', 
        'Artist64', 
        'Song4', 
        'Song95', 
        'Song53', 
        'Song80', 
        'Artist29', 
        'Artist75', 
        'Artist35', 
        'Artist18', 
        'Song47', 
        'Song36', 
        'Song6', 
        'Song69', 
        'Artist31', 
        'Song21', 
        'Artist22', 
        'Song14', 
        'Artist53', 
        'Artist4', 
        'Artist26', 
        'Song43', 
        'Artist42', 
        'Artist58', 
        'Artist3', 
        'Artist98', 
        'Song32', 
        'Artist15', 
        'Song93', 
        'Artist68', 
        'Song25', 
        'Song1', 
        'Song28', 
        'Song98', 
        'Artist47', 
        'Artist81', 
        'Song76', 
        'Song50', 
        'Artist87', 
        'Song87', 
        'Song99', 
        'Song61', 
        'Song17', 
        'Artist19', 
        'Artist79', 
        'Artist8', 
        'Song54', 
        'Artist36', 
        'Artist92', 
        'Song39', 
        'Artist11', 
        'Artist39', 
        'Song83', 
        'Artist76', 
        'Artist70', 
        'Song72', 
        'Song5', 
        'Song65', 
        'Song58', 
        'Song10', 
        'Artist65'
      ], 
      true
    )
  }}

),

Formula_30_0 AS (

  SELECT 
    CAST((REGEXP_REPLACE(Name, 'Song', '')) AS STRING) AS Name,
    * EXCEPT (`name`)
  
  FROM Transpose_29 AS in0

),

Formula_30_1 AS (

  SELECT 
    CAST((REGEXP_REPLACE(Name, 'Artist', '')) AS STRING) AS Name,
    * EXCEPT (`name`)
  
  FROM Formula_30_0 AS in0

),

CrossTab_31 AS (

  SELECT *
  
  FROM (
    SELECT 
      Name,
      VALUE
    
    FROM Formula_30_1 AS in0
  )
  PIVOT (
    STRING_AGG(VALUE, ', ') AS Concat
    FOR Name
    IN (
      '45', 
      '98', 
      '34', 
      '67', 
      '93', 
      '12', 
      '66', 
      '89', 
      '51', 
      '84', 
      '8', 
      '73', 
      '78', 
      '19', 
      '23', 
      '62', 
      '4', 
      '88', 
      '77', 
      '40', 
      '15', 
      '11', 
      '90', 
      '9', 
      '44', 
      '33', 
      '22', 
      '56', 
      '55', 
      '26', 
      '50', 
      '37', 
      '68', 
      '61', 
      '13', 
      '46', 
      '99', 
      '24', 
      '94', 
      '83', 
      '35', 
      '16', 
      '79', 
      '5', 
      '72', 
      '10', 
      '59', 
      '87', 
      '48', 
      '21', 
      '76', 
      '54', 
      '43', 
      '65', 
      '71', 
      '57', 
      '32', 
      '80', 
      '82', 
      '49', 
      '6', 
      '36', 
      '1', 
      '39', 
      '17', 
      '25', 
      '60', 
      '14', 
      '47', 
      '31', 
      '96', 
      '69', 
      '95', 
      '58', 
      '64', 
      '53', 
      '42', 
      '75', 
      '0', 
      '20', 
      '27', 
      '70', 
      '2', 
      '86', 
      '38', 
      '81', 
      '92', 
      '18', 
      '30', 
      '7', 
      '97', 
      '29', 
      '41', 
      '63', 
      '3', 
      '74', 
      '91', 
      '52', 
      '85', 
      '28'
    )
  )

),

CrossTab_31_rename AS (

  SELECT 
    Concat_45 AS `45`,
    Concat_98 AS `98`,
    Concat_34 AS `34`,
    Concat_67 AS `67`,
    Concat_93 AS `93`,
    Concat_12 AS `12`,
    Concat_66 AS `66`,
    Concat_89 AS `89`,
    Concat_51 AS `51`,
    Concat_84 AS `84`,
    Concat_8 AS `8`,
    Concat_73 AS `73`,
    Concat_78 AS `78`,
    Concat_19 AS `19`,
    Concat_23 AS `23`,
    Concat_62 AS `62`,
    Concat_4 AS `4`,
    Concat_88 AS `88`,
    Concat_77 AS `77`,
    Concat_40 AS `40`,
    Concat_15 AS `15`,
    Concat_11 AS `11`,
    Concat_90 AS `90`,
    Concat_9 AS `9`,
    Concat_44 AS `44`,
    Concat_33 AS `33`,
    Concat_22 AS `22`,
    Concat_56 AS `56`,
    Concat_55 AS `55`,
    Concat_26 AS `26`,
    Concat_50 AS `50`,
    Concat_37 AS `37`,
    Concat_68 AS `68`,
    Concat_61 AS `61`,
    Concat_13 AS `13`,
    Concat_46 AS `46`,
    Concat_99 AS `99`,
    Concat_24 AS `24`,
    Concat_94 AS `94`,
    Concat_83 AS `83`,
    Concat_35 AS `35`,
    Concat_16 AS `16`,
    Concat_79 AS `79`,
    Concat_5 AS `5`,
    Concat_72 AS `72`,
    Concat_10 AS `10`,
    Concat_59 AS `59`,
    Concat_87 AS `87`,
    Concat_48 AS `48`,
    Concat_21 AS `21`,
    Concat_76 AS `76`,
    Concat_54 AS `54`,
    Concat_43 AS `43`,
    Concat_65 AS `65`,
    Concat_71 AS `71`,
    Concat_57 AS `57`,
    Concat_32 AS `32`,
    Concat_80 AS `80`,
    Concat_82 AS `82`,
    Concat_49 AS `49`,
    Concat_6 AS `6`,
    Concat_36 AS `36`,
    Concat_1 AS `1`,
    Concat_39 AS `39`,
    Concat_17 AS `17`,
    Concat_25 AS `25`,
    Concat_60 AS `60`,
    Concat_14 AS `14`,
    Concat_47 AS `47`,
    Concat_31 AS `31`,
    Concat_96 AS `96`,
    Concat_69 AS `69`,
    Concat_95 AS `95`,
    Concat_58 AS `58`,
    Concat_64 AS `64`,
    Concat_53 AS `53`,
    Concat_42 AS `42`,
    Concat_75 AS `75`,
    Concat_0 AS `0`,
    Concat_20 AS `20`,
    Concat_27 AS `27`,
    Concat_70 AS `70`,
    Concat_2 AS `2`,
    Concat_86 AS `86`,
    Concat_38 AS `38`,
    Concat_81 AS `81`,
    Concat_92 AS `92`,
    Concat_18 AS `18`,
    Concat_30 AS `30`,
    Concat_7 AS `7`,
    Concat_97 AS `97`,
    Concat_29 AS `29`,
    Concat_41 AS `41`,
    Concat_63 AS `63`,
    Concat_3 AS `3`,
    Concat_74 AS `74`,
    Concat_91 AS `91`,
    Concat_52 AS `52`,
    Concat_85 AS `85`,
    Concat_28 AS `28`
  
  FROM CrossTab_31 AS in0

),

Transpose_32 AS (

  {{
    prophecy_basics.Transpose(
      ['CrossTab_31_rename'], 
      [], 
      [
        '0', 
        '1', 
        '2', 
        '3', 
        '4', 
        '5', 
        '6', 
        '7', 
        '8', 
        '9', 
        '10', 
        '11', 
        '12', 
        '13', 
        '14', 
        '15', 
        '16', 
        '17', 
        '18', 
        '19', 
        '20', 
        '21', 
        '22', 
        '23', 
        '24', 
        '25', 
        '26', 
        '27', 
        '28', 
        '29', 
        '30', 
        '31', 
        '32', 
        '33', 
        '34', 
        '35', 
        '36', 
        '37', 
        '38', 
        '39', 
        '40', 
        '41', 
        '42', 
        '43', 
        '44', 
        '45', 
        '46', 
        '47', 
        '48', 
        '49', 
        '50', 
        '51', 
        '52', 
        '53', 
        '54', 
        '55', 
        '56', 
        '57', 
        '58', 
        '59', 
        '60', 
        '61', 
        '62', 
        '63', 
        '64', 
        '65', 
        '66', 
        '67', 
        '68', 
        '69', 
        '70', 
        '71', 
        '72', 
        '73', 
        '74', 
        '75', 
        '76', 
        '77', 
        '78', 
        '79', 
        '80', 
        '81', 
        '82', 
        '83', 
        '84', 
        '85', 
        '86', 
        '87', 
        '88', 
        '89', 
        '90', 
        '91', 
        '92', 
        '93', 
        '94', 
        '95', 
        '96', 
        '97', 
        '98', 
        '99'
      ], 
      'Name', 
      'Value', 
      [
        '45', 
        '98', 
        '34', 
        '67', 
        '93', 
        '12', 
        '66', 
        '89', 
        '51', 
        '84', 
        '8', 
        '73', 
        '78', 
        '19', 
        '23', 
        '62', 
        '4', 
        '88', 
        '77', 
        '40', 
        '15', 
        '11', 
        '90', 
        '9', 
        '44', 
        '33', 
        '22', 
        '56', 
        '55', 
        '26', 
        '50', 
        '37', 
        '68', 
        '61', 
        '13', 
        '46', 
        '99', 
        '24', 
        '94', 
        '83', 
        '35', 
        '16', 
        '79', 
        '5', 
        '72', 
        '10', 
        '59', 
        '87', 
        '48', 
        '21', 
        '76', 
        '54', 
        '43', 
        '65', 
        '71', 
        '57', 
        '32', 
        '80', 
        '82', 
        '49', 
        '6', 
        '36', 
        '1', 
        '39', 
        '17', 
        '25', 
        '60', 
        '14', 
        '47', 
        '31', 
        '96', 
        '69', 
        '95', 
        '58', 
        '64', 
        '53', 
        '42', 
        '75', 
        '0', 
        '20', 
        '27', 
        '70', 
        '2', 
        '86', 
        '38', 
        '81', 
        '92', 
        '18', 
        '30', 
        '7', 
        '97', 
        '29', 
        '41', 
        '63', 
        '3', 
        '74', 
        '91', 
        '52', 
        '85', 
        '28'
      ], 
      true
    )
  }}

),

TextToColumns_33 AS (

  {{
    prophecy_basics.TextToColumns(
      ['Transpose_32'], 
      'Value', 
      ";", 
      'splitColumns', 
      2, 
      'leaveExtraCharLastCol', 
      'Value', 
      'Value', 
      'generatedColumnName'
    )
  }}

),

TextToColumns_33_dropGem_0 AS (

  SELECT 
    Value_1_Value AS Value1,
    Value_2_Value AS Value2,
    *
  
  FROM TextToColumns_33 AS in0

),

AlteryxSelect_35 AS (

  SELECT 
    Value_2_Value AS Value_2_Value,
    Value_1_Value AS Value_1_Value,
    CAST(Name AS INT64) AS Rank,
    Value1 AS Song,
    Value2 AS Artist
  
  FROM TextToColumns_33_dropGem_0 AS in0

),

Formula_36_0 AS (

  SELECT 
    CAST(((coalesce(CAST(Rank AS FLOAT64), CAST((REGEXP_EXTRACT(Rank, '^[0-9]+', 0)) AS INT64), 0)) + 1) AS INT64) AS Rank,
    * EXCEPT (`rank`)
  
  FROM AlteryxSelect_35 AS in0

),

AlteryxSelect_49 AS (

  SELECT {{ var('List_Box_48') }}
  
  FROM Formula_36_0 AS in0

),

Sample_44 AS (

  {{ prophecy_basics.Sample('', [], 1002, 'firstN', 100) }}

)

SELECT *

FROM Sample_44
