---
version: 2
models:
- name: "Billboard_Webscraping_App__Download_21_21_requestComponents_0"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App__Error_58"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App__Error_59"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App__Error_60"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App__Error_61"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App__Error_62"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App__Error_63"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App__Error_64"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App__Sample_44"
  tags:
  - "prophecy_temp"
