---
version: 2
models:
- name: "challenge_241_solution__Summarize_47"
  tags:
  - "prophecy_temp"
- name: "challenge_241_solution__TextInput_41_cast"
  tags:
  - "prophecy_temp"
- name: "challenge_241_solution__TextInput_42_cast"
  tags:
  - "prophecy_temp"
