---
version: 2
models:
- name: "Billboard_Webscraping_App_1___DataCleansing_1"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___Download_21_21_requestComponents_0"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___Error_58"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___Error_59"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___Error_60"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___Error_61"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___Error_62"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___Error_63"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___Error_64"
  tags:
  - "prophecy_temp"
- name: "Billboard_Webscraping_App_1___RegEx_25"
  tags:
  - "prophecy_temp"
