---
version: 2
models:
- name: "m_rep_cards_orig_client_flag_update__CLIENT_FLAG"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_flag_update__EXP_CLIENT_FLAG_VARS_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_flag_update__EXP_CLIENT_FLAG_reformat"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_flag_update__INS_CHOOSES"
  tags:
  - "prophecy_temp"
