---
version: 2
models:
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__AlteryxSelect_852_3118"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__AppendFields_842_3118"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__Filter_844_3118"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__Filter_863_3118_to_Filter_870_3118"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__Filter_875_3118"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__Filter_875_3118_reject"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__Formula_845_3118_1"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__RecordID_1270_3118"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__Summarize_848_3118"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__table_3118_Exit_macro_op"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3118__table_3118_Loop_macro_op"
  tags:
  - "prophecy_temp"
