---
version: 2
models:
- name: "Debtors_Unmatched_Cash_Comment_App__CrossTab_24"
  tags:
  - "prophecy_temp"
- name: "Debtors_Unmatched_Cash_Comment_App__CrossTab_67"
  tags:
  - "prophecy_temp"
- name: "Debtors_Unmatched_Cash_Comment_App__Filter_107"
  tags:
  - "prophecy_temp"
- name: "Debtors_Unmatched_Cash_Comment_App__Filter_111"
  tags:
  - "prophecy_temp"
- name: "Debtors_Unmatched_Cash_Comment_App__Filter_26"
  tags:
  - "prophecy_temp"
- name: "Debtors_Unmatched_Cash_Comment_App__Union_55"
  tags:
  - "prophecy_temp"
- name: "Debtors_Unmatched_Cash_Comment_App__Unique_118"
  tags:
  - "prophecy_temp"
- name: "Debtors_Unmatched_Cash_Comment_App__aka_SnowflakePR_12"
  tags:
  - "prophecy_temp"
