---
version: 2
models:
- name: "4PL_Inventory_Report_Extended__AlteryxSelect_139"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_Extended__CrossTab_67_1"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_Extended__LockInFilter_128"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_Extended__MajorCodes_w_Bu_126"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_Extended__PortfolioComposerRender_57"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_Extended__PortfolioComposerRender_9"
  tags:
  - "prophecy_temp"
