---
version: 2
models:
- name: "m_rep_cards_orig_cust_add_paf__SQ_WORK_CARDS_ORIG_STAGING_GENERATE_SK_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_cust_add_paf__SQ_WORK_CARDS_ORIG_STAGING_GENERATE_SK_EXPR_74"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_cust_add_paf__WORK_CARDSORIG_CUST_ADD_PAF"
  tags:
  - "prophecy_temp"
