---
version: 2
models:
- name: "Challenge_419_solution_file__Formula_22_0"
  tags:
  - "prophecy_temp"
- name: "Challenge_419_solution_file__MultiRowFormula_19_0"
  tags:
  - "prophecy_temp"
- name: "Challenge_419_solution_file__TextInput_31_cast"
  tags:
  - "prophecy_temp"
- name: "Challenge_419_solution_file__TextInput_32_cast"
  tags:
  - "prophecy_temp"
- name: "Challenge_419_solution_file__TextInput_33_cast"
  tags:
  - "prophecy_temp"
- name: "Challenge_419_solution_file__TextInput_48_cast"
  tags:
  - "prophecy_temp"
- name: "Challenge_419_solution_file__TextInput_49_cast"
  tags:
  - "prophecy_temp"
