---
version: 2
models:
- name: "alteryx_all_test_sql__MakeColumns_32_groupAndPosition_0"
  tags:
  - "prophecy_temp"
- name: "alteryx_all_test_sql__MakeColumns_33_groupAndPosition_0"
  tags:
  - "prophecy_temp"
- name: "alteryx_all_test_sql__MakeColumns_34_groupAndPosition_0"
  tags:
  - "prophecy_temp"
- name: "alteryx_all_test_sql__MakeColumns_35_groupAndPosition_0"
  tags:
  - "prophecy_temp"
- name: "alteryx_all_test_sql__MakeColumns_36_groupAndPosition_0"
  tags:
  - "prophecy_temp"
- name: "alteryx_all_test_sql__MakeColumns_37_groupAndPosition_0"
  tags:
  - "prophecy_temp"
- name: "alteryx_all_test_sql__TextInput_31_cast"
  tags:
  - "prophecy_temp"
- name: "alteryx_all_test_sql__Union_283"
  tags:
  - "prophecy_temp"
