---
version: 2
models:
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___AlteryxSelect_25"
  tags:
  - "prophecy_temp"
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___AppendFields_64"
  tags:
  - "prophecy_temp"
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___Filter_7"
  tags:
  - "prophecy_temp"
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___Join_71_inner"
  tags:
  - "prophecy_temp"
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___RegEx_68"
  tags:
  - "prophecy_temp"
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___RunCommand_37"
  tags:
  - "prophecy_temp"
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___Sample_73"
  tags:
  - "prophecy_temp"
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___TextInput_70_cast"
  tags:
  - "prophecy_temp"
- name: "SRC_SAP_GD12_ON_DEMAND_EXPORT_excl_AU30_AU50_NZ40_J1___Union_44"
  tags:
  - "prophecy_temp"
