---
version: 2
models:
- name: "challenge_154_solution_DL__AlteryxSelect_57"
  tags:
  - "prophecy_temp"
- name: "challenge_154_solution_DL__CountRecords_48"
  tags:
  - "prophecy_temp"
- name: "challenge_154_solution_DL__RecordID_52"
  tags:
  - "prophecy_temp"
- name: "challenge_154_solution_DL__TextInput_36_cast"
  tags:
  - "prophecy_temp"
