---
version: 2
sources:
- name: "transpiled_sources"
  config:
    enabled: true
  tables:
  - name: "household_clust_173_ref"
    identifier: "{{ var('household_clust_173') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_2_Household_Creation_Priority_2"
    columns:
    - name: "MBR_INDV_BE_KEY"
      dataType:
        type: "String"
    - name: "Current Occupants"
      dataType:
        type: "String"
    - name: "lat lon"
      dataType:
        type: "String"
    - name: "Last Occupants"
      dataType:
        type: "String"
    - name: "Max_Matching Occupants"
      dataType:
        type: "String"
    - name: "ACTVTY_YR_MO_SK"
      dataType:
        type: "String"
    - name: "Household"
      dataType:
        type: "Numeric"
    - name: "Min_Max_Matching Occupants"
      dataType:
        type: "String"
  - name: "address_for_geo_186_ref"
    identifier: "{{ var('address_for_geo_186') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_2_Household_Creation_Priority_2"
    columns:
    - name: "MBR_HOME_ADDR_CITY_NM"
      dataType:
        type: "String"
    - name: "Address"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_2"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ZIP_CD_5"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_CNTY_NM"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_1"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ST_CD"
      dataType:
        type: "String"
  - name: "address_for_geo_18_ref"
    identifier: "{{ var('address_for_geo_18') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_1_Household_Creation_Priority_2"
    columns:
    - name: "MBR_HOME_ADDR_CITY_NM"
      dataType:
        type: "String"
    - name: "Address"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_2"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ZIP_CD_5"
      dataType:
        type: "String"
    - name: "variabledate"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_CNTY_NM"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_1"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ST_CD"
      dataType:
        type: "String"
  - name: "recast_cache_20_187_ref"
    identifier: "{{ var('recast_cache_20_187') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_2_Household_Creation_Priority_2"
    columns:
    - name: "MBR_INDV_BE_KEY"
      dataType:
        type: "String"
    - name: "SUB_ID"
      dataType:
        type: "String"
    - name: "MBR_SK"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_CITY_NM"
      dataType:
        type: "String"
    - name: "MBR_FIRST_NM"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_2"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ZIP_CD_5"
      dataType:
        type: "String"
    - name: "GRP_ID"
      dataType:
        type: "String"
    - name: "ACTVTY_YR_MO_SK"
      dataType:
        type: "String"
    - name: "FEP_IN"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_CNTY_NM"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_1"
      dataType:
        type: "String"
    - name: "MBR_LAST_NM"
      dataType:
        type: "String"
    - name: "MBR_RELSHP_CD"
      dataType:
        type: "String"
    - name: "MBR_AGE_AT_ACTVTY_YR_MO"
      dataType:
        type: "String"
    - name: "PROD_RANK"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ST_CD"
      dataType:
        type: "String"
  - name: "aka_alxaa2_Quer_174_ref"
    identifier: "{{ var('aka_alxaa2_Quer_174') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_2_Household_Creation_Priority_2"
    columns:
    - name: "GRP_ADDR_LN_3"
      dataType:
        type: "String"
    - name: "GRP_CITY_NM"
      dataType:
        type: "String"
    - name: "GRP_ADDR_LN_2"
      dataType:
        type: "String"
    - name: "GRP_ST_CD"
      dataType:
        type: "String"
    - name: "GRP_ID"
      dataType:
        type: "String"
    - name: "GRP_ADDR_LN_1"
      dataType:
        type: "String"
  - name: "household_clust_165_ref"
    identifier: "{{ var('household_clust_165') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_2_Household_Creation_Priority_2"
    columns:
    - name: "variableDate"
      dataType:
        type: "String"
    - name: "MBR_INDV_BE_KEY"
      dataType:
        type: "String"
    - name: "Current Occupants"
      dataType:
        type: "String"
    - name: "lat lon"
      dataType:
        type: "String"
    - name: "Last Occupants"
      dataType:
        type: "String"
    - name: "Max_Matching Occupants"
      dataType:
        type: "String"
    - name: "ACTVTY_YR_MO_SK"
      dataType:
        type: "String"
    - name: "Household"
      dataType:
        type: "Numeric"
    - name: "Min_Max_Matching Occupants"
      dataType:
        type: "String"
  - name: "address_for_geo_185_ref"
    identifier: "{{ var('address_for_geo_185') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_2_Household_Creation_Priority_2"
    columns:
    - name: "MFSuppliedPostCode"
      dataType:
        type: "String"
    - name: "Province"
      dataType:
        type: "String"
    - name: "MFCityChanged"
      dataType:
        type: "String"
    - name: "MFAddNumberOutOfRange"
      dataType:
        type: "String"
    - name: "MFUnitDesAssumed"
      dataType:
        type: "String"
    - name: "StreetName"
      dataType:
        type: "String"
    - name: "MFStreetPostChanged"
      dataType:
        type: "String"
    - name: "StreetPreDir"
      dataType:
        type: "String"
    - name: "MFAddLetterMovedToUnitNum"
      dataType:
        type: "String"
    - name: "IntersectingStreetPostType"
      dataType:
        type: "String"
    - name: "HouseNumber"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_CITY_NM"
      dataType:
        type: "String"
    - name: "Lon"
      dataType:
        type: "String"
    - name: "Address"
      dataType:
        type: "String"
    - name: "ClusterLevelId"
      dataType:
        type: "String"
    - name: "Lat"
      dataType:
        type: "String"
    - name: "UnitDesignator"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ZIP_CD_5"
      dataType:
        type: "String"
    - name: "FirstLine"
      dataType:
        type: "String"
    - name: "LastLine"
      dataType:
        type: "String"
    - name: "MFPreDirChanged"
      dataType:
        type: "String"
    - name: "IntersectingStreetPreType"
      dataType:
        type: "String"
    - name: "MFPostDirChanged"
      dataType:
        type: "String"
    - name: "IntersectingStreetName"
      dataType:
        type: "String"
    - name: "StateAbbrev"
      dataType:
        type: "String"
    - name: "MFStreetPreChanged"
      dataType:
        type: "String"
    - name: "StreetPreType"
      dataType:
        type: "String"
    - name: "CensusId"
      dataType:
        type: "String"
    - name: "MFPostCodeChanged"
      dataType:
        type: "String"
    - name: "StreetPostType"
      dataType:
        type: "String"
    - name: "GeoLevel"
      dataType:
        type: "String"
    - name: "MFSuppliedCity"
      dataType:
        type: "String"
    - name: "StreetPostDir"
      dataType:
        type: "String"
    - name: "MFSuppliedState"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_CNTY_NM"
      dataType:
        type: "String"
    - name: "MFEvenOddAddDiffer"
      dataType:
        type: "String"
    - name: "City"
      dataType:
        type: "String"
    - name: "IntersectingStreetPreDir"
      dataType:
        type: "String"
    - name: "Score"
      dataType:
        type: "String"
    - name: "UnitNumber"
      dataType:
        type: "String"
    - name: "MFStreetNameChanged"
      dataType:
        type: "String"
    - name: "Zip"
      dataType:
        type: "String"
    - name: "IntersectingStreetPostDir"
      dataType:
        type: "String"
    - name: "RecordID"
      dataType:
        type: "String"
    - name: "MFStateChanged"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ST_CD"
      dataType:
        type: "String"
    - name: "IntersectingHouseNumber"
      dataType:
        type: "String"
    - name: "MFUsedCityAlias"
      dataType:
        type: "String"
    - name: "PostalCode"
      dataType:
        type: "String"
  - name: "recast_cache_cs_2_ref"
    identifier: "{{ var('recast_cache_cs_2') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_1_Household_Creation_Priority_2"
    columns:
    - name: "MBR_INDV_BE_KEY"
      dataType:
        type: "String"
    - name: "SUB_ID"
      dataType:
        type: "String"
    - name: "MBR_SK"
      dataType:
        type: "Numeric"
    - name: "MBR_HOME_ADDR_CITY_NM"
      dataType:
        type: "String"
    - name: "MBR_FIRST_NM"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_2"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ZIP_CD_5"
      dataType:
        type: "String"
    - name: "variabledate"
      dataType:
        type: "String"
    - name: "GRP_ID"
      dataType:
        type: "String"
    - name: "ACTVTY_YR_MO_SK"
      dataType:
        type: "String"
    - name: "FEP_IN"
      dataType:
        type: "Numeric"
    - name: "MBR_HOME_ADDR_CNTY_NM"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_1"
      dataType:
        type: "String"
    - name: "MBR_LAST_NM"
      dataType:
        type: "String"
    - name: "MBR_RELSHP_CD"
      dataType:
        type: "String"
    - name: "MBR_AGE_AT_ACTVTY_YR_MO"
      dataType:
        type: "String"
    - name: "PROD_RANK"
      dataType:
        type: "Numeric"
    - name: "MBR_HOME_ADDR_ST_CD"
      dataType:
        type: "String"
  - name: "aka_alxaa2_Quer_1_ref"
    identifier: "{{ var('aka_alxaa2_Quer_1') }}"
    config:
      tags:
      - "pipeline:Household_Clustering_1_Household_Creation_Priority_2"
    columns:
    - name: "MBR_INDV_BE_KEY"
      dataType:
        type: "String"
    - name: "SUB_ID"
      dataType:
        type: "String"
    - name: "MBR_SK"
      dataType:
        type: "Numeric"
    - name: "MBR_HOME_ADDR_CITY_NM"
      dataType:
        type: "String"
    - name: "MBR_FIRST_NM"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_2"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_ZIP_CD_5"
      dataType:
        type: "String"
    - name: "GRP_ID"
      dataType:
        type: "String"
    - name: "ACTVTY_YR_MO_SK"
      dataType:
        type: "String"
    - name: "FEP_IN"
      dataType:
        type: "Numeric"
    - name: "MBR_HOME_ADDR_CNTY_NM"
      dataType:
        type: "String"
    - name: "MBR_HOME_ADDR_LN_1"
      dataType:
        type: "String"
    - name: "MBR_LAST_NM"
      dataType:
        type: "String"
    - name: "MBR_RELSHP_CD"
      dataType:
        type: "String"
    - name: "MBR_AGE_AT_ACTVTY_YR_MO"
      dataType:
        type: "String"
    - name: "PROD_RANK"
      dataType:
        type: "Numeric"
    - name: "MBR_HOME_ADDR_ST_CD"
      dataType:
        type: "String"
