{{
  config({    
    "materialized": "table",
    "alias": "UPD_LOCATOR_CLOSE",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_CARDS_ORIG_LOCATOR AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_locator_update__EXP_CARDS_ORIG_LOCATOR')}}

),

RTR_CARDS_ORIG_LOCATOR_out2 AS (

  SELECT * 
  
  FROM EXP_CARDS_ORIG_LOCATOR AS in0
  
  WHERE ((CLID_LOCATOR IS NOT NULL) AND (VALUE IS NULL))

),

RTR_CARDS_ORIG_LOCATOR_EXPR_CLOSE_LOCATOR AS (

  SELECT 
    CLID_CLIENT_ALIAS AS CLID_CLIENT_ALIAS4,
    MERGE_CLID_CLIENT_ALIAS AS MERGE_CLID_CLIENT_ALIAS4,
    CLASS AS CLASS4,
    SUBCLASS AS SUBCLASS4,
    VALUE AS VALUE4,
    CLID_LOCATOR AS CLID_LOCATOR4,
    EFROM_LOCATOR AS EFROM_LOCATOR4,
    CLASS_LOCATOR AS CLASS_LOCATOR4,
    SUBCLASS_LOCATOR AS SUBCLASS_LOCATOR4,
    VALUE_LOCATOR AS VALUE_LOCATOR4,
    SOURCE_TYPE AS SOURCE_TYPE4,
    business_date AS business_date4,
    business_date_minus_1 AS business_date_minus_14,
    feed_update_id AS feed_update_id4,
    TOTAL_COMPARE AS TOTAL_COMPARE4
  
  FROM RTR_CARDS_ORIG_LOCATOR_out2 AS in0

),

UPD_LOCATOR_CLOSE1_add_missing_column_0 AS (

  SELECT 
    CAST(NULL AS NUMERIC) AS MERGE_CLID,
    CAST(NULL AS STRING) AS CONTACT_POINT_EXTRA_INFO,
    *
  
  FROM RTR_CARDS_ORIG_LOCATOR_EXPR_CLOSE_LOCATOR AS in0

),

UPD_LOCATOR_CLOSE1_add_missing_column_EXPR_6 AS (

  SELECT 
    CLID_LOCATOR4 AS CLID,
    CONTACT_POINT_EXTRA_INFO AS CONTACT_POINT_EXTRA_INFO,
    VALUE_LOCATOR4 AS `VALUE`,
    EFROM_LOCATOR4 AS EFROM,
    business_date_minus_14 AS ETO,
    SOURCE_TYPE4 AS SOURCE_TYPE,
    SUBCLASS_LOCATOR4 AS SUBCLASS,
    MERGE_CLID AS MERGE_CLID,
    CLASS_LOCATOR4 AS CLASS
  
  FROM UPD_LOCATOR_CLOSE1_add_missing_column_0 AS in0

)

SELECT *

FROM UPD_LOCATOR_CLOSE1_add_missing_column_EXPR_6
