---
version: 2
models:
- name: "m_rep_cards_orig_locator_update__CHOOSES"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_locator_update__EXP_CARDS_ORIG_LOCATOR"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_locator_update__INS_LOCATOR_NEW"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_locator_update__INS_LOCATOR_OPEN"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_locator_update__RTR_CARDS_ORIG_LOCATOR_EXPR_OPEN_CLOSE_LOCATOR"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_locator_update__UPD_LOCATOR"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_locator_update__UPD_LOCATOR_CLOSE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_locator_update__find_business_date"
  tags:
  - "prophecy_temp"
