---
version: 2
models:
- name: "perpetual_inventory_details__AlteryxSelect_103"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory_details__AlteryxSelect_39"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory_details__AlteryxSelect_48"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory_details__AlteryxSelect_62"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory_details__AppendFields_16"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory_details__Formula_27_0"
  tags:
  - "prophecy_temp"
- name: "perpetual_inventory_details__Formula_29_0"
  tags:
  - "prophecy_temp"
