version: 1
files:
- path: "attachment/xml_data_as_text.txt"
  codec: "gzip"
  rawSize: 747
  contentType: "text/plain"
  encoding: "raw"
  sha256: "4291e64a9da82ec95c32cbad843bee658bdebc344a81007fa9bcb401f6137546"
- path: "attachment/titanic.parquet"
  codec: "none"
  rawSize: 40013
  encoding: "raw"
  sha256: "ec8a698c518baa3a2c50ab185090ec09405eddb87186c9aa2ec2453a36157971"
- path: "attachment/Book1.xlsx"
  codec: "none"
  rawSize: 20451
  contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  encoding: "raw"
  sha256: "6ef03f24fd2bfa1936bbea416fca7c5e1b65a1107e7678ff5544c098d414ebaa"
- path: "attachment/industry.csv"
  codec: "gzip"
  rawSize: 749
  contentType: "text/csv"
  encoding: "raw"
  sha256: "2044d457122be4b28c373554860f1f5e74ccd9ca512c58c044821de57ceb244f"
