{{
  config({    
    "materialized": "table",
    "alias": "CLIENT_STAGING_NEW_CLIENT",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_CARDSORIG_CLIENT_EXPR_40 AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_client_staging_update__EXP_CARDSORIG_CLIENT_EXPR_40')}}

),

RTR_CARDSORIG_CLIENT_out0 AS (

  SELECT * 
  
  FROM EXP_CARDSORIG_CLIENT_EXPR_40 AS in0
  
  WHERE (CLID_LKP IS NULL)

),

RTR_CARDSORIG_CLIENT_EXPR_NEW_CLIENT AS (

  SELECT 
    CLID AS CLID,
    CUSTOMER_NUMBER AS SOURCE_CLIENT_REF,
    OUTPUT_TITLE AS TITLE,
    INITIALS AS INITIALS,
    FORENAMES AS FORENAMES,
    SURNAME AS SURNAME,
    DOB AS DOB,
    GENDER AS GENDER,
    CLIENT_CLASS AS CLIENT_CLASS,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    SOURCE_RECORD_TYPE AS SOURCE_RECORD_TYPE,
    CLIENT_STATUS AS CLIENT_STATUS
  
  FROM RTR_CARDSORIG_CLIENT_out0 AS in0

)

SELECT *

FROM RTR_CARDSORIG_CLIENT_EXPR_NEW_CLIENT
