---
version: 2
models:
- name: "4PL_Inventory_Report_1___AlteryxSelect_127"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___AlteryxSelect_139"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___AlteryxSelect_139_1"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___CrossTab_67_1"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___LockInFilter_128"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___PortfolioComposerRender_57"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___PortfolioComposerRender_9"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___RecordID_1"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___TextInput_138_cast"
  tags:
  - "prophecy_temp"
- name: "4PL_Inventory_Report_1___generate_incremental_recordid"
  tags:
  - "prophecy_temp"
