pipelines:
  CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1_:
    visualGroups:
      CREDITSDM:
        isCollapsed: true
        height: 72
        nodes:
        - "AlteryxSelect_31"
        - "AlteryxSelect_32"
        - "AlteryxSelect_38"
        - "AppendFields_33"
        - "Cleanse_150"
        - "Configuration_t_28"
        - "Configuration_t_29"
        - "Filter_48"
        - "Formula_213_0"
        - "Formula_37_0"
        - "Formula_42_0"
        - "Formula_43_0"
        - "Formula_50_0"
        - "Join_30_inner"
        - "Join_35_inner"
        - "Join_35_left"
        - "NaN_Credit_DM_x_26"
        - "PortfolioComposerRender_216"
        - "PortfolioComposerRender_45"
        - "PortfolioComposerTable_214"
        - "PortfolioComposerTable_39"
        - "Sample_27"
        - "Summarize_212"
        - "Summarize_44"
        - "TextToColumns_148"
        - "TextToColumns_148_dropGem_0"
        width: 2377
        colorPreset: "gray-blue"
      CREDITSEM:
        isCollapsed: true
        height: 72
        nodes:
        - "AlteryxSelect_184"
        - "AlteryxSelect_52"
        - "AlteryxSelect_60"
        - "AlteryxSelect_61"
        - "AlteryxSelect_65"
        - "AppendFields_62"
        - "Configuration_t_57"
        - "Configuration_t_58"
        - "DateTime_183_0"
        - "Directory_51"
        - "Directory_51_reformat"
        - "Filter_232"
        - "Filter_72"
        - "Formula_182_0"
        - "Formula_185_0"
        - "Formula_186_0"
        - "Formula_208_0"
        - "Formula_64_0"
        - "Formula_69_0"
        - "Formula_73_0"
        - "Join_59_inner"
        - "Join_63_inner"
        - "Join_63_left"
        - "Macro_76"
        - "PortfolioComposerRender_187"
        - "PortfolioComposerRender_211"
        - "PortfolioComposerTable_209"
        - "PortfolioComposerTable_66"
        - "Sample_56"
        - "Summarize_207"
        - "Summarize_231"
        - "Summarize_70"
        - "TextToColumns_180"
        - "TextToColumns_180_dropGem_0"
        - "TextToColumns_181"
        - "TextToColumns_181_dropGem_0"
        - "table_76_Output4_macro_op"
        width: 4521
        colorPreset: "gray-blue"
      Container191:
        isCollapsed: false
        height: 280
        nodes:
        - "Formula_198_0"
        - "PortfolioComposerTable_192"
        - "Summarize_188"
        width: 880
        colorPreset: "gray-blue"
      RATES:
        isCollapsed: true
        height: 72
        nodes:
        - "AlteryxSelect_11"
        - "AlteryxSelect_21"
        - "AlteryxSelect_4"
        - "AlteryxSelect_7"
        - "AlteryxSelect_9"
        - "AppendFields_12"
        - "Cleanse_151"
        - "Configuration_t_14"
        - "Configuration_t_5"
        - "Directory_1"
        - "Directory_1_reformat"
        - "Formula_13_0"
        - "Formula_20_0"
        - "Formula_218_0"
        - "Formula_3_0"
        - "Formula_3_1"
        - "Join_15_inner"
        - "Join_15_left"
        - "Join_8_inner"
        - "Macro_75"
        - "PortfolioComposerRender_220"
        - "PortfolioComposerRender_24"
        - "PortfolioComposerTable_219"
        - "PortfolioComposerTable_22"
        - "Sample_10"
        - "Summarize_16"
        - "Summarize_217"
        - "TextToColumns_147"
        - "TextToColumns_147_dropGem_0"
        - "TextToColumns_2"
        - "TextToColumns_2_dropGem_0"
        - "TextToColumns_6"
        - "TextToColumns_6_dropGem_0"
        - "table_75_Output4_macro_op"
        width: 3593
        colorPreset: "gray-blue"
