{{
  config({    
    "materialized": "table",
    "alias": "MINERVA_EXCEPTION",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH SQ_CARDS_ORIG_DECISION_HISTORY AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_decision_history__SQ_CARDS_ORIG_DECISION_HISTORY')}}

),

RTR_CARDS_ORIG_DECISION_HISTORY_out1 AS (

  SELECT * 
  
  FROM SQ_CARDS_ORIG_DECISION_HISTORY AS in0
  
  WHERE ((LAST_ACTION_DATE IS NULL) OR ((LENGTH(LAST_ACTION_DATE)) = 0))

),

RTR_CARDS_ORIG_DECISION_HISTORY_EXPR_DATE_NOT_PRESENT AS (

  SELECT 
    ACCID AS ACCID3,
    APPLICATION_NUMBER AS APPLICATION_NUMBER,
    APPLICATION_STATUS AS APPLICATION_STATUS3,
    LAST_ACTION_DATE AS LAST_ACTION_DATE3
  
  FROM RTR_CARDS_ORIG_DECISION_HISTORY_out1 AS in0

),

EXP_GET_BUSINESS_DATE AS (

  SELECT 
    ACCID3 AS ACCID,
    APPLICATION_NUMBER AS ACCOUNT_ALIAS_ID,
    (
      CASE
        WHEN CAST((
          (
            CASE
              WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                THEN (FIND_BUSINESS_DATE('businessdate'))
              ELSE CAST(NULL AS STRING)
            END
          ) IS NULL
        ) AS BOOL)
          THEN (force_error('No Business date found on DBATTRIBUTE'))
        ELSE (
          PARSE_TIMESTAMP(
            '%Y%m%d', 
            SUBSTRING(
              (
                CASE
                  WHEN ((SUM(1) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = 1)
                    THEN (FIND_BUSINESS_DATE('businessdate'))
                  ELSE CAST(NULL AS STRING)
                END
              ) FROM 0 FOR 8))
        )
      END
    ) AS BUSINESS_DATE,
    'm_rep_cards_orig_decision_history' AS PROCESS_NAME,
    'Last Action Date not Present in Cards Origination record' AS EXCEPTION_COMMENT,
    'RTR_CHECK_ACTION_DATE' AS FUNCTION_NAME,
    'N' AS LOAD_INDICATOR,
    'U' AS SOURCE_SYSTEM_CODE,
    18 AS ERROR_NUMBER,
    5053 AS CLASS
  
  FROM RTR_CARDS_ORIG_DECISION_HISTORY_EXPR_DATE_NOT_PRESENT AS in0

),

MINERVA_EXCEPTION_EXP AS (

  SELECT 
    CLASS AS CLASS,
    BUSINESS_DATE AS BUSINESS_DATE,
    CAST(NULL AS NUMERIC) AS CLID,
    ACCID AS ACCID,
    CAST(NULL AS NUMERIC) AS ADID,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    CAST(NULL AS STRING) AS SOURCE_CLIENT_REF,
    ACCOUNT_ALIAS_ID AS ACCOUNT_ALIAS_ID,
    ERROR_NUMBER AS ERROR_NUMBER,
    PROCESS_NAME AS PROCESS_NAME,
    FUNCTION_NAME AS FUNCTION_NAME,
    CAST(NULL AS STRING) AS ADDITIONAL_IDENTIFIER,
    CAST(NULL AS NUMERIC) AS ADDITIONAL_IDENTIFIER_TYPE,
    LOAD_INDICATOR AS LOAD_INDICATOR,
    EXCEPTION_COMMENT AS EXCEPTION_COMMENT
  
  FROM EXP_GET_BUSINESS_DATE AS in0

)

SELECT *

FROM MINERVA_EXCEPTION_EXP
