---
version: 2
models:
- name: "m_rep_cards_orig_decision_history__CREDIT_APPLICATION_DAILY_HIST"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_decision_history__MINERVA_EXCEPTION"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_decision_history__SQ_CARDS_ORIG_DECISION_HISTORY"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_decision_history__find_business_date"
  tags:
  - "prophecy_temp"
