---
version: 2
models:
- name: "CCI__AlteryxSelect_69"
  tags:
  - "prophecy_temp"
- name: "CCI__CCI_Break_Out_c_80"
  tags:
  - "prophecy_temp"
- name: "CCI__CCI_Scores_yxdb_81"
  tags:
  - "prophecy_temp"
- name: "CCI__Formula_73_0"
  tags:
  - "prophecy_temp"
- name: "CCI__Join_74_inner"
  tags:
  - "prophecy_temp"
- name: "CCI__Summarize_62"
  tags:
  - "prophecy_temp"
- name: "CCI__Summarize_71"
  tags:
  - "prophecy_temp"
- name: "CCI__Unique_78"
  tags:
  - "prophecy_temp"
