---
version: 2
models:
- name: "productos_1_part1__Filter_989"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__Formula_990_0"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__Formula_996_0"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__Join_988_inner"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_1012"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_1025"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_1098"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_1210"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_1241"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_1288"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_991"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_994"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_AlteryxSelect_997"
  tags:
  - "prophecy_temp"
- name: "productos_1_part1__intermediate_productos_1_Formula_1161"
  tags:
  - "prophecy_temp"
