---
version: 2
models:
- name: "m_rep_gems_monthly_stmt_summ_calc_load__EXP_IDENTIFY_CORRECT_PERIODS"
  tags:
  - "prophecy_temp"
- name: "m_rep_gems_monthly_stmt_summ_calc_load__Reformat_1"
  tags:
  - "prophecy_temp"
