{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH Union_449 AS (

  SELECT *
  
  FROM {{ ref('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Union_449')}}

),

Summarize_584 AS (

  SELECT 
    *,
    (FIRST_VALUE(SOURCE_SKU) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) OVER (PARTITION BY DATE_OF_EVENT, 
    SKU_CATEGORY, 
    WH_ID_STANDARD, 
    SALES_ORDER, 
    CUSTOMER, 
    DELIVERY_DT, 
    FILENAME, 
    ROWTYPE, 
    PO_NUMBER, 
    PICKUP_OR_DELIVERY, 
    SOURCE_WH_DESC, 
    SHIP_DT, 
    WH_DESC_STANDARD, 
    PRODUCTION_OR_TRANSFER, 
    SKU_DESC_STANDARD, 
    SKU_STANDARD, 
    ROWSORTTIER ORDER BY SKU_STANDARD ASC NULLS FIRST, WH_ID_STANDARD ASC NULLS FIRST, ROWSORTTIER ASC NULLS FIRST, DATE_OF_EVENT ASC NULLS FIRST, QTY DESC NULLS FIRST) AS SOURCE_SKU_TMP,
    SUM(QTY) OVER (PARTITION BY DATE_OF_EVENT, 
    SKU_CATEGORY, 
    WH_ID_STANDARD, 
    SALES_ORDER, 
    CUSTOMER, 
    DELIVERY_DT, 
    FILENAME, 
    ROWTYPE, 
    PO_NUMBER, 
    PICKUP_OR_DELIVERY, 
    SOURCE_WH_DESC, 
    SHIP_DT, 
    WH_DESC_STANDARD, 
    PRODUCTION_OR_TRANSFER, 
    SKU_DESC_STANDARD, 
    SKU_STANDARD, 
    ROWSORTTIER ORDER BY SKU_STANDARD ASC NULLS FIRST, WH_ID_STANDARD ASC NULLS FIRST, ROWSORTTIER ASC NULLS FIRST, DATE_OF_EVENT ASC NULLS FIRST, QTY DESC NULLS FIRST) AS QTY_TMP,
    (FIRST_VALUE(SOURCE_SKU_DESC) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) OVER (PARTITION BY DATE_OF_EVENT, 
    SKU_CATEGORY, 
    WH_ID_STANDARD, 
    SALES_ORDER, 
    CUSTOMER, 
    DELIVERY_DT, 
    FILENAME, 
    ROWTYPE, 
    PO_NUMBER, 
    PICKUP_OR_DELIVERY, 
    SOURCE_WH_DESC, 
    SHIP_DT, 
    WH_DESC_STANDARD, 
    PRODUCTION_OR_TRANSFER, 
    SKU_DESC_STANDARD, 
    SKU_STANDARD, 
    ROWSORTTIER ORDER BY SKU_STANDARD ASC NULLS FIRST, WH_ID_STANDARD ASC NULLS FIRST, ROWSORTTIER ASC NULLS FIRST, DATE_OF_EVENT ASC NULLS FIRST, QTY DESC NULLS FIRST) AS SOURCE_SKU_DESC_TMP,
    ROW_NUMBER() OVER (PARTITION BY DATE_OF_EVENT, 
    SKU_CATEGORY, 
    WH_ID_STANDARD, 
    SALES_ORDER, 
    CUSTOMER, 
    DELIVERY_DT, 
    FILENAME, 
    ROWTYPE, 
    PO_NUMBER, 
    PICKUP_OR_DELIVERY, 
    SOURCE_WH_DESC, 
    SHIP_DT, 
    WH_DESC_STANDARD, 
    PRODUCTION_OR_TRANSFER, 
    SKU_DESC_STANDARD, 
    SKU_STANDARD, 
    ROWSORTTIER ORDER BY SKU_STANDARD ASC NULLS FIRST, WH_ID_STANDARD ASC NULLS FIRST, ROWSORTTIER ASC NULLS FIRST, DATE_OF_EVENT ASC NULLS FIRST, QTY DESC NULLS FIRST) AS ROW_NUMBER
  
  FROM Union_449 AS in0

),

Summarize_584_rename AS (

  SELECT 
    SOURCE_SKU_TMP AS SOURCE_SKU,
    QTY_TMP AS QTY,
    SOURCE_SKU_DESC_TMP AS SOURCE_SKU_DESC,
    * EXCLUDE ("SOURCE_SKU", "QTY", "SOURCE_SKU_DESC", "SOURCE_SKU_TMP", "QTY_TMP", "SOURCE_SKU_DESC_TMP")
  
  FROM Summarize_584 AS in0

),

"584_filter" AS (

  SELECT * 
  
  FROM Summarize_584_rename AS in0
  
  WHERE (ROW_NUMBER = 1)

),

Summarize_584_drop_0 AS (

  SELECT * EXCLUDE ("ROW_NUMBER")
  
  FROM "584_filter" AS in0

),

MultiRowFormula_230_row_id_0 AS (

  SELECT 
    (SEQ8()) AS PROPHECY_ROW_ID,
    *
  
  FROM Summarize_584_drop_0 AS in0

),

MultiRowFormula_230 AS (

  {{ prophecy_basics.ToDo('Multi Row Formula tool for this case is not supported by transpiler in SQL') }}

),

MultiRowFormula_230_row_id_drop_0 AS (

  SELECT * EXCLUDE ("PROPHECY_ROW_ID")
  
  FROM MultiRowFormula_230 AS in0

),

Formula_243_0 AS (

  SELECT 
    CAST((
      CASE
        WHEN (ROWTYPE = '1_BEG_INVENTORY')
          THEN QTY
        ELSE NULL
      END
    ) AS INTEGER) AS BEGINNING_INVENTORY,
    CAST((
      CASE
        WHEN (ROWTYPE = '2_SALES_BY_CUSTOMER_DETAIL')
          THEN (-1 * QTY)
        ELSE NULL
      END
    ) AS INTEGER) AS SALES_QTY,
    CAST((
      CASE
        WHEN (PRODUCTION_OR_TRANSFER = 'Production')
          THEN QTY
        ELSE NULL
      END
    ) AS INTEGER) AS PRODUCTION_QTY,
    CAST((
      CASE
        WHEN (PRODUCTION_OR_TRANSFER = 'Transfer')
          THEN QTY
        ELSE NULL
      END
    ) AS INTEGER) AS TRANSFER_QTY,
    *
  
  FROM MultiRowFormula_230_row_id_drop_0 AS in0

),

AlteryxSelect_228 AS (

  SELECT 
    SKU_CATEGORY AS SKU_CATEGORY,
    SKU_STANDARD AS SKU_STANDARD,
    SKU_DESC_STANDARD AS SKU_DESC_STANDARD,
    SOURCE_SKU AS SOURCE_SKU,
    SOURCE_SKU_DESC AS SOURCE_SKU_DESC,
    WH_ID_STANDARD AS WH_ID_STANDARD,
    WH_DESC_STANDARD AS WH_DESC_STANDARD,
    ROWTYPE AS ROWTYPE,
    DATE_OF_EVENT AS DATE_OF_EVENT,
    QTY AS QTY,
    BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    SALES_QTY AS SALES_QTY,
    PRODUCTION_QTY AS PRODUCTION_QTY,
    TRANSFER_QTY AS TRANSFER_QTY,
    ENDING_INVENTORY AS ENDING_INVENTORY,
    PICKUP_OR_DELIVERY AS PICKUP_OR_DELIVERY,
    SHIP_DT AS SHIP_DT,
    DELIVERY_DT AS DELIVERY_DT,
    CUSTOMER AS CUSTOMER,
    SALES_ORDER AS SALES_ORDER,
    PO_NUMBER AS PO_NUMBER,
    PRODUCTION_OR_TRANSFER AS PRODUCTION_OR_TRANSFER,
    ROWSORTTIER AS ROWSORTTIER,
    FILENAME AS FILENAME
  
  FROM Formula_243_0 AS in0

)

SELECT *

FROM AlteryxSelect_228
