---
version: 2
models:
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__AlteryxSelect_228"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__AlteryxSelect_533"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__AlteryxSelect_551"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Cleanse_214"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Cleanse_316"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Cleanse_317"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Formula_215_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Formula_237_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Formula_282_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Formula_350_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Join_195_left"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Join_202_left"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Join_339_left"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__SelectRecords_386_cleanup_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Summarize_173"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Summarize_355"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Summarize_626"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Union_160"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Union_198"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4__Union_449"
  tags:
  - "prophecy_temp"
