---
version: 2
models:
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_142"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_21"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_226"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_38"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_4"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_52"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_65"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_77"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___AlteryxSelect_96"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Filter_206"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Filter_93"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_198_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_199_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_200_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_208_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_213_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_218_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_229_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_50_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Formula_82_0"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Join_94_left"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Summarize_124"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Summarize_16"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Summarize_231"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Union_103"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_Upload_v_1_0_1___Union_197"
  tags:
  - "prophecy_temp"
