{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "qa_test_dataset"
  })
}}

WITH Join_805_left_UnionLeftOuter AS (

  SELECT *
  
  FROM {{ ref('intervention__Join_805_left_UnionLeftOuter')}}

),

CKD_Risk_List_c_1675 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('intervention', 'CKD_Risk_List_c_1675') }}

),

Join_822_left_UnionLeftOuter AS (

  SELECT 
    in0.`Member Individual Business Entity Key` AS `Member Individual Business Entity Key`,
    in0.`_Null_` AS _Null_,
    in0.Asthma AS Asthma,
    in0.CAD AS CAD,
    in0.Cancer AS Cancer,
    in0.CHF AS CHF,
    in0.COPD AS COPD,
    in0.Diabetes AS Diabetes,
    in0.ESRD AS ESRD,
    in0.Hypertension AS Hypertension,
    in0.`Risk Cost Code` AS `Risk Cost Code`,
    in0.`Concurrent Normalized Risk Score` AS `Concurrent Normalized Risk Score`,
    in0.`Prospective Normalized Risk Score` AS `Prospective Normalized Risk Score`,
    in0.`Recent 3 Months Total Allowable Amount` AS `Recent 3 Months Total Allowable Amount`,
    in0.`Current 12 Months Total Allowable Amount` AS `Current 12 Months Total Allowable Amount`,
    in0.SOURCE_ID AS SOURCE_ID,
    in0.MBR_INDV_BE_KEY AS MBR_INDV_BE_KEY,
    in0.TOTAL_ALLOWED_AMT AS TOTAL_ALLOWED_AMT,
    in0.READMIN_DSCHG_DT AS READMIN_DSCHG_DT,
    in0.`Prediction Value` AS `Prediction Value`,
    in0.`Prediction Score` AS `Prediction Score`,
    in0.ADMITTING_DX AS ADMITTING_DX,
    in0.UNIQUE_DRUG_CT_CURRENT AS UNIQUE_DRUG_CT_CURRENT,
    in0.READMITPREDICTION AS READMITPREDICTION,
    in0.NONEMERGENT_RATE AS NONEMERGENT_RATE,
    in0.NONEMERGENT_COUNT_PAST_60 AS NONEMERGENT_COUNT_PAST_60,
    in0.ER_COUNT_PAST_2_MONTHS AS ER_COUNT_PAST_2_MONTHS,
    in0.ER_COUNT_PAST_3_MONTHS AS ER_COUNT_PAST_3_MONTHS,
    in0.ED_DSCHG_DT AS ED_DSCHG_DT,
    in0.ER_COUNT AS ER_COUNT,
    in0.LATEST_ED_DX AS LATEST_ED_DX,
    in0.`ED Prediction Score` AS `ED Prediction Score`,
    in0.`ED Prediction Value` AS `ED Prediction Value`,
    in0.EDPREDICTION AS EDPREDICTION,
    in0.MBR_UNIQ_KEY AS MBR_UNIQ_KEY,
    in0.MBR_FULL_NM AS MBR_FULL_NM,
    in0.PROD_SH_NM AS PROD_SH_NM,
    in0.MBR_GNDR_CD AS MBR_GNDR_CD,
    in0.MBR_AGE AS MBR_AGE,
    in0.AGE_RANGE AS AGE_RANGE,
    in0.MBR_RELSHP_CD AS MBR_RELSHP_CD,
    in0.GRP_FUNDING_ARRANGEMENT AS GRP_FUNDING_ARRANGEMENT,
    in0.GRP_ID AS GRP_ID,
    in0.GRP_NM AS GRP_NM,
    in0.PRNT_GRP_SIC_NACIS_CD AS PRNT_GRP_SIC_NACIS_CD,
    in0.PRNT_GRP_SIC_NACIS_NM AS PRNT_GRP_SIC_NACIS_NM,
    in0.SUB_CNTGS_CNTY_CD AS SUB_CNTGS_CNTY_CD,
    in0.SUB_MKTNG_METRO_RURAL_CD AS SUB_MKTNG_METRO_RURAL_CD,
    in0.MBR_HOME_ADDR_LN_1 AS MBR_HOME_ADDR_LN_1,
    in0.MBR_HOME_ADDR_LN_2 AS MBR_HOME_ADDR_LN_2,
    in0.MBR_HOME_ADDR_CITY_NM AS MBR_HOME_ADDR_CITY_NM,
    in0.MBR_HOME_ADDR_ST_CD AS MBR_HOME_ADDR_ST_CD,
    in0.MBR_HOME_ADDR_ZIP_CD_5 AS MBR_HOME_ADDR_ZIP_CD_5,
    in0.MBR_HOME_ADDR_CNTY_NM AS MBR_HOME_ADDR_CNTY_NM,
    in0.SPIRA_BNF_ID AS SPIRA_BNF_ID,
    in0.SPIRA_CARE_IND AS SPIRA_CARE_IND,
    in0.MBR_HOME_ADDR_PHN_NO AS MBR_HOME_ADDR_PHN_NO,
    in0.CELL_PHN_NO AS CELL_PHN_NO,
    in0.TOTAL_DX_SCORE AS TOTAL_DX_SCORE,
    in0.TOTAL_TX_SCORE AS TOTAL_TX_SCORE,
    in0.TOTAL_AS_SCORE AS TOTAL_AS_SCORE,
    in0.VULNERABILITY_INDEX AS VULNERABILITY_INDEX,
    in0.DOB AS DOB,
    in0.PROV_SK AS PROV_SK,
    in0.MED_HOME_GRP_DESC AS MED_HOME_GRP_DESC,
    in0.MED_HOME_LOC_DESC AS MED_HOME_LOC_DESC,
    in0.PCMH_ATTRIBUTED AS PCMH_ATTRIBUTED,
    in0.ATTRIBUTED AS ATTRIBUTED,
    in0.PROV_NM AS PROV_NM,
    in0.PROV_REL_GRP_PROV_NM AS PROV_REL_GRP_PROV_NM,
    in0.LATEST_PCP_VISIT_DT AS LATEST_PCP_VISIT_DT,
    in0.MAX_ROW_EFF_DT AS MAX_ROW_EFF_DT,
    in0.MATCHLEVEL AS MATCHLEVEL,
    in0.`Person 1colon Ethnic - Country Of Origin` AS `Person 1colon Ethnic - Country Of Origin`,
    in0.`Person 1colon Ethnic - Ethnic` AS `Person 1colon Ethnic - Ethnic`,
    in0.`Person 1colon Ethnic - Group` AS `Person 1colon Ethnic - Group`,
    in0.`Person 1colon Ethnic - Religion` AS `Person 1colon Ethnic - Religion`,
    in0.`Person 1colon Ethnic - Language Preference` AS `Person 1colon Ethnic - Language Preference`,
    in0.`Person 1colon Ethnic - Assimilation` AS `Person 1colon Ethnic - Assimilation`,
    in0.est_hh_income AS est_hh_income,
    in0.est_hh_income_range AS est_hh_income_range,
    in0.est_hh_income_range_low AS est_hh_income_range_low,
    in0.est_hh_income_range_high AS est_hh_income_range_high,
    in1.MBR_ID AS MBR_ID,
    in1.AdvancedCKD_Risk AS AdvancedCKD_Risk,
    in1.Dialysis_Flag AS Dialysis_Flag,
    in1.`Previous CKD Risk` AS `Previous CKD Risk`,
    in1.MIN_RELATIONSHIP_EFF_DT AS MIN_RELATIONSHIP_EFF_DT,
    in0.* EXCEPT (`Member Individual Business Entity Key`, 
    `_Null_`, 
    `Asthma`, 
    `CAD`, 
    `Cancer`, 
    `CHF`, 
    `COPD`, 
    `Diabetes`, 
    `ESRD`, 
    `Hypertension`, 
    `Risk Cost Code`, 
    `Concurrent Normalized Risk Score`, 
    `Prospective Normalized Risk Score`, 
    `Recent 3 Months Total Allowable Amount`, 
    `Current 12 Months Total Allowable Amount`, 
    `SOURCE_ID`, 
    `MBR_INDV_BE_KEY`, 
    `TOTAL_ALLOWED_AMT`, 
    `READMIN_DSCHG_DT`, 
    `Prediction Value`, 
    `Prediction Score`, 
    `ADMITTING_DX`, 
    `UNIQUE_DRUG_CT_CURRENT`, 
    `READMITPREDICTION`, 
    `NONEMERGENT_RATE`, 
    `NONEMERGENT_COUNT_PAST_60`, 
    `ER_COUNT_PAST_2_MONTHS`, 
    `ER_COUNT_PAST_3_MONTHS`, 
    `ED_DSCHG_DT`, 
    `ER_COUNT`, 
    `LATEST_ED_DX`, 
    `ED Prediction Score`, 
    `ED Prediction Value`, 
    `EDPREDICTION`, 
    `MBR_UNIQ_KEY`, 
    `MBR_FULL_NM`, 
    `PROD_SH_NM`, 
    `MBR_GNDR_CD`, 
    `MBR_AGE`, 
    `AGE_RANGE`, 
    `MBR_RELSHP_CD`, 
    `GRP_FUNDING_ARRANGEMENT`, 
    `GRP_ID`, 
    `GRP_NM`, 
    `PRNT_GRP_SIC_NACIS_CD`, 
    `PRNT_GRP_SIC_NACIS_NM`, 
    `SUB_CNTGS_CNTY_CD`, 
    `SUB_MKTNG_METRO_RURAL_CD`, 
    `MBR_HOME_ADDR_LN_1`, 
    `MBR_HOME_ADDR_LN_2`, 
    `MBR_HOME_ADDR_CITY_NM`, 
    `MBR_HOME_ADDR_ST_CD`, 
    `MBR_HOME_ADDR_ZIP_CD_5`, 
    `MBR_HOME_ADDR_CNTY_NM`, 
    `SPIRA_BNF_ID`, 
    `SPIRA_CARE_IND`, 
    `MBR_HOME_ADDR_PHN_NO`, 
    `CELL_PHN_NO`, 
    `TOTAL_DX_SCORE`, 
    `TOTAL_TX_SCORE`, 
    `TOTAL_AS_SCORE`, 
    `VULNERABILITY_INDEX`, 
    `DOB`, 
    `PROV_SK`, 
    `MED_HOME_GRP_DESC`, 
    `MED_HOME_LOC_DESC`, 
    `PCMH_ATTRIBUTED`, 
    `ATTRIBUTED`, 
    `PROV_NM`, 
    `PROV_REL_GRP_PROV_NM`, 
    `LATEST_PCP_VISIT_DT`, 
    `MAX_ROW_EFF_DT`, 
    `MATCHLEVEL`, 
    `Person 1colon Ethnic - Country Of Origin`, 
    `Person 1colon Ethnic - Ethnic`, 
    `Person 1colon Ethnic - Group`, 
    `Person 1colon Ethnic - Religion`, 
    `Person 1colon Ethnic - Language Preference`, 
    `Person 1colon Ethnic - Assimilation`, 
    `est_hh_income`, 
    `est_hh_income_range`, 
    `est_hh_income_range_low`, 
    `est_hh_income_range_high`)
  
  FROM Join_805_left_UnionLeftOuter AS in0
  LEFT JOIN CKD_Risk_List_c_1675 AS in1
     ON (in0.`Member Individual Business Entity Key` = in1.UNIVERSALMEMBERID)

)

SELECT *

FROM Join_822_left_UnionLeftOuter
