---
version: 2
models:
- name: "intervention__AlteryxSelect_838"
  tags:
  - "prophecy_temp"
- name: "intervention__AlteryxSelect_860"
  tags:
  - "prophecy_temp"
- name: "intervention__AlteryxSelect_890"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1019"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1019_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1020"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1020_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1649"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1649_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1650"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1650_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1652"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1652_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1655"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1655_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1656"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1656_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1659"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_1659_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_816"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_869"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_869_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_870"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_870_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_871"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_871_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_872"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_872_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_873"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_873_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_874"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_874_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_875"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_875_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_876"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_876_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_877"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_877_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_878"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_878_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_879"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_879_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_880"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_880_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_883"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_883_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_884"
  tags:
  - "prophecy_temp"
- name: "intervention__Filter_884_reject"
  tags:
  - "prophecy_temp"
- name: "intervention__Formula_1021_0"
  tags:
  - "prophecy_temp"
- name: "intervention__Formula_782_0"
  tags:
  - "prophecy_temp"
- name: "intervention__Formula_814_0"
  tags:
  - "prophecy_temp"
- name: "intervention__INTERVENTION_LI_765"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_776_left_UnionFullOuter"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_792_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_798_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_800_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_805_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_815_inner"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_822_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_834_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_850_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "intervention__Join_864_inner"
  tags:
  - "prophecy_temp"
- name: "intervention__MultiFieldFormula_772"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_771"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_777"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_779"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_785"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_786"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_801"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_818"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_819"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_820"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_824"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_825"
  tags:
  - "prophecy_temp"
- name: "intervention__Summarize_826"
  tags:
  - "prophecy_temp"
- name: "intervention__Union_784"
  tags:
  - "prophecy_temp"
- name: "intervention__Union_817"
  tags:
  - "prophecy_temp"
- name: "intervention__Union_866"
  tags:
  - "prophecy_temp"
- name: "intervention__Unique_1018"
  tags:
  - "prophecy_temp"
