---
version: 2
models:
- name: "Step_1_Contribution_Margin_BulkLoader__Join_26_inner"
  tags:
  - "prophecy_temp"
- name: "Step_1_Contribution_Margin_BulkLoader__Summarize_43"
  tags:
  - "prophecy_temp"
