---
version: 2
models:
- name: "productos__Union_895"
  tags:
  - "prophecy_temp"
- name: "productos__aka_Server_UYDB_898"
  tags:
  - "prophecy_temp"
- name: "productos__aka_Server_UYDB_900"
  tags:
  - "prophecy_temp"
