---
version: 2
models:
- name: "RM_SEM_V3__AlteryxSelect_338"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Formula_321_0"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Join_311_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Join_329_inner"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Join_373_inner"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Join_384_inner"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Sort_377"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Summarize_323"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Summarize_367"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Summarize_370"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__Summarize_379"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3__googlesheetsoutput_476"
  tags:
  - "prophecy_temp"
