---
version: 2
models:
- name: "wf_standard_core_recruitment_review_thaded__AlteryxSelect_477_cast"
  tags:
  - "prophecy_temp"
- name: "wf_standard_core_recruitment_review_thaded__AlteryxSelect_589"
  tags:
  - "prophecy_temp"
- name: "wf_standard_core_recruitment_review_thaded__AlteryxSelect_590"
  tags:
  - "prophecy_temp"
- name: "wf_standard_core_recruitment_review_thaded__Formula_374_1"
  tags:
  - "prophecy_temp"
- name: "wf_standard_core_recruitment_review_thaded__Formula_395_0"
  tags:
  - "prophecy_temp"
- name: "wf_standard_core_recruitment_review_thaded__Summarize_432"
  tags:
  - "prophecy_temp"
- name: "wf_standard_core_recruitment_review_thaded__aka_GPD_UDDL_Wr_366"
  tags:
  - "prophecy_temp"
