---
version: 2
models:
- name: "Resumo_de_CFOP_SAPXSATI__Filter_11_reject"
  tags:
  - "prophecy_temp"
- name: "Resumo_de_CFOP_SAPXSATI__Formula_57_0"
  tags:
  - "prophecy_temp"
- name: "Resumo_de_CFOP_SAPXSATI__MultiRowFormula_10_row_id_drop_0"
  tags:
  - "prophecy_temp"
