---
version: 2
models:
- name: "alteryx_medio__AppendFields_227"
  tags:
  - "prophecy_temp"
- name: "alteryx_medio__Filter_160"
  tags:
  - "prophecy_temp"
- name: "alteryx_medio__Filter_160_reject"
  tags:
  - "prophecy_temp"
- name: "alteryx_medio__Join_172_left"
  tags:
  - "prophecy_temp"
- name: "alteryx_medio__Summarize_158"
  tags:
  - "prophecy_temp"
- name: "alteryx_medio__TextInput_285_cast"
  tags:
  - "prophecy_temp"
- name: "alteryx_medio__Union_159"
  tags:
  - "prophecy_temp"
- name: "alteryx_medio__Union_170"
  tags:
  - "prophecy_temp"
- name: "alteryx_medio__aka_Server_UYDB_192"
  tags:
  - "prophecy_temp"
