pipelines:
  alteryx_all_test_stage2_sql:
    visualGroups:
      Sampledatedata:
        isCollapsed: false
        height: 417
        width: 1014
        nodes:
        - "JoinMultiple_78"
        - "JoinMultiple_78_in0"
        - "JoinMultiple_78_in1"
        - "TextInput_260"
        - "TextInput_260_cast"
