entityType: ""
providerType: "BigQuery"
fields:
- name: "NM"
  dataType:
    type: "String"
- name: "RSKF"
  dataType:
    type: "String"
- name: "QN_4"
  dataType:
    type: "String"
- name: "UPM"
  dataType:
    type: "String"
- name: "SDK"
  dataType:
    type: "String"
- name: "RSK"
  dataType:
    type: "String"
- name: "VPM"
  dataType:
    type: "String"
- name: "QN_3"
  dataType:
    type: "String"
- name: "MESS_DATUM"
  dataType:
    type: "String"
- name: "PM"
  dataType:
    type: "String"
- name: "TMK"
  dataType:
    type: "String"
- name: "STATIONS_ID"
  dataType:
    type: "String"
- name: "eor"
  dataType:
    type: "String"
- name: "FM"
  dataType:
    type: "String"
- name: "TGK"
  dataType:
    type: "String"
- name: "FX"
  dataType:
    type: "String"
- name: "SHK_TAG"
  dataType:
    type: "String"
- name: "TNK"
  dataType:
    type: "String"
- name: "TXK"
  dataType:
    type: "String"
