---
version: 2
models:
- name: "Barrier_Bend_Monitoring_1___AlteryxSelect_80"
  tags:
  - "prophecy_temp"
- name: "Barrier_Bend_Monitoring_1___AlteryxSelect_84"
  tags:
  - "prophecy_temp"
- name: "Barrier_Bend_Monitoring_1___Formula_72_3"
  tags:
  - "prophecy_temp"
- name: "Barrier_Bend_Monitoring_1___Formula_85_0"
  tags:
  - "prophecy_temp"
- name: "Barrier_Bend_Monitoring_1___PortfolioComposerTable_98"
  tags:
  - "prophecy_temp"
