# ==================
# Project Details
# ==================
name: "new_sec_proj"
config-version: 2
require-dbt-version:
- ">=1.0.0"
- "<2.0.0"
version: "0.1"
profile: "prophecy-default"

# ==================
# File Path Configs
# ==================
test-paths:
- "tests"
clean-targets:
- "target"
- "dbt_modules"
- "logs"
snapshot-paths:
- "snapshots"
seed-paths:
- "seeds"
packages-install-path: "dbt_packages"
model-paths:
- "models"
- "prophecy-sources"
log-path: "logs"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  Configuration_t_137: ""
  Configuration_t_14: ""
  Configuration_t_28: ""
  Configuration_t_29: ""
  Configuration_t_5: ""
  Configuration_t_57: ""
  Configuration_t_58: ""
  Configuration_t_83: ""
  Configuration_t_88: ""
  Configuration_t_89: ""
  Configuration_t_90: ""
  GEM_Credit_Trad_1_76: ""
  GEM_Credit_Trad_1_79: ""
  NaN_Credit_DM_x_26: ""
  VCGBondVolumesR_1_75: ""
  db_name: ""
  schema_name: ""
  table_75_Output4_macro_op: ""
  table_76_Output4_macro_op: ""
  table_79_Output4_macro_op: ""

# ============
# Misc
# ============
dispatch: []
