---
version: 2
models:
- name: "check_stuff__exclude_id_column"
  tags:
  - "prophecy_temp"
- name: "check_stuff__generate_record_id"
  tags:
  - "prophecy_temp"
- name: "check_stuff__query_with_redundant_aliases"
  tags:
  - "prophecy_temp"
- name: "check_stuff__reformat_1"
  tags:
  - "prophecy_temp"
