pipelines:
  "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1_":
    visualGroups:
      DataQualityIssues:
        isCollapsed: false
        height: 2647.666748046875
        width: 3194.28564453125
        nodes:
        - "AlteryxSelect_398"
        - "AlteryxSelect_400"
        - "AlteryxSelect_407"
        - "AlteryxSelect_410"
        - "AlteryxSelect_428"
        - "AlteryxSelect_555"
        - "AlteryxSelect_596"
        - "AlteryxSelect_597"
        - "AppendFields_561"
        - "DynamicRename_598"
        - "Filter_426"
        - "Filter_439"
        - "Formula_394_0"
        - "Formula_399_0"
        - "Formula_401_0"
        - "Formula_406_0"
        - "Formula_409_0"
        - "Formula_412_0"
        - "Formula_417_0"
        - "Formula_429_0"
        - "Formula_433_0"
        - "Formula_441_0"
        - "Formula_564_0"
        - "Formula_604_0"
        - "Join_592_inner"
        - "Transpose_424"
        - "Union_395"
        - "Union_395_reformat_0"
        - "Union_395_reformat_1"
        - "Union_395_reformat_10"
        - "Union_395_reformat_11"
        - "Union_395_reformat_2"
        - "Union_395_reformat_3"
        - "Union_395_reformat_4"
        - "Union_395_reformat_5"
        - "Union_395_reformat_6"
        - "Union_395_reformat_7"
        - "Union_395_reformat_8"
        - "Union_395_reformat_9"
        - "Union_562"
        - "Union_599"
        - "Union_599_reformat_0"
        - "Union_599_reformat_1"
        - "Unique_321_drop_0"
        - "Unique_321_filter"
        - "Unique_321_window"
        - "Unique_397_drop_0"
        - "Unique_397_filter"
        - "Unique_397_window"
        - "Unique_587"
        - "Unique_587_drop_0"
        - "Unique_587_filter"
        - "Unique_587_window"
      INPUTITEMMASTER:
        isCollapsed: false
        height: 515
        width: 1000
        nodes:
        - "AlteryxSelect_130"
        - "AlteryxSelect_9"
        - "Cleanse_214"
        - "Cleanse_316"
        - "DbFileInput_8_8"
        - "Filter_13"
        - "Formula_215_0"
        - "WarehouseMaster_129"
