pipelines:
  "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1_":
    visualGroups:
      DataQualityIssues:
        isCollapsed: false
        height: 2647.666748046875
        width: 3194.28564453125
        nodes:
        - "AlteryxSelect_398"
        - "AlteryxSelect_400"
        - "AlteryxSelect_407"
        - "AlteryxSelect_410"
        - "AlteryxSelect_428"
        - "AlteryxSelect_555"
        - "AlteryxSelect_596"
        - "AlteryxSelect_597"
        - "AppendFields_561"
        - "DynamicRename_598"
        - "Filter_426"
        - "Filter_439"
        - "Formula_394_0"
        - "Formula_399_0"
        - "Formula_401_0"
        - "Formula_406_0"
        - "Formula_409_0"
        - "Formula_412_0"
        - "Formula_417_0"
        - "Formula_429_0"
        - "Formula_433_0"
        - "Formula_441_0"
        - "Formula_564_0"
        - "Formula_604_0"
        - "Join_592_inner"
        - "Transpose_424"
        - "Union_395"
        - "Union_395_reformat_0"
        - "Union_395_reformat_1"
        - "Union_395_reformat_10"
        - "Union_395_reformat_11"
        - "Union_395_reformat_2"
        - "Union_395_reformat_3"
        - "Union_395_reformat_4"
        - "Union_395_reformat_5"
        - "Union_395_reformat_6"
        - "Union_395_reformat_7"
        - "Union_395_reformat_8"
        - "Union_395_reformat_9"
        - "Union_562"
        - "Union_599"
        - "Union_599_reformat_0"
        - "Union_599_reformat_1"
        - "Unique_321_drop_0"
        - "Unique_321_filter"
        - "Unique_321_window"
        - "Unique_397_drop_0"
        - "Unique_397_filter"
        - "Unique_397_window"
        - "Unique_587"
        - "Unique_587_drop_0"
        - "Unique_587_filter"
        - "Unique_587_window"
      INPUTITEMMASTER:
        isCollapsed: false
        height: 515
        width: 1000
        nodes:
        - "AlteryxSelect_130"
        - "AlteryxSelect_9"
        - "Cleanse_214"
        - "Cleanse_316"
        - "DbFileInput_8_8"
        - "Filter_13"
        - "Formula_215_0"
        - "WarehouseMaster_129"
  "102_trade_area_overlap_The_Rad_Valentina":
    visualGroups:
      Workflow:
        isCollapsed: false
        height: 2472
        width: 3550
        nodes:
        - "AlteryxSelect_133"
        - "County_Polygons_5"
        - "CreatePoints_125"
        - "CreatePoints_125_cast_lonlat"
        - "Formula_137"
        - "Formula_145_0"
        - "Formula_145_1"
        - "SpatialInfo_134"
        - "SpatialInfo_135"
        - "SpatialMatch_128"
        - "SpatialMatch_142"
        - "SpatialProcess_131"
        - "Stores_yxdb_4"
        - "Summarize_140"
        - "TradeArea_127"
  Alteryx_Data_Visualization_for_2021_Adidas_Sales_Data:
    visualGroups:
      Adidas2021SalesinUSAforDataVisualization:
        isCollapsed: false
        height: 2400
        width: 5126
        nodes:
        - "AdidasUSSalesDa_1"
        - "AlteryxSelect_11"
        - "AlteryxSelect_14"
        - "AlteryxSelect_2"
        - "AlteryxSelect_8"
        - "CrossTab_13"
        - "CrossTab_13_rename"
        - "Filter_10"
        - "Formula_18_0"
        - "Formula_4_0"
        - "Formula_50_0"
        - "Formula_50_1"
        - "Formula_56_0"
        - "Formula_56_1"
        - "Formula_63_0"
        - "Formula_63_1"
        - "JoinMultiple_75"
        - "JoinMultiple_75_in0"
        - "JoinMultiple_75_in1"
        - "JoinMultiple_75_in2"
        - "JoinMultiple_75_in3"
        - "MultiFieldFormula_24"
        - "MultiFieldFormula_25"
        - "PlotlyCharting_51"
        - "PlotlyCharting_58"
        - "PlotlyCharting_65"
        - "PortfolioComposerImage_71"
        - "PortfolioComposerLayout_74"
        - "PortfolioComposerLayout_80"
        - "PortfolioComposerRender_81"
        - "PortfolioComposerTable_26"
        - "PortfolioComposerText_67"
        - "PortfolioComposerText_68"
        - "PortfolioComposerText_69"
        - "PortfolioComposerText_70"
        - "PortfolioComposerText_72"
        - "Sample_34"
        - "Sample_55"
        - "Sample_62"
        - "Summarize_29"
        - "Summarize_53"
        - "Summarize_60"
        - "Summarize_9"
