{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH FindReplace_390 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1_', 'FindReplace_390') }}

),

FindReplace_390_reorg_0 AS (

  SELECT 
    (GET_PATH((PARSE_JSON(_EXTRACTED_RULE)), 'EVENT')) AS EVENT,
    * EXCLUDE ("_RULES", "_EXTRACTED_RULE")
  
  FROM FindReplace_390 AS in0

),

Formula_380_0 AS (

  SELECT 
    (
      CASE
        WHEN ((EVENT IS NULL) OR ((LENGTH(EVENT)) = 0))
          THEN PRODUCTION_OR_TRANSFER
        ELSE EVENT
      END
    ) AS EVENT,
    (
      CASE
        WHEN (WH_ID_STANDARD = '99999')
          THEN 'TOTAL-ITEM'
        ELSE WH_DESC_STANDARD
      END
    ) AS WH_DESC_STANDARD,
    (-1 * CAST(SALES_QTY AS INTEGER)) AS SALES_QTY,
    CAST((REGEXP_REPLACE((REGEXP_REPLACE((REGEXP_REPLACE(CURRENT_TIMESTAMP, ':', '')), '-', '')), ' ', '_')) AS STRING) AS RUNDATETIME,
    * EXCLUDE ("EVENT", "SALES_QTY", "WH_DESC_STANDARD")
  
  FROM FindReplace_390_reorg_0 AS in0

),

RecordID_381 AS (

  {{
    prophecy_basics.RecordID(
      ['Formula_380_0'], 
      'incremental_id', 
      'ROWID', 
      'integer', 
      6, 
      1, 
      'tableLevel', 
      'first_column', 
      [], 
      []
    )
  }}

),

AlteryxSelect_372 AS (

  SELECT 
    ROWID AS ROWID,
    SKU_CATEGORY AS SKU_CATEGORY,
    SKU_STANDARD AS SKU_STANDARD,
    SKU_DESC_STANDARD AS SKU_DESC_STANDARD,
    WH_ID_STANDARD AS WH_ID_STANDARD,
    WH_DESC_STANDARD AS WH_DESC_STANDARD,
    EVENT AS EVENT,
    DATE_OF_EVENT AS DATE_OF_EVENT,
    BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    SALES_QTY AS SALES_QTY,
    PRODUCTION_QTY AS PRODUCTION_QTY,
    TRANSFER_QTY AS TRANSFER_QTY,
    ENDING_INVENTORY AS ENDING_INVENTORY,
    PICKUP_OR_DELIVERY AS PICKUP_OR_DELIVERY,
    SHIP_DT AS SHIP_DT,
    DELIVERY_DT AS DELIVERY_DT,
    CUSTOMER AS CUSTOMER,
    SALES_ORDER AS SALES_ORDER,
    PO_NUMBER AS PO_NUMBER,
    "13_WK_WKLY_AVG_SALES" AS "13_WK_WKLY_AVG_SALES",
    WEEKS_ON_HAND_INV AS WEEKS_ON_HAND_INV,
    "FCST_2021-11-01" AS "FCST_2021-11-01",
    "FCST_2021-12-01" AS "FCST_2021-12-01",
    "FCST_2022-01-01" AS "FCST_2022-01-01",
    "FCST_2022-02-01" AS "FCST_2022-02-01",
    "FCST_2022-03-01" AS "FCST_2022-03-01",
    "FCST_2022-04-01" AS "FCST_2022-04-01",
    PRODUCTION_OR_TRANSFER AS PRODUCTION_OR_TRANSFER,
    ALERT_ITEM_WOH_INV_LOW AS ALERT_ITEM_WOH_INV_LOW,
    ALERT_ITEM_WOH_INV_HIGH AS ALERT_ITEM_WOH_INV_HIGH,
    ALERT_PROJECTED_SHORT_IN_WH_FOR_ITEM AS ALERT_PROJECTED_SHORT_IN_WH_FOR_ITEM,
    FILENAME AS FILENAME,
    ROWTYPE AS ROWTYPE,
    ROWSORTTIER AS ROWSORTTIER,
    RUNDATETIME AS RUNDATETIME,
    SOURCE_SKU AS SOURCE_SKU,
    SOURCE_SKU_DESC AS SOURCE_SKU_DESC,
    * EXCLUDE ("QTY", 
    "ROWID", 
    "SKU_CATEGORY", 
    "SKU_STANDARD", 
    "SKU_DESC_STANDARD", 
    "WH_ID_STANDARD", 
    "WH_DESC_STANDARD", 
    "EVENT", 
    "DATE_OF_EVENT", 
    "BEGINNING_INVENTORY", 
    "SALES_QTY", 
    "PRODUCTION_QTY", 
    "TRANSFER_QTY", 
    "ENDING_INVENTORY", 
    "PICKUP_OR_DELIVERY", 
    "SHIP_DT", 
    "DELIVERY_DT", 
    "CUSTOMER", 
    "SALES_ORDER", 
    "PO_NUMBER", 
    "13_WK_WKLY_AVG_SALES", 
    "WEEKS_ON_HAND_INV", 
    "FCST_2021-11-01", 
    "FCST_2021-12-01", 
    "FCST_2022-01-01", 
    "FCST_2022-02-01", 
    "FCST_2022-03-01", 
    "FCST_2022-04-01", 
    "PRODUCTION_OR_TRANSFER", 
    "ALERT_ITEM_WOH_INV_LOW", 
    "ALERT_ITEM_WOH_INV_HIGH", 
    "ALERT_PROJECTED_SHORT_IN_WH_FOR_ITEM", 
    "FILENAME", 
    "ROWTYPE", 
    "ROWSORTTIER", 
    "RUNDATETIME", 
    "SOURCE_SKU", 
    "SOURCE_SKU_DESC")
  
  FROM RecordID_381 AS in0

)

SELECT *

FROM AlteryxSelect_372
