{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH Cleanse_316 AS (

  SELECT *
  
  FROM {{ ref('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Cleanse_316')}}

),

FindReplace_370_allRules AS (

  SELECT (ARRAY_AGG((OBJECT_CONSTRUCT('WH_DESC_STANDARD', WH_DESC_STANDARD, 'WH_ID_STANDARD', WH_ID_STANDARD)))) AS _RULES
  
  FROM Cleanse_316 AS in0

),

FindReplace_369 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1_', 'FindReplace_369') }}

),

FindReplace_369_reorg_0 AS (

  SELECT 
    (GET_PATH((PARSE_JSON(_EXTRACTED_RULE)), 'SKU_DESC_STANDARD')) AS SKU_DESC_STANDARD,
    (GET_PATH((PARSE_JSON(_EXTRACTED_RULE)), 'SKU_CATEGORY')) AS SKU_CATEGORY,
    * EXCLUDE ("_RULES", "_EXTRACTED_RULE")
  
  FROM FindReplace_369 AS in0

),

FindReplace_370_join AS (

  SELECT 
    in0.SOURCE_SKU AS SOURCE_SKU,
    in0.ALERT_ITEM_WOH_INV_HIGH AS ALERT_ITEM_WOH_INV_HIGH,
    in0.TRANSFER_QTY AS TRANSFER_QTY,
    in0.ALERT_PROJECTED_SHORT_IN_WH_FOR_ITEM AS ALERT_PROJECTED_SHORT_IN_WH_FOR_ITEM,
    in0.PICKUP_OR_DELIVERY AS PICKUP_OR_DELIVERY,
    in0.DATE_OF_EVENT AS DATE_OF_EVENT,
    in0.SKU_CATEGORY AS SKU_CATEGORY,
    in0.SKU_STANDARD AS SKU_STANDARD,
    in0.PRODUCTION_OR_TRANSFER AS PRODUCTION_OR_TRANSFER,
    in0."FCST_2022-01-01" AS "FCST_2022-01-01",
    in0.ROWTYPE AS ROWTYPE,
    in0.DELIVERY_DT AS DELIVERY_DT,
    in0."FCST_2022-02-01" AS "FCST_2022-02-01",
    in0."FCST_2021-12-01" AS "FCST_2021-12-01",
    in0."FCST_2021-09-01" AS "FCST_2021-09-01",
    in0."FCST_2021-11-01" AS "FCST_2021-11-01",
    in0.WH_ID_STANDARD AS WH_ID_STANDARD,
    in0."13_WK_WKLY_AVG_SALES" AS "13_WK_WKLY_AVG_SALES",
    in0.SKU_DESC_STANDARD AS SKU_DESC_STANDARD,
    in0.BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    in0.WEEKS_ON_HAND_INV AS WEEKS_ON_HAND_INV,
    in0.PRODUCTION_QTY AS PRODUCTION_QTY,
    in0.ALERT_ITEM_WOH_INV_LOW AS ALERT_ITEM_WOH_INV_LOW,
    in0.PO_NUMBER AS PO_NUMBER,
    in0."FCST_2022-03-01" AS "FCST_2022-03-01",
    in0."FCST_2021-10-01" AS "FCST_2021-10-01",
    in0.ENDING_INVENTORY AS ENDING_INVENTORY,
    in0."FCST_2022-04-01" AS "FCST_2022-04-01",
    in0.FILENAME AS FILENAME,
    in0.CUSTOMER AS CUSTOMER,
    in0.QTY AS QTY,
    in1._RULES AS _RULES,
    in0.SALES_ORDER AS SALES_ORDER,
    in0.SHIP_DT AS SHIP_DT,
    in0.SALES_QTY AS SALES_QTY,
    in0.ROWSORTTIER AS ROWSORTTIER,
    in0.SOURCE_SKU_DESC AS SOURCE_SKU_DESC
  
  FROM FindReplace_369_reorg_0 AS in0
  FULL JOIN FindReplace_370_allRules AS in1
     ON TRUE

)

SELECT *

FROM FindReplace_370_join
