{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH AlteryxSelect_228 AS (

  SELECT *
  
  FROM {{ ref('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_228')}}

),

Union_240_reformat_0 AS (

  SELECT 
    BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    CAST(CUSTOMER AS STRING) AS CUSTOMER,
    DATE_OF_EVENT AS DATE_OF_EVENT,
    (TO_CHAR(DELIVERY_DT, 'YYYY-MM-DD')) AS DELIVERY_DT,
    ENDING_INVENTORY AS ENDING_INVENTORY,
    CAST(FILENAME AS STRING) AS FILENAME,
    CAST(PICKUP_OR_DELIVERY AS STRING) AS PICKUP_OR_DELIVERY,
    CAST(PO_NUMBER AS STRING) AS PO_NUMBER,
    CAST(PRODUCTION_OR_TRANSFER AS STRING) AS PRODUCTION_OR_TRANSFER,
    PRODUCTION_QTY AS PRODUCTION_QTY,
    CAST(QTY AS FLOAT) AS QTY,
    ROWSORTTIER AS ROWSORTTIER,
    ROWTYPE AS ROWTYPE,
    CAST(SALES_ORDER AS STRING) AS SALES_ORDER,
    SALES_QTY AS SALES_QTY,
    (TO_CHAR(SHIP_DT, 'YYYY-MM-DD')) AS SHIP_DT,
    CAST(SKU_CATEGORY AS STRING) AS SKU_CATEGORY,
    CAST(SKU_DESC_STANDARD AS STRING) AS SKU_DESC_STANDARD,
    SKU_STANDARD AS SKU_STANDARD,
    CAST(SOURCE_SKU AS STRING) AS SOURCE_SKU,
    CAST(SOURCE_SKU_DESC AS STRING) AS SOURCE_SKU_DESC,
    TRANSFER_QTY AS TRANSFER_QTY,
    CAST(WH_DESC_STANDARD AS STRING) AS WH_DESC_STANDARD,
    CAST(WH_ID_STANDARD AS STRING) AS WH_ID_STANDARD
  
  FROM AlteryxSelect_228 AS in0

),

Formula_215_0 AS (

  SELECT *
  
  FROM {{ ref('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Formula_215_0')}}

),

FindReplace_369_allRules AS (

  SELECT (
           ARRAY_AGG(
             (OBJECT_CONSTRUCT('SKU_DESC_STANDARD', SKU_DESC_STANDARD, 'SKU_CATEGORY', SKU_CATEGORY, 'SKU_STANDARD', SKU_STANDARD)))
         ) AS _RULES
  
  FROM Formula_215_0 AS in0

),

Formula_347_1 AS (

  SELECT *
  
  FROM {{ ref('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Formula_347_1')}}

),

AlteryxSelect_551 AS (

  SELECT *
  
  FROM {{ ref('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_551')}}

),

Join_553_left_UnionLeftOuter AS (

  SELECT 
    in0.SKU_STANDARD AS SKU_STANDARD,
    in0.DATE_OF_EVENT AS DATE_OF_EVENT,
    in0.BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    in0.SALES_QTY AS SALES_QTY,
    in0.PRODUCTION_QTY AS PRODUCTION_QTY,
    in0.TRANSFER_QTY AS TRANSFER_QTY,
    in0.ENDING_INVENTORY AS ENDING_INVENTORY,
    in0.ROWTYPE AS ROWTYPE,
    in0.ROWSORTTIER AS ROWSORTTIER,
    in0.WH_ID_STANDARD AS WH_ID_STANDARD,
    in0."13_WK_WKLY_AVG_SALES" AS "13_WK_WKLY_AVG_SALES",
    in0.WEEKS_ON_HAND_INV AS WEEKS_ON_HAND_INV,
    in1."FCST_2021-11-01" AS "FCST_2021-11-01",
    in1."FCST_2021-12-01" AS "FCST_2021-12-01",
    in1."FCST_2022-01-01" AS "FCST_2022-01-01",
    in1."FCST_2022-02-01" AS "FCST_2022-02-01",
    in1."FCST_2022-03-01" AS "FCST_2022-03-01",
    in1."FCST_2022-04-01" AS "FCST_2022-04-01",
    in0.* EXCLUDE ("SKU_STANDARD", 
    "DATE_OF_EVENT", 
    "BEGINNING_INVENTORY", 
    "SALES_QTY", 
    "PRODUCTION_QTY", 
    "TRANSFER_QTY", 
    "ENDING_INVENTORY", 
    "ROWTYPE", 
    "ROWSORTTIER", 
    "WH_ID_STANDARD", 
    "13_WK_WKLY_AVG_SALES", 
    "WEEKS_ON_HAND_INV"),
    in1.* EXCLUDE ("SKU_STANDARD", 
    "FCST_2021-11-01", 
    "FCST_2021-12-01", 
    "FCST_2022-01-01", 
    "FCST_2022-02-01", 
    "FCST_2022-03-01", 
    "FCST_2022-04-01")
  
  FROM Formula_347_1 AS in0
  LEFT JOIN AlteryxSelect_551 AS in1
     ON (in0.SKU_STANDARD = in1.SKU_STANDARD)

),

Union_240_reformat_1 AS (

  SELECT 
    "13_WK_WKLY_AVG_SALES" AS "13_WK_WKLY_AVG_SALES",
    BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    DATE_OF_EVENT AS DATE_OF_EVENT,
    ENDING_INVENTORY AS ENDING_INVENTORY,
    CAST("FCST_2021-09-01" AS STRING) AS "FCST_2021-09-01",
    CAST("FCST_2021-10-01" AS STRING) AS "FCST_2021-10-01",
    CAST("FCST_2021-11-01" AS STRING) AS "FCST_2021-11-01",
    CAST("FCST_2021-12-01" AS STRING) AS "FCST_2021-12-01",
    CAST("FCST_2022-01-01" AS STRING) AS "FCST_2022-01-01",
    CAST("FCST_2022-02-01" AS STRING) AS "FCST_2022-02-01",
    CAST("FCST_2022-03-01" AS STRING) AS "FCST_2022-03-01",
    CAST("FCST_2022-04-01" AS STRING) AS "FCST_2022-04-01",
    PRODUCTION_QTY AS PRODUCTION_QTY,
    ROWSORTTIER AS ROWSORTTIER,
    ROWTYPE AS ROWTYPE,
    SALES_QTY AS SALES_QTY,
    SKU_STANDARD AS SKU_STANDARD,
    TRANSFER_QTY AS TRANSFER_QTY,
    WEEKS_ON_HAND_INV AS WEEKS_ON_HAND_INV,
    CAST(WH_ID_STANDARD AS STRING) AS WH_ID_STANDARD
  
  FROM Join_553_left_UnionLeftOuter AS in0

),

Summarize_232 AS (

  SELECT 
    MAX(DATE_OF_EVENT) AS DATE_OF_EVENT,
    SUM(BEGINNING_INVENTORY) AS BEGINNING_INVENTORY,
    SUM(SALES_QTY) AS SALES_QTY,
    SUM(PRODUCTION_QTY) AS PRODUCTION_QTY,
    SUM(TRANSFER_QTY) AS TRANSFER_QTY,
    SUM(QTY) AS ENDING_INVENTORY,
    SKU_STANDARD AS SKU_STANDARD,
    WH_ID_STANDARD AS WH_ID_STANDARD
  
  FROM AlteryxSelect_228 AS in0
  
  GROUP BY 
    SKU_STANDARD, WH_ID_STANDARD

),

Formula_234_0 AS (

  SELECT 
    CAST('3_TOTAL_ITEM_WH_LEVEL' AS STRING) AS ROWTYPE,
    3 AS ROWSORTTIER,
    *
  
  FROM Summarize_232 AS in0

),

Union_240_reformat_2 AS (

  SELECT 
    BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    DATE_OF_EVENT AS DATE_OF_EVENT,
    ENDING_INVENTORY AS ENDING_INVENTORY,
    PRODUCTION_QTY AS PRODUCTION_QTY,
    ROWSORTTIER AS ROWSORTTIER,
    ROWTYPE AS ROWTYPE,
    SALES_QTY AS SALES_QTY,
    SKU_STANDARD AS SKU_STANDARD,
    TRANSFER_QTY AS TRANSFER_QTY,
    CAST(WH_ID_STANDARD AS STRING) AS WH_ID_STANDARD
  
  FROM Formula_234_0 AS in0

),

Union_240 AS (

  {{
    prophecy_basics.UnionByName(
      ['Union_240_reformat_0', 'Union_240_reformat_2', 'Union_240_reformat_1'], 
      [
        '[{"name": "BEGINNING_INVENTORY", "dataType": "Number"}, {"name": "CUSTOMER", "dataType": "String"}, {"name": "DATE_OF_EVENT", "dataType": "Date"}, {"name": "DELIVERY_DT", "dataType": "String"}, {"name": "ENDING_INVENTORY", "dataType": "Number"}, {"name": "FILENAME", "dataType": "String"}, {"name": "PICKUP_OR_DELIVERY", "dataType": "String"}, {"name": "PO_NUMBER", "dataType": "String"}, {"name": "PRODUCTION_OR_TRANSFER", "dataType": "String"}, {"name": "PRODUCTION_QTY", "dataType": "Number"}, {"name": "QTY", "dataType": "Float"}, {"name": "ROWSORTTIER", "dataType": "Number"}, {"name": "ROWTYPE", "dataType": "String"}, {"name": "SALES_ORDER", "dataType": "String"}, {"name": "SALES_QTY", "dataType": "Number"}, {"name": "SHIP_DT", "dataType": "String"}, {"name": "SKU_CATEGORY", "dataType": "String"}, {"name": "SKU_DESC_STANDARD", "dataType": "String"}, {"name": "SKU_STANDARD", "dataType": "String"}, {"name": "SOURCE_SKU", "dataType": "String"}, {"name": "SOURCE_SKU_DESC", "dataType": "String"}, {"name": "TRANSFER_QTY", "dataType": "Number"}, {"name": "WH_DESC_STANDARD", "dataType": "String"}, {"name": "WH_ID_STANDARD", "dataType": "String"}]', 
        '[{"name": "BEGINNING_INVENTORY", "dataType": "Number"}, {"name": "DATE_OF_EVENT", "dataType": "Date"}, {"name": "ENDING_INVENTORY", "dataType": "Float"}, {"name": "PRODUCTION_QTY", "dataType": "Number"}, {"name": "ROWSORTTIER", "dataType": "Number"}, {"name": "ROWTYPE", "dataType": "String"}, {"name": "SALES_QTY", "dataType": "Number"}, {"name": "SKU_STANDARD", "dataType": "String"}, {"name": "TRANSFER_QTY", "dataType": "Number"}, {"name": "WH_ID_STANDARD", "dataType": "String"}]', 
        '[{"name": "13_WK_WKLY_AVG_SALES", "dataType": "Number"}, {"name": "BEGINNING_INVENTORY", "dataType": "Number"}, {"name": "DATE_OF_EVENT", "dataType": "Date"}, {"name": "ENDING_INVENTORY", "dataType": "Float"}, {"name": "FCST_2021-09-01", "dataType": "String"}, {"name": "FCST_2021-10-01", "dataType": "String"}, {"name": "FCST_2021-11-01", "dataType": "String"}, {"name": "FCST_2021-12-01", "dataType": "String"}, {"name": "FCST_2022-01-01", "dataType": "String"}, {"name": "FCST_2022-02-01", "dataType": "String"}, {"name": "FCST_2022-03-01", "dataType": "String"}, {"name": "FCST_2022-04-01", "dataType": "String"}, {"name": "PRODUCTION_QTY", "dataType": "Number"}, {"name": "ROWSORTTIER", "dataType": "Number"}, {"name": "ROWTYPE", "dataType": "String"}, {"name": "SALES_QTY", "dataType": "Number"}, {"name": "SKU_STANDARD", "dataType": "String"}, {"name": "TRANSFER_QTY", "dataType": "Number"}, {"name": "WEEKS_ON_HAND_INV", "dataType": "Number"}, {"name": "WH_ID_STANDARD", "dataType": "String"}]'
      ], 
      'allowMissingColumns'
    )
  }}

),

AlteryxSelect_325 AS (

  SELECT 
    SKU_STANDARD AS SKU_STANDARD,
    SKU_DESC_STANDARD AS SKU_DESC_STANDARD,
    WH_ID_STANDARD AS WH_ID_STANDARD,
    WH_DESC_STANDARD AS WH_DESC_STANDARD,
    ROWTYPE AS ROWTYPE,
    DATE_OF_EVENT AS DATE_OF_EVENT,
    QTY AS QTY,
    BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    SALES_QTY AS SALES_QTY,
    PRODUCTION_QTY AS PRODUCTION_QTY,
    TRANSFER_QTY AS TRANSFER_QTY,
    ENDING_INVENTORY AS ENDING_INVENTORY,
    PICKUP_OR_DELIVERY AS PICKUP_OR_DELIVERY,
    SHIP_DT AS SHIP_DT,
    DELIVERY_DT AS DELIVERY_DT,
    CUSTOMER AS CUSTOMER,
    SALES_ORDER AS SALES_ORDER,
    PO_NUMBER AS PO_NUMBER,
    "13_WK_WKLY_AVG_SALES" AS "13_WK_WKLY_AVG_SALES",
    WEEKS_ON_HAND_INV AS WEEKS_ON_HAND_INV,
    PRODUCTION_OR_TRANSFER AS PRODUCTION_OR_TRANSFER,
    ROWSORTTIER AS ROWSORTTIER,
    FILENAME AS FILENAME,
    SOURCE_SKU AS SOURCE_SKU,
    SOURCE_SKU_DESC AS SOURCE_SKU_DESC,
    SKU_CATEGORY AS SKU_CATEGORY,
    "FCST_2021-11-01" AS "FCST_2021-11-01",
    "FCST_2021-12-01" AS "FCST_2021-12-01",
    "FCST_2022-01-01" AS "FCST_2022-01-01",
    "FCST_2022-02-01" AS "FCST_2022-02-01",
    "FCST_2022-03-01" AS "FCST_2022-03-01",
    "FCST_2022-04-01" AS "FCST_2022-04-01",
    * EXCLUDE ("SKU_STANDARD", 
    "SKU_DESC_STANDARD", 
    "WH_ID_STANDARD", 
    "WH_DESC_STANDARD", 
    "ROWTYPE", 
    "DATE_OF_EVENT", 
    "QTY", 
    "BEGINNING_INVENTORY", 
    "SALES_QTY", 
    "PRODUCTION_QTY", 
    "TRANSFER_QTY", 
    "ENDING_INVENTORY", 
    "PICKUP_OR_DELIVERY", 
    "SHIP_DT", 
    "DELIVERY_DT", 
    "CUSTOMER", 
    "SALES_ORDER", 
    "PO_NUMBER", 
    "13_WK_WKLY_AVG_SALES", 
    "WEEKS_ON_HAND_INV", 
    "PRODUCTION_OR_TRANSFER", 
    "ROWSORTTIER", 
    "FILENAME", 
    "SOURCE_SKU", 
    "SOURCE_SKU_DESC", 
    "SKU_CATEGORY", 
    "FCST_2021-11-01", 
    "FCST_2021-12-01", 
    "FCST_2022-01-01", 
    "FCST_2022-02-01", 
    "FCST_2022-03-01", 
    "FCST_2022-04-01")
  
  FROM Union_240 AS in0

),

Formula_350_0 AS (

  SELECT *
  
  FROM {{ ref('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Formula_350_0')}}

),

Join_364_inner AS (

  SELECT 
    in0.* EXCLUDE ("DATE_OF_EVENT", 
    "13_WK_WKLY_AVG_SALES", 
    "WH_ID_STANDARD", 
    "WEEKS_ON_HAND_INV", 
    "PRODUCTION_QTY", 
    "TRANSFER_QTY", 
    "ROWTYPE", 
    "ENDING_INVENTORY", 
    "SALES_QTY", 
    "BEGINNING_INVENTORY", 
    "ROWSORTTIER"),
    in1.* EXCLUDE ("SKU_STANDARD")
  
  FROM AlteryxSelect_325 AS in0
  INNER JOIN Formula_350_0 AS in1
     ON (in0.SKU_STANDARD = in1.SKU_STANDARD)

),

Summarize_355 AS (

  SELECT *
  
  FROM {{ ref('0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Summarize_355')}}

),

Join_375_left_UnionLeftOuter AS (

  SELECT 
    in0.*,
    in1.* EXCLUDE ("SKU_STANDARD", "WH_ID_STANDARD")
  
  FROM Join_364_inner AS in0
  LEFT JOIN Summarize_355 AS in1
     ON ((in0.SKU_STANDARD = in1.SKU_STANDARD) AND (in0.WH_ID_STANDARD = CAST(in1.WH_ID_STANDARD AS DOUBLE)))

),

AlteryxSelect_371 AS (

  SELECT * EXCLUDE ("SKU_DESC_STANDARD", "WH_DESC_STANDARD", "SKU_CATEGORY")
  
  FROM Join_375_left_UnionLeftOuter AS in0

),

FindReplace_369_join AS (

  SELECT 
    in0.SOURCE_SKU AS SOURCE_SKU,
    in0.ALERT_ITEM_WOH_INV_HIGH AS ALERT_ITEM_WOH_INV_HIGH,
    in0.TRANSFER_QTY AS TRANSFER_QTY,
    in0.ALERT_PROJECTED_SHORT_IN_WH_FOR_ITEM AS ALERT_PROJECTED_SHORT_IN_WH_FOR_ITEM,
    in0.PICKUP_OR_DELIVERY AS PICKUP_OR_DELIVERY,
    in0.DATE_OF_EVENT AS DATE_OF_EVENT,
    in0.SKU_STANDARD AS SKU_STANDARD,
    in0.PRODUCTION_OR_TRANSFER AS PRODUCTION_OR_TRANSFER,
    in0."FCST_2022-01-01" AS "FCST_2022-01-01",
    in0.ROWTYPE AS ROWTYPE,
    in0.DELIVERY_DT AS DELIVERY_DT,
    in0."FCST_2022-02-01" AS "FCST_2022-02-01",
    in0."FCST_2021-12-01" AS "FCST_2021-12-01",
    in0."FCST_2021-09-01" AS "FCST_2021-09-01",
    in0."FCST_2021-11-01" AS "FCST_2021-11-01",
    in0.WH_ID_STANDARD AS WH_ID_STANDARD,
    in0."13_WK_WKLY_AVG_SALES" AS "13_WK_WKLY_AVG_SALES",
    in0.BEGINNING_INVENTORY AS BEGINNING_INVENTORY,
    in0.WEEKS_ON_HAND_INV AS WEEKS_ON_HAND_INV,
    in0.PRODUCTION_QTY AS PRODUCTION_QTY,
    in0.ALERT_ITEM_WOH_INV_LOW AS ALERT_ITEM_WOH_INV_LOW,
    in0.PO_NUMBER AS PO_NUMBER,
    in0."FCST_2022-03-01" AS "FCST_2022-03-01",
    in0."FCST_2021-10-01" AS "FCST_2021-10-01",
    in0.ENDING_INVENTORY AS ENDING_INVENTORY,
    in0."FCST_2022-04-01" AS "FCST_2022-04-01",
    in0.FILENAME AS FILENAME,
    in0.CUSTOMER AS CUSTOMER,
    in0.QTY AS QTY,
    in1._RULES AS _RULES,
    in0.SALES_ORDER AS SALES_ORDER,
    in0.SHIP_DT AS SHIP_DT,
    in0.SALES_QTY AS SALES_QTY,
    in0.ROWSORTTIER AS ROWSORTTIER,
    in0.SOURCE_SKU_DESC AS SOURCE_SKU_DESC
  
  FROM AlteryxSelect_371 AS in0
  FULL JOIN FindReplace_369_allRules AS in1
     ON TRUE

)

SELECT *

FROM FindReplace_369_join
