---
version: 2
models:
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_228"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_338"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_372"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_387"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_422"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_533"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_547"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___AlteryxSelect_551"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Cleanse_214"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Cleanse_316"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Cleanse_317"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Filter_480"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___FindReplace_369_join"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___FindReplace_370_join"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___FindReplace_390_join"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Formula_215_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Formula_237_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Formula_282_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Formula_347_1"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Formula_350_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Join_195_left"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Join_202_left"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Join_339_left"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___SelectRecords_386_cleanup_0"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Summarize_173"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Summarize_355"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Summarize_626"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Union_160"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Union_198"
  tags:
  - "prophecy_temp"
- name: "0_SUPPLY_PLANNING_CALCULATION_ENGINE_v0_4_1___Union_449"
  tags:
  - "prophecy_temp"
