# ==================
# Project Details
# ==================
name: ""
version: ""

# ==================
# File Path Configs
# ==================
test-paths:
- "tests"
snapshot-paths:
- "snapshots"
seed-paths:
- "seeds"
packages-install-path: "dbt_packages"
model-paths:
- "models"
- "prophecy-sources"
log-path: "logs"
macro-paths:
- "macros"
target-path: "target"

# ============
# Misc
# ============
dispatch: []
