---
version: 2
models:
- name: "facility_master_wf_updated_macro_paths_1004__Filter_26_1004"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths_1004__FuzzyMatch_41_1004_reformat"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths_1004__table_1004_Output6_macro_op"
  tags:
  - "prophecy_temp"
