{{
  config({    
    "materialized": "table",
    "alias": "MISS_TO_MRS_CLIENT",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_client_staging_update__RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT')}}

),

RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT_EXPR_19 AS (

  SELECT 
    CLID4 AS CLID1,
    SOURCE_TYPE4 AS source_type1,
    MERGE_CLID4 AS MERGE_CLID1,
    business_date4 AS business_date1,
    TITLE_LKP4 AS TITLE_L1,
    OUTPUT_TITLE4 AS TITLE_E1,
    SURNAME_LKP4 AS SURNAME_L1,
    SURNAME4 AS SURNAME_E1,
    FORENAMES4 AS FORENAMES,
    INITIALS4 AS INITIALS,
    GENDER4 AS GENDER_E1,
    DOB4 AS DOB,
    feed_update_id4 AS FEED_UPDATE_ID,
    CLIENT_CLASS4 AS CLIENT_CLASS,
    CLIENT_STATUS4 AS CLIENT_STATUS,
    EFROM4 AS EFROM4,
    CLID_LKP4 AS CLID_LKP4,
    CUSTOMER_NUMBER4 AS CUSTOMER_NUMBER4,
    SOURCE_SYSTEM_CODE4 AS SOURCE_SYSTEM_CODE4,
    SOURCE_RECORD_TYPE4 AS SOURCE_RECORD_TYPE4,
    business_date_minus_14 AS business_date_minus_14,
    TOTAL_COMPARE4 AS TOTAL_COMPARE4,
    BUSINESS_DATE_CHK4 AS BUSINESS_DATE_CHK4
  
  FROM RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT AS in0

),

FIL_MISS_TO_MRS AS (

  SELECT * 
  
  FROM RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT_EXPR_19 AS in0
  
  WHERE CAST((
          ((CAST(UPPER(TITLE_L1) AS STRING) = 'MISS') AND (CAST(UPPER(TITLE_E1) AS STRING) = 'MRS'))
          AND (UPPER(SURNAME_L1) <> UPPER(SURNAME_E1))
        ) AS BOOL)

),

FIL_MISS_TO_MRS_EXPR_10 AS (

  SELECT 
    CLID1 AS CLID,
    business_date1 AS BUSINESS_DATE,
    GENDER_E1 AS GENDER,
    source_type1 AS SOURCE_TYPE,
    MERGE_CLID1 AS MERGE_CLID,
    FORENAMES AS FORENAMES,
    DOB AS DOB,
    CLIENT_STATUS AS STATUS,
    FEED_UPDATE_ID AS FEED_UPDATE_ID,
    SURNAME_E1 AS SURNAME,
    CLIENT_CLASS AS CLASS,
    INITIALS AS INITIALS,
    TITLE_E1 AS TITLE
  
  FROM FIL_MISS_TO_MRS AS in0

)

SELECT *

FROM FIL_MISS_TO_MRS_EXPR_10
