---
version: 2
models:
- name: "m_rep_cards_orig_client_staging_update__CHOOSES"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__CHOOSES1_EXP"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__CLIENT_STAGING_EXISTING_CLIENT_DIFF_DATE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__CLIENT_STAGING_NEW_CLIENT"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__CLIENT_STAGING_UPDATE_SAME_DAY"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__EXP_CARDSORIG_CLIENT"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__EXP_CARDSORIG_CLIENT_EXPR_12"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__MINERVA_EXCEPTION_NEW_RECORD"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__MISS_TO_MRS_CLIENT"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__RTR_CARDSORIG_CLIENT_EXPR_SAME_CLIENT_DIFFERENT_DATE_INSERT"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__SEQ_clid_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_client_staging_update__find_business_date"
  tags:
  - "prophecy_temp"
