pipelines:
  Alteryx_Data_Visualization_for_2021_Adidas_Sales_Data:
    visualGroups:
      Adidas2021SalesinUSAforDataVisualization:
        isCollapsed: false
        height: 880
        width: 3871.428466796875
        nodes:
        - "AdidasUSSalesDa_1"
        - "AlteryxSelect_11"
        - "AlteryxSelect_14"
        - "AlteryxSelect_2"
        - "AlteryxSelect_8"
        - "CrossTab_13"
        - "CrossTab_13_rename"
        - "Filter_10"
        - "Formula_18_0"
        - "Formula_4_0"
        - "Formula_50_0"
        - "Formula_50_1"
        - "Formula_56_0"
        - "Formula_56_1"
        - "Formula_63_0"
        - "Formula_63_1"
        - "JoinMultiple_75"
        - "JoinMultiple_75_in0"
        - "JoinMultiple_75_in1"
        - "JoinMultiple_75_in2"
        - "JoinMultiple_75_in3"
        - "MultiFieldFormula_24"
        - "MultiFieldFormula_25"
        - "PlotlyCharting_51"
        - "PlotlyCharting_58"
        - "PlotlyCharting_65"
        - "PortfolioComposerImage_71"
        - "PortfolioComposerLayout_74"
        - "PortfolioComposerLayout_80"
        - "PortfolioComposerRender_81"
        - "PortfolioComposerTable_26"
        - "PortfolioComposerText_67"
        - "PortfolioComposerText_68"
        - "PortfolioComposerText_69"
        - "PortfolioComposerText_70"
        - "PortfolioComposerText_72"
        - "Sample_34"
        - "Sample_55"
        - "Sample_62"
        - "Summarize_29"
        - "Summarize_53"
        - "Summarize_60"
        - "Summarize_9"
  Alteryx_Data_Visualization_for_2021_Adidas_Sales_Data11:
    visualGroups:
      Adidas2021SalesinUSAforDataVisualization:
        isCollapsed: false
        height: 880
        width: 3871.428466796875
        nodes:
        - "AdidasUSSalesDa_1"
        - "AlteryxSelect_11"
        - "AlteryxSelect_14"
        - "AlteryxSelect_2"
        - "AlteryxSelect_8"
        - "CrossTab_13"
        - "CrossTab_13_rename"
        - "Filter_10"
        - "Formula_18_0"
        - "Formula_4_0"
        - "Formula_50_0"
        - "Formula_50_1"
        - "Formula_56_0"
        - "Formula_56_1"
        - "Formula_63_0"
        - "Formula_63_1"
        - "JoinMultiple_75"
        - "JoinMultiple_75_in0"
        - "JoinMultiple_75_in1"
        - "JoinMultiple_75_in2"
        - "JoinMultiple_75_in3"
        - "MultiFieldFormula_24"
        - "MultiFieldFormula_25"
        - "PlotlyCharting_51"
        - "PlotlyCharting_58"
        - "PlotlyCharting_65"
        - "PortfolioComposerImage_71"
        - "PortfolioComposerLayout_74"
        - "PortfolioComposerLayout_80"
        - "PortfolioComposerRender_81"
        - "PortfolioComposerTable_26"
        - "PortfolioComposerText_67"
        - "PortfolioComposerText_68"
        - "PortfolioComposerText_69"
        - "PortfolioComposerText_70"
        - "PortfolioComposerText_72"
        - "Sample_34"
        - "Sample_55"
        - "Sample_62"
        - "Summarize_29"
        - "Summarize_53"
        - "Summarize_60"
        - "Summarize_9"
  Log_Extraction:
    visualGroups:
      ReadfromSpecifiedDirectory:
        isCollapsed: false
        height: 280
        width: 280
