---
version: 2
models:
- name: "p1__AppendFields_67"
  tags:
  - "prophecy_temp"
- name: "p1__TextInput_1_cast"
  tags:
  - "prophecy_temp"
- name: "p1__batch_macro_61_in0"
  tags:
  - "prophecy_temp"
- name: "p1__truncate_61"
  tags:
  - "prophecy_temp"
