pipelines:
  FDI_HL_Owned_Loans_Tertiary_Monthly:
    visualGroups:
      PublishtoTableau:
        isCollapsed: false
        height: 399
        width: 366
        nodes:
        - "Macro_48"
      PublishtoSLF:
        isCollapsed: false
        height: 399
        width: 316
        nodes:
        - "Macro_50"
      Next3months:
        isCollapsed: false
        height: 399
        width: 386
        nodes:
        - "Source__User_Db_45"
      First3months:
        isCollapsed: false
        height: 399
        width: 386
        nodes:
        - "Source__User_Db_42"
      FDIHLOwnedLoansSummary:
        isCollapsed: false
        height: 1233
        width: 1716
        nodes:
        - "First3months"
        - "Formula_41_0"
        - "Next3months"
        - "PublishtoSLF"
        - "PublishtoTableau"
        - "Union_39"
