---
version: 2
models:
- name: "right_s_1__Union_895"
  tags:
  - "prophecy_temp"
- name: "right_s_1__aka_Server_UYDB_898"
  tags:
  - "prophecy_temp"
- name: "right_s_1__aka_Server_UYDB_900"
  tags:
  - "prophecy_temp"
