---
version: 2
models:
- name: "RM_SEM_V3656__AlteryxSelect_338"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Filter_288"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Formula_321_0"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Join_311_left_UnionLeftOuter"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Join_329_inner"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Join_373_inner"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Join_384_inner"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__MultiRowFormula_440_row_id_0"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Sort_377"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Summarize_323"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Summarize_367"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Summarize_370"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__Summarize_379"
  tags:
  - "prophecy_temp"
- name: "RM_SEM_V3656__googlesheetsoutput_476"
  tags:
  - "prophecy_temp"
