entityType: ""
providerType: "Databricks"
fields:
- name: "APPLICATION_DATE"
  dataType:
    type: "Timestamp"
- name: "PERIODID"
  dataType:
    type: "Double"
- name: "MIGRATION_FLAG"
  dataType:
    type: "String"
- name: "CLIENTID"
  dataType:
    type: "Double"
- name: "FINAL_DECISION_PRIMARY"
  dataType:
    type: "String"
- name: "LAST_DECISION_DATE"
  dataType:
    type: "Timestamp"
- name: "APPLICATION_TYPE"
  dataType:
    type: "String"
- name: "STATUS"
  dataType:
    type: "String"
- name: "DISPLAY_ACCOUNT_NUMBER"
  dataType:
    type: "String"
- name: "PRODUCT"
  dataType:
    type: "String"
- name: "ACC_NUM"
  dataType:
    type: "String"
- name: "CARD_ORIGIN"
  dataType:
    type: "Double"
- name: "ACCID"
  dataType:
    type: "Double"
- name: "CARDSAFE"
  dataType:
    type: "String"
- name: "EMBOSSER_NUMBER"
  dataType:
    type: "String"
- name: "FINAL_DECISION_COARSE"
  dataType:
    type: "String"
- name: "CARD_PROTECTION"
  dataType:
    type: "String"
- name: "CUSTOMER_NUMBER"
  dataType:
    type: "String"
- name: "SOURCE_CODE"
  dataType:
    type: "String"
- name: "PRODUCT_CODE"
  dataType:
    type: "String"
- name: "SYSTEM_CREDIT_LIMIT"
  dataType:
    type: "Double"
- name: "OFFER_CODE"
  dataType:
    type: "String"
- name: "INITIAL_DECISION_COARSE"
  dataType:
    type: "String"
