# ==================
# Project Details
# ==================
name: "test_bq_gcp"
config-version: 2
require-dbt-version:
- ">=1.0.0"
- "<2.0.0"
version: "0.1"
profile: "prophecy-default"

# ==================
# File Path Configs
# ==================
clean-targets:
- "target"
- "dbt_modules"
- "logs"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  CCI_Break_Out_c_80: ""
  CCI_Scores_yxdb_81: ""
  Database__LOADI_111: ""
  Database__LOADI_98: ""
  Database__REPOR_1: ""
  Database__REPOR_2: ""
  Database__REPOR_301: ""
  Database__REPOR_36: ""
  Database__REPOR_84: ""
  Database__Repor_8: ""
  Database__loadi_234: ""
  Database__loadi_236: ""
  Database__loadi_237: ""
  Database__loadi_298: ""
  Database__repor_1: ""
  Database__repor_11: ""
  Database__repor_118: ""
  Database__repor_12: ""
  Database__repor_31: ""
  Database__repor_32: ""
  Database__repor_49: ""
  Database__repor_50: ""
  Database__repor_6: ""
  Database__repor_88: ""
  Database__repor_9: ""
  OverallSystemTe_1: ""
  OverallSystemTe_111: ""
  OverallTestFilt_90: ""
  Query_SELECTF___4: ""
  aka_Server_UYDB_192: ""
  aka_Server_UYDB_194: ""
  aka_Server_UYDB_201: ""
  aka_Server_UYDB_213: ""
  aka_Server_UYDB_214: ""
  aka_Server_UYDB_215: ""
  aka_Server_UYDB_216: ""
  aka_Server_UYDB_217: ""
  aka_Server_UYDB_218: ""
  aka_Server_UYDB_219: ""
  aka_Server_UYDB_220: ""
  aka_Server_UYDB_221: ""
  aka_Server_UYDB_222: ""
  aka_Server_UYDB_223: ""
  aka_Server_UYDB_311: ""
  aka_Server_UYDB_501: ""
  aka_Server_UYDB_502: ""
  aka_Server_UYDB_504: ""
  aka_Server_UYDB_51: ""
  aka_Server_UYDB_543: ""
  aka_Server_UYDB_551: ""
  aka_Server_UYDB_597: ""
  aka_Server_UYDB_606: ""
  aka_Server_UYDB_616: ""
  aka_Server_UYDB_660: ""
  aka_Server_UYDB_662: ""
  aka_Server_UYDB_692: ""
  aka_Server_UYDB_696: ""
  aka_Server_UYDB_704: ""
  aka_Server_UYDB_740: ""
  aka_Server_UYDB_827: ""
  aka_Server_UYDB_830: ""
  db_name: ""
  dcm_phpdatabase_3: ""
  dcm_phpdatabase_4: ""
  dcm_phpdatabase_47: ""
  dcm_phpdatabase_49: ""
  dcm_phpdatabase_72: ""
  numberofcallsto_231: ""
  post_tree_join__43: ""
  post_tree_join__44: ""
  post_tree_join__45: ""
  schema_name: ""
