---
version: 2
models:
- name: "m_rep_cards_orig_account_update__EXP_ACCOUNT_CHANGE_VARS_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_update__EXP_ACCOUNT_COMPARE"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_update__HOLDS"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_update__MINERVA_EXCEPTION"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_update__NEW_ACCOUNT"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_update__NEW_CHOOSES"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_update__NEW_MAINTAINS"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_update__RTR_ACCOUNT_JOIN_EXPR_42"
  tags:
  - "prophecy_temp"
- name: "m_rep_cards_orig_account_update__UPD_ACCOUNT"
  tags:
  - "prophecy_temp"
