---
version: 2
models:
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__AppendFields_265"
  tags:
  - "prophecy_temp"
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__AppendFields_282"
  tags:
  - "prophecy_temp"
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__AppendFields_283"
  tags:
  - "prophecy_temp"
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__AppendFields_290"
  tags:
  - "prophecy_temp"
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__Filter_251"
  tags:
  - "prophecy_temp"
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__Formula_220_to_Formula_286_2"
  tags:
  - "prophecy_temp"
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__Formula_233_0"
  tags:
  - "prophecy_temp"
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__Formula_263_to_Formula_259_3"
  tags:
  - "prophecy_temp"
- name: "FDI_Treasury_Altx_Sol_FAS107_2025_Q1__Formula_273_1"
  tags:
  - "prophecy_temp"
