---
version: 2
models:
- name: "facility_master_wf_updated_macro_paths__Filter_221"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Filter_867"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Formula_793_to_Formula_1078_0"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Summarize_1020"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Summarize_239"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Summarize_866"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Union_897"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Union_947"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Unique_1018"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__Unique_949"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__aka_GPD_UDDL_Wr_788"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__table_1004_Input43_macro_ip"
  tags:
  - "prophecy_temp"
- name: "facility_master_wf_updated_macro_paths__table_1070_Input12_macro_ip"
  tags:
  - "prophecy_temp"
