pipelines:
  productos_part1:
    visualGroups:
      CODIGUERAS:
        isCollapsed: false
        height: 630
        width: 306
        nodes:
        - "aka_Server_UYDB_1116"
      CONTRATOS:
        isCollapsed: false
        height: 585
        width: 310
        nodes:
        - "aka_Server_UYDB_1128"
      CalculoProductosMDP:
        isCollapsed: false
        height: 3786
        width: 3678
        nodes:
        - "CalculoTCCodigoProducto1436373839"
        - "CalculoTDCodigoProducto15"
        - "CalculoTrilogyCodigoProducto1"
        - "Cleanse_1016"
        - "Filter_989"
        - "Filter_989_reject"
        - "Join_1014_left_UnionLeftOuter"
        - "Join_1028_inner"
        - "Join_988_inner"
        - "Summarize_1027"
        - "TarjetasCorporativasCodigoProducto21"
        - "Unique_987"
      CalculoTCCodigoProducto1436373839:
        isCollapsed: false
        height: 891
        width: 938
        nodes:
        - "AlteryxSelect_991"
        - "AlteryxSelect_994"
        - "Filter_993"
        - "Formula_990_0"
        - "Formula_992_0"
      CalculoTDCodigoProducto15:
        isCollapsed: false
        height: 720
        width: 566
        nodes:
        - "AlteryxSelect_997"
        - "Formula_996_0"
      CalculoTrilogyCodigoProducto1:
        isCollapsed: false
        height: 1062
        width: 1898
        nodes:
        - "AlteryxSelect_1012"
        - "Filter_1003"
        - "Filter_1004"
        - "Filter_1005"
        - "Filter_1007"
        - "Filter_1008"
        - "Formula_1011_0"
        - "JoinMultiple_999"
        - "Join_1006_inner"
        - "Join_1009_inner"
        - "Summarize_1000"
        - "Summarize_1001"
        - "Summarize_1002"
        - "Union_1010"
      CobrodeSueldosProd9:
        isCollapsed: false
        height: 2808
        width: 8302
        nodes:
        - "CrossTab_1159"
        - "DynamicRename_1160"
        - "Estoesparaponertodoslosmesesaunqueesteen0_3"
        - "Filter_1164"
        - "Formula_1161_0"
        - "Formula_1177_to_Formula_1163_0"
        - "Join_1170_inner"
        - "Join_1175_inner_UnionRightOuter"
        - "PagodeNominasProd18"
        - "RecordID_1169"
        - "Sample_1168"
        - "Summarize_1165"
        - "Summarize_1166"
        - "Summarize_1179"
      Estoesparaponertodoslosmesesaunqueesteen0:
        isCollapsed: false
        height: 417
        width: 782
        nodes:
        - "AppendFields_1224"
        - "Summarize_1223"
      Estoesparaponertodoslosmesesaunqueesteen0_1:
        isCollapsed: false
        height: 507
        width: 782
        nodes:
        - "AppendFields_1283"
        - "Summarize_1282"
      Estoesparaponertodoslosmesesaunqueesteen0_2:
        isCollapsed: false
        height: 417
        width: 782
        nodes:
        - "AppendFields_1260"
        - "Summarize_1259"
      Estoesparaponertodoslosmesesaunqueesteen0_3:
        isCollapsed: false
        height: 381
        width: 782
        nodes:
        - "AppendFields_1172"
        - "Summarize_1171"
      Estoesparaponertodoslosmesesaunqueesteen0_4:
        isCollapsed: false
        height: 603
        width: 950
        nodes:
        - "AppendFields_1107"
        - "AppendFields_1109"
        - "Summarize_1106"
        - "Summarize_1111"
      GetnetProd34:
        isCollapsed: false
        height: 756
        width: 1358
        nodes:
        - "AlteryxSelect_1241"
        - "Filter_1242"
        - "Formula_1240_0"
        - "Formula_1240_1"
        - "Summarize_1243"
        - "Summarize_1244"
      INVENTARIOS:
        isCollapsed: false
        height: 2358
        width: 1496
        nodes:
        - "aka_Server_UYDB_1030"
        - "aka_Server_UYDB_1031"
        - "aka_Server_UYDB_1032"
        - "aka_Server_UYDB_1033"
        - "aka_Server_UYDB_1034"
        - "aka_Server_UYDB_1035"
        - "aka_Server_UYDB_1036"
        - "aka_Server_UYDB_1037"
        - "aka_Server_UYDB_1038"
        - "aka_Server_UYDB_1039"
        - "aka_Server_UYDB_1040"
        - "aka_Server_UYDB_1041"
        - "aka_Server_UYDB_1042"
        - "aka_Server_UYDB_1043"
        - "aka_Server_UYDB_1044"
        - "aka_Server_UYDB_1045"
        - "aka_Server_UYDB_1046"
        - "aka_Server_UYDB_1047"
        - "aka_Server_UYDB_1048"
      Intermediate Target Nodes:
        isCollapsed: false
        height: 4500
        width: 240
        nodes:
        - "intermediate_productos_AlteryxSelect_1012"
        - "intermediate_productos_AlteryxSelect_1025"
        - "intermediate_productos_AlteryxSelect_1098"
        - "intermediate_productos_AlteryxSelect_1210"
        - "intermediate_productos_AlteryxSelect_1241"
        - "intermediate_productos_AlteryxSelect_1288"
        - "intermediate_productos_AlteryxSelect_991"
        - "intermediate_productos_AlteryxSelect_994"
        - "intermediate_productos_AlteryxSelect_997"
        - "intermediate_productos_Formula_1161"
        - "intermediate_productos_aka_Server_UYDB_1032"
        - "intermediate_productos_aka_Server_UYDB_1033"
        - "intermediate_productos_aka_Server_UYDB_1034"
        - "intermediate_productos_aka_Server_UYDB_1035"
        - "intermediate_productos_aka_Server_UYDB_1037"
        - "intermediate_productos_aka_Server_UYDB_1038"
        - "intermediate_productos_aka_Server_UYDB_1039"
        - "intermediate_productos_aka_Server_UYDB_1040"
        - "intermediate_productos_aka_Server_UYDB_1042"
        - "intermediate_productos_aka_Server_UYDB_1044"
        - "intermediate_productos_aka_Server_UYDB_1045"
        - "intermediate_productos_aka_Server_UYDB_1047"
        - "intermediate_productos_aka_Server_UYDB_1048"
        - "intermediate_productos_aka_Server_UYDB_1116"
        - "intermediate_productos_aka_Server_UYDB_1128"
      PagodeImpuestosProd33:
        isCollapsed: false
        height: 1767
        width: 5598
        nodes:
        - "AlteryxSelect_1210"
        - "CrossTab_1211"
        - "DynamicRename_1212"
        - "Estoesparaponertodoslosmesesaunqueesteen0"
        - "Filter_1216"
        - "Formula_1213_0"
        - "Formula_1229_to_Formula_1215_0"
        - "Formula_1230_0"
        - "GetnetProd34"
        - "Join_1222_inner"
        - "Join_1227_inner_UnionRightOuter"
        - "RecordID_1221"
        - "Sample_1220"
        - "Summarize_1217"
        - "Summarize_1218"
      PagodeNominasProd18:
        isCollapsed: false
        height: 1788
        width: 4600
        nodes:
        - "AlteryxSelect_1288"
        - "CrossTab_1250"
        - "CrossTab_1270"
        - "DynamicRename_1248"
        - "DynamicRename_1268"
        - "Estoesparaponertodoslosmesesaunqueesteen0_1"
        - "Estoesparaponertodoslosmesesaunqueesteen0_2"
        - "Filter_1286"
        - "Filter_1286_reject"
        - "Formula_1247_0"
        - "Formula_1254_to_Formula_1246_0"
        - "Formula_1267_0"
        - "Formula_1273_to_Formula_1266_0"
        - "Join_1253_inner"
        - "Join_1263_inner_UnionRightOuter"
        - "Join_1272_inner"
        - "Join_1278_inner_UnionRightOuter"
        - "MultiFieldFormula_1249"
        - "MultiFieldFormula_1269"
        - "RecordID_1258"
        - "RecordID_1277"
        - "Sample_1257"
        - "Sample_1276"
        - "Summarize_1251"
        - "Summarize_1255"
        - "Summarize_1274"
        - "Summarize_1281"
        - "Union_1287"
      TPVProd19:
        isCollapsed: false
        height: 1443
        width: 4780
        nodes:
        - "AlteryxSelect_1098"
        - "CrossTab_1092"
        - "DynamicRename_1093"
        - "Estoesparaponertodoslosmesesaunqueesteen0_4"
        - "Filter_1096"
        - "Filter_1114"
        - "Formula_1091_to_Formula_1095_0"
        - "Formula_1094_0"
        - "Join_1089_inner_UnionRightOuter"
        - "Join_1101_inner"
        - "MultiFieldFormula_1099"
        - "RecordID_1105"
        - "Sample_1104"
        - "Summarize_1097"
        - "Summarize_1102"
      TarjetasCorporativasCodigoProducto21:
        isCollapsed: false
        height: 828
        width: 1766
        nodes:
        - "AlteryxSelect_1025"
        - "Filter_1017_to_Filter_1019"
        - "Formula_1020_0"
        - "Formula_1020_1"
        - "Join_1023_left_UnionLeftOuter"
        - "Summarize_1018"
        - "Summarize_1022"
  productos_part2:
    visualGroups:
      AcuerdodeSobregiro:
        isCollapsed: false
        height: 447
        width: 458
        nodes:
        - "AlteryxSelect_1234"
        - "Formula_1233_0"
      AvalesProd29:
        isCollapsed: false
        height: 666
        width: 986
        nodes:
        - "Filter_1144_to_Filter_1143"
        - "Formula_1140_0"
        - "Summarize_1142"
      ComprasconTCCodigoProducto4yComprasconTDCodigoProducto5:
        isCollapsed: false
        height: 855
        width: 1178
        nodes:
        - "AlteryxSelect_1121"
        - "AlteryxSelect_1125"
        - "Filter_1118"
        - "Filter_1122"
        - "Formula_1119_0"
        - "Formula_1123_0"
        - "Join_1126_inner"
        - "Summarize_1120"
        - "Summarize_1124"
      CreditoGTMProd25:
        isCollapsed: false
        height: 576
        width: 698
        nodes:
        - "AlteryxSelect_1072"
        - "Filter_1070"
        - "Formula_1071_0"
      CreditosComercialesCodigoProducto32:
        isCollapsed: false
        height: 447
        width: 680
        nodes:
        - "AlteryxSelect_1065"
        - "Formula_1064_0"
      CuentasActivasProd26:
        isCollapsed: false
        height: 756
        width: 890
        nodes:
        - "Filter_1148"
        - "Formula_1146_0"
        - "Summarize_1149"
      DebitosAutomaticosServiciosenCuentayTCProd3:
        isCollapsed: false
        height: 702
        width: 806
        nodes:
        - "AlteryxSelect_1052"
        - "Filter_1051"
        - "Formula_1050_0"
      DescuentodeChequesProd23:
        isCollapsed: false
        height: 447
        width: 626
        nodes:
        - "Formula_1137_0"
        - "Summarize_1138"
      DomiciliacionTCCodigoProducto2:
        isCollapsed: false
        height: 585
        width: 698
        nodes:
        - "AlteryxSelect_1183"
        - "Filter_1181"
        - "Formula_1182_0"
      FondosdeInversionProd8:
        isCollapsed: false
        height: 612
        width: 1130
        nodes:
        - "Filter_1130"
        - "Formula_1132_0"
        - "Join_1133_inner"
        - "Summarize_1131"
      GarantiasProd35:
        isCollapsed: false
        height: 687
        width: 1598
        nodes:
        - "AlteryxSelect_1298"
        - "AlteryxSelect_1300"
        - "Filter_1295"
        - "Formula_1297_0"
        - "Formula_1297_1"
        - "Join_1296_inner"
        - "Summarize_1299"
      Intermediate Source Nodes:
        isCollapsed: false
        height: 4500
        width: 240
        nodes:
        - "intermediate_productos_AlteryxSelect_1012"
        - "intermediate_productos_AlteryxSelect_1025"
        - "intermediate_productos_AlteryxSelect_1098"
        - "intermediate_productos_AlteryxSelect_1210"
        - "intermediate_productos_AlteryxSelect_1241"
        - "intermediate_productos_AlteryxSelect_1288"
        - "intermediate_productos_AlteryxSelect_991"
        - "intermediate_productos_AlteryxSelect_994"
        - "intermediate_productos_AlteryxSelect_997"
        - "intermediate_productos_Formula_1161"
        - "intermediate_productos_aka_Server_UYDB_1032"
        - "intermediate_productos_aka_Server_UYDB_1033"
        - "intermediate_productos_aka_Server_UYDB_1034"
        - "intermediate_productos_aka_Server_UYDB_1035"
        - "intermediate_productos_aka_Server_UYDB_1037"
        - "intermediate_productos_aka_Server_UYDB_1038"
        - "intermediate_productos_aka_Server_UYDB_1039"
        - "intermediate_productos_aka_Server_UYDB_1040"
        - "intermediate_productos_aka_Server_UYDB_1042"
        - "intermediate_productos_aka_Server_UYDB_1044"
        - "intermediate_productos_aka_Server_UYDB_1045"
        - "intermediate_productos_aka_Server_UYDB_1047"
        - "intermediate_productos_aka_Server_UYDB_1048"
        - "intermediate_productos_aka_Server_UYDB_1116"
        - "intermediate_productos_aka_Server_UYDB_1128"
      InversionesProd7:
        isCollapsed: false
        height: 447
        width: 650
        nodes:
        - "Formula_1086_0"
        - "Summarize_1085"
      LeasingCodigoProducto28:
        isCollapsed: false
        height: 495
        width: 698
        nodes:
        - "AlteryxSelect_1074"
        - "Filter_1076"
        - "Formula_1075_0"
      Outputs:
        isCollapsed: false
        height: 540
        width: 308
        nodes:
        - "aka_Server_UYDB_900"
      PagoProveedoresProd22:
        isCollapsed: false
        height: 1170
        width: 3146
        nodes:
        - "AlteryxSelect_1193"
        - "AlteryxSelect_1196"
        - "AlteryxSelect_1202"
        - "AppendFields_1194"
        - "AppendFields_1197"
        - "Cleanse_1195"
        - "Cleanse_1198"
        - "CrossTab_1189"
        - "CrossTab_1191"
        - "CrossTab_1200"
        - "Formula_1192_0"
        - "Formula_1199_0"
        - "Formula_1203_0"
        - "Join_1204_inner"
        - "RecordID_1190"
        - "Sample_1188"
        - "Summarize_1185"
        - "Summarize_1186"
        - "Union_1201"
      PrestamoCocheProd12:
        isCollapsed: false
        height: 447
        width: 890
        nodes:
        - "Filter_1057"
        - "Formula_1054_0"
        - "Summarize_1056"
      PrestamoConsumoCodigoProducto17:
        isCollapsed: false
        height: 447
        width: 890
        nodes:
        - "Filter_1062"
        - "Filter_1062_reject_to_Filter_1066"
        - "Formula_1059_0"
        - "Summarize_1061"
      PrestamoHipotecarioProd13:
        isCollapsed: false
        height: 447
        width: 890
        nodes:
        - "Filter_1081"
        - "Formula_1078_0"
        - "Summarize_1080"
      Prestamos:
        isCollapsed: false
        height: 3765
        width: 2404
        nodes:
        - "CreditoGTMProd25"
        - "CreditosComercialesCodigoProducto32"
        - "Filter_1083"
        - "Join_1068_inner"
        - "LeasingCodigoProducto28"
        - "PrestamoCocheProd12"
        - "PrestamoConsumoCodigoProducto17"
        - "PrestamoHipotecarioProd13"
        - "Unique_1069"
      Seguros:
        isCollapsed: false
        height: 711
        width: 938
        nodes:
        - "AlteryxSelect_1154"
        - "AlteryxSelect_1155"
        - "Filter_1151"
        - "Filter_1151_reject"
        - "Filter_1156"
        - "Formula_1152_0"
        - "Formula_1153_0"
      ValoresalCobro:
        isCollapsed: false
        height: 720
        width: 698
        nodes:
        - "AlteryxSelect_1208"
        - "Formula_1207_0"
        - "Summarize_1206"
