{{
  config({    
    "materialized": "table",
    "alias": "CREDIT_APPLICATION_DAILY_HIST",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH SQ_CARDS_ORIG_DECISION_HISTORY AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_decision_history__SQ_CARDS_ORIG_DECISION_HISTORY')}}

),

RTR_CARDS_ORIG_DECISION_HISTORY_out0 AS (

  SELECT * 
  
  FROM SQ_CARDS_ORIG_DECISION_HISTORY AS in0
  
  WHERE ((LAST_ACTION_DATE IS NOT NULL) AND ((LENGTH(CAST(LAST_ACTION_DATE AS STRING))) > 0))

),

RTR_CARDS_ORIG_DECISION_HISTORY_EXPR_DATE_PRESENT AS (

  SELECT 
    ACCID AS ACCID,
    APPLICATION_NUMBER AS APPLICATION_NUMBER1,
    APPLICATION_STATUS AS in_APPLICATION_STATUS,
    LAST_ACTION_DATE AS LAST_ACTION_DATE
  
  FROM RTR_CARDS_ORIG_DECISION_HISTORY_out0 AS in0

),

EXPTRANS AS (

  SELECT 
    ACCID AS ACCID,
    (
      CASE
        WHEN (in_APPLICATION_STATUS = 'CANCELLED')
          THEN 'CA'
        WHEN (in_APPLICATION_STATUS = 'APPROVED')
          THEN 'AP'
        WHEN (in_APPLICATION_STATUS = 'ABORTED')
          THEN 'AX'
        WHEN (in_APPLICATION_STATUS = 'PRODUCT_ONBOARDING_COMPLETED')
          THEN 'AF'
        WHEN (in_APPLICATION_STATUS = 'REFERRED')
          THEN 'RF'
        WHEN (in_APPLICATION_STATUS = 'DECLINED')
          THEN 'DE'
        ELSE NULL
      END
    ) AS EQA_STATUS,
    LAST_ACTION_DATE AS OCCURRENCE_DATE,
    2 AS CARD_ORIGIN
  
  FROM RTR_CARDS_ORIG_DECISION_HISTORY_EXPR_DATE_PRESENT AS in0

),

CREDIT_APPLICATION_DAILY_HIST_EXP AS (

  SELECT 
    ACCID AS ACCID,
    EQA_STATUS AS EQA_STATUS,
    CAST(NULL AS STRING) AS DECISION_ACTION,
    OCCURRENCE_DATE AS OCCURRENCE_DATE,
    CAST(NULL AS STRING) AS DECISION_OPERATOR,
    CAST(NULL AS STRING) AS DECISION_CLASS,
    CAST(NULL AS STRING) AS DECISION_CODE,
    CAST(NULL AS STRING) AS DECISION_SUBCODE,
    CAST(NULL AS STRING) AS DECISION_QUEUE_ID,
    CAST(NULL AS STRING) AS DECISION_LETTER_CODE,
    CARD_ORIGIN AS CARD_ORIGIN
  
  FROM EXPTRANS AS in0

)

SELECT *

FROM CREDIT_APPLICATION_DAILY_HIST_EXP
