{{
  config({    
    "materialized": "ephemeral",
    "database": "QA_DATABASE",
    "schema": "PUBLIC"
  })
}}

WITH housingdata_csv_49 AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('1_challenge_1', 'housingdata_csv_49') }}

),

Formula_50_0 AS (

  SELECT 
    CAST((CONCAT('120950', TRACT, "SUB TRACT")) AS string) AS GEOID,
    *
  
  FROM housingdata_csv_49 AS in0

),

AlteryxSelect_54 AS (

  SELECT 
    GEOID AS GEOID,
    CAST("TOTAL HOUSING UNITS" AS INTEGER) AS "TOTAL HOUSING UNITS",
    CAST("TOTAL VACANT HOUSES" AS INTEGER) AS "TOTAL VACANT HOUSES",
    CAST("    FOR RENT" AS INTEGER) AS "    FOR RENT",
    CAST("    RENTEDCOMMA NOT OCCUPIED" AS INTEGER) AS "    RENTEDCOMMA NOT OCCUPIED",
    CAST("    FOR SALE ONLY" AS INTEGER) AS "    FOR SALE ONLY",
    CAST("    SOLDCOMMA NOT OCCUPIED" AS INTEGER) AS "    SOLDCOMMA NOT OCCUPIED",
    CAST("    FOR SEASONALCOMMA RECREATIONALCOMMA OR OCCASIONAL USE" AS INTEGER) AS "    FOR SEASONALCOMMA RECREATIONALCOMMA OR OCCASIONAL USE",
    CAST("    FOR MIGRANT WORKERS" AS INTEGER) AS "    FOR MIGRANT WORKERS",
    CAST("    OTHER VACANT" AS INTEGER) AS "    OTHER VACANT"
  
  FROM Formula_50_0 AS in0

),

Formula_29_1 AS (

  SELECT *
  
  FROM {{ ref('1_challenge_1__Formula_29_1')}}

),

Join_51_inner AS (

  SELECT 
    in0.* EXCLUDE ("STATE_FIPS_CODE", "COUNTY_FIPS_CODE"),
    in1.* EXCLUDE ("GEOID")
  
  FROM Formula_29_1 AS in0
  INNER JOIN AlteryxSelect_54 AS in1
     ON (in0.GEOID = in1.GEOID)

),

Summarize_53 AS (

  SELECT 
    SUM("TOTAL VACANT HOUSES") AS "SUM_TOTAL VACANT HOUSES",
    SUM("    FOR RENT") AS "SUM_    FOR RENT",
    SUM("    RENTEDCOMMA NOT OCCUPIED") AS "SUM_    RENTEDCOMMA NOT OCCUPIED",
    SUM("    FOR SALE ONLY") AS "SUM_    FOR SALE ONLY",
    SUM("    SOLDCOMMA NOT OCCUPIED") AS "SUM_    SOLDCOMMA NOT OCCUPIED",
    SUM("    FOR MIGRANT WORKERS") AS "SUM_    FOR MIGRANT WORKERS",
    AVG("MEDIAN MONTHLY HOUSING COST  - RENTER") AS "AVG_MEDIAN MONTHLY HOUSING COST  - RENTER",
    "INCOME CATEGORY" AS "INCOME CATEGORY"
  
  FROM Join_51_inner AS in0
  
  GROUP BY "INCOME CATEGORY"

),

Formula_56_0 AS (

  SELECT 
    CAST((("SUM_    FOR RENT" / "SUM_TOTAL VACANT HOUSES") * 100) AS INTEGER) AS "SUM_    FOR RENT",
    CAST((("SUM_    RENTEDCOMMA NOT OCCUPIED" / "SUM_TOTAL VACANT HOUSES") * 100) AS INTEGER) AS "SUM_    RENTEDCOMMA NOT OCCUPIED",
    CAST((("SUM_    FOR SALE ONLY" / "SUM_TOTAL VACANT HOUSES") * 100) AS INTEGER) AS "SUM_    FOR SALE ONLY",
    CAST((("SUM_    SOLDCOMMA NOT OCCUPIED" / "SUM_TOTAL VACANT HOUSES") * 100) AS INTEGER) AS "SUM_    SOLDCOMMA NOT OCCUPIED",
    CAST((("SUM_    FOR MIGRANT WORKERS" / "SUM_TOTAL VACANT HOUSES") * 100) AS INTEGER) AS "SUM_    FOR MIGRANT WORKERS",
    * EXCLUDE ("SUM_    FOR SALE ONLY", 
    "SUM_    RENTEDCOMMA NOT OCCUPIED", 
    "SUM_    SOLDCOMMA NOT OCCUPIED", 
    "SUM_    FOR MIGRANT WORKERS", 
    "SUM_    FOR RENT")
  
  FROM Summarize_53 AS in0

)

SELECT *

FROM Formula_56_0
