---
version: 2
models:
- name: "DQ_Macro__AlteryxSelect_112"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__AlteryxSelect_147"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__AlteryxSelect_148"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__AlteryxSelect_19"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__AlteryxSelect_20"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__AlteryxSelect_25"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__DbFileOutput_18_182"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__Filter_24"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__Formula_163_0"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__Formula_23_1"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__Join_72_inner"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__PortfolioComposerRender_111"
  tags:
  - "prophecy_temp"
- name: "DQ_Macro__PortfolioComposerText_173"
  tags:
  - "prophecy_temp"
