---
version: 2
models:
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__AlteryxSelect_25_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Filter_107_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Filter_107_3124_reject"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Filter_126_3124_reject"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Filter_135_3124_reject"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Formula_145_3124_0"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Join_112_3124_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Join_121_3124_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Join_150_3124_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Join_152_3124_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Join_153_3124_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Join_158_3124_inner"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__RecordID_110_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__RecordID_129_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__RecordID_148_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_114_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_116_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_118_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_123_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_156_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_161_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_163_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_171_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__Summarize_173_3124"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__table_3124_Exit_macro_op"
  tags:
  - "prophecy_temp"
- name: "Databricks_Calculation_Engine_Monthly_Master_EC2_Version_MoM_3124__table_3124_Loop_macro_op"
  tags:
  - "prophecy_temp"
