---
version: 2
models:
- name: "1_challenge_1_1___Formula_29_1"
  tags:
  - "prophecy_temp"
- name: "1_challenge_1_1___Formula_56_0"
  tags:
  - "prophecy_temp"
- name: "1_challenge_1_1___Summarize_40"
  tags:
  - "prophecy_temp"
- name: "1_challenge_1_1___Summarize_47"
  tags:
  - "prophecy_temp"
