{{
  config({    
    "materialized": "table",
    "alias": "INS_LOCATOR_NEW",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_CARDS_ORIG_LOCATOR_reformat AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_locator_update__EXP_CARDS_ORIG_LOCATOR_reformat')}}

),

RTR_CARDS_ORIG_LOCATOR_out0 AS (

  SELECT * 
  
  FROM EXP_CARDS_ORIG_LOCATOR_reformat AS in0
  
  WHERE ((CLID_LOCATOR IS NULL) AND (VALUE IS NOT NULL))

),

RTR_CARDS_ORIG_LOCATOR_EXPR_NEW_LOCATOR AS (

  SELECT 
    CLID_CLIENT_ALIAS AS CLID_CLIENT_ALIAS1,
    MERGE_CLID_CLIENT_ALIAS AS MERGE_CLID_CLIENT_ALIAS1,
    CLASS AS CLASS1,
    SUBCLASS AS SUBCLASS1,
    VALUE AS VALUE1,
    CLID_LOCATOR AS CLID_LOCATOR1,
    EFROM_LOCATOR AS EFROM_LOCATOR1,
    CLASS_LOCATOR AS CLASS_LOCATOR1,
    SUBCLASS_LOCATOR AS SUBCLASS_LOCATOR1,
    VALUE_LOCATOR AS VALUE_LOCATOR1,
    SOURCE_TYPE AS SOURCE_TYPE1,
    business_date AS business_date1,
    business_date_minus_1 AS business_date_minus_11,
    feed_update_id AS feed_update_id1,
    TOTAL_COMPARE AS TOTAL_COMPARE1
  
  FROM RTR_CARDS_ORIG_LOCATOR_out0 AS in0

),

INS_LOCATOR_NEW1_add_missing_column_0 AS (

  SELECT 
    CAST(NULL AS TIMESTAMP) AS ETO,
    *
  
  FROM RTR_CARDS_ORIG_LOCATOR_EXPR_NEW_LOCATOR AS in0

),

INS_LOCATOR_NEW_EXP AS (

  SELECT 
    CLID_CLIENT_ALIAS1 AS CLID,
    SOURCE_TYPE1 AS SOURCE_TYPE,
    MERGE_CLID_CLIENT_ALIAS1 AS MERGE_CLID,
    business_date1 AS EFROM,
    CLASS1 AS CLASS,
    SUBCLASS1 AS SUBCLASS,
    VALUE1 AS `VALUE`,
    CAST(NULL AS STRING) AS CONTACT_POINT_EXTRA_INFO,
    ETO AS ETO
  
  FROM INS_LOCATOR_NEW1_add_missing_column_0 AS in0

)

SELECT *

FROM INS_LOCATOR_NEW_EXP
