---
version: 2
sources:
- name: "QA_DATABASE_QA_SCHEMA"
  database: "QA_DATABASE"
  schema: "QA_SCHEMA"
  tables:
  - name: "account_report"
    quoting:
      identifier: true
    columns:
    - name: "ID"
      dataType:
        type: "String"
    - name: "ISDELETED"
      dataType:
        type: "Number"
    - name: "MASTERRECORDID"
      dataType:
        type: "String"
    - name: "NAME"
      dataType:
        type: "String"
    - name: "TYPE"
      dataType:
        type: "String"
    - name: "PARENTID"
      dataType:
        type: "String"
    - name: "BILLINGSTREET"
      dataType:
        type: "String"
    - name: "BILLINGCITY"
      dataType:
        type: "String"
    - name: "BILLINGSTATE"
      dataType:
        type: "String"
    - name: "BILLINGPOSTALCODE"
      dataType:
        type: "Number"
    - name: "BILLINGCOUNTRY"
      dataType:
        type: "String"
    - name: "BILLINGLATITUDE"
      dataType:
        type: "String"
    - name: "BILLINGLONGITUDE"
      dataType:
        type: "String"
    - name: "BILLINGGEOCODEACCURACY"
      dataType:
        type: "String"
    - name: "SHIPPINGSTREET"
      dataType:
        type: "String"
    - name: "SHIPPINGCITY"
      dataType:
        type: "String"
    - name: "SHIPPINGSTATE"
      dataType:
        type: "String"
    - name: "SHIPPINGPOSTALCODE"
      dataType:
        type: "Number"
    - name: "SHIPPINGCOUNTRY"
      dataType:
        type: "String"
    - name: "SHIPPINGLATITUDE"
      dataType:
        type: "String"
    - name: "SHIPPINGLONGITUDE"
      dataType:
        type: "String"
    - name: "SHIPPINGGEOCODEACCURACY"
      dataType:
        type: "String"
    - name: "PHONE"
      dataType:
        type: "String"
    - name: "FAX"
      dataType:
        type: "String"
    - name: "ACCOUNTNUMBER"
      dataType:
        type: "String"
    - name: "WEBSITE"
      dataType:
        type: "String"
    - name: "SIC"
      dataType:
        type: "Number"
    - name: "INDUSTRY"
      dataType:
        type: "String"
    - name: "ANNUALREVENUE"
      dataType:
        type: "Number"
    - name: "NUMBEROFEMPLOYEES"
      dataType:
        type: "Number"
    - name: "OWNERSHIP"
      dataType:
        type: "String"
    - name: "TICKERSYMBOL"
      dataType:
        type: "String"
    - name: "DESCRIPTION"
      dataType:
        type: "String"
    - name: "RATING"
      dataType:
        type: "String"
    - name: "SITE"
      dataType:
        type: "String"
    - name: "OWNERID"
      dataType:
        type: "String"
    - name: "CREATEDDATE"
      dataType:
        type: "Timestamp"
    - name: "CREATEDBYID"
      dataType:
        type: "String"
    - name: "LASTMODIFIEDDATE"
      dataType:
        type: "Timestamp"
    - name: "LASTMODIFIEDBYID"
      dataType:
        type: "String"
    - name: "SYSTEMMODSTAMP"
      dataType:
        type: "Timestamp"
    - name: "LASTACTIVITYDATE"
      dataType:
        type: "String"
    - name: "JIGSAW"
      dataType:
        type: "String"
    - name: "JIGSAWCOMPANYID"
      dataType:
        type: "String"
    - name: "CLEANSTATUS"
      dataType:
        type: "String"
    - name: "ACCOUNTSOURCE"
      dataType:
        type: "String"
    - name: "DUNSNUMBER"
      dataType:
        type: "String"
    - name: "TRADESTYLE"
      dataType:
        type: "String"
    - name: "NAICSCODE"
      dataType:
        type: "String"
    - name: "NAICSDESC"
      dataType:
        type: "String"
    - name: "YEARSTARTED"
      dataType:
        type: "String"
    - name: "SICDESC"
      dataType:
        type: "String"
    - name: "DANDBCOMPANYID"
      dataType:
        type: "String"
    - name: "OPERATINGHOURSID"
      dataType:
        type: "String"
    - name: "CUSTOMERPRIORITY__C"
      dataType:
        type: "String"
    - name: "SLA__C"
      dataType:
        type: "String"
    - name: "ACTIVE__C"
      dataType:
        type: "String"
    - name: "NUMBEROFLOCATIONS__C"
      dataType:
        type: "Float"
    - name: "UPSELLOPPORTUNITY__C"
      dataType:
        type: "String"
    - name: "SLASERIALNUMBER__C"
      dataType:
        type: "Number"
    - name: "SLAEXPIRATIONDATE__C"
      dataType:
        type: "Timestamp"
    type: "table"
