---
version: 2
models:
- name: "CEM_Securities_PruVal_6m_Trade_Volume_57__metrics_summary"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_57__region_desk_flow_groupBy_002"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_57__region_product_heatmap"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_57__scatter_data_projection_002"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_57__sorted_by_count"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_57__sorted_by_date"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_57__trades_by_product_type"
  tags:
  - "prophecy_temp"
- name: "CEM_Securities_PruVal_6m_Trade_Volume_57__trades_by_region"
  tags:
  - "prophecy_temp"
