{{
  config({    
    "materialized": "table",
    "alias": "REP_CARDS_ORIG_STAGING",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH cardsorigin AS (

  SELECT *
  
  FROM {{ prophecy_tmp_source('m_rep_cards_orig_staging_load', 'cardsorigin') }}

),

SQ_cardsorigin_EXPR_76 AS (

  SELECT 
    productCode AS PRODUCT_CODE,
    product AS PRODUCT,
    productNumber AS PRODUCT_NUMBER,
    applicationNumber AS APPLICATION_NUMBER,
    customerNumber AS CUSTOMER_NUMBER,
    applicationSourceCode AS APPLICATION_SOURCE_CODE,
    applicationType AS APPLICATION_TYPE,
    applicationStoreNumber AS APPLICATION_STORE_NUMBER,
    offerId AS OFFER_ID,
    lastActionDate AS LAST_ACTION_DATE,
    lastDecisionDate AS LAST_DECISION_DATE,
    applicationDate AS APPLICATION_DATE,
    applicationStatus AS APPLICATION_STATUS,
    applicationId AS APPLICATION_ID,
    applicationExpiryDateTime AS APPLICATION_EXPIRY_DATETIME,
    createCustomerResult AS CREATE_CUSTOMER_RESULT,
    accountNumber AS ACCOUNT_NUMBER,
    cardCreationStatus AS CARD_CREATION_STATUS,
    cardSyncStatus AS CARD_SYNC_STATUS,
    cardExpiryDate AS CARD_EXPIRY_DATE,
    cardTokenizationResult AS CARD_TOKENIZATION_RESULT,
    termsAndConditionsAcceptanceTimestamp AS TERMS_AND_CONDITIONS_ACCEPTANCE_TIMESTAMP,
    agreementSignedTimestamp AS AGREEMENT_SIGNED_TIMESTAMP,
    initialOverallDecision AS INITIAL_OVERALL_DECISION,
    initialOverallDecisionReasonCodes AS INITIAL_OVERALL_DECISION_REASON_CODES,
    finalCreditDecisionResult AS FINAL_CREDIT_DECISION_RESULT,
    finalCreditDecisionReasonCodes AS FINAL_CREDIT_DECISION_REASON_CODES,
    finalDecisionDate AS FINAL_DECISION_DATE,
    offeredLimitAmount AS OFFERED_LIMIT_AMOUNT,
    duplicateCustomer AS DUPLICATE_CUSTOMER,
    rtsTransactionStatus AS RTS_TRANSACTION_STATUS,
    rtsRssTransactionId AS RTS_RSS_TRANSACTION_ID,
    identityVerificationMechanism AS IDENTITIY_VERIFICATION_MECHANISM,
    identityVerificationStatus AS IDENTITY_VERIFICATION_STATUS,
    identityVerificationStatusReasonDescription AS IDENTITY_VERIFICATION_STATUS_REASON_DESCRIPTION,
    digitalVerificationMechanism AS DIGITAL_VERIFICATION_MECHANISM,
    digitalVerificationCheck AS DIGITAL_VERIFICATION_CHECK,
    digitalVerificationCheckReasonDescription AS DIGITAL_VERIFICATION_CHECK_REASON_DESCRIPTION,
    bankVerificationCheckMechanism AS BANK_VERIFICATION_CHECK_MECHANISM,
    bankVerificationCheck AS BANK_VERIFICATION_CHECK,
    bankVerificationCheckReasonDescription AS BANK_VERIFICATION_CHECK_REASON_DESCRIPTION,
    fraudResult AS FRAUD_RESULT,
    fraudReason AS FRAUD_REASON,
    creditDecisionResult AS CREDIT_DECISION_RESULT,
    creditDecisionReasons AS CREDIT_DECISION_REASONS,
    creditDecisionFinalCreditLimitOffer AS CREDIT_DECISION_FINAL_CREDIT_LIMIT_OFFER,
    creditDecisionOfferIdRequested AS CREDIT_DECISION_OFFERID_REQUESTED,
    creditDecisionOfferIdApproved AS CREDIT_DECISION_OFFERID_APPROVED,
    creditDecisionAnnualPercentageRate AS CREDIT_DECISION_ANNUAL_PERCENTAGE_RATE,
    creditDecisionTotalAmountToPay AS CREDIT_DECISION_TOTAL_AMOUNT_TO_PAY,
    creditDecisionBasePricingCode AS CREDIT_DECISION_BASE_PRICING_CODE,
    creditDecisionOfferPricingCode AS CREDIT_DECISION_OFFER_PRICING_CODE,
    cddProfileId AS CDD_PROFILEID,
    cddResult AS CDD_RESULT,
    cddInformationDetailsRiskRating AS CDD_INFORMATION_DETAILS_RISK_RATING,
    applicationScore AS APPLICATION_SCORE,
    firstPartyFraudScore AS FIRST_PARTY_FRAUD_SCORE,
    delphiScore AS DELPHI_SCORE,
    ciiScore AS CIISCORE,
    title AS TITLE,
    firstNames AS FIRSTNAMES,
    lastName AS LASTNAME,
    hasPreviousNames AS HAS_PREVIOUS_NAMES,
    originalFirstName AS ORIGINAL_FIRSTNAME,
    originalLastName AS ORIGINAL_LASTNAME,
    previousTitle AS PREVIOUS_TITLE,
    previousFirstNames AS PREVIOUS_FIRSTNAMES,
    previousLastNames AS PREVIOUS_LASTNAMES,
    dateOfBirth AS DATE_OF_BIRTH,
    gender AS GENDER,
    nationalities AS NATIONALITIES,
    nationality1 AS NATIONALITY1,
    nationality2 AS NATIONALITY2,
    nationality3 AS NATIONALITY3,
    maritalStatus AS MARITAL_STATUS,
    numberOfDependents AS NUMBER_OF_DEPENDENTS,
    addressLine2 AS ADDRESSLINE2,
    email AS EMAIL,
    telephoneNumber AS TELEPHONE_NUMBER,
    addressLine1 AS ADDRESSLINE1,
    addressLine3 AS ADDRESSLINE3,
    addressLine4 AS ADDRESSLINE4,
    addressLine5 AS ADDRESSLINE5,
    addressLine6 AS ADDRESSLINE6,
    postcode AS POSTCODE,
    country AS COUNTRY,
    previousAddressesAddressLine1 AS PREVIOUS_ADDRESSES_ADDRESS_LINE1,
    previousAddressesAddressLine2 AS PREVIOUS_ADDRESSES_ADDRESS_LINE2,
    previousAddressesAddressLine3 AS PREVIOUS_ADDRESSES_ADDRESS_LINE3,
    previousAddressesAddressLine4 AS PREVIOUS_ADDRESSES_ADDRESS_LINE4,
    previousAddressesAddressLine5 AS PREVIOUS_ADDRESSES_ADDRESS_LINE5,
    previousAddressesAddressLine6 AS PREVIOUS_ADDRESSES_ADDRESS_LINE6,
    previousAddressesPostcode AS PREVIOUS_ADDRESSES_POSTCODE,
    previousAddressesCountry AS PREVIOUS_ADDRESSES_COUNTRY,
    previousAddressesMovedInDate AS PREVIOUS_ADDRESSES_MOVED_IN_DATE,
    residentialStatus AS RESIDENTIAL_STATUS,
    residentialMovedInDate AS RESIDENTIAL_MOVED_IN_DATE,
    employmentStatus AS EMPLOYMENT_STATUS,
    occupation AS OCCUPATION,
    employmentRole AS EMPLOYMENT_ROLE,
    businessName AS BUSINESSNAME,
    annualSalaryAmount AS ANNUAL_SALARY_AMOUNT,
    annualIncomeAmount AS ANNUAL_INCOME_AMOUNT,
    creditLimitIncreaseOption AS CREDIT_LIMIT_INCREASE_OPTION,
    foreseeChangesToPersonalCircumstances AS FORESEE_CHANGES_TO_PERSONAL_CIRCUMSTANCES,
    creditRequestedAmount AS CREDIT_REQUESTED_AMOUNT,
    creditRequestedCurrency AS CREDIT_REQUESTED_CURRENCY,
    employmentMainStartDate AS EMPLOYMENT_MAIN_STARTDATE,
    employmentPartTimeStartDate AS EMPLOYMENT_PART_TIME_STARTDATE,
    directDebitSortCode AS DIRECT_DEBIT_SORT_CODE,
    directDebitAccountNumber AS DIRECT_DEBIT_ACCOUNT_NUMBER,
    directDebitBalancePaymentOption AS DIRECT_DEBIT_BALANCE_PAYMENT_OPTION,
    directDebitSetupStatus AS DIRECT_DEBIT_SETUP_STATUS,
    directDebitSetupRepayments AS DIRECT_DEBIT_SETUP_REPAYMENTS,
    directDebitAccountHolderFullName AS DIRECT_DEBIT_ACCOUNT_HOLDER_FULLNAME,
    marketingPreferencesOptInformation AS MARKETING_PREFERENCES_OPT_INFORMATION,
    marketingPreferencesPreferredChannels AS MARKETING_PREFERENCES_PREFERRED_CHANNELS
  
  FROM cardsorigin AS in0

)

SELECT *

FROM SQ_cardsorigin_EXPR_76
