---
version: 2
sources:
- name: "transpiled_sources"
  database: "sony"
  schema: "orch_test"
  config:
    enabled: true
  tables:
  - name: "table_79_Output4_macro_op"
    columns:
    - name: "Deal ID"
      dataType:
        type: "String"
    - name: "Instrument Description"
      dataType:
        type: "String"
    - name: "Inflation Index Ratio"
      dataType:
        type: "String"
    - name: "Accrual"
      dataType:
        type: "String"
    - name: "Legal Entity"
      dataType:
        type: "String"
    - name: "Revision Date"
      dataType:
        type: "String"
    - name: "Traded Price Type"
      dataType:
        type: "String"
    - name: "Instrument Name"
      dataType:
        type: "String"
    - name: "Maturity Date"
      dataType:
        type: "String"
    - name: "Traded Clean Price"
      dataType:
        type: "String"
    - name: "DV01"
      dataType:
        type: "String"
    - name: "Portfolio"
      dataType:
        type: "String"
    - name: "Counterparty Name"
      dataType:
        type: "String"
    - name: "Trade Date"
      dataType:
        type: "String"
    - name: "Counterparty Id"
      dataType:
        type: "String"
    - name: "Denominated"
      dataType:
        type: "String"
    - name: "Traded Yield"
      dataType:
        type: "String"
    - name: "Trade Date EOD Price"
      dataType:
        type: "String"
    - name: "Notional"
      dataType:
        type: "String"
    - name: "FileName"
      dataType:
        type: "String"
    - name: "ISIN"
      dataType:
        type: "String"
    - name: "Traded Price"
      dataType:
        type: "String"
    - name: "Debt Type"
      dataType:
        type: "String"
  - name: "table_76_Output4_macro_op"
    columns:
    - name: "BuySell"
      dataType:
        type: "String"
    - name: "IssuerName"
      dataType:
        type: "String"
    - name: "LegalEntity"
      dataType:
        type: "String"
    - name: "Field_25"
      dataType:
        type: "String"
    - name: "Trader"
      dataType:
        type: "String"
    - name: "Notional USD"
      dataType:
        type: "String"
    - name: "FXRate"
      dataType:
        type: "String"
    - name: "TradePriceInDecimal"
      dataType:
        type: "String"
    - name: "Portfolio"
      dataType:
        type: "String"
    - name: "SPN"
      dataType:
        type: "String"
    - name: "Market Value Local"
      dataType:
        type: "String"
    - name: "CustomerDescription"
      dataType:
        type: "String"
    - name: "MaturityDate"
      dataType:
        type: "String"
    - name: "Notional Local"
      dataType:
        type: "String"
    - name: "SettlementDate"
      dataType:
        type: "String"
    - name: "TradeDate"
      dataType:
        type: "String"
    - name: "Currency"
      dataType:
        type: "String"
    - name: "FileName"
      dataType:
        type: "String"
    - name: "SettlementCurrency"
      dataType:
        type: "String"
    - name: "ISIN"
      dataType:
        type: "String"
    - name: "Market Value USD"
      dataType:
        type: "String"
    - name: "Product"
      dataType:
        type: "String"
    - name: "SalesPerson"
      dataType:
        type: "String"
    - name: "CleanPrice"
      dataType:
        type: "String"
    - name: "Instrument"
      dataType:
        type: "String"
    - name: "TradeID"
      dataType:
        type: "String"
  - name: "table_75_Output4_macro_op"
    columns:
    - name: "FileName"
      dataType:
        type: "String"
    - name: "NetNotionalTradedUSD"
      dataType:
        type: "String"
    - name: "GrossNotionalTradedUSD"
      dataType:
        type: "String"
    - name: "ISIN"
      dataType:
        type: "String"
    - name: "AverageNotionalTradedUSD"
      dataType:
        type: "String"
  - name: "table_57_Output4_macro_op"
    config:
      tags:
      - "pipeline:CEM_Securities_PruVal_6m_Trade_Volume"
    columns:
    - name: "Instrument Description"
      dataType:
        type: "String"
    - name: "Counterparty LEI"
      dataType:
        type: "String"
    - name: "Clean Price"
      dataType:
        type: "String"
    - name: "Trader"
      dataType:
        type: "String"
    - name: "Desk"
      dataType:
        type: "String"
    - name: "Coupon (%)"
      dataType:
        type: "String"
    - name: "Maturity Date"
      dataType:
        type: "String"
    - name: "Product Type"
      dataType:
        type: "String"
    - name: "Region"
      dataType:
        type: "String"
    - name: "Consideration"
      dataType:
        type: "String"
    - name: "Counterparty"
      dataType:
        type: "String"
    - name: "Counterparty Name"
      dataType:
        type: "String"
    - name: "Settlement Date"
      dataType:
        type: "String"
    - name: "Trade Date"
      dataType:
        type: "String"
    - name: "Denominated"
      dataType:
        type: "String"
    - name: "Book"
      dataType:
        type: "String"
    - name: "Notional"
      dataType:
        type: "String"
    - name: "Currency"
      dataType:
        type: "String"
    - name: "FileName"
      dataType:
        type: "String"
    - name: "Consideration (USD)"
      dataType:
        type: "String"
    - name: "Accrued Interest"
      dataType:
        type: "String"
    - name: "FX Rate (vs USD)"
      dataType:
        type: "String"
    - name: "ISIN"
      dataType:
        type: "String"
    - name: "Dirty Price"
      dataType:
        type: "String"
    - name: "Notional (USD)"
      dataType:
        type: "String"
    - name: "Trade ID"
      dataType:
        type: "String"
    - name: "Buy/Sell"
      dataType:
        type: "String"
    - name: "Bond Description"
      dataType:
        type: "String"
    - name: "Status"
      dataType:
        type: "String"
