---
version: 2
models:
- name: "Health_Buckets_MVP_Priority_2__CrossTab_151"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Filter_99"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Filter_99_reject"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Formula_127_0"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Formula_159_0"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Health_Bucket_c_118"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Join_146_inner_formula_to_Formula_148_1"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Join_155_inner"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__MultiRowFormula_129_row_id_drop_0"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Sample_142"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Sample_143"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Sort_125"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Sort_135"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Sort_141"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Sort_153"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Summarize_104"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Summarize_173"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Summarize_174"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Summarize_188"
  tags:
  - "prophecy_temp"
- name: "Health_Buckets_MVP_Priority_2__Summarize_190"
  tags:
  - "prophecy_temp"
