{{
  config({    
    "materialized": "table",
    "alias": "MINERVA_EXCEPTION",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH RTR_ACCOUNT_JOIN_EXPR_25 AS (

  SELECT *
  
  FROM {{ ref('m_rep_cards_orig_account_update__RTR_ACCOUNT_JOIN_EXPR_25')}}

),

RTR_ACCOUNT_out2 AS (

  SELECT * 
  
  FROM RTR_ACCOUNT_JOIN_EXPR_25 AS in0
  
  WHERE (CLID_CLIENT_ALIAS IS NULL)

),

RTR_ACCOUNT_EXPR_EXCEPTION_CLIENT_NOT_FOUND AS (

  SELECT 
    ACCID_ACCOUNT AS ACCID_ACCOUNT4,
    ACCID_ACCOUNT_ALIAS AS NEW_ACCID,
    CLID_CLIENT_ALIAS AS CLID_CLIENT_ALIAS4,
    MERGE_CLID AS MERGE_CLID4,
    APPLICATION_NUMBER AS APPLICATION_NUMBER,
    o_PRODUCT_SRC AS o_PRODUCT_SRC4,
    APPLICATION_SOURCE_CODE AS APPLICATION_SOURCE_CODE4,
    APPLICATION_STORE_NUMBER AS APPLICATION_STORE_NUMBER4,
    o_APPLICATION_STATUS_SRC AS o_APPLICATION_STATUS_SRC4,
    LAST_ACTION_DATE_SRC AS LAST_ACTION_DATE_SRC4,
    BUSINESS_DATE AS BUSINESS_DATE,
    TOTAL_COMPARE AS TOTAL_COMPARE4,
    o_DATE_LAST_ACC_STATUS_CHANGE AS o_DATE_LAST_ACC_STATUS_CHANGE4,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE4,
    feed_update_id AS feed_update_id4,
    SOURCE_TYPE AS SOURCE_TYPE4,
    HOLDS_CLASS AS HOLDS_CLASS4
  
  FROM RTR_ACCOUNT_out2 AS in0

),

EXP_MINERVA_EXCEPTION_NO_CLIENT_FOUND AS (

  SELECT 
    NEW_ACCID AS ACCID,
    APPLICATION_NUMBER AS ACCOUNT_ALIAS_ID,
    BUSINESS_DATE AS BUSINESS_DATE,
    5002 AS CLASS,
    'm_rep_cards_orig_account_update' AS PROCESS_NAME,
    'Client not Found for Application' AS EXCEPTION_COMMENT,
    'RTR_ACCOUNT' AS FUNCTION_NAME,
    'Y' AS LOAD_INDICATOR,
    'U' AS SOURCE_SYSTEM_CODE,
    2 AS ERROR_NUMBER
  
  FROM RTR_ACCOUNT_EXPR_EXCEPTION_CLIENT_NOT_FOUND AS in0

),

MINERVA_EXCEPTION_EXP AS (

  SELECT 
    CLASS AS CLASS,
    BUSINESS_DATE AS BUSINESS_DATE,
    CAST(NULL AS NUMERIC) AS CLID,
    ACCID AS ACCID,
    CAST(NULL AS NUMERIC) AS ADID,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    CAST(NULL AS STRING) AS SOURCE_CLIENT_REF,
    ACCOUNT_ALIAS_ID AS ACCOUNT_ALIAS_ID,
    ERROR_NUMBER AS ERROR_NUMBER,
    PROCESS_NAME AS PROCESS_NAME,
    FUNCTION_NAME AS FUNCTION_NAME,
    CAST(NULL AS STRING) AS ADDITIONAL_IDENTIFIER,
    CAST(NULL AS NUMERIC) AS ADDITIONAL_IDENTIFIER_TYPE,
    LOAD_INDICATOR AS LOAD_INDICATOR,
    EXCEPTION_COMMENT AS EXCEPTION_COMMENT
  
  FROM EXP_MINERVA_EXCEPTION_NO_CLIENT_FOUND AS in0

)

SELECT *

FROM MINERVA_EXCEPTION_EXP
