{{
  config({    
    "materialized": "table",
    "alias": "CLOSE_ACCOUNT_TRANSFER_HISTORY_Target_Definition",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY AS (

  SELECT *
  
  FROM {{ ref('m_rep_ohc_account_transfer_history_update__RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY')}}

),

CLOSE_ACCOUNT_TRANSFER_HISTORY_Target_Definition_EXP AS (

  SELECT 
    ACCID AS ACCID,
    EFROM AS EFROM,
    ETO AS ETO,
    CAST(NULL AS STRING) AS PREV_ACCOUNT_ALIAS_ID,
    CAST(NULL AS STRING) AS CURR_ACCOUNT_ALIAS_ID,
    CAST(NULL AS STRING) AS SOURCE_SYSTEM_CODE,
    CAST(NULL AS STRING) AS TRANSFER_EFFECTIVE_DATE,
    CAST(NULL AS NUMERIC) AS NUMBER_OF_TRANSFERS
  
  FROM RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY AS in0

)

SELECT *

FROM CLOSE_ACCOUNT_TRANSFER_HISTORY_Target_Definition_EXP
