{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_DERIVE_ACCID AS (

  SELECT *
  
  FROM {{ ref('m_rep_ohc_account_transfer_history_update__EXP_DERIVE_ACCID')}}

),

SOURCE_LKP_ACCOUNT_TRANSFER_HISTORY AS (

  SELECT /*+ parallel(A) */  	A.EFROM as EFROM,  	A.PREV_ACCOUNT_ALIAS_ID as PREV_ACCOUNT_ALIAS_ID, 	A.CURR_ACCOUNT_ALIAS_ID as CURR_ACCOUNT_ALIAS_ID,  	A.SOURCE_SYSTEM_CODE as SOURCE_SYSTEM_CODE,  	A.TRANSFER_EFFECTIVE_DATE as TRANSFER_EFFECTIVE_DATE 	A.NUMBER_OF_TRANSFERS as NUMBER_OF_TRANSFERS,  	A.ACCID as ACCID  FROM  	ACCOUNT_TRANSFER_HISTORY A WHERE 	A.ETO IS NULL

),

RTR_ACCID_FOUND_out0 AS (

  SELECT * 
  
  FROM EXP_DERIVE_ACCID AS in0
  
  WHERE (PRIMARY_ACCID IS NOT NULL)

),

RTR_ACCID_FOUND_EXPR_ACCID_FOUND AS (

  SELECT 
    business_date AS business_date1,
    business_date_minus_1 AS business_date_minus_11,
    feed_update_id AS feed_update_id1,
    OLD_ACCOUNT_NUMBER AS OLD_ACCOUNT_NUMBER1,
    NEW_ACCOUNT_NUMBER AS NEW_ACCOUNT_NUMBER1,
    TRANSFER_EFFECTIVE_DATE AS TRANSFER_EFFECTIVE_DATE1,
    PRIMARY_ACCID AS PRIMARY_ACCID1,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE1,
    (ROW_NUMBER() OVER ()) AS prophecy_sk,
    PRIMARY_ACCID AS PRIMARY_ACCID
  
  FROM RTR_ACCID_FOUND_out0 AS in0

),

RTRTRANS_JOIN_merged AS (

  SELECT 
    in0.NEW_ACCOUNT_NUMBER1 AS NEW_ACCOUNT_NUMBER1,
    in1.NUMBER_OF_TRANSFERS AS NUMBER_OF_TRANSFERS,
    in1.ACCID AS ACCID,
    in0.feed_update_id1 AS feed_update_id1,
    in1.TRANSFER_EFFECTIVE_DATE AS TRANSFER_EFFECTIVE_DATE,
    in1.EFROM AS EFROM,
    in0.PRIMARY_ACCID1 AS PRIMARY_ACCID1,
    in1.PREV_ACCOUNT_ALIAS_ID AS PREV_ACCOUNT_ALIAS_ID,
    in0.PRIMARY_ACCID AS PRIMARY_ACCID,
    in1.CURR_ACCOUNT_ALIAS_ID AS CURR_ACCOUNT_ALIAS_ID,
    in1.SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    in0.OLD_ACCOUNT_NUMBER1 AS OLD_ACCOUNT_NUMBER1,
    in0.business_date1 AS business_date1,
    in0.prophecy_sk AS prophecy_sk,
    in0.TRANSFER_EFFECTIVE_DATE1 AS TRANSFER_EFFECTIVE_DATE1,
    in0.SOURCE_SYSTEM_CODE1 AS SOURCE_SYSTEM_CODE1,
    in0.business_date_minus_11 AS business_date_minus_11
  
  FROM RTR_ACCID_FOUND_EXPR_ACCID_FOUND AS in0
  INNER JOIN SOURCE_LKP_ACCOUNT_TRANSFER_HISTORY AS in1
     ON (in1.ACCID = in0.PRIMARY_ACCID)
  INNER JOIN RTR_ACCID_FOUND_EXPR_ACCID_FOUND AS in2
     ON in0.prophecy_sk = in2.prophecy_sk

),

RTRTRANS_JOIN_EXPR_107 AS (

  SELECT 
    ACCID AS LKP_ACCID,
    EFROM AS LKP_EFROM,
    PREV_ACCOUNT_ALIAS_ID AS LKP_PREV_ACCOUNT_ALIAS_ID,
    CURR_ACCOUNT_ALIAS_ID AS LKP_CURR_ACCOUNT_ALIAS_ID,
    SOURCE_SYSTEM_CODE AS LKP_SOURCE_SYSTEM_CODE,
    TRANSFER_EFFECTIVE_DATE AS LKP_TRANSFER_EFFECTIVE_DATE,
    NUMBER_OF_TRANSFERS AS NUMBER_OF_ACCOUNT_TRANSFERS,
    PRIMARY_ACCID AS PRIMARY_ACCID,
    prophecy_sk AS prophecy_sk,
    business_date1 AS business_date,
    business_date_minus_11 AS business_date_minus_1,
    feed_update_id1 AS feed_update_id,
    OLD_ACCOUNT_NUMBER1 AS OLD_ACCOUNT_NUMBER,
    NEW_ACCOUNT_NUMBER1 AS NEW_ACCOUNT_NUMBER,
    TRANSFER_EFFECTIVE_DATE1 AS TRANSFER_EFFECTIVE_DATE,
    SOURCE_SYSTEM_CODE1 AS SOURCE_SYSTEM_CODE1
  
  FROM RTRTRANS_JOIN_merged AS in0

)

SELECT *

FROM RTRTRANS_JOIN_EXPR_107
