{{
  config({    
    "materialized": "table",
    "alias": "OPEN_ACCOUNT_TRANSFER_HISTORY_Target_Definition",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY AS (

  SELECT *
  
  FROM {{ ref('m_rep_ohc_account_transfer_history_update__RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY')}}

),

EXP_NUMBER_OF_ACCOUNT_TRANSFERS AS (

  SELECT 
    LKP_ACCID3 AS ACCID,
    business_date3 AS EFROM,
    OLD_ACCOUNT_NUMBER3 AS PREV_ACCOUNT_ALIAS_ID,
    NEW_ACCOUNT_NUMBER3 AS CURR_ACCOUNT_ALIAS_ID,
    SOURCE_SYSTEM_CODE13 AS SOURCE_SYSTEM_CODE,
    TRANSFER_EFFECTIVE_DATE3 AS TRANSFER_EFFECTIVE_DATE,
    (CAST(NUMBER_OF_ACCOUNT_TRANSFERS3 AS INT64) + 1) AS NUMBER_OF_TRANSFERS
  
  FROM RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY AS in0

),

OPEN_ACCOUNT_TRANSFER_HISTORY_Target_Definition_EXP AS (

  SELECT 
    ACCID AS ACCID,
    EFROM AS EFROM,
    CAST(NULL AS STRING) AS ETO,
    PREV_ACCOUNT_ALIAS_ID AS PREV_ACCOUNT_ALIAS_ID,
    CURR_ACCOUNT_ALIAS_ID AS CURR_ACCOUNT_ALIAS_ID,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    TRANSFER_EFFECTIVE_DATE AS TRANSFER_EFFECTIVE_DATE,
    NUMBER_OF_TRANSFERS AS NUMBER_OF_TRANSFERS
  
  FROM EXP_NUMBER_OF_ACCOUNT_TRANSFERS AS in0

)

SELECT *

FROM OPEN_ACCOUNT_TRANSFER_HISTORY_Target_Definition_EXP
