{{
  config({    
    "materialized": "ephemeral",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH RTRTRANS_JOIN_EXPR_107 AS (

  SELECT *
  
  FROM {{ ref('m_rep_ohc_account_transfer_history_update__RTRTRANS_JOIN_EXPR_107')}}

),

RTRTRANS_out1 AS (

  SELECT * 
  
  FROM RTRTRANS_JOIN_EXPR_107 AS in0
  
  WHERE (LKP_ACCID IS NOT NULL)

),

RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY AS (

  SELECT 
    LKP_ACCID AS LKP_ACCID3,
    LKP_EFROM AS LKP_EFROM3,
    LKP_ETO AS LKP_ETO3,
    LKP_PREV_ACCOUNT_ALIAS_ID AS LKP_PREV_ACCOUNT_ALIAS_ID3,
    LKP_CURR_ACCOUNT_ALIAS_ID AS LKP_CURR_ACCOUNT_ALIAS_ID3,
    LKP_SOURCE_SYSTEM_CODE AS LKP_SOURCE_SYSTEM_CODE3,
    LKP_TRANSFER_EFFECTIVE_DATE AS LKP_TRANSFER_EFFECTIVE_DATE3,
    PRIMARY_ACCID AS PRIMARY_ACCID3,
    business_date AS business_date3,
    business_date_minus_1 AS business_date_minus_13,
    feed_update_id AS feed_update_id3,
    OLD_ACCOUNT_NUMBER AS OLD_ACCOUNT_NUMBER3,
    NEW_ACCOUNT_NUMBER AS NEW_ACCOUNT_NUMBER3,
    TRANSFER_EFFECTIVE_DATE AS TRANSFER_EFFECTIVE_DATE3,
    SOURCE_SYSTEM_CODE1 AS SOURCE_SYSTEM_CODE13,
    NUMBER_OF_ACCOUNT_TRANSFERS AS NUMBER_OF_ACCOUNT_TRANSFERS3,
    business_date_minus_1 AS ETO,
    LKP_ACCID AS ACCID,
    LKP_EFROM AS EFROM
  
  FROM RTRTRANS_out1 AS in0

)

SELECT *

FROM RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY
