{{
  config({    
    "materialized": "table",
    "alias": "MINERVA_EXCEPTION",
    "database": "prophecy-databricks-qa",
    "schema": "pramit_test"
  })
}}

WITH EXP_DERIVE_ACCID AS (

  SELECT *
  
  FROM {{ ref('m_rep_ohc_account_transfer_history_update__EXP_DERIVE_ACCID')}}

),

RTR_ACCID_FOUND_out1 AS (

  SELECT * 
  
  FROM EXP_DERIVE_ACCID AS in0
  
  WHERE (PRIMARY_ACCID IS NULL)

),

RTR_ACCID_FOUND_EXPR_ACCID_NOT_FOUND AS (

  SELECT 
    business_date AS business_date3,
    business_date_minus_1 AS business_date_minus_13,
    feed_update_id AS feed_update_id3,
    OLD_ACCOUNT_NUMBER AS OLD_ACCOUNT_NUMBER3,
    NEW_ACCOUNT_NUMBER AS NEW_ACCOUNT_NUMBER3,
    TRANSFER_EFFECTIVE_DATE AS TRANSFER_EFFECTIVE_DATE3,
    PRIMARY_ACCID AS PRIMARY_ACCID3,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE3
  
  FROM RTR_ACCID_FOUND_out1 AS in0

),

EXP_MINERVA_EXCEPTION AS (

  SELECT 
    business_date3 AS BUSINESS_DATE,
    OLD_ACCOUNT_NUMBER3 AS ACCOUNT_ALIAS_ID,
    NEW_ACCOUNT_NUMBER3 AS ADDITIONAL_IDENTIFIER,
    TRANSFER_EFFECTIVE_DATE3 AS TRANSFER_EFFECTIVE_DATE3,
    PRIMARY_ACCID3 AS PRIMARY_ACCID3,
    '65' AS ERROR_NUMBER,
    5052 AS CLASS,
    'G' AS SOURCE_SYSTEM_CODE,
    'm_rep_whirl_gems_account_transfer_history_update' AS PROCESS_NAME,
    'rtr_accid_found' AS FUNCTION_NAME,
    'N' AS LOAD_INDICATOR,
    'No account found on Minerva for this Account number' AS EXCEPTION_COMMENT
  
  FROM RTR_ACCID_FOUND_EXPR_ACCID_NOT_FOUND AS in0

),

MINERVA_EXCEPTION_EXP AS (

  SELECT 
    CLASS AS CLASS,
    BUSINESS_DATE AS BUSINESS_DATE,
    CAST(NULL AS NUMERIC) AS CLID,
    CAST(NULL AS NUMERIC) AS ACCID,
    CAST(NULL AS NUMERIC) AS ADID,
    SOURCE_SYSTEM_CODE AS SOURCE_SYSTEM_CODE,
    CAST(NULL AS STRING) AS SOURCE_CLIENT_REF,
    ACCOUNT_ALIAS_ID AS ACCOUNT_ALIAS_ID,
    ERROR_NUMBER AS ERROR_NUMBER,
    PROCESS_NAME AS PROCESS_NAME,
    FUNCTION_NAME AS FUNCTION_NAME,
    ADDITIONAL_IDENTIFIER AS ADDITIONAL_IDENTIFIER,
    CAST(NULL AS NUMERIC) AS ADDITIONAL_IDENTIFIER_TYPE,
    LOAD_INDICATOR AS LOAD_INDICATOR,
    EXCEPTION_COMMENT AS EXCEPTION_COMMENT
  
  FROM EXP_MINERVA_EXCEPTION AS in0

)

SELECT *

FROM MINERVA_EXCEPTION_EXP
