---
version: 2
models:
- name: "m_rep_ohc_account_transfer_history_update__CLOSE_ACCOUNT_TRANSFER_HISTORY_Target_Definition"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_account_transfer_history_update__EXP_CONV_VARS_0"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_account_transfer_history_update__EXP_DERIVE_ACCID"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_account_transfer_history_update__MINERVA_EXCEPTION"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_account_transfer_history_update__NEW_ACCOUNT_TRANSFER_HISTORY_Target_Definition"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_account_transfer_history_update__OPEN_ACCOUNT_TRANSFER_HISTORY_Target_Definition"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_account_transfer_history_update__RTRTRANS_EXPR_EXISTING_ACCOUNT_TRANSFER_HISTORY"
  tags:
  - "prophecy_temp"
- name: "m_rep_ohc_account_transfer_history_update__RTRTRANS_JOIN_EXPR_107"
  tags:
  - "prophecy_temp"
