pipelines:
  p1:
    visualGroups:
      AddConfigHereandAddtoJoin:
        isCollapsed: false
        height: 280
        width: 400
        nodes:
        - "Config_46_xlsx__69"
        - "Formula_73_0"
      AlteryxProjectDetail:
        isCollapsed: false
        height: 1221
        width: 750
        nodes:
        - "AddConfigHereandAddtoJoin"
        - "AppendFields_67"
        - "CallAlteryxProjectworkflowhere"
        - "VCGARTProjectID"
      CallAlteryxProjectworkflowhere:
        isCollapsed: false
        height: 280
        width: 280
        nodes:
        - "Macro_61"
      VCGARTProjectID:
        isCollapsed: false
        height: 280
        width: 400
        nodes:
        - "Formula_27_to_Formula_39_0"
        - "Formula_27_to_Formula_39_1"
      ValidateUserwithCloudIDinfo:
        isCollapsed: false
        height: 715
        width: 1000
        nodes:
        - "AppendFields_33"
        - "CountRecords_32"
        - "DynamicInput_5"
        - "Filter_34"
        - "Formula_36_0"
        - "Formula_37_0"
        - "Join_31_inner"
        - "TextInput_1"
        - "TextInput_1_cast"
        - "User_Repository_30"
