---
version: 2
models:
- name: "boeing__AlteryxSelect_25"
  tags:
  - "prophecy_temp"
- name: "boeing__Database__LOADI_111"
  tags:
  - "prophecy_temp"
- name: "boeing__Database__LOADI_98"
  tags:
  - "prophecy_temp"
- name: "boeing__Filter_68"
  tags:
  - "prophecy_temp"
- name: "boeing__Formula_78_0"
  tags:
  - "prophecy_temp"
- name: "boeing__Formula_7_0"
  tags:
  - "prophecy_temp"
- name: "boeing__Unique_97"
  tags:
  - "prophecy_temp"
